INSERT INTO `P_TEMPLATE_TYPE` (`TETY_ID`, `TETY_NAME`, `TETY_CODE`, `TETY_DESC`, `TETY_ACTION`, `TETY_PARENT`, `TETY_CHILD`, `TETY_CLASS`, `TETY_TYPE`, `TETY_FORM_FLAG`, `ACTIVE`, `VERSION`, `REMOVED`) VALUES
(1, '件数包装', 'FBl', 'blPackages', NULL),
(1, '铅封号', 'FBl', 'blSealNo', NULL);

ALTER TABLE `F_BL`
	ADD COLUMN `BL_SEAL_NO` VARCHAR(500) NULL DEFAULT NULL AFTER `BL_CONTAINER_NO`;
