ALTER TABLE `G_CARGO_TYPE`
    CHANGE COLUMN `CATY_DANAGE_NO` `CATY_DANAGER_NO` VARCHAR(16) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CATY_DANAGER_FLAG`,
	ADD COLUMN `CATY_MANU_NO` VARCHAR(64) NULL DEFAULT NULL AFTER `CATY_NAME_EN`,
	ADD COLUMN `CATY_SPEC` VARCHAR(64) NULL DEFAULT NULL AFTER `CATY_MANU_No`,
	ADD COLUMN `CATY_CARGO_TYPE` VARCHAR(64) NULL DEFAULT NULL AFTER `CATY_SPEC`;
