ALTER TABLE `S_INVOICE`
	CHANGE COLUMN `VOUC_NO` `VOUC_NO` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `INVO_WRITE_OFF_DATE`;

ALTER TABLE `S_INVOICE`
	CHANGE COLUMN `INVO_CONTRACT_NO` `INVO_CONTRACT_NO` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `INVO_OPERATOR`;
	
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(7, '箱封号', 'FConsign', 'consSealNo', NULL),
(26, '箱号', 'FConsign', 'consContainerNo', NULL),
(26, '箱封号', 'FConsign', 'consSealNo', NULL);


ALTER TABLE `G_PORT`
	CHANGE COLUMN `COUN_CODE` `COUN_CODE` CHAR(2) NOT NULL COLLATE 'utf8_unicode_ci' AFTER `UUID`;