UPDATE P_TEMPLATE_MAP SET TEMA_FIELD = 'settlementObject' WHERE TETY_ID=34 AND TEMA_NAME='发票抬头';
	
ALTER TABLE `C_SALES_COMMISSION`
	ADD COLUMN `REMOVED` TINYINT NOT NULL DEFAULT '0' AFTER `VERSION`;
