-- 订舱委托书（货物）
DELETE FROM P_TEMPLATE_MAP WHERE TETY_ID=41;
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(41, '发货人', 'FConsign', 'consShipper', NULL),
(41, '收货人', 'FConsign', 'consConsignee', NULL),
(41, '通知人', 'FConsign', 'consNotifyParty', NULL),
(41, '前程运输', 'FConsign', 'consPrecarriage', NULL),
(41, '收货地点', 'FConsign', 'consReceiptPlace', NULL),
(41, '船名', 'FConsign', 'vessName', NULL),
(41, '航次', 'FConsign', 'voyaName', NULL),
(41, '装货港', 'FConsign', 'consPolEn', NULL),
(41, '卸货港', 'FConsign', 'consPodEn', NULL),
(41, '交货地点', 'FConsign', 'consDeliveryPlace', NULL),
(41, '目的地', 'FConsign', 'consDestination', NULL),
(41, '标记唛码', 'FConsign', 'consCargoMarks', NULL),
(41, '件数', 'FConsign', 'consTotalPackages', NULL),
(41, '包装', 'FConsign', 'packId', NULL),
(41, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(41, '尺码', 'FConsign', 'consTotalMeasurement', NULL),
(41, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(41, '货物描述', 'FConsign', 'consCargoDesc', NULL),
(41, '运费条款', 'FConsign', 'pateName', NULL),
(41, '运输方式', 'FConsign', 'tranId', NULL),
(41, '英文件数', 'FConsign', 'consTotalPackagesInWord', NULL),
(41, '签发地点', 'FConsign', 'consBlIssuePlace', NULL),
(41, '正本份数', 'FConsign', 'consOriginalBlNum', NULL),
(41, '可否转船', 'FConsign', 'consTransFlag', 'Bool'),
(41, '可否分批', 'FConsign', 'consPartialFlag', 'Bool'),
(41, '装期', 'FConsign', 'consLoadDate', NULL),
(41, '备注', 'FConsign', 'consBlRemarks', NULL),
(41, '合计大写', 'FConsign', 'consTotalPackagesInWord', NULL),
(41, '特殊货物信息', 'FConsign', 'consCargoSpecial', NULL),
(41, '第二通知人', 'FConsign', 'consNotifyParty2', NULL),
(41, '操作员', 'FConsign', 'consOperatorName', NULL),
(41, '提单号', 'FConsign', 'consMblNo', NULL);

-- 订舱委托书（提单）
DELETE FROM P_TEMPLATE_MAP WHERE TETY_ID=42;
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(42, '发货人', 'FConsign', 'consShipper', NULL),
(42, '收货人', 'FConsign', 'consConsignee', NULL),
(42, '通知人', 'FConsign', 'consNotifyParty', NULL),
(42, '前程运输', 'FConsign', 'consPrecarriage', NULL),
(42, '收货地点', 'FConsign', 'consReceiptPlace', NULL),
(42, '船名', 'FConsign', 'vessName', NULL),
(42, '航次', 'FConsign', 'voyaName', NULL),
(42, '装货港', 'FConsign', 'consPolEn', NULL),
(42, '卸货港', 'FConsign', 'consPodEn', NULL),
(42, '交货地点', 'FConsign', 'consDeliveryPlace', NULL),
(42, '目的地', 'FConsign', 'consDestination', NULL),
(42, '标记唛码', 'FConsign', 'consCargoMarks', NULL),
(42, '件数包装', 'FConsign', 'consCargoPackages', NULL),
(42, '货物描述', 'FConsign', 'consCargoDesc', NULL),
(42, '件数', 'FConsign', 'consTotalPackages', NULL),
(42, '包装', 'FConsign', 'packId', NULL),
(42, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(42, '尺码', 'FConsign', 'consTotalMeasurement', NULL),
(42, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(42, '运费条款', 'FConsign', 'pateName', NULL),
(42, '运输方式', 'FConsign', 'tranId', NULL),
(42, '英文件数', 'FConsign', 'consTotalPackagesInWord', NULL),
(42, '签发地点', 'FConsign', 'consBlIssuePlace', NULL),
(42, '正本份数', 'FConsign', 'consOriginalBlNum', NULL),
(42, '可否转船', 'FConsign', 'consTransFlag', 'Bool'),
(42, '可否分批', 'FConsign', 'consPartialFlag', 'Bool'),
(42, '装期', 'FConsign', 'consLoadDate', NULL),
(42, '备注', 'FConsign', 'consBlRemarks', NULL),
(42, '合计大写', 'FConsign', 'consTotalPackagesInWord', NULL),
(42, '特殊货物信息', 'FConsign', 'consCargoSpecial', NULL),
(42, '第二通知人', 'FConsign', 'consNotifyParty2', NULL),
(42, '操作员', 'FConsign', 'consOperatorName', NULL),
(42, '提单号', 'FConsign', 'consMblNo', NULL);

DELETE FROM P_TEMPLATE_MAP WHERE TETY_ID=50;
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(50, '装货港', 'FCustomsDeclaration', 'cudePolEn', NULL),
(50, '卸货港', 'FCustomsDeclaration', 'cudePodEn', NULL),
(50, '发票号', 'FCustomsDeclaration', 'cudeInvoiceNo', NULL),
(50, '发票日期', 'FCustomsDeclaration', 'cudeInvoiceDate', NULL),
(50, '发货人', 'FCustomsDeclaration', 'cudeShipper', NULL),
(50, '收货人', 'FCustomsDeclaration', 'cudeConsignee', NULL),
(50, '结汇方式', 'FCustomsDeclaration', 'exseCode', NULL),
(50, '成交方式', 'FCustomsDeclaration', 'trteCode', NULL),
(50, '英文结汇方式', 'FCustomsDeclaration', 'exseCodeEn', NULL),
(50, '英文成交方式', 'FCustomsDeclaration', 'trteCodeEn', NULL),
(50, '件数合计', 'FCustomsDeclaration', 'cudePackageNum', NULL),
(50, '包装合计', 'FCustomsDeclaration', 'packCode', NULL),
(50, '毛重合计', 'FCustomsDeclaration', 'cudeGrossWeight', NULL),
(50, '净重合计', 'FCustomsDeclaration', 'cudeNetWeight', NULL),
(50, '体积合计', 'FCustomsDeclaration', 'cudeMeasurement', NULL),
(50, '大写件数', 'FCustomsDeclaration', 'cudeTotalSay', NULL),
(50, '唛头与项号', 'FCustomsEntry', 'cuenNo', NULL),
(50, '英文品名', 'FCustomsEntry', 'cuenCargoNameEn', NULL),
(50, '件数', 'FCustomsEntry', 'cuenPackageNum', NULL),
(50, '数量', 'FCustomsEntry', 'cuenCargoNum', NULL),
(50, '包装', 'FCustomsEntry', 'packCode', NULL),
(50, '毛重', 'FCustomsEntry', 'cuenCargoGrossWeight', NULL),
(50, '净重', 'FCustomsEntry', 'cuenCargoNetWeight', NULL),
(50, '体积', 'FCustomsEntry', 'cuenCargoMeasurement', NULL),
(51, '备注', 'FCustomsEntry', 'cuenRemarks', NULL);

ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_NUM` VARCHAR(32) NULL DEFAULT NULL AFTER `CUDE_PACKAGE_NUM`,
	ADD COLUMN `CUDE_MEASUREMENT` VARCHAR(32) NULL DEFAULT NULL AFTER `CUDE_NET_WEIGHT`;