ALTER TABLE `F_CONSIGN`
	CHANGE COLUMN `CONS_CONTRACT_NO` `CONS_CONTRACT_NO` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONS_REF_NO`;
INSERT INTO `P_ACTION` (`ACT_NAME`, `ACT_SERVICE`, `ACT_METHOD`, `ACT_REMARK`) VALUES
('EXPE_X_S', 'SExpenseService', 'complexQuerySingle', '费用单表复杂查询');