INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES 
(1, 'MBLNO3', 'FBL', 'mblNo', 'getBlNo3'),
(1, '会计信息', 'FBl', 'blAccountingInfo', NULL),
(1, 'IATA', 'FBl', 'blAgentIataCode', NULL),
(1, '付费方式', 'FBl', 'blValuePayment', 'overridePP'),
(1, '付款方式', 'FBl', 'blValuePayment', NULL),
(1, '其他付款方式', 'FBl', 'blOtherPayment', NULL),
(1, '预付其他费用', 'FBl', 'blOtherDcPp', NULL),
(1, '到付其他费用', 'FBl', 'blOtherDcCc', NULL);

UPDATE `P_TEMPLATE_MAP` SET `TEMA_CONVERTER`='getBlNo' WHERE  `TEMA_ID`=7 LIMIT 1;

ALTER TABLE `G_PORT`
	ADD COLUMN `CREATE_BY` VARCHAR(16)  AFTER `PORT_TRANS_FLAG`,
	ADD COLUMN `CREATE_TIME` DATETIME  AFTER `CREATE_BY`,
	ADD COLUMN `MODIFY_BY` INT  AFTER `CREATE_TIME`,
	ADD COLUMN `MODIFY_TIME` CHAR(4)  AFTER `MODIFY_BY`,
	ADD COLUMN `UUID` VARCHAR(32)  AFTER `MODIFY_TIME`,
	CHANGE COLUMN `PORT_NAME_EN` `PORT_NAME_EN` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `PORT_CODE`,
	CHANGE COLUMN `PORT_NAME_CN` `PORT_NAME_CN` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `PORT_NAME_EN`;
ALTER TABLE `C_CUSTOMER`
	ADD COLUMN `CUST_PROVINCE_ID` INT(11) NULL DEFAULT NULL AFTER `COUN_CODE`,
	ADD COLUMN `CUST_CITY_ID` INT(11) NULL DEFAULT NULL AFTER `CUST_PROVINCE`,
	ADD COLUMN `CUST_OIL_FLAG` TINYINT(4) NULL DEFAULT NULL AFTER `CUST_CONTAINER_FLAG`,
	ADD COLUMN `CUST_FACTORY_FLAG` TINYINT(4) NULL DEFAULT NULL AFTER `CUST_OIL_FLAG`,
	ADD COLUMN `MARINE_FLAG` TINYINT(4) NULL DEFAULT NULL AFTER `CUST_FACTORY_FLAG`,
	ADD COLUMN `AIR_FLAG` TINYINT(4) NULL DEFAULT NULL AFTER `MARINE_FLAG`,
	ADD COLUMN `EXPRESS_FLAG` TINYINT(4) NULL DEFAULT NULL AFTER `AIR_FLAG`,
	ADD COLUMN `CUSTOMS_FLAG` TINYINT(4) NULL DEFAULT NULL AFTER `EXPRESS_FLAG`,
	ADD COLUMN `WMS_FLAG` TINYINT(4) NULL DEFAULT NULL AFTER `CUSTOMS_FLAG`,
	ADD COLUMN `TMS_FLAG` TINYINT(4) NULL DEFAULT NULL AFTER `WMS_FLAG`,
	ADD COLUMN `UUID` VARCHAR(32) NULL DEFAULT NULL AFTER `REMOVED`,
	ADD COLUMN `PARENT_ID` INT(11) NULL DEFAULT NULL AFTER `UUID`,
	CHANGE COLUMN `CUST_CLASS` `CUST_CLASS` VARCHAR(16) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUST_CODE`;