--
-- 初始化 `G_PACKAGE`
--

INSERT INTO `G_PACKAGE` (`PACK_CODE`,`PACK_NAME_CN`, `PACK_NAME`, `ACTIVE`, `COMP_CODE`, `VERSION`, `REMOVED`) VALUES
('WB', '柳条包', 'wickerbottle', 1, '{CC}', 0, 0),
('VY', '散装微粒子(粉末)固体', 'bulk,solid,fine particles (powders)', 1, '{CC}', 0, 0),
('VR', '散装粗粒子固体(颗粒)', 'bulk,solid,granular particles(grains)', 1, '{CC}', 0, 0),
('VQ', '散装液化气(在特殊温度/压力下)', '	bulk,liqufiedg gas', 1, '{CC}', 0, 0),
('VP', '真空包装', 'vacuumpacked', 1, '{CC}', 0, 0),
('VO', '散装大粒子固体', 'bulk,solid,large particles(nodules)', 1, '{CC}', 0, 0),
('VL', '散装液体', '	bulk ,liquid', 1, '{CC}', 0, 0),
('VI', '小玻璃瓶', '	vial', 1, '{CC}', 0, 0),
('VG', '散装气体(1031毫巴，15/C )', 'bulk,gas', 1, '{CC}', 0, 0),
('VA', '桶', 'vat', 1, '{CC}', 0, 0),
('TZ', '堆/束/捆形式的管', 'tubes,inbundle/bunch/truss', 1, '{CC}', 0, 0),
('TY', '圆柱形油箱', 'tank,cylindrical', 1, '{CC}', 0, 0),
('TU', '管', 'tube', 1, '{CC}', 0, 0),
('TS', '捆', 'truss', 1, '{CC}', 0, 0),
('TR', '衣箱', '	trunk', 1, '{CC}', 0, 0),
('TO', '大酒桶', 'tun', 1, '{CC}', 0, 0),
('TN', '马口铁', 'tin', 1, '{CC}', 0, 0),
('TK', '矩形油箱', 'tank,rectangular', 1, '{CC}', 0, 0),
('TD', '收缩管', 'collapsible tube', 1, '{CC}', 0, 0),
('TC', '茶叶箱', 'tea-chest', 1, '{CC}', 0, 0),
('TB', '盆', 'tub', 1, '{CC}', 0, 0),
('SZ', '堆/束/捆形式的薄板', 'sheets,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('SW', '收缩包装', 'shrinkwrapped', 1, '{CC}', 0, 0),
('SU', '手提箱', 'suitcase', 1, '{CC}', 0, 0),
('ST', '薄板', 'sheet', 1, '{CC}', 0, 0),
('SM', '薄板金属', '	sheetmetal', 1, '{CC}', 0, 0),
('SL', '薄衬纸', 'slipsheet', 1, '{CC}', 0, 0),
('SK', '箱', 'skeleton case', 1, '{CC}', 0, 0),
('SH', '小包装袋	', 'sachet', 1, '{CC}', 0, 0),
('SD', '轴', 'spindle', 1, '{CC}', 0, 0),
('SC', '薄板条箱', 'shallow crate', 1, '{CC}', 0, 0),
('SA', '袋', 'sack', 1, '{CC}', 0, 0),
('RZ', '堆/束/捆形式的钢筋', 'rods,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('RT', '红色网', 'rednet', 1, '{CC}', 0, 0),
('RO', '卷钢', 'roll', 1, '{CC}', 0, 0),
('RL', '卷筒', '	reel', 1, '{CC}', 0, 0),
('RG', '环', 'ring', 1, '{CC}', 0, 0),
('RD', '钢筋', '	rod', 1, '{CC}', 0, 0),
('PZ', '堆/束/捆形式的厚木板', 'planks,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('PY', '堆/束/捆形式的金属薄板', 'plates,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('PV', '堆/束/捆形式的管子', 'pipes,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('PU', '托盘', '	tray', 1, '{CC}', 0, 0),
('PT', '罐', 'pot', 1, '{CC}', 0, 0),
('PO', '袋装', '	pouch', 1, '{CC}', 0, 0),
('PN', '厚木板', 'plank', 1, '{CC}', 0, 0),
('PL', '桶', 'pail', 1, '{CC}', 0, 0),
('PK', '包', 'package', 1, '{CC}', 0, 0),
('PI', '管子', '	pipe', 1, '{CC}', 0, 0),
('PH', '大水瓶', 'pitcher', 1, '{CC}', 0, 0),
('PG', '金属薄板', '	plate', 1, '{CC}', 0, 0),
('PC', '包裹', '	parcel', 1, '{CC}', 0, 0),
('PA', '小包裹', 'packet', 1, '{CC}', 0, 0),
('NT', '网', 'net', 1, '{CC}', 0, 0),
('NS', '成套器具	', 'nest', 1, '{CC}', 0, 0),
('NE', '无包装', 'unpacked or unpackaged', 1, '{CC}', 0, 0),
('MX', '火柴盒', 'match box', 1, '{CC}', 0, 0),
('MT', '麻袋', '	mat', 1, '{CC}', 0, 0),
('MS', '多层包', 'multiwall sack', 1, '{CC}', 0, 0),
('MC', '装奶板条箱', 'milk crate', 1, '{CC}', 0, 0),
('MB', '多用包', 'mutiply bag', 1, '{CC}', 0, 0),
('LZ', '堆/束/捆形式的木材', 'logs,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('LG', '木材', '	log', 1, '{CC}', 0, 0),
('KG', '(小于30加仑)桶', 'keg', 1, '{CC}', 0, 0),
('JY', '圈柱形五加仑液体罐', 'jerrican,cylindrical', 1, '{CC}', 0, 0),
('JT', '黄麻包', 'jutebag', 1, '{CC}', 0, 0),
('JR', '大口瓶', 'jar', 1, '{CC}', 0, 0),
('JG', '带柄的水罐', 'jug', 1, '{CC}', 0, 0),
('JC', '矩形五加仑液体罐', 'jerrican,rectangular', 1, '{CC}', 0, 0),
('IZ', '堆/束/捆形式的锭', 'ingots,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('IN', '锭', 'ingot', 1, '{CC}', 0, 0),
('HR', '带盖的篮', '	hamper', 1, '{CC}', 0, 0),
('HG', '大啤酒桶	', 'hogshead', 1, '{CC}', 0, 0),
('GZ', '堆/束/捆形式的桁架', 'girders,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('GI', '桁架', '	girder', 1, '{CC}', 0, 0),
('GB', '气瓶', '	gas bottle', 1, '{CC}', 0, 0),
('FR', '框架', '	frame', 1, '{CC}', 0, 0),
('FP', '薄膜包装', '	filmpack', 1, '{CC}', 0, 0),
('FO', '底箱	', 'footlocker', 1, '{CC}', 0, 0),
('FL', '细颈瓶', 'flask', 1, '{CC}', 0, 0),
('FI', '小桶	', 'firkin', 1, '{CC}', 0, 0),
('FD', '框架板条箱', 'framed crate', 1, '{CC}', 0, 0),
('FC', '装水果板条箱', 'fruit crate', 1, '{CC}', 0, 0),
('EN', '包', 'envelope', 1, '{CC}', 0, 0),
('DR', '金属桶', 'drum', 1, '{CC}', 0, 0),
('DP', '加保护细颈坛', 'demijohn,protected', 1, '{CC}', 0, 0),
('DJ', '未加保护的细颈坛', 'demijohn,non-protected', 1, '{CC}', 0, 0),
('CZ', '帆布', 'canvas', 1, '{CC}', 0, 0),
('CY', '圆柱	', 'cylinder', 1, '{CC}', 0, 0),
('CX', '圆柱形罐', '	can,cylindrical', 1, '{CC}', 0, 0),
('CV', '包裹', '	cover', 1, '{CC}', 0, 0),
('CU', '杯', 'cup', 1, '{CC}', 0, 0),
('CT', '纸板箱', 'carton', 1, '{CC}', 0, 0),
('CS', '箱', 'case', 1, '{CC}', 0, 0),
('CR', '板条箱', 'crate', 1, '{CC}', 0, 0),
('CP', '加保护的带筐', 'carboy,protected', 1, '{CC}', 0, 0),
('CO', '未加保护的带筐', 'carboy,non-protected', 1, '{CC}', 0, 0),
('CL', '圈', 'coil', 1, '{CC}', 0, 0),
('CK', '木桶	', 'cask', 1, '{CC}', 0, 0),
('CJ', '屏蔽容器	', 'coffin', 1, '{CC}', 0, 0),
('CI', '金属罐', 'canister', 1, '{CC}', 0, 0),
('CH', '木箱', '	chest', 1, '{CC}', 0, 0),
('CG', '笼', 'cage', 1, '{CC}', 0, 0),
('CF', '保险箱', 'coffer', 1, '{CC}', 0, 0),
('CE', '柳条鱼篮', '	creel', 1, '{CC}', 0, 0),
('CC', '盛奶器', 'churn', 1, '{CC}', 0, 0),
('CB', '装啤酒板条箱', '	beer,crate', 1, '{CC}', 0, 0),
('CA', '矩形罐', 'can rectangular', 1, '{CC}', 0, 0),
('BZ', '堆/束/捆形式的钢条', 'bars,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('BY', '堆/束/捆形式板', 'board,in bundle/bunch/truss', 1, '{CC}', 0, 0),
('BX', '盒', 'box', 1, '{CC}', 0, 0),
('BV', '加保护的球型瓶', 'bottle,protected bulbous', 1, '{CC}', 0, 0),
('BU', '大桶	', 'butt', 1, '{CC}', 0, 0),
('BT', '纸卷	', 'bolt', 1, '{CC}', 0, 0),
('BS', '未加保护的球形瓶', 'bottle,non-protected,bu lbous', 1, '{CC}', 0, 0),
('BR', '棒', 'bar', 1, '{CC}', 0, 0),
('BQ', '加保护的圆柱形瓶', 'bottle,pr otected,cy lindrical', 1, '{CC}', 0, 0),
('BP', '加保护球型瓶', 'ballon,protected', 1, '{CC}', 0, 0),
('BO', '未加保护的圆柱形瓶', 'bottle,non-protected,cy lindrical', 1, '{CC}', 0, 0),
('BN', '未压缩包', 'bale,non-compressed', 1, '{CC}', 0, 0),
('BL', '已压缩包', 'bale,compressed', 1, '{CC}', 0, 0),
('BK', '筐', 'basket', 1, '{CC}', 0, 0),
('BJ', '吊桶	', 'bucket', 1, '{CC}', 0, 0),
('BI', '料箱', 'bin', 1, '{CC}', 0, 0),
('BH', '束', 'bunch', 1, '{CC}', 0, 0),
('BG', '袋', 'bag', 1, '{CC}', 0, 0),
('BF', '未加保护球型瓶', 'ballon,non-protected', 1, '{CC}', 0, 0),
('BE', '捆', 'bundle', 1, '{CC}', 0, 0),
('BD', '板', 'board', 1, '{CC}', 0, 0),
('BC', '带有瓶架的板条箱', 'bottle crate bottlerack', 1, '{CC}', 0, 0),
('BB', '细绳	', 'bobbin', 1, '{CC}', 0, 0),
('BA', '桶', 'barrel', 1, '{CC}', 0, 0),
('AT', '喷雾器瓶', '	atomizer', 1, '{CC}', 0, 0),
('AP', '加保护安瓿瓶', '	ampoule,protected', 1, '{CC}', 0, 0),
('AM', '未加保护安瓿瓶', 'ampoule,non-protecte', 1, '{CC}', 0, 0),
('AE', '按纽式喷雾器瓶', 'aerosol', 1, '{CC}', 0, 0)
;