ALTER TABLE `S_PR`
	ADD COLUMN `PR_WRITE_OFF_STATUS` TINYINT(4) NULL DEFAULT NULL AFTER `PR_STATUS`;
	
ALTER TABLE `S_PR`
	CHANGE COLUMN `PR_FIN_APPROVE_BY` `PR_FIN_APPROVE_BY` VARCHAR(32) NULL DEFAULT NULL AFTER `PR_REMARKS`,
	CHANGE COLUMN `PR_APPROVE_BY` `PR_APPROVE_BY` VARCHAR(32) NULL DEFAULT NULL AFTER `PR_FIN_APPROVE_DATE`;