ALTER TABLE `P_USER`
	ADD COLUMN `USER_DEFAULT_BRANCH` INT(11) NULL DEFAULT NULL AFTER `USER_DEFAULT_GROUP`;

ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_BRANCH_ID` INT NULL DEFAULT NULL AFTER `CONS_OPERATOR_NAME`,
	ADD COLUMN `CONS_BRANCH_NAME` VARCHAR(50) NULL DEFAULT NULL AFTER `CONS_BRANCH_ID`;

INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(9, '到港日期', 'SInvoice', 'invoSailDate', NULL);

INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(4, '启运国', 'FCustomsDeclaration', 'cudeLoadCountry', NULL),
(22, '委托单位', 'FConsign', 'custName', NULL),
(22, '集装箱号', 'FConsign', 'consContainerNo', NULL);