
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package haitai.edi;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-04-20T20:24:10.597+08:00
 * Generated source version: 2.7.14
 * 
 */
public class ProductServiceClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://impl.edi.haitai/", "ProductServiceImplService");
        QName portName = new QName("http://impl.edi.haitai/", "ProductServiceImplPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/ProductServiceImplPort"); 
        haitai.edi.ProductService client = service.getPort(portName,  haitai.edi.ProductService.class);
        
        // Insert code to invoke methods on the client here
    }

}