
package haitai.edi;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2015-01-26T15:49:39.043+08:00
 * Generated source version: 2.7.14
 * 
 */
 
public class ProductServiceServer{

    protected ProductServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new haitai.edi.impl.ProductServiceImpl();
        String address = "http://localhost:9090/ProductServiceImplPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ProductServiceServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 