
package haitai.edi.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.14
 * Mon Jan 26 15:22:03 CST 2015
 * Generated source version: 2.7.14
 */

@XmlRootElement(name = "SuspendResponse", namespace = "http://edi.haitai/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuspendResponse", namespace = "http://edi.haitai/")

public class SuspendResponse {


}

