ALTER TABLE `S_EXPENSE`
	ADD COLUMN `EXPE_INVOICE_FLAG` TINYINT(4) NULL DEFAULT '1' AFTER `EXPE_INVOICE_TITLE`;
ALTER TABLE `P_USER`
	ADD COLUMN `USER_NETWORK_FLAG` TINYINT(4) NULL DEFAULT '1' AFTER `USER_DEFAULT_ROLE`;

INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(1, '委托单位', 'FBl', 'custName', NULL),
(1, '提单类型', 'FBl', 'blType', NULL),
(1, '是否电放提单', 'FBl', 'istyId', 'getBillofLadingWay'),
(1, '操作员', 'FBl', 'userId', 'getOperatorName');