ALTER TABLE `S_EXPENSE`
	ADD COLUMN `EXPE_INVOICE_FLAG` TINYINT(4) NULL DEFAULT '1' AFTER `EXPE_INVOICE_TITLE`;
ALTER TABLE `P_USER`
	ADD COLUMN `USER_NETWORK_FLAG` TINYINT(4) NULL DEFAULT '1' AFTER `USER_DEFAULT_ROLE`;

