ALTER TABLE `F_CARGO`
	ADD COLUMN `PACK_CODE` VARCHAR(16) NULL DEFAULT NULL AFTER `PACK_ID`;
ALTER TABLE `F_CONTAINER`
	ADD COLUMN `COTY_CODE` VARCHAR(16) NULL DEFAULT NULL AFTER `COTY_ID`;
ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_DELIVERY_PLACE_CODE` VARCHAR(32) NULL DEFAULT NULL AFTER `CONS_DELIVERY_PLACE`,
	ADD COLUMN `CONS_DESTINATION_CODE` VARCHAR(32) NULL DEFAULT NULL AFTER `CONS_DESTINATION`;