--
-- 初始化 `G_PORT`
--
INSERT INTO `G_PORT` (`PORT_CODE`,`PORT_NAME_CN`,  `PORT_NAME_EN`, `PORT_TYPE`, `ACTIVE`, `COUN_CODE`, `VERSION`, `REMOVED`, `COMP_CODE`) VALUES
('AESHJ', '沙迦', 'Sharjah',  0, 1, 'AE', 0, 0, '{CC}'),
('AEPRA', '拉希德港', 'Port Rashid',  0, 1, 'AE', 0, 0, '{CC}'),
('AEKLF', '豪尔费坎','Khor al Fakkan（Khawr Fakkan）',  0, 1, 'AE', 0, 0, '{CC}'),
('AEJEA', '阿里山','Jebel Ali',  0, 1, 'AE', 0, 0, '{CC}'),
('AEFJR', '富查伊拉','Al Fujayrah',  0, 1, 'AE', 0, 0, '{CC}'),
('AEDXB', '迪拜','Dubai',  0, 1, 'AE', 0, 0, '{CC}'),
('AEAUH', '阿布扎比','Abu Dhabi',  0, 1, 'AE', 0, 0, '{CC}'),
('AGSJO', '圣约翰斯','St Johns',  0, 1, 'AG', 0, 0, '{CC}'),
('AIROA', '路德湾','The Road',  0, 1, 'AI', 0, 0, '{CC}'),
('ALVOA', '发罗拉','Vlora（Vlone）',  0, 1, 'AL', 0, 0, '{CC}'),
('ALSHG', '圣吉尼','Shengjin',  0, 1, 'AL', 0, 0, '{CC}'),
('ALSAR', '萨兰达','Sarande',  0, 1, 'AL', 0, 0, '{CC}'),
('ALDRZ', '都拉斯','Durres',  0, 1, 'AL', 0, 0, '{CC}'),
('ANWIL', '威廉斯塔德', 'Willemstad', 0, 1, 'AN', 0, 0, '{CC}'),
('ANPHI', '菲利普斯堡', 'Philipsburg', 0, 1, 'AN', 0, 0, '{CC}'),
('ANKRA', '克拉伦代克', 'Kralendijk', 0, 1, 'AN', 0, 0, '{CC}'),
('AOPLE', '亚历山大港', 'Porto Alexandre (Tombua)', 0, 1, 'AO', 0, 0, '{CC}'),
('AOPBN', '安博因港', 'Porto Amboim', 0, 1, 'AO', 0, 0, '{CC}'),
('AONDD', '松贝', 'Sumbe（Novo Redondo）', 0, 1, 'AO', 0, 0, '{CC}'),
('AOMSZ', '纳米贝', 'Namibe', 0, 1, 'AO', 0, 0, '{CC}'),
('AOLOB', '洛比托', 'Lobito', 0, 1, 'AO', 0, 0, '{CC}'),
('AOLAD', '罗安达', 'Luanda', 0, 1, 'AO', 0, 0, '{CC}'),
('AOCAB', '卡宾达', 'Cabinda', 0, 1, 'AO', 0, 0, '{CC}'),
('AOBUG', '本格拉', 'Benguela', 0, 1, 'AO', 0, 0, '{CC}'),
('ARUSH', '乌斯怀亚', 'Ushuaia', 0, 1, 'AR', 0, 0, '{CC}'),
('ARULA', '圣胡利安', 'San Julian', 0, 1, 'AR', 0, 0, '{CC}'),
('ARSSN', '圣塞瓦斯蒂安', 'San Sebastian', 0, 1, 'AR', 0, 0, '{CC}'),
('ARSNS', '圣尼古拉斯', 'San Nicolas de los Arroyos', 0, 1, 'AR', 0, 0, '{CC}'),
('ARRZA', '圣克鲁斯', 'Santa Cruz', 0, 1, 'AR', 0, 0, '{CC}'),
('ARROS', '罗萨里奥', 'Rosario', 0, 1, 'AR', 0, 0, '{CC}'),
('ARRGL', '里奥加耶戈斯', 'Rio Gallegos', 0, 1, 'AR', 0, 0, '{CC}'),
('ARQQN', '克肯', 'Quequen', 0, 1, 'AR', 0, 0, '{CC}'),
('ARPUD', '德塞阿多港', 'Puerto Deseado', 0, 1, 'AR', 0, 0, '{CC}'),
('ARPMY', '马德林港', 'Puerto Madryn', 0, 1, 'AR', 0, 0, '{CC}'),
('ARNEC', '内科切阿', 'Necochea', 0, 1, 'AR', 0, 0, '{CC}'),
('ARMDQ', '马德普拉塔', 'Mar del Plata', 0, 1, 'AR', 0, 0, '{CC}'),
('ARLPG', '拉普拉塔', 'La Plata', 0, 1, 'AR', 0, 0, '{CC}'),
('ARDME', '迪亚曼泰', 'Diamante', 0, 1, 'AR', 0, 0, '{CC}'),
('ARCVI', '奥利维亚', 'Caleta Olivia', 0, 1, 'AR', 0, 0, '{CC}'),
('ARCRD', '里瓦达维亚海军准将城', 'Comodoro Rivadavia', 0, 1, 'AR', 0, 0, '{CC}'),
('ARCMP', '坎帕纳', 'Campana', 0, 1, 'AR', 0, 0, '{CC}'),
('ARBUE', '布宜诺斯艾利斯', 'Buenos Aires', 0, 1, 'AR', 0, 0, '{CC}'),
('ARBHI', '布兰卡港', 'Bahia Blanca', 0, 1, 'AR', 0, 0, '{CC}'),
('ASPPG', '帕果帕果', 'Pago Pago', 0, 1, 'AS', 0, 0, '{CC}'),
('AUYAM', '扬皮桑德', 'Yampi Sound', 0, 1, 'AU', 0, 0, '{CC}'),
('AUWYA', '怀阿拉', 'Whyalla', 0, 1, 'AU', 0, 0, '{CC}'),
('AUWEI', '韦帕', 'Weipa', 0, 1, 'AU', 0, 0, '{CC}'),
('AUTSV', '汤斯维尔', 'Townsville', 0, 1, 'AU', 0, 0, '{CC}'),
('AUSYD', '悉尼', 'Sydney', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPUG', '奥古斯塔港', 'Port Augusta', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPTJ', '波特兰', 'Portland', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPPI', '皮里港', 'Port Pirie', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPLO', '林肯港', 'Port Lincoln', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPHE', '黑德兰港', 'Port Hedland', 0, 1, 'AU', 0, 0, '{CC}'),
('AUNTL', '纽卡斯尔', 'Newcastle', 0, 1, 'AU', 0, 0, '{CC}'),
('AUMKY', '麦凯', 'Mackay', 0, 1, 'AU', 0, 0, '{CC}'),
('AUMEL', '墨尔本', 'Melbourne', 0, 1, 'AU', 0, 0, '{CC}'),
('AUHBA', '霍巴特', 'Hobart', 0, 1, 'AU', 0, 0, '{CC}'),
('AUGLT', '格拉德斯通', 'Gladstone', 0, 1, 'AU', 0, 0, '{CC}'),
('AUGEX', '吉朗', 'Geelong', 0, 1, 'AU', 0, 0, '{CC}'),
('AUGET', '杰拉尔顿', 'Geraldton', 0, 1, 'AU', 0, 0, '{CC}'),
('AUFRE', '弗里曼特尔', 'Fremantle', 0, 1, 'AU', 0, 0, '{CC}'),
('AUDRW', '达尔文', 'Darwin', 0, 1, 'AU', 0, 0, '{CC}'),
('AUDAM', '丹皮尔', 'Dampier', 0, 1, 'AU', 0, 0, '{CC}'),
('AUCNS', '凯恩斯', 'Cairns', 0, 1, 'AU', 0, 0, '{CC}'),
('AUBUY', '班伯里', 'Bunbury', 0, 1, 'AU', 0, 0, '{CC}'),
('AUBNE', '布里斯班', 'Brisbane', 0, 1, 'AU', 0, 0, '{CC}'),
('AUALH', '奥尔巴尼', 'Albany', 0, 1, 'AU', 0, 0, '{CC}'),
('AUADL', '阿德莱德', 'Adelaide', 0, 1, 'AU', 0, 0, '{CC}'),
('AWSNL', '圣尼古拉斯湾', 'Sint Nicolaas', 0, 1, 'AW', 0, 0, '{CC}'),
('AWORJ', '奥拉涅斯塔德', 'Oranjestad', 0, 1, 'AW', 0, 0, '{CC}'),
('BBBGI', '布里奇敦', 'Bridgetown',  0, 1, 'BB', 0, 0, '{CC}'),
('BDMGL', '蒙拉', 'Mongla（Mungla）', 0, 1, 'BD', 0, 0, '{CC}'),
('BDKHL', '库尔纳', 'Khulna', 0, 1, 'BD', 0, 0, '{CC}'),
('BDCHL', '贾尔纳', 'Chalna',  0, 1, 'BD', 0, 0, '{CC}'),
('BDCGP', '吉大港', 'Chittagong', 0, 1, 'BD', 0, 0, '{CC}'),
('BEZEE', '泽布吕赫/泽布腊赫', 'Zeebrugge', 0, 1, 'BE', 0, 0, '{CC}'),
('BEOST', '奥斯坦德', 'Ostend (Oostende)', 0, 1, 'BE', 0, 0, '{CC}'),
('BEGNE', '根特', 'Gent (Ghent)', 0, 1, 'BE', 0, 0, '{CC}'),
('BEANR', '安特卫普', 'Antwerpen', 0, 1, 'BE', 0, 0, '{CC}'),
('BGVAR', '瓦尔纳', 'Varna', 0, 1, 'BG', 0, 0, '{CC}'),
('BGSOZ', '索佐波尔', 'Sozopol', 0, 1, 'BG', 0, 0, '{CC}'),
('BGNES', '纳塞巴尔', 'Nessebar', 0, 1, 'BG', 0, 0, '{CC}'),
('BGBOJ', '布尔加斯', 'Burgas', 0, 1, 'BG', 0, 0, '{CC}'),
('BHSIT', '锡特拉', 'Sitra', 0, 1, 'BH', 0, 0, '{CC}'),
('BHMIN', '米纳苏尔曼', 'Mina Sulman', 0, 1, 'BH', 0, 0, '{CC}'),
('BHMAN', '麦纳麦', 'Manama（Al Manamah）', 0, 1, 'BH', 0, 0, '{CC}'),
('BHBAH', '巴林', 'Bahrain', 0, 1, 'BH', 0, 0, '{CC}'),
('BJPTN', '波多诺伏', 'Porto-Novo', 0, 1, 'BJ', 0, 0, '{CC}'),
('BJCOO', '科托努', 'Cotonou',  0, 1, 'BJ', 0, 0, '{CC}'),
('BMSGE', '圣乔治', 'Saint George',  0, 1, 'BM', 0, 0, '{CC}'),
('BMBDA', '哈密尔顿', 'Hamilton', 0, 1, 'BM', 0, 0, '{CC}'),
('BNSER', '诗里亚', 'Seria', 0, 1, 'BM', 0, 0, '{CC}'),
('BNMUA', '麻拉', 'Muara',  0, 1, 'BM', 0, 0, '{CC}'),
('BNBWN', '斯里巴加湾港', 'Bandar Seri Begawan', 0, 1, 'BM', 0, 0, '{CC}'),
('BRVIX', '维多利亚', 'Vitoria', 0, 1, 'BR', 0, 0, '{CC}'),
('BRTUB', '图巴朗', 'Tubarao', 0, 1, 'BR', 0, 0, '{CC}'),
('BRTRM', '特拉曼达伊', 'Tramandai', 0, 1, 'BR', 0, 0, '{CC}'),
('BRSSZ', '桑托斯', 'Santos', 0, 1, 'BR', 0, 0, '{CC}'),
('BRSSO', '圣塞巴斯蒂昂', 'Sao Sebastiao',  0, 1, 'BR', 0, 0, '{CC}'),
('BRSSA', '萨尔瓦多', 'Salvador',  0, 1, 'BR', 0, 0, '{CC}'),
('BRSLZ', '圣路易斯', 'Sao Luis',  0, 1, 'BR', 0, 0, '{CC}'),
('BRSFS', '南圣弗朗西斯科', 'Sao Francisco do Sul',  0, 1, 'BR', 0, 0, '{CC}'),
('BRRIO', '里约热内卢', 'Rio de Janeiro',  0, 1, 'BR', 0, 0, '{CC}'),
('BRRIG', '里奥格兰德', 'Rio Grande',  0, 1, 'BR', 0, 0, '{CC}'),
('BRREC', '累西腓', 'Recife',  0, 1, 'BR', 0, 0, '{CC}'),
('BRPOA', '阿雷格里港', 'Porto Alegre',  0, 1, 'BR', 0, 0, '{CC}'),
('BRPNG', '巴拉那瓜', 'Paranagua',  0, 1, 'BR', 0, 0, '{CC}'),
('BRPET', '佩洛塔斯', 'Pelotas',  0, 1, 'BR', 0, 0, '{CC}'),
('BRNTR', '尼泰罗伊', 'Niteroi',  0, 1, 'BR', 0, 0, '{CC}'),
('BRNAT', '纳塔尔', 'Natal',  0, 1, 'BR', 0, 0, '{CC}'),
('BRMCZ', '马塞约', 'Maceio',  0, 1, 'BR', 0, 0, '{CC}'),
('BRMCP', '马卡帕', 'Macapa',  0, 1, 'BR', 0, 0, '{CC}'),
('BRMAO', '马瑙斯', 'Manaus',  0, 1, 'BR', 0, 0, '{CC}'),
('BRITJ', '伊塔雅伊', 'Itajai',  0, 1, 'BR', 0, 0, '{CC}'),
('BRIQI', '伊塔基', 'Itaqui',  0, 1, 'BR', 0, 0, '{CC}'),
('BRIOS', '伊列乌斯', 'Ilheus',  0, 1, 'BR', 0, 0, '{CC}'),
('BRIBB', '因比图巴', 'Imbituba',  0, 1, 'BR', 0, 0, '{CC}'),
('BRFOR', '福塔莱萨', 'Fortaleza',  0, 1, 'BR', 0, 0, '{CC}'),
('BRBEL', '贝伦', 'Belem',  0, 1, 'BR', 0, 0, '{CC}'),
('BRAJU', '阿拉卡茹', '	Aracaju',  0, 1, 'BR', 0, 0, '{CC}'),
('BRADR', '安格拉-杜斯雷斯', 'Angra dos Reis',  0, 1, 'BR', 0, 0, '{CC}'),
('BSNAS', '拿骚', 'Nassau',  0, 1, 'BR', 0, 0, '{CC}'),
('BSFPO', '弗里波特', 'Freeport',  0, 1, 'BR', 0, 0, '{CC}'),
('BZBZE', '伯利兹城', 'Belize City',  0, 1, 'BR', 0, 0, '{CC}'),
('CAYRH', '雅茅思', 'Yarmouth',  0, 1, 'CA', 0, 0, '{CC}'),
('CAVIC', '维多利亚', 'Victoria',  0, 1, 'CA', 0, 0, '{CC}'),
('CAVAN', '温哥华', 'Vancouver',  0, 1, 'CA', 0, 0, '{CC}'),
('CATRR', '三河城', 'Three Rivers（Trois-Rivieres）',  0, 1, 'CA', 0, 0, '{CC}'),
('CATOR', '多伦多', 'Toronto',  0, 1, 'CA', 0, 0, '{CC}'),
('CATHU', '散德湾', 'Thunder Bay',  0, 1, 'CA', 0, 0, '{CC}'),
('CASYD', '悉尼', 'Sydney',  0, 1, 'CA', 0, 0, '{CC}'),
('CASSM', '苏圣马丽', 'Sault Ste Marie',  0, 1, 'CA', 0, 0, '{CC}'),
('CASNI', '萨尔尼亚', 'Sarnia',  0, 1, 'CA', 0, 0, '{CC}'),
('CASJF', '圣约翰斯', 'St John s',  0, 1, 'CA', 0, 0, '{CC}'),
('CASJB', '圣约翰', 'St John',  0, 1, 'CA', 0, 0, '{CC}'),
('CASEI', '七岛', 'Sept-Iles',  0, 1, 'CA', 0, 0, '{CC}'),
('CAQUE', '魁北克', 'Quebec',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPTA', '塔西斯', 'Tahsis',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPRR', '鲁珀特港', 'Prince Rupert',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPOW', '鲍威尔', 'Powell River',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPCO', '科尔本港', 'Port Colborne',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPCA', '卡捷港', 'Port-Cartier',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPAF', '艾尔夫雷德港', 'Port-Alfred',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPAB', '艾伯尼港', 'Port Alberni',  0, 1, 'CA', 0, 0, '{CC}'),
('CANNO', '纳奈莫', 'Nanaimo',  0, 1, 'CA', 0, 0, '{CC}'),
('CAMTR', '蒙特利尔', 'Montreal',  0, 1, 'CA', 0, 0, '{CC}'),
('CAHAM', '哈密尔顿', 'Hamilton',  0, 1, 'CA', 0, 0, '{CC}'),
('CAHAL', '哈利法克斯', 'Halifax',  0, 1, 'CA', 0, 0, '{CC}'),
('CAGOR', '戈尔德里弗', 'Gold River',  0, 1, 'CA', 0, 0, '{CC}'),
('CACHV', '丘吉尔', 'Churchill',  0, 1, 'CA', 0, 0, '{CC}'),
('CACHA', '夏洛特敦', 'Charlottetown',  0, 1, 'CA', 0, 0, '{CC}'),
('CDMAT', '马塔迪', 'Matadi',  0, 1, 'CD', 0, 0, '{CC}'),
('CDBOA', '博马', 'Boma',  0, 1, 'CD', 0, 0, '{CC}'),
('CDBNW', '巴纳纳', 'Banana',  0, 1, 'CD', 0, 0, '{CC}'),
('CGPNR', '黑角', 'Pointe Noire',  0, 1, 'CG', 0, 0, '{CC}'),
('CGDJE', '杰诺港', 'Djeno Terminal',  0, 1, 'CG', 0, 0, '{CC}'),
('CIZSS', '萨桑德拉', 'Sassandra',  0, 1, 'CI', 0, 0, '{CC}'),
('CISPY', '圣佩德罗', 'San-Pedro',  0, 1, 'CI', 0, 0, '{CC}'),
('CIDAB', '达布', 'Dabou',  0, 1, 'CI', 0, 0, '{CC}'),
('CIABJ', '阿比让', 'Abidjan',  0, 1, 'CI', 0, 0, '{CC}'),
('CKRAR', '拉罗通加岛', 'Rarotonga',  0, 1, 'CK', 0, 0, '{CC}'),
('CKAVA', '阿瓦鲁阿', 'Avarua',  0, 1, 'CK', 0, 0, '{CC}'),
('CKARU', '阿鲁通加', 'Arutunga',  0, 1, 'CK', 0, 0, '{CC}'),
('CLZAL', '瓦尔迪维亚', 'Valdivia',  0, 1, 'CL', 0, 0, '{CC}'),
('CLWCA', '卡斯特罗', 'Castro',  0, 1, 'CL', 0, 0, '{CC}'),
('CLVAP', '瓦尔帕莱索', 'Valparaiso',  0, 1, 'CL', 0, 0, '{CC}'),
('CLTOQ', '托科皮亚', 'Tocopilla',  0, 1, 'CL', 0, 0, '{CC}'),
('CLTAL', '塔尔卡瓦诺', 'Talcahuano',  0, 1, 'CL', 0, 0, '{CC}'),
('CLSVE', '圣维森特', 'San Vicente',  0, 1, 'CL', 0, 0, '{CC}'),
('CLSAI', '圣安东尼奥', 'San Antonio',  0, 1, 'CL', 0, 0, '{CC}'),
('CLQTV', '金特罗', 'Quintero',  0, 1, 'CL', 0, 0, '{CC}'),
('CLQMC', '奎姆什', 'Quemchi',  0, 1, 'CL', 0, 0, '{CC}'),
('CLPUQ', '蓬塔阿雷纳斯', 'Punta Arenas',  0, 1, 'CL', 0, 0, '{CC}'),
('CLPMC', '蒙特港', 'Puerto Montt',  0, 1, 'CL', 0, 0, '{CC}'),
('CLMJS', '梅希约内斯', 'Mejillones',  0, 1, 'CL', 0, 0, '{CC}'),
('CLLQN', '利尔奎', 'Lirquen',  0, 1, 'CL', 0, 0, '{CC}'),
('CLIQQ', '伊基克', 'Iquique',  0, 1, 'CL', 0, 0, '{CC}'),
('CLHSO', '瓦斯科', 'Huasco',  0, 1, 'CL', 0, 0, '{CC}'),
('CLCQQ', '科金博', 'Coquimbo',  0, 1, 'CL', 0, 0, '{CC}'),
('CLCNR', '查尼亚拉尔', 'Chanaral',  0, 1, 'CL', 0, 0, '{CC}'),
('CLCLD', '卡尔德拉', 'Caldera',  0, 1, 'CL', 0, 0, '{CC}'),
('CLARI', '阿里卡', 'Arica',  0, 1, 'CL', 0, 0, '{CC}'),
('CLANF', '安托法加斯塔', 'Antofagasta',  0, 1, 'CL', 0, 0, '{CC}'),
('CMVCC', '维多利亚', 'Victoria', 0, 1, 'CL', 0, 0, '{CC}'),
('CMTKC', '蒂科', 'Tiko', 0, 1, 'CL', 0, 0, '{CC}'),
('CMKBI', '克里比', 'Kribi', 0, 1, 'CL', 0, 0, '{CC}'),
('CMDLA', '杜阿拉', 'Douala', 0, 1, 'CL', 0, 0, '{CC}'),
('CNZZU', '漳州', 'Zhangzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZUH', '珠海', 'Zhuhai', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZSN', '中山', 'Zhongshan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZPU', '乍浦', 'Zhapu', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZOS', '舟山', 'Zhoushan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZNG', '湛江', 'Zhanjiang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZJG', '张家港', 'Zhangjiagang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZHI', '镇海港', 'Zhenhaigang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZHE', '镇江', 'Zhenjiang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYZH', '扬州', 'Yangzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYUL', '榆林', 'Yulin', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYTN', '盐田', 'Yantian', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYTG', '烟台', 'Yantai', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYSA', '洋山港', 'Yangshangang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYPG', '洋浦', 'Yangpu', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYJI', '阳江', 'Yangjiang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYIK', '营口', 'Yingkou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNXYG', '秀屿', 'Xiuyu', 0, 1, 'CN', 0, 0, '{CC}'),
('CNXIS', '象山港', 'Xiangshangang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNXAM', '厦门', 'Xiamen', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWZO', '温州', 'Wenzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWUG', '吴淞', 'Wusong', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWLG', '温岭港', 'Wenlinggang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWGQ', '外高桥', 'Waigaoqiao', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWEI', '威海', 'Weihai', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTZU', '泰州', 'Taizhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTXG', '天津新港', 'Tianjinxingang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTNJ', '天津', 'Tianjin', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTGS', '唐山', 'Tangshan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTAZ', '台州', 'Taizhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTAC', '太仓', 'Taicang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSZH', '苏州', 'Suzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSZG', '深圳', 'Shenzhen', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSYA', '三亚', 'Sanya', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSWE', '汕尾', 'Shanwei', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSTG', '汕头', 'Shantou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSTB', '石头埠', 'Shitoubu', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSON', '松下', 'Songxia', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSHP', '秦皇岛', 'Qinhuangdao', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSHK', '蛇口', 'Shekou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSHG', '上海', 'Shanghai', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSHD', '石岛', 'Shidao', 0, 1, 'CN', 0, 0, '{CC}'),
('CNRZH', '日照', 'Rizhao', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQZJ', '泉州', 'Quanzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQZH', '钦州', 'Qinzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQSA', '企沙', 'Qisha', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQLN', '清澜', 'Qinglan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQDG', '青岛', 'Qingdao', 0, 1, 'CN', 0, 0, '{CC}'),
('CNPUT', '莆田', 'Putian', 0, 1, 'CN', 0, 0, '{CC}'),
('CNPTG', '普陀港', 'Putuogang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNPLI', '蓬莱', 'Penglai', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNTG', '南通', 'Nantong', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNSA', '南沙', 'Nansha', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNJG', '南京', 'Nanjing', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNIH', '宁海港', 'Ninghaigang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNDS', '宁德', 'Ningde', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNBG', '宁波', 'Ningbo', 0, 1, 'CN', 0, 0, '{CC}'),
('CNMWN', '妈湾', 'Mawan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNMSG', '梅山港', 'Meishangang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNMMI', '茂名', 'Maoming', 0, 1, 'CN', 0, 0, '{CC}'),
('CNMAW', '马尾', 'Mawei', 0, 1, 'CN', 0, 0, '{CC}'),
('CNLZO', '莱州', 'Laizhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNLYG', '连云港', 'Lianyungang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNLSN', '岚山', 'Lanshan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNLKU', '龙口', 'Longkou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJZU', '九洲', 'Jiuzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJTG', '京唐港', 'Jingtanggang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJNZ', '锦州', 'Jinzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJMN', '江门', 'Jiangmen', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJIS', '江山', 'Jiangshan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJIA', '江阴', 'Jiangyin', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJAX', '嘉兴', 'Jiaxing', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHXG', '海口新港', 'Haikouxingang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHUI', '惠州', 'Huizhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHUH', '黄骅', 'Huanghua', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHUD', '葫芦岛', 'Huludao', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHUA', '黄埔', 'Huangpu', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHMN', '虎门', 'Humen', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHME', '海门港', 'Haimengang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHIG', '海口', 'Haikou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHDO', '黄岛', 'Huangdao', 0, 1, 'CN', 0, 0, '{CC}'),
('CNGZG', '广州', 'Guangzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNGNA', '广澳', 'Guang ao', 0, 1, 'CN', 0, 0, '{CC}'),
('CNGHI', '广海', 'Guanghai', 0, 1, 'CN', 0, 0, '{CC}'),
('CNGAO', '高港', 'Gaogang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNFZG', '福州', 'Fuzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNFAN', '防城港', 'Fangchenggang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDYG', '东营', 'Dongying', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDXG', '大连新港', 'Dalianxingang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDSN', '东山', 'Dongshan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDOU', '斗门', 'Doumen', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDJT', '东角头', 'Dongjiaotou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDGG', '东莞', 'Dongguan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDDG', '丹东', 'Dandong', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDAX', '大榭港', 'Daxiegang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDAG', '大连', 'Dalian', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCZX', '常州', 'Changzhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCWN', '赤湾', 'Chiwan', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCSG', '穿山港', 'Chuanshangang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCOZ', '潮州', 'Chaozhou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCHY', '潮阳', 'Chaoyang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCHE', '城澳', 'Cheng ao', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCGS', '常熟', 'Changshu', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCFD', '曹妃甸', 'Caofeidian', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBSP', '八所', 'Basuo', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBSD', '宝山码头', 'Baoshanmatou', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBLG', '北仑港', 'Beilungang', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBJN', '北津', 'Beijin', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBIH', '北海', 'Beihai', 0, 1, 'CN', 0, 0, '{CC}'),
('COTRB', '图尔博', 'Turbo', 0, 1, 'CO', 0, 0, '{CC}'),
('COTCO', '图马科', 'Tumaco', 0, 1, 'CO', 0, 0, '{CC}'),
('COSMR', '圣玛尔塔', 'Santa Marta', 0, 1, 'CO', 0, 0, '{CC}'),
('COPCR', '卡雷尼奥港', 'Puerto Carreno', 0, 1, 'CO', 0, 0, '{CC}'),
('COCTG', '卡塔赫纳', 'Cartagena', 0, 1, 'CO', 0, 0, '{CC}'),
('COBUN', '布韦那文图拉', 'Buenaventura', 0, 1, 'CO', 0, 0, '{CC}'),
('COBAQ', '巴兰基利亚', 'Barranquilla', 0, 1, 'CO', 0, 0, '{CC}'),
('CRPAS', '彭塔雷纳斯', 'Puntarenas', 0, 1, 'CR', 0, 0, '{CC}'),
('CRLIO', '利蒙港', 'Puerto Limon', 0, 1, 'CR', 0, 0, '{CC}'),
('CRGLF', '戈尔菲托', 'Golfito', 0, 1, 'CR', 0, 0, '{CC}'),
('CRCAL', '卡尔德拉', 'Caldera', 0, 1, 'CR', 0, 0, '{CC}'),
('CUSCU', '圣地亚哥', 'Santiago de Cuba', 0, 1, 'CU', 0, 0, '{CC}'),
('CUSCS', '南圣克鲁斯', 'Santa Cruz del Sur', 0, 1, 'CU', 0, 0, '{CC}'),
('CUQMA', '马坦萨斯', 'Matanzas', 0, 1, 'CU', 0, 0, '{CC}'),
('CUMZO', '曼萨尼略', 'Manzanillo', 0, 1, 'CU', 0, 0, '{CC}'),
('CUICR', '尼卡罗', 'Nicaro', 0, 1, 'CU', 0, 0, '{CC}'),
('CUHAV', '哈瓦那', 'La Habana', 0, 1, 'CU', 0, 0, '{CC}'),
('CUCFG', '西恩富戈斯', 'Cienfuegos', 0, 1, 'CU', 0, 0, '{CC}'),
('CUCAR', '卡德纳斯', 'Cardenas', 0, 1, 'CU', 0, 0, '{CC}'),
('CUCAI', '凯巴连', 'Caibarien', 0, 1, 'CU', 0, 0, '{CC}'),
('CUANT', '安蒂亚', 'Antilla', 0, 1, 'CU', 0, 0, '{CC}'),
('CVRAI', '普拉亚', 'Praia', 0, 1, 'CV', 0, 0, '{CC}'),
('CVMIN', '明德卢', 'Mindelo', 0, 1, 'CV', 0, 0, '{CC}'),
('CYPFO', '帕福斯', 'Paphos', 0, 1, 'CY', 0, 0, '{CC}'),
('CYLMS', '利马索尔', 'Limassol', 0, 1, 'CY', 0, 0, '{CC}'),
('CYLCA', '拉纳卡', 'Larnaca', 0, 1, 'CY', 0, 0, '{CC}'),
('CYFMG', '法马古斯塔', 'Famagusta', 0, 1, 'CY', 0, 0, '{CC}'),
('DEWVN', '威廉港', 'Wilhelmshaven', 0, 1, 'DE', 0, 0, '{CC}'),
('DEWIS', '维斯马', 'Wismar', 0, 1, 'DE', 0, 0, '{CC}'),
('DERSK', '罗斯托克', 'Rostock', 0, 1, 'DE', 0, 0, '{CC}'),
('DELBC', '吕贝克', 'Lubeck', 0, 1, 'DE', 0, 0, '{CC}'),
('DEKEL', '基尔', 'Kiel', 0, 1, 'DE', 0, 0, '{CC}'),
('DEHAM', '汉堡', 'Hamburg', 0, 1, 'DE', 0, 0, '{CC}'),
('DEEME', '埃姆登', 'Emden', 0, 1, 'DE', 0, 0, '{CC}'),
('DECUX', '库克斯港', 'Cuxhaven', 0, 1, 'DE', 0, 0, '{CC}'),
('DECGN', '科隆', 'Koln（Cologne）', 0, 1, 'DE', 0, 0, '{CC}'),
('DEBRV', '不来梅港', 'Bremerhaven', 0, 1, 'DE', 0, 0, '{CC}'),
('DEBRE', '不来梅', 'Bremen', 0, 1, 'DE', 0, 0, '{CC}'),
('DEBRB', '布伦斯比特尔', 'Brunsbuttel', 0, 1, 'DE', 0, 0, '{CC}'),
('DJJIB', '吉布提', 'Djibouti', 0, 1, 'DJ', 0, 0, '{CC}'),
('DKODE', '欧登塞', 'Odense', 0, 1, 'DK', 0, 0, '{CC}'),
('DKKAL', '凯隆堡', 'Kalundborg', 0, 1, 'DK', 0, 0, '{CC}'),
('DKHLS', '赫尔辛格', 'Helsingor', 0, 1, 'DK', 0, 0, '{CC}'),
('DKFRC', '腓特烈西亚', 'Fredericia', 0, 1, 'DK', 0, 0, '{CC}'),
('DKFDH', '腓特烈港', 'Frederikshavn', 0, 1, 'DK', 0, 0, '{CC}'),
('DKEBJ', '埃斯比约', 'Esbjerg', 0, 1, 'DK', 0, 0, '{CC}'),
('DKCPH', '哥本哈根', 'Kobenhavn（Copenhagen）', 0, 1, 'DK', 0, 0, '{CC}'),
('DKAAR', '奥胡斯', 'Arhus', 0, 1, 'DK', 0, 0, '{CC}'),
('DKAAL', '奥尔堡', 'Aalborg', 0, 1, 'DK', 0, 0, '{CC}'),
('DMRSU', '罗索', 'Roseau', 0, 1, 'DM', 0, 0, '{CC}'),
('DOSPM', '圣佩得罗德马科里斯', '	San Pedro de Macoris', 0, 1, 'DO', 0, 0, '{CC}'),
('DOSDQ', '圣多明各', 'Santo Domingo', 0, 1, 'DO', 0, 0, '{CC}'),
('DOPOP', '普拉塔港', 'Puerto Plata', 0, 1, 'DO', 0, 0, '{CC}'),
('DOLRM', '拉罗马纳', 'La Romana', 0, 1, 'DO', 0, 0, '{CC}'),
('DOHAI', '海纳', 'Rio Haina', 0, 1, 'DO', 0, 0, '{CC}'),
('DOBRX', '巴拉奥纳', 'Barahona', 0, 1, 'DO', 0, 0, '{CC}'),
('DZTEN', '提奈斯', 'Tenes', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZSKI', '斯基克达', '	Skikda', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZORN', '奥兰', 'Oran', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZDJI', '吉杰勒', 'Djidjelli（Jijel）', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZBJA', '贝贾亚', 'Bejaia', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZAZW', '阿尔泽', 'Arzew', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZALG', '阿尔及尔', 'Alger (Algiers)', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZAAE', '安纳巴', 'Annaba', 0, 1, 'DZ', 0, 0, '{CC}'),
('ECSNC', '萨利纳斯', 'Salinas', 0, 1, 'EC', 0, 0, '{CC}'),
('ECMEC', '曼塔', 'Manta', 0, 1, 'EC', 0, 0, '{CC}'),
('ECGYE', '瓜亚基尔', 'Guayaquil', 0, 1, 'EC', 0, 0, '{CC}'),
('ECESM', '埃斯梅拉达斯', 'Esmeraldas', 0, 1, 'EC', 0, 0, '{CC}'),
('ECBHA', '卡拉克斯港', 'Bahia de Caraquez', 0, 1, 'EC', 0, 0, '{CC}'),
('EETLL', '塔林', 'Tallinn', 0, 1, 'EE', 0, 0, '{CC}'),
('EEPRN', '派尔努/皮亚尔努', 'Parnu', 0, 1, 'EE', 0, 0, '{CC}'),
('EGSUZ', '苏伊士', 'El Suweis', 0, 1, 'EG', 0, 0, '{CC}'),
('EGSGA', '塞法杰', 'Safaga', 0, 1, 'EG', 0, 0, '{CC}'),
('EGRAG', '拉斯加里卜', 'Ras Gharib', 0, 1, 'EG', 0, 0, '{CC}'),
('EGPSD', '塞得港', 'Port Said', 0, 1, 'EG', 0, 0, '{CC}'),
('EGDAM', '达米埃塔', 'Damietta', 0, 1, 'EG', 0, 0, '{CC}'),
('EGAZA', '阿布宰尼迈', 'Abu Zenimah', 0, 1, 'EG', 0, 0, '{CC}'),
('EGALY', '亚历山大', 'El Iskandariya', 0, 1, 'EG', 0, 0, '{CC}'),
('EGADA', '阿代比耶', 'Adabiya', 0, 1, 'EG', 0, 0, '{CC}'),
('EHVIC', '达赫拉', 'Ad Dakhla', 0, 1, 'EH', 0, 0, '{CC}'),
('ERMSW', '马萨瓦', 'Massawa (Mitsiwa)', 0, 1, 'EH', 0, 0, '{CC}'),
('ERASA', '阿萨布', 'Assab', 0, 1, 'EH', 0, 0, '{CC}'),
('ESVLC', '巴伦西亚', 'Valencia', 0, 1, 'ES', 0, 0, '{CC}'),
('ESVGO', '维哥', 'Vigo', 0, 1, 'ES', 0, 0, '{CC}'),
('ESTAR', '塔拉戈纳', 'Tarragona', 0, 1, 'ES', 0, 0, '{CC}'),
('ESSVQ', '塞维利亚', 'Sevilla', 0, 1, 'ES', 0, 0, '{CC}'),
('ESSDR', '桑坦德', 'Santander', 0, 1, 'ES', 0, 0, '{CC}'),
('ESSCT', '圣克鲁斯', 'Santa Cruz de Tenerife', 0, 1, 'ES', 0, 0, '{CC}'),
('ESSAG', '萨贡托', 'Sagunto', 0, 1, 'ES', 0, 0, '{CC}'),
('ESROT', '罗塔', 'Rota', 0, 1, 'ES', 0, 0, '{CC}'),
('ESPMI', '帕尔马', 'Palma de Mallorca', 0, 1, 'ES', 0, 0, '{CC}'),
('ESPAS', '帕萨赫斯', 'Pasajes', 0, 1, 'ES', 0, 0, '{CC}'),
('ESMLN', '梅利利亚', 'Melilla', 0, 1, 'ES', 0, 0, '{CC}'),
('ESLPA', '拉斯帕尔马斯', 'Las Palmas', 0, 1, 'ES', 0, 0, '{CC}'),
('ESLEI', '阿尔梅里亚', 'Almeria', 0, 1, 'ES', 0, 0, '{CC}'),
('ESLCG', '拉科鲁尼亚', 'La Coruna', 0, 1, 'ES', 0, 0, '{CC}'),
('ESGIJ', '希洪', 'Gijon', 0, 1, 'ES', 0, 0, '{CC}'),
('ESFUE', '罗萨里奥港', 'Puerto del Rosario-Fuerteventura', 0, 1, 'ES', 0, 0, '{CC}'),
('ESFRO', '费罗尔', 'Ferrol', 0, 1, 'ES', 0, 0, '{CC}'),
('ESCEU', '休达', 'Ceuta', 0, 1, 'ES', 0, 0, '{CC}'),
('ESCAR', '卡塔赫纳', 'Cartagena', 0, 1, 'ES', 0, 0, '{CC}'),
('ESCAD', '加的斯', 'Cadiz', 0, 1, 'ES', 0, 0, '{CC}'),
('ESBIO', '毕尔巴鄂', 'Bilbao', 0, 1, 'ES', 0, 0, '{CC}'),
('ESBCN', '巴塞罗那', 'Barcelona', 0, 1, 'ES', 0, 0, '{CC}'),
('ESAVS', '阿维莱斯', 'Aviles', 0, 1, 'ES', 0, 0, '{CC}'),
('ESALG', '阿尔赫西拉斯', 'Algeciras', 0, 1, 'ES', 0, 0, '{CC}'),
('ESALC', '阿利坎特', 'Alicante', 0, 1, 'ES', 0, 0, '{CC}'),
('ESAGP', '马拉加', 'Malaga', 0, 1, 'ES', 0, 0, '{CC}'),
('ESACE', '阿雷西费', 'Arrecife de Lanzarote', 0, 1, 'ES', 0, 0, '{CC}'),
('FIVAA', '瓦萨', 'Vaasa (Vasa)', 0, 1, 'FI', 0, 0, '{CC}'),
('FITOR', '托尔尼奥', 'Tornio (Tornea)', 0, 1, 'FI', 0, 0, '{CC}'),
('FITKU', '图尔库', 'Turku (Abo)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIRAU', '劳马', 'Rauma (Raumo)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIPOR', '波里', 'Pori (Bjorneborg)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIOLU', '奥卢', 'Oulu', 0, 1, 'FI', 0, 0, '{CC}'),
('FIKTK', '科特卡', 'Kotka', 0, 1, 'FI', 0, 0, '{CC}'),
('FIKRS', '克里斯蒂娜城', 'Kristiinankaupunki (Kristinestad)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIKOK', '科科拉', 'Kokkola (Karleby)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIKEM', '凯米', 'Kemi', 0, 1, 'FI', 0, 0, '{CC}'),
('FIHMN', '哈米纳', 'Hamina (Fredrikshamn)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIHKO', '汉科', 'Hango (Hanko)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIHEL', '赫尔辛基', 'Helsinki (Helsingfors)', 0, 1, 'FI', 0, 0, '{CC}'),
('FJSUV', '苏瓦', 'Suva', 0, 1, 'FJ', 0, 0, '{CC}'),
('FJLTK', '劳托卡', 'Lautoka', 0, 1, 'FJ', 0, 0, '{CC}'),
('FJLBS', '兰巴萨', 'Labasa(Lambasa)', 0, 1, 'FJ', 0, 0, '{CC}'),
('FKPSY', '斯坦利港', 'Port Stanley', 0, 1, 'FK', 0, 0, '{CC}'),
('FMYAP', '雅浦', 'Yap', 0, 1, 'FM', 0, 0, '{CC}'),
('FMTKK', '丘克群岛', 'Chuuk (Truk)', 0, 1, 'FM', 0, 0, '{CC}'),
('FMPNI', '波纳佩', 'Pohnpei', 0, 1, 'FM', 0, 0, '{CC}'),
('FOVES', '韦斯特门港', 'Vestmanhavn', 0, 1, 'FO', 0, 0, '{CC}'),
('FOTHO', '托尔斯港', 'Thorshavn', 0, 1, 'FO', 0, 0, '{CC}'),
('FRURO', '鲁昂', 'Rouen', 0, 1, 'FR', 0, 0, '{CC}'),
('FRTLN', '土伦', 'Toulon', 0, 1, 'FR', 0, 0, '{CC}'),
('FRSNR', '圣纳泽尔', 'St Nazaire', 0, 1, 'FR', 0, 0, '{CC}'),
('FRSML', '圣马洛', 'St Malo', 0, 1, 'FR', 0, 0, '{CC}'),
('FRSET', '塞特', 'Sete', 0, 1, 'FR', 0, 0, '{CC}'),
('FRNTE', '南特', 'Nantes', 0, 1, 'FR', 0, 0, '{CC}'),
('FRNCE', '尼斯', 'Nice', 0, 1, 'FR', 0, 0, '{CC}'),
('FRMRS', '马赛', 'Marseille', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLRT', '洛里昂', 'Lorient', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLRH', '拉罗谢尔', 'La Rochelle', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLEH', '勒阿弗尔', 'Le Havre', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLCT', '拉西约塔', 'La Ciotat', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLAV', '拉瓦拉', 'Lavera', 0, 1, 'FR', 0, 0, '{CC}'),
('FRFOS', '福斯', 'Fos-sur-Mer', 0, 1, 'FR', 0, 0, '{CC}'),
('FRDPE', '迪耶普', 'Dieppe', 0, 1, 'FR', 0, 0, '{CC}'),
('FRDKK', '敦刻尔克', 'Dunkerque', 0, 1, 'FR', 0, 0, '{CC}'),
('FRCQF', '加来', 'Calais', 0, 1, 'FR', 0, 0, '{CC}'),
('FRCFR', '卡昂', 'Caen', 0, 1, 'FR', 0, 0, '{CC}'),
('FRCER', '瑟堡', 'Cherbourg', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBOL', '布洛涅', 'Boulogne-sur-Mer', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBOD', '波尔多', 'Bordeaux', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBIA', '巴斯蒂亚', 'Bastia', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBES', '布雷斯特', 'Brest', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBAY', '巴约讷', 'Bayonne', 0, 1, 'FR', 0, 0, '{CC}'),
('FRAJA', '阿雅克修', 'Ajaccio', 0, 1, 'FR', 0, 0, '{CC}'),
('GAPOG', '让蒂尔港', 'Port Gentil', 0, 1, 'FR', 0, 0, '{CC}'),
('GAOWE', '奥文多', 'Owendo', 0, 1, 'FR', 0, 0, '{CC}'),
('GALBV', '利伯维尔', 'Libreville', 0, 1, 'FR', 0, 0, '{CC}'),
('GACLZ', '洛佩斯角', 'Cap Lopez', 0, 1, 'FR', 0, 0, '{CC}'),
('GBTIL', '蒂尔伯里', 'Tilbury', 0, 1, 'GB', 0, 0, '{CC}'),
('GBTEE', '提斯港', 'Teesport', 0, 1, 'GB', 0, 0, '{CC}'),
('GBSWA', '斯旺西', 'Swansea', 0, 1, 'GB', 0, 0, '{CC}'),
('GBSUN', '森德兰', 'Sunderland', 0, 1, 'GB', 0, 0, '{CC}'),
('GBSOU', '南安普顿', 'Southampton', 0, 1, 'GB', 0, 0, '{CC}'),
('GBSHO', '肖勒姆', 'Shoreham', 0, 1, 'GB', 0, 0, '{CC}'),
('GBPTB', '塔尔伯特港', 'Port Talbot', 0, 1, 'GB', 0, 0, '{CC}'),
('GBPME', '朴次茅斯', 'Portsmouth', 0, 1, 'GB', 0, 0, '{CC}'),
('GBPLY', '普利茅斯', 'Plymouth', 0, 1, 'GB', 0, 0, '{CC}'),
('GBNPT', '纽波特', 'Newport', 0, 1, 'GB', 0, 0, '{CC}'),
('GBNCL', '纽卡斯尔', 'Newcastle upon Tyne', 0, 1, 'GB', 0, 0, '{CC}'),
('GBMTH', '梅西尔', 'Methil', 0, 1, 'GB', 0, 0, '{CC}'),
('GBMNC', '曼彻斯特', 'Manchester', 0, 1, 'GB', 0, 0, '{CC}'),
('GBMLF', '米尔福德港', 'Milford Haven', 0, 1, 'GB', 0, 0, '{CC}'),
('GBMID', '米德尔斯伯勒', 'Middlesbrough', 0, 1, 'GB', 0, 0, '{CC}'),
('GBLON', '伦敦', 'London', 0, 1, 'GB', 0, 0, '{CC}'),
('GBLIV', '利物浦', 'Liverpool', 0, 1, 'GB', 0, 0, '{CC}'),
('GBLEI', '利斯', 'Leith', 0, 1, 'GB', 0, 0, '{CC}'),
('GBLDY', '伦敦德里', 'Londonderry', 0, 1, 'GB', 0, 0, '{CC}'),
('GBIPS', '伊普斯威奇', 'Ipswich', 0, 1, 'GB', 0, 0, '{CC}'),
('GBIMM', '伊明赫姆', 'Immingham', 0, 1, 'GB', 0, 0, '{CC}'),
('GBHUL', '赫尔', 'Hull', 0, 1, 'GB', 0, 0, '{CC}'),
('GBHTP', '哈特尔浦', 'Hartlepool', 0, 1, 'GB', 0, 0, '{CC}'),
('GBHRW', '哈里奇', 'Harwich', 0, 1, 'GB', 0, 0, '{CC}'),
('GBGRG', '格兰奇茅斯', 'Grangemouth', 0, 1, 'GB', 0, 0, '{CC}'),
('GBGLW', '格拉斯哥', 'Glasgow', 0, 1, 'GB', 0, 0, '{CC}'),
('GBFXT', '弗利克斯托', 'Felixstowe', 0, 1, 'GB', 0, 0, '{CC}'),
('GBFAL', '法尔茅斯', 'Falmouth', 0, 1, 'GB', 0, 0, '{CC}'),
('GBDVR', '多佛尔', 'Dover', 0, 1, 'GB', 0, 0, '{CC}'),
('GBDUN', '邓迪', 'Dundee', 0, 1, 'GB', 0, 0, '{CC}'),
('GBCYP', '克莱德港', 'Clydeport', 0, 1, 'GB', 0, 0, '{CC}'),
('GBCDF', '加的夫', 'Cardiff', 0, 1, 'GB', 0, 0, '{CC}'),
('GBBRS', '布里斯托尔', 'Bristol', 0, 1, 'GB', 0, 0, '{CC}'),
('GBBOS', '波士顿', 'Boston', 0, 1, 'GB', 0, 0, '{CC}'),
('GBBID', '比迪福德', 'Bideford', 0, 1, 'GB', 0, 0, '{CC}'),
('GBBEL', '贝尔法斯特', 'Belfast', 0, 1, 'GB', 0, 0, '{CC}'),
('GBABD', '阿伯丁', 'Aberdeen', 0, 1, 'GB', 0, 0, '{CC}'),
('GDSTG', '圣乔治', 'Saint George s', 0, 1, 'GD', 0, 0, '{CC}'),
('GEPTI', '波季', 'Poti', 0, 1, 'GE', 0, 0, '{CC}'),
('GEBUS', '巴统', 'Batumi', 0, 1, 'GE', 0, 0, '{CC}'),
('GFQKR', '库鲁', 'Kourou', 0, 1, 'GF', 0, 0, '{CC}'),
('GFCAY', '卡宴', 'Cayenne', 0, 1, 'GF', 0, 0, '{CC}'),
('GGSPT', '圣彼得港', 'St Peter Port', 0, 1, 'GG', 0, 0, '{CC}'),
('GHWEA', '温尼巴', 'Winneba', 0, 1, 'GH', 0, 0, '{CC}'),
('GHTKD', '塔科拉迪', 'Takoradi', 0, 1, 'GH', 0, 0, '{CC}'),
('GHTEM', '特马', 'Tema', 0, 1, 'GH', 0, 0, '{CC}'),
('GHCCT', '海岸角', 'Cape Coast', 0, 1, 'GH', 0, 0, '{CC}'),
('GIGIB', '直布罗陀', 'Gibraltar', 0, 1, 'GI', 0, 0, '{CC}'),
('GLUAK', '纳萨尔苏瓦克', 'Narsarsuaq', 0, 1, 'GI', 0, 0, '{CC}'),
('GLJSU', '马尼措克', 'Maniitsoq (Sukkertoppen)', 0, 1, 'GI', 0, 0, '{CC}'),
('GLJEG', '奥希奥特', 'Aasiaat (Egedesminde)', 0, 1, 'GI', 0, 0, '{CC}'),
('GLGOH', '努克', 'Nuuk (Godthaab)', 0, 1, 'GI', 0, 0, '{CC}'),
('GMBJL', '班珠尔', 'Banjul', 0, 1, 'GM', 0, 0, '{CC}'),
('GNKMR', '卡姆萨尔', 'Port-Kamsar', 0, 1, 'GN', 0, 0, '{CC}'),
('GNCKY', '科纳克里', 'Conakry', 0, 1, 'GN', 0, 0, '{CC}'),
('GPPTP', '皮特尔角城', 'Pointe-a-Pitre', 0, 1, 'GP', 0, 0, '{CC}'),
('GPBBR', '巴斯特尔', 'Basse-Terre', 0, 1, 'GP', 0, 0, '{CC}'),
('GQSSG','马拉博', 'Malabo', 0, 1, 'GQ', 0, 0, '{CC}'),
('GQBSG', '巴塔', 'Bata', 0, 1, 'GQ', 0, 0, '{CC}'),
('GRVOL', '沃洛斯', 'Volos', 0, 1, 'GR', 0, 0, '{CC}'),
('GRSKG', '塞萨洛尼基', 'Thessaloniki', 0, 1, 'GR', 0, 0, '{CC}'),
('GRRHO', '罗得', 'Rhodes', 0, 1, 'GR', 0, 0, '{CC}'),
('GRPIR', '比雷埃夫斯', 'Piraeus', 0, 1, 'GR', 0, 0, '{CC}'),
('GRMJT', '米提林尼', 'Mitylene', 0, 1, 'GR', 0, 0, '{CC}'),
('GRMGR', '迈加拉', 'Megara', 0, 1, 'GR', 0, 0, '{CC}'),
('GRKVA', '卡瓦拉', 'Kavala', 0, 1, 'GR', 0, 0, '{CC}'),
('GRKLX', '卡拉迈', 'Kalamata', 0, 1, 'GR', 0, 0, '{CC}'),
('GRJSY', '锡罗斯', 'Syros（Syra）', 0, 1, 'GR', 0, 0, '{CC}'),
('GRJKH', '希俄斯', 'Chios', 0, 1, 'GR', 0, 0, '{CC}'),
('GRITA', '伊泰阿', 'Itea', 0, 1, 'GR', 0, 0, '{CC}'),
('GRHER', '伊拉克利翁', 'Iraklion（Heraklion）', 0, 1, 'GR', 0, 0, '{CC}'),
('GRGPA', '帕特雷', 'Patras', 0, 1, 'GR', 0, 0, '{CC}'),
('GTSTC', '圣托马斯德卡斯蒂利亚', 'Puerto Santo Tomas de Castilla', 0, 1, 'GT', 0, 0, '{CC}'),
('GTSNJ', '圣何塞', 'San Jose', 0, 1, 'GT', 0, 0, '{CC}'),
('GTPRQ', '夸特扎尔港', 'Puerto Quetzal', 0, 1, 'GT', 0, 0, '{CC}'),
('GTPBR', '巴里奥斯港', 'Puerto Barrios', 0, 1, 'GT', 0, 0, '{CC}'),
('GUGUM', '关岛', 'Guam', 0, 1, 'GU', 0, 0, '{CC}'),
('GUAPR', '阿普拉', 'Apra', 0, 1, 'GU', 0, 0, '{CC}'),
('GUAGA', '阿加尼亚', 'Agana', 0, 1, 'GU', 0, 0, '{CC}'),
('GWOXB', '比绍', 'Bissau', 0, 1, 'GW', 0, 0, '{CC}'),
('GWCAC', '卡谢马', 'Cacheu', 0, 1, 'GW', 0, 0, '{CC}'),
('GWBOL', '博拉多', 'Bolama', 0, 1, 'GW', 0, 0, '{CC}'),
('GYNAM', '新阿姆斯特丹', 'New Amsterdam', 0, 1, 'GY', 0, 0, '{CC}'),
('GYGEO', '乔治敦', 'Georgetown', 0, 1, 'GY', 0, 0, '{CC}'),
('HKHKG', '香港', 'Hong Kong', 0, 1, 'HK', 0, 0, '{CC}'),
('HNTEA', '特拉', 'Tela', 0, 1, 'HN', 0, 0, '{CC}'),
('HNSLO', '圣洛伦索', 'San Lorenzo', 0, 1, 'HN', 0, 0, '{CC}'),
('HNPCR', '科尔特斯港', 'Puerto Cortes', 0, 1, 'HN', 0, 0, '{CC}'),
('HNPCA', '卡斯蒂利亚港', 'Puerto Castilla', 0, 1, 'HN', 0, 0, '{CC}'),
('HRZAD', '扎达尔', 'Zadar', 0, 1, 'HR', 0, 0, '{CC}'),
('HRSPU', '斯普利特', 'Split', 0, 1, 'HR', 0, 0, '{CC}'),
('HRRJK', '里耶卡', 'Rijeka', 0, 1, 'HR', 0, 0, '{CC}'),
('HRPUY', '普拉', 'Pula', 0, 1, 'HR', 0, 0, '{CC}'),
('HRPLE', '普洛切', 'Ploce', 0, 1, 'HR', 0, 0, '{CC}'),
('HRDBV', '杜布罗夫尼克', 'Dubrovnik', 0, 1, 'HR', 0, 0, '{CC}'),
('HTPAP', '太子港', 'Port-au-Prince', 0, 1, 'HR', 0, 0, '{CC}'),
('HTGVS', '戈纳伊夫', 'Gonaives', 0, 1, 'HR', 0, 0, '{CC}'),
('HTCAP', '海地角', 'Cap-Haitien', 0, 1, 'HR', 0, 0, '{CC}'),
('HTACA', '莱凯', 'Les Cayes', 0, 1, 'HR', 0, 0, '{CC}'),
('IDUPG', '乌戎潘当', 'Ujung Pandang', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTTE', '德那第', 'Ternate', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTRH', '打拉根', 'Tarahan', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTJQ', '丹戎潘丹', 'Tanjung Pandan', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTBR', '直落巴由', 'Telukbayur', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTAN', '丹戎乌班', 'Tanjunguban', 0, 1, 'ID', 0, 0, '{CC}'),
('IDSUB', '泗水', 'Surabaya', 0, 1, 'ID', 0, 0, '{CC}'),
('IDSRG', '三宝垄', 'Semarang', 0, 1, 'ID', 0, 0, '{CC}'),
('IDSBG', '沙璜', 'Sabang', 0, 1, 'ID', 0, 0, '{CC}'),
('IDSAT', '桑坦港', 'Santan Terminal', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPRO', '普罗博林戈', 'Probolinggo', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPNK', '坤甸', 'Pontianak', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPNJ', '潘姜', 'Panjang', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPLM', '巨港', 'Palembang', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPKS', '庞卡兰苏苏', 'Pangkalan Susu', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPEX', '北加浪岸', 'Pekalongan', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPDG', '巴东', 'Padang', 0, 1, 'ID', 0, 0, '{CC}'),
('IDMDC', '万鸦老', 'Menado', 0, 1, 'ID', 0, 0, '{CC}'),
('IDKOE', '古邦', 'Kupang', 0, 1, 'ID', 0, 0, '{CC}'),
('IDJKT', '雅加达', 'Jakarta', 0, 1, 'ID', 0, 0, '{CC}'),
('IDDUM', '杜迈', 'Dumai', 0, 1, 'ID', 0, 0, '{CC}'),
('IDDJJ', '查亚普拉', 'Jayapura', 0, 1, 'ID', 0, 0, '{CC}'),
('IDCXP', '芝拉扎', 'Cilacap', 0, 1, 'ID', 0, 0, '{CC}'),
('IDBPN', '巴厘巴板', 'Balikpapan', 0, 1, 'ID', 0, 0, '{CC}'),
('IDBLW', '勿拉湾', 'Belawan', 0, 1, 'ID', 0, 0, '{CC}'),
('IDBJU', '巴纽旺宣', 'Banjuwangi', 0, 1, 'ID', 0, 0, '{CC}'),
('IDBIT', '比通', 'Bitung', 0, 1, 'ID', 0, 0, '{CC}'),
('IDAMQ', '安汶', 'Ambon', 0, 1, 'ID', 0, 0, '{CC}'),
('IEWAT', '沃特福德', 'Waterford', 0, 1, 'IE', 0, 0, '{CC}'),
('IEORK', '科克', 'Cork', 0, 1, 'IE', 0, 0, '{CC}'),
('IELMK', '利默里克', 'Limerick', 0, 1, 'IE', 0, 0, '{CC}'),
('IEGWY', '戈尔韦', 'Galway', 0, 1, 'IE', 0, 0, '{CC}'),
('IEFOV', '福因斯', 'Foynes', 0, 1, 'IE', 0, 0, '{CC}'),
('IEDUB', '都柏林', 'Dublin', 0, 1, 'IE', 0, 0, '{CC}'),
('IEDLG', '邓莱里', 'Dun Laoghaire', 0, 1, 'IE', 0, 0, '{CC}'),
('IEBYT', '班特里', 'Bantry', 0, 1, 'IE', 0, 0, '{CC}'),
('ILTLV', '特拉维夫-雅法', 'Tel Aviv-Yafo', 0, 1, 'IE', 0, 0, '{CC}'),
('ILHFA', '海法', 'Haifa', 0, 1, 'IE', 0, 0, '{CC}'),
('ILETH', '埃拉特', 'Eilat（Eilath）', 0, 1, 'IE', 0, 0, '{CC}'),
('ILASH', '阿什杜德', 'Ashdod', 0, 1, 'IE', 0, 0, '{CC}'),
('ILAKL', '阿什克伦', 'Ashkelon', 0, 1, 'IE', 0, 0, '{CC}'),
('IMDGS', '道格拉斯', 'Douglas', 0, 1, 'IM', 0, 0, '{CC}'),
('INVTZ', '维沙卡帕特南', 'Visakhapatnam', 0, 1, 'IN', 0, 0, '{CC}'),
('INTUT', '杜蒂戈林', 'Tuticorin', 0, 1, 'IN', 0, 0, '{CC}'),
('INRED', '雷迪', 'Redi', 0, 1, 'IN', 0, 0, '{CC}'),
('INPRT', '巴拉迪布', 'Paradip Garh', 0, 1, 'IN', 0, 0, '{CC}'),
('INPBD', '博尔本德尔', 'Porbandar', 0, 1, 'IN', 0, 0, '{CC}'),
('INNSA', '哈瓦舍瓦（尼赫鲁）', '	Nhava Sheva (Jawaharlal Nehru)', 0, 1, 'IN', 0, 0, '{CC}'),
('INNPT', '纳格伯蒂讷姆', 'Nagappattinam', 0, 1, 'IN', 0, 0, '{CC}'),
('INNML', '新芒格洛尔', 'New Mangalore', 0, 1, 'IN', 0, 0, '{CC}'),
('INMUN', '蒙德拉', 'Mundra', 0, 1, 'IN', 0, 0, '{CC}'),
('INMRM', '莫尔穆冈', 'Marmagao (Marmugao)', 0, 1, 'IN', 0, 0, '{CC}'),
('INMAA', '金奈', 'Chennai（Madras）', 0, 1, 'IN', 0, 0, '{CC}'),
('INKRK', '加里加尔', 'Karaikal（Karikal）', 0, 1, 'IN', 0, 0, '{CC}'),
('INIXZ', '布莱尔港', 'Port Blair', 0, 1, 'IN', 0, 0, '{CC}'),
('INIXY', '根德拉', 'Kandla', 0, 1, 'IN', 0, 0, '{CC}'),
('INCOK', '科钦', 'Cochin', 0, 1, 'IN', 0, 0, '{CC}'),
('INCCU', '加尔各答', 'Kolkata（Calcutta）', 0, 1, 'IN', 0, 0, '{CC}'),
('INBOM', '孟买', 'Mumbai（Bombay）', 0, 1, 'IN', 0, 0, '{CC}'),
('INBHU', '包纳加尔', 'Bhavnagar', 0, 1, 'IN', 0, 0, '{CC}'),
('IQUQR', '乌姆盖斯尔', 'Umm Qasr', 0, 1, 'IQ', 0, 0, '{CC}'),
('IQFAO', '法奥', 'Fao', 0, 1, 'IQ', 0, 0, '{CC}'),
('IQBSR', '巴士拉', 'Basra', 0, 1, 'IQ', 0, 0, '{CC}'),
('IRZBR', '恰赫巴哈尔', 'Chah Bahar', 0, 1, 'IR', 0, 0, '{CC}'),
('IRMRX', '马赫沙赫尔港', 'Bandar-e Mah Shahr', 0, 1, 'IR', 0, 0, '{CC}'),
('IRKHO', '胡宁沙赫尔', 'Khorramshahr', 0, 1, 'IR', 0, 0, '{CC}'),
('IRKHK', '哈尔克岛', 'Khark Island（Kharg Island）', 0, 1, 'IR', 0, 0, '{CC}'),
('IRBUZ', '布什尔', 'Bushehr（Bushire）', 0, 1, 'IR', 0, 0, '{CC}'),
('IRBND', '阿巴斯港', 'Bandar Abbas', 0, 1, 'IR', 0, 0, '{CC}'),
('IRBKM', '霍梅尼港', 'Bandar Khomeini', 0, 1, 'IR', 0, 0, '{CC}'),
('IRABD', '阿巴丹', 'Abadan', 0, 1, 'IR', 0, 0, '{CC}'),
('ISVES', '韦斯特曼纳岛', 'Vestmannaeyjar - hofn', 0, 1, 'IS', 0, 0, '{CC}'),
('ISREY', '雷克雅未克', 'Reykjavik', 0, 1, 'IS', 0, 0, '{CC}'),
('ISKEV', '凯夫拉维克', 'Keflavikurkaupstadur', 0, 1, 'IS', 0, 0, '{CC}'),
('ISISA', '伊萨菲厄泽', 'Isafjordur - hofn', 0, 1, 'IS', 0, 0, '{CC}'),
('ISAKU', '阿克雷里', 'Akureyri', 0, 1, 'IS', 0, 0, '{CC}'),
('ITVCE', '威尼斯', 'Venezia（Venice）', 0, 1, 'IT', 0, 0, '{CC}'),
('ITTRS', '的里雅斯特', 'Trieste', 0, 1, 'IT', 0, 0, '{CC}'),
('ITTAR', '塔兰托', 'Taranto', 0, 1, 'IT', 0, 0, '{CC}'),
('ITSVN', '萨沃纳', 'Savona/ Funivie', 0, 1, 'IT', 0, 0, '{CC}'),
('ITSPE', '斯佩齐亚', 'La Spezia', 0, 1, 'IT', 0, 0, '{CC}'),
('ITSAL', '萨莱诺', 'Salerno', 0, 1, 'IT', 0, 0, '{CC}'),
('ITRAN', '腊万纳', 'Ravenna', 0, 1, 'IT', 0, 0, '{CC}'),
('ITPTO', '托雷斯港', 'Porto Torres', 0, 1, 'IT', 0, 0, '{CC}'),
('ITPMO', '巴勒莫', 'Palermo', 0, 1, 'IT', 0, 0, '{CC}'),
('ITPFX', '萨罗克（福克西港）', '	Sarroch (Porto Foxi)', 0, 1, 'IT', 0, 0, '{CC}'),
('ITNAP', '那波利', 'Napoli', 0, 1, 'IT', 0, 0, '{CC}'),
('ITMSN', '墨西拿', 'Messina', 0, 1, 'IT', 0, 0, '{CC}'),
('ITMLZ', '米拉佐', 'Milazzo', 0, 1, 'IT', 0, 0, '{CC}'),
('ITLIV', '里窝那', 'Livorno', 0, 1, 'IT', 0, 0, '{CC}'),
('ITGOA', '热那亚', 'Genoa', 0, 1, 'IT', 0, 0, '{CC}'),
('ITGEA', '杰拉', 'Gela', 0, 1, 'IT', 0, 0, '{CC}'),
('ITGAE', '加埃塔', 'Gaeta', 0, 1, 'IT', 0, 0, '{CC}'),
('ITFCO', '菲乌米奇诺', 'Fiumicino', 0, 1, 'IT', 0, 0, '{CC}'),
('ITFAL', '法尔科纳拉', 'Falconara', 0, 1, 'IT', 0, 0, '{CC}'),
('ITCVV', '奇维塔韦基亚', 'Civitavecchia', 0, 1, 'IT', 0, 0, '{CC}'),
('ITCTA', '卡塔尼亚', 'Catania', 0, 1, 'IT', 0, 0, '{CC}'),
('ITCAG', '卡利亚里', 'Cagliari', 0, 1, 'IT', 0, 0, '{CC}'),
('ITBRI', '巴里', 'Bari', 0, 1, 'IT', 0, 0, '{CC}'),
('ITBLT', '巴列塔', 'Barletta', 0, 1, 'IT', 0, 0, '{CC}'),
('ITBDS', '布林迪西', 'Brindisi', 0, 1, 'IT', 0, 0, '{CC}'),
('ITAUG', '奥古斯塔', 'Augusta', 0, 1, 'IT', 0, 0, '{CC}'),
('ITAOI', '安科纳', 'Ancona', 0, 1, 'IT', 0, 0, '{CC}'),
('JESTH', '圣赫利尔', 'St Helier', 0, 1, 'JE', 0, 0, '{CC}'),
('JMPOT', '安东尼奥港', 'Port Antonio', 0, 1, 'JM', 0, 0, '{CC}'),
('JMOCJ', '奥乔里奥斯', 'Ocho Rios', 0, 1, 'JM', 0, 0, '{CC}'),
('JMMBJ', '蒙特哥贝', 'Montego Bay', 0, 1, 'JM', 0, 0, '{CC}'),
('JMKIN', '金斯敦', 'Kingston', 0, 1, 'JM', 0, 0, '{CC}'),
('JOAQJ', '亚喀巴', 'Aqaba（Al ‘Aqabah）', 0, 1, 'JO', 0, 0, '{CC}'),
('JPYOS', '横须贺', 'Yokosuka', 0, 1, 'JP', 0, 0, '{CC}'),
('JPYOK', '横滨', 'Yokohama', 0, 1, 'JP', 0, 0, '{CC}'),
('JPYKK', '四日市', 'Yokkaichi', 0, 1, 'JP', 0, 0, '{CC}'),
('JPWAK', '和歌山', 'Wakayama', 0, 1, 'JP', 0, 0, '{CC}'),
('JPUKB', '神户', 'Kobe', 0, 1, 'JP', 0, 0, '{CC}'),
('JPUBJ', '宇部', 'Ube', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTYO', '东京', 'Tokyo', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTRG', '敦贺', 'Tsuruga', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTMK', '苫小牧', 'Tomakomai', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTKY', '德山', 'Tokuyama', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTAK', '高松', 'Takamatsu', 0, 1, 'JP', 0, 0, '{CC}'),
('JPSSB', '佐世保', 'Sasebo', 0, 1, 'JP', 0, 0, '{CC}'),
('JPSMZ', '清水', 'Shimizu', 0, 1, 'JP', 0, 0, '{CC}'),
('JPSHS', '下关', 'Shimonoseki', 0, 1, 'JP', 0, 0, '{CC}'),
('JPOTR', '小樽', 'Otaru', 0, 1, 'JP', 0, 0, '{CC}'),
('JPOSA', '大阪', 'Osaka', 0, 1, 'JP', 0, 0, '{CC}'),
('JPONA', '小名滨', 'Onahama', 0, 1, 'JP', 0, 0, '{CC}'),
('JPOIT', '大分', 'Oita', 0, 1, 'JP', 0, 0, '{CC}'),
('JPNGS', '长崎', 'Nagasaki', 0, 1, 'JP', 0, 0, '{CC}'),
('JPNGO', '名古屋', 'Nagoya', 0, 1, 'JP', 0, 0, '{CC}'),
('JPNAH', '那霸', 'Naha', 0, 1, 'JP', 0, 0, '{CC}'),
('JPMUR', '室兰', 'Muroran', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKZU', '木更津', 'Kisarazu', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKUH', '钏路', 'Kushiro', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKOJ', '鹿儿岛', 'Kagoshima', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKNZ', '金泽', 'Kanazawa', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKKJ', '北九州', 'Kitakyushu', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKIJ', '新泻', 'Niigata', 0, 1, 'JP', 0, 0, '{CC}'),
('JPIWK', '岩国', 'Iwakuni', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHTC', '日立', 'Hitachi', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHSM', '细岛', 'Hososhima', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHMD', '滨田', 'Hamada', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHKD', '函馆', 'Hakodate', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHIM', '姬路', 'Himeji', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHIJ', '广岛', 'Hiroshima', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHHE', '八户', 'Hachinohe', 0, 1, 'JP', 0, 0, '{CC}'),
('JPFUK', '福冈', 'Fukuoka', 0, 1, 'JP', 0, 0, '{CC}'),
('JPFKY', '福山', 'Fukuyama', 0, 1, 'JP', 0, 0, '{CC}'),
('JPCHB', '千叶', 'Chiba', 0, 1, 'JP', 0, 0, '{CC}'),
('JPAXT', '秋田', '	Akita', 0, 1, 'JP', 0, 0, '{CC}'),
('KEMYD', '马林迪', 'Malindi', 0, 1, 'KE', 0, 0, '{CC}'),
('KEMBA', '蒙巴萨', 'Mombasa', 0, 1, 'KE', 0, 0, '{CC}'),
('KELAU', '拉穆', 'Lamu', 0, 1, 'KE', 0, 0, '{CC}'),
('KHPNH', '金边', 'Phnom Penh', 0, 1, 'KH', 0, 0, '{CC}'),
('KHKOS', '磅逊', 'Kompong Som（Kampong Saom）', 0, 1, 'KH', 0, 0, '{CC}'),
('KITRW', '塔拉瓦', 'Tarawa', 0, 1, 'KI', 0, 0, '{CC}'),
('KMYVA', '莫罗尼', 'Moroni', 0, 1, 'KM', 0, 0, '{CC}'),
('KNBAS', '巴斯特尔', 'Basseterre', 0, 1, 'KN', 0, 0, '{CC}'),
('KPWON', '元山', 'Wonsan', 0, 1, 'KP', 0, 0, '{CC}'),
('KPSIN', '新浦', 'Sinpo', 0, 1, 'KP', 0, 0, '{CC}'),
('KPNAM', '南浦', 'Nampo', 0, 1, 'KP', 0, 0, '{CC}'),
('KPHGM', '兴南', 'Hungnam', 0, 1, 'KP', 0, 0, '{CC}'),
('KPHAE', '海州', 'Haeju', 0, 1, 'KP', 0, 0, '{CC}'),
('KPCHO', '清津', 'Chongjin', 0, 1, 'KP', 0, 0, '{CC}'),
('KRYOS', '丽水', 'Yeosu(Yosu)', 0, 1, 'KR', 0, 0, '{CC}'),
('KRUSN', '蔚山', 'Ulsan', 0, 1, 'KR', 0, 0, '{CC}'),
('KRPUS', '釜山', 'Busan', 0, 1, 'KR', 0, 0, '{CC}'),
('KRPTK', '平泽', 'Pyeongtaek', 0, 1, 'KR', 0, 0, '{CC}'),
('KRMUK', '墨湖', 'Mukho', 0, 1, 'KR', 0, 0, '{CC}'),
('KRMOK', '木浦', 'Mokpo', 0, 1, 'KR', 0, 0, '{CC}'),
('KRMAS', '马山', 'Masan', 0, 1, 'KR', 0, 0, '{CC}'),
('KRKUV', '群山', 'Gunsan(Kunsan)', 0, 1, 'KR', 0, 0, '{CC}'),
('KRKPO', '浦项', 'Pohang', 0, 1, 'KR', 0, 0, '{CC}'),
('KRKAN', '光阳', 'Gwangyang(Kwangyang)', 0, 1, 'KR', 0, 0, '{CC}'),
('KRICH', '仁川', 'Incheon(Inchon)', 0, 1, 'KR', 0, 0, '{CC}'),
('KWSAA', '舒艾拜', 'Shuaiba', 0, 1, 'KW', 0, 0, '{CC}'),
('KWMEA', '艾哈迈迪港', 'Mina’ al Ahmadi', 0, 1, 'KW', 0, 0, '{CC}'),
('KWKWI', '科威特', 'Kuwait', 0, 1, 'KW', 0, 0, '{CC}'),
('KYGEC', '乔治敦', 'Georgetown', 0, 1, 'KY', 0, 0, '{CC}'),
('LBSUR', '苏尔', 'Sur（Tyre） ', 0, 1, 'LB', 0, 0, '{CC}'),
('LBSAY', '赛达', 'Sayda', 0, 1, 'LB', 0, 0, '{CC}'),
('LBKYE', '的黎波里', 'Tripoli', 0, 1, 'LB', 0, 0, '{CC}'),
('LBBEY', '贝鲁特', 'Beirut', 0, 1, 'LB', 0, 0, '{CC}'),
('LCCAS', '卡斯特里', 'Castries', 0, 1, 'LC', 0, 0, '{CC}'),
('LKTRR', '亭可马里', 'Trincomalee', 0, 1, 'LK', 0, 0, '{CC}'),
('LKTAL', '塔莱曼纳尔', 'Talaimannar', 0, 1, 'LK', 0, 0, '{CC}'),
('LKMAN', '马纳尔', 'Mannar', 0, 1, 'LK', 0, 0, '{CC}'),
('LKKNK', '坎凯桑图赖', 'Kankesanturai', 0, 1, 'LK', 0, 0, '{CC}'),
('LKGAL', '加勒', 'Galle', 0, 1, 'LK', 0, 0, '{CC}'),
('LKCMB', '科伦坡', 'Colombo', 0, 1, 'LK', 0, 0, '{CC}'),
('LRUCN', '布坎南', 'Buchanan', 0, 1, 'LR', 0, 0, '{CC}'),
('LRMLW', '蒙罗维亚', 'Monrovia', 0, 1, 'LR', 0, 0, '{CC}'),
('LRCPA', '帕尔马斯角', 'Cape Palmas', 0, 1, 'LR', 0, 0, '{CC}'),
('LTKLJ', '克莱佩达', 'Klaipeda', 0, 1, 'LR', 0, 0, '{CC}'),
('LVVNT', '文茨皮尔斯', 'Ventspils', 0, 1, 'LV', 0, 0, '{CC}'),
('LVRIX', '里加', 'Riga', 0, 1, 'LV', 0, 0, '{CC}'),
('LVLPX', '利耶帕亚', 'Liepaja', 0, 1, 'LV', 0, 0, '{CC}'),
('LYZUE', '祖埃提纳', 'Zueitina', 0, 1, 'LY', 0, 0, '{CC}'),
('LYTOB', '图卜鲁格', 'Tobruk', 0, 1, 'LY', 0, 0, '{CC}'),
('LYTIP', '的黎波里', 'Tripoli', 0, 1, 'LY', 0, 0, '{CC}'),
('LYRLA', '拉斯拉努夫', 'Ras Lanuf', 0, 1, 'LY', 0, 0, '{CC}'),
('LYMRA', '米苏拉塔', 'Misurata', 0, 1, 'LY', 0, 0, '{CC}'),
('LYMHR', '哈里盖港', 'Marsa el Hariga', 0, 1, 'LY', 0, 0, '{CC}'),
('LYLMQ', '卜雷加港', 'Marsa Brega', 0, 1, 'LY', 0, 0, '{CC}'),
('LYESI', '锡德尔', 'As Sidr', 0, 1, 'LY', 0, 0, '{CC}'),
('LYDRX', '德尔纳', 'Darnah', 0, 1, 'LY', 0, 0, '{CC}'),
('LYBEN', '班加西', 'Bingazi (Benghazi)', 0, 1, 'LY', 0, 0, '{CC}'),
('MATTU', '得土安', 'Tetouan', 0, 1, 'MA', 0, 0, '{CC}'),
('MATNG', '丹吉尔', 'Tangier', 0, 1, 'MA', 0, 0, '{CC}'),
('MASFI', '萨菲', 'Safi', 0, 1, 'MA', 0, 0, '{CC}'),
('MARBA', '拉巴特', 'Rabat', 0, 1, 'MA', 0, 0, '{CC}'),
('MANNA', '盖尼特拉', 'Kenitra', 0, 1, 'MA', 0, 0, '{CC}'),
('MAMOH', '穆罕默迪耶', 'Mohammedia', 0, 1, 'MA', 0, 0, '{CC}'),
('MAEUN', '欧云（阿尤恩）', 'Laayoune（El Aaiun）', 0, 1, 'MA', 0, 0, '{CC}'),
('MACAS', '卡萨布兰卡', 'Casablanca', 0, 1, 'MA', 0, 0, '{CC}'),
('MAAGA', '阿加迪尔', 'Agadir', 0, 1, 'MA', 0, 0, '{CC}'),
('MCMON', '摩纳哥', 'Monaco', 0, 1, 'MC', 0, 0, '{CC}'),
('MCMCM', '蒙特卡洛', 'Monte Carlo', 0, 1, 'MC', 0, 0, '{CC}'),
('MEKOT', '科托尔', 'Kotor', 0, 1, 'ME', 0, 0, '{CC}'),
('MEBAR', '巴尔', 'Bar', 0, 1, 'ME', 0, 0, '{CC}'),
('MGWVK', '马纳卡拉', 'Manakara', 0, 1, 'MG', 0, 0, '{CC}'),
('MGTMM', '塔马塔夫', 'Tamatave (Toamasina)', 0, 1, 'MG', 0, 0, '{CC}'),
('MGTLE', '图莱亚尔', 'Tulear (Toliara)', 0, 1, 'MG', 0, 0, '{CC}'),
('MGRVA', '法拉凡加纳', 'Farafangana', 0, 1, 'MG', 0, 0, '{CC}'),
('MGMXM', '穆龙贝', 'Morombe', 0, 1, 'MG', 0, 0, '{CC}'),
('MGMOQ', '穆龙达瓦', 'Morondava', 0, 1, 'MG', 0, 0, '{CC}'),
('MGMNJ', '马南扎里', 'Mananjary', 0, 1, 'MG', 0, 0, '{CC}'),
('MGMJN', '马任加', 'Majunga (Mahajanga)', 0, 1, 'MG', 0, 0, '{CC}'),
('MGFTU', '多凡堡', 'Fort Dauphin (Toalagnaro)', 0, 1, 'MG', 0, 0, '{CC}'),
('MGDIE', '安齐拉纳纳', 'Antsiranana（Diego-Suarez）', 0, 1, 'MG', 0, 0, '{CC}'),
('MHTAR', '塔罗阿', 'Taroa', 0, 1, 'MH', 0, 0, '{CC}'),
('MHMAJ', '马朱罗', 'Majuro', 0, 1, 'MH', 0, 0, '{CC}'),
('MMXYE', '耶城', 'Ye', 0, 1, 'MM', 0, 0, '{CC}'),
('MMTAV', '土瓦', 'Tavoy', 0, 1, 'MM', 0, 0, '{CC}'),
('MMSAN', '丹兑（山多威）', 'Thandwe（Sandoway）', 0, 1, 'MM', 0, 0, '{CC}'),
('MMRGN', '仰光', 'Yangon（Rangoon）', 0, 1, 'MM', 0, 0, '{CC}'),
('MMMNU', '毛淡棉', 'Mawlamyine（Moulmein）', 0, 1, 'MM', 0, 0, '{CC}'),
('MMMER', '墨吉', 'Mergui', 0, 1, 'MM', 0, 0, '{CC}'),
('MMKYP', '皎漂', 'Kyaukpyu', 0, 1, 'MM', 0, 0, '{CC}'),
('MMBSX', '勃生', 'Bassein', 0, 1, 'MM', 0, 0, '{CC}'),
('MMAKY', '实兑', 'Akyab（Sittwe）', 0, 1, 'MM', 0, 0, '{CC}'),
('MOMFM', '澳门', 'Macau', 0, 1, 'MO', 0, 0, '{CC}'),
('MPTIQ', '提尼安岛', 'Tinian', 0, 1, 'MP', 0, 0, '{CC}'),
('MPSPN', '塞班岛', 'Saipan', 0, 1, 'MP', 0, 0, '{CC}'),
('MQFDF', '法兰西堡', 'Fort-de-France', 0, 1, 'MQ', 0, 0, '{CC}'),
('MRNKC', '努瓦克肖特', 'Nouakchott', 0, 1, 'MR', 0, 0, '{CC}'),
('MRNDB', '努瓦迪布', 'Nouadhibou', 0, 1, 'MR', 0, 0, '{CC}'),
('MSPLY', '普利茅斯', 'Plymouth', 0, 1, 'MS', 0, 0, '{CC}'),
('MTMLA', '瓦莱塔', 'Valetta', 0, 1, 'MT', 0, 0, '{CC}'),
('MTMAR', '马尔萨什洛克', 'Marsaxlokk', 0, 1, 'MT', 0, 0, '{CC}'),
('MUPLU', '路易港', 'Port Louis', 0, 1, 'MU', 0, 0, '{CC}'),
('MVMLE', '马累岛', 'Male Island', 0, 1, 'MV', 0, 0, '{CC}'),
('MXZLO', '曼萨尼略', 'Manzanillo', 0, 1, 'MX', 0, 0, '{CC}'),
('MXVER', '韦拉克鲁斯', 'Veracruz', 0, 1, 'MX', 0, 0, '{CC}'),
('MXTAM', '坦皮科', 'Tampico', 0, 1, 'MX', 0, 0, '{CC}'),
('MXSRL', '圣罗萨利亚', 'Santa Rosalia', 0, 1, 'MX', 0, 0, '{CC}'),
('MXSCX', '萨利纳克鲁斯', 'Salina Cruz', 0, 1, 'MX', 0, 0, '{CC}'),
('MXPMD', '马德罗港', 'Puerto Madero', 0, 1, 'MX', 0, 0, '{CC}'),
('MXMZT', '马萨特兰', 'Mazatlan', 0, 1, 'MX', 0, 0, '{CC}'),
('MXMTT', '米纳蒂特兰', 'Minatitlan', 0, 1, 'MX', 0, 0, '{CC}'),
('MXLZC', '拉萨罗卡德纳斯', 'Lazaro Cardenas', 0, 1, 'MX', 0, 0, '{CC}'),
('MXGYM', '瓜伊马斯', 'Guaymas', 0, 1, 'MX', 0, 0, '{CC}'),
('MXESE', '恩塞纳达', 'Ensenada', 0, 1, 'MX', 0, 0, '{CC}'),
('MXCPE', '坎佩切', 'Campeche', 0, 1, 'MX', 0, 0, '{CC}'),
('MXCOA', '夸察夸尔科斯', 'Coatzacoalcos', 0, 1, 'MX', 0, 0, '{CC}'),
('MXAVD', '阿尔瓦拉多', 'Alvarado', 0, 1, 'MX', 0, 0, '{CC}'),
('MXACA', '阿卡普尔科', 'Acapulco', 0, 1, 'MX', 0, 0, '{CC}'),
('MYTWU', '斗湖', 'Tawau', 0, 1, 'MY', 0, 0, '{CC}'),
('MYSDK', '山打根', 'Sandakan', 0, 1, 'MY', 0, 0, '{CC}'),
('MYSBW', '诗巫', 'Sibu', 0, 1, 'MY', 0, 0, '{CC}'),
('MYPKG', '巴生港', 'Port Kelang', 0, 1, 'MY', 0, 0, '{CC}'),
('MYPGU', '帕西古当', 'Pasir Gudang', 0, 1, 'MY', 0, 0, '{CC}'),
('MYPEN', '槟城', 'Penang(Georgetown)', 0, 1, 'MY', 0, 0, '{CC}'),
('MYMYY', '米里', 'Miri', 0, 1, 'MY', 0, 0, '{CC}'),
('MYMKZ', '马六甲', 'Malacca', 0, 1, 'MY', 0, 0, '{CC}'),
('MYLBU', '纳闽', 'Labuan', 0, 1, 'MY', 0, 0, '{CC}'),
('MYKUD', '古达', 'Kudat', 0, 1, 'MY', 0, 0, '{CC}'),
('MYKCH', '古晋', 'Kuching', 0, 1, 'MY', 0, 0, '{CC}'),
('MYJHB', '新山', 'Johore Bahru', 0, 1, 'MY', 0, 0, '{CC}'),
('MYBTU', '民都鲁', 'Bintulu', 0, 1, 'MY', 0, 0, '{CC}'),
('MYBKI', '哥打基纳巴卢', 'Kota Kinabalu', 0, 1, 'MY', 0, 0, '{CC}'),
('MZPOL', '彭巴', 'Pemba', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZMZQ', '莫桑比克', 'Mocambique', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZMPM', '马普托', 'Maputo', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZMNC', '纳卡拉', 'Nacala', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZINH', '伊尼扬巴内', 'Inhambane', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZBEW', '贝拉', 'Beira', 0, 1, 'MZ', 0, 0, '{CC}'),
('NAWVB', '鲸湾港', 'Walvis Bay', 0, 1, 'NA', 0, 0, '{CC}'),
('NALUD', '吕德里茨', 'Luderitz', 0, 1, 'NA', 0, 0, '{CC}'),
('NCNOU', '努美阿', 'Noumea', 0, 1, 'NC', 0, 0, '{CC}'),
('NFNLK', '诺福克岛', 'Norfolk Island', 0, 1, 'NF', 0, 0, '{CC}'),
('NGWAR', '瓦里', 'Warri', 0, 1, 'NG', 0, 0, '{CC}'),
('NGTIN', '廷坎岛', 'Tincan', 0, 1, 'NG', 0, 0, '{CC}'),
('NGPHC', '哈科特港', 'Port Harcourt', 0, 1, 'NG', 0, 0, '{CC}'),
('NGORO', '奥尼', 'Oron', 0, 1, 'NG', 0, 0, '{CC}'),
('NGLOS', '拉各斯', 'Lagos', 0, 1, 'NG', 0, 0, '{CC}'),
('NGFOR', '福卡多斯', 'Forcados', 0, 1, 'NG', 0, 0, '{CC}'),
('NGCBQ', '卡拉巴尔', 'Calabar', 0, 1, 'NG', 0, 0, '{CC}'),
('NGBON', '邦尼', 'Bonny', 0, 1, 'NG', 0, 0, '{CC}'),
('NGAPP', '阿帕帕', 'Apapa', 0, 1, 'NG', 0, 0, '{CC}'),
('NISJS', '南圣胡安', 'San Juan del Sur', 0, 1, 'NI', 0, 0, '{CC}'),
('NIPUZ', '卡贝萨斯港', 'Puerto Cabezas', 0, 1, 'NI', 0, 0, '{CC}'),
('NICIO', '科林托', 'Corinto', 0, 1, 'NI', 0, 0, '{CC}'),
('NIBEF', '布卢菲尔兹', 'Bluefields', 0, 1, 'NI', 0, 0, '{CC}'),
('NLZAA', '赞丹', 'Zaandam', 0, 1, 'NL', 0, 0, '{CC}'),
('NLVLI', '弗利辛恩', 'Vlissingen', 0, 1, 'NL', 0, 0, '{CC}'),
('NLVLA', '弗拉尔丁恩', 'Vlaardingen', 0, 1, 'NL', 0, 0, '{CC}'),
('NLTNZ', '泰尔讷曾', 'Terneuzen', 0, 1, 'NL', 0, 0, '{CC}'),
('NLRTM', '鹿特丹', 'Rotterdam', 0, 1, 'NL', 0, 0, '{CC}'),
('NLIJM', '艾默伊登', 'IJmuiden', 0, 1, 'NL', 0, 0, '{CC}'),
('NLDZL', '代尔夫宰尔', 'Delfzijl', 0, 1, 'NL', 0, 0, '{CC}'),
('NLAMS', '阿姆斯特丹', 'Amsterdam', 0, 1, 'NL', 0, 0, '{CC}'),
('NOTRD', '特隆赫姆', 'Trondheim', 0, 1, 'NO', 0, 0, '{CC}'),
('NOTOS', '特罗姆瑟', 'Tromso', 0, 1, 'NO', 0, 0, '{CC}'),
('NOTON', '滕斯贝格', 'Tonsberg', 0, 1, 'NO', 0, 0, '{CC}'),
('NOSVG', '斯塔万格', 'Stavanger', 0, 1, 'NO', 0, 0, '{CC}'),
('NOOSL', '奥斯陆', 'Oslo', 0, 1, 'NO', 0, 0, '{CC}'),
('NONVK', '纳尔维克', 'Narvik', 0, 1, 'NO', 0, 0, '{CC}'),
('NOMSS', '莫斯', 'Moss', 0, 1, 'NO', 0, 0, '{CC}'),
('NOMOL', '莫尔德', 'Molde', 0, 1, 'NO', 0, 0, '{CC}'),
('NOMJF', '莫舍恩', 'Mosjoen', 0, 1, 'NO', 0, 0, '{CC}'),
('NOLAR', '拉尔维克', 'Larvik', 0, 1, 'NO', 0, 0, '{CC}'),
('NOKSU', '克里斯蒂安松', 'Kristiansund', 0, 1, 'NO', 0, 0, '{CC}'),
('NOKRS', '克里斯蒂安桑', 'Kristiansand', 0, 1, 'NO', 0, 0, '{CC}'),
('NOKKN', '希尔克内斯', 'Kirkenes', 0, 1, 'NO', 0, 0, '{CC}'),
('NOHRD', '哈尔斯塔', 'Harstad', 0, 1, 'NO', 0, 0, '{CC}'),
('NOHFT', '哈默弗斯特', 'Hammerfest', 0, 1, 'NO', 0, 0, '{CC}'),
('NOHAU', '海于格松', 'Haugesund', 0, 1, 'NO', 0, 0, '{CC}'),
('NOGTD', '格里姆斯塔', 'Grimstad', 0, 1, 'NO', 0, 0, '{CC}'),
('NOFRK', '腓特烈斯塔', 'Fredrikstad', 0, 1, 'NO', 0, 0, '{CC}'),
('NODRM', '德拉门', 'Drammen', 0, 1, 'NO', 0, 0, '{CC}'),
('NOBOO', '博多', 'Bodo', 0, 1, 'NO', 0, 0, '{CC}'),
('NOBGO', '卑尔根', 'Bergen', 0, 1, 'NO', 0, 0, '{CC}'),
('NOARE', '阿伦达尔', 'Arendal', 0, 1, 'NO', 0, 0, '{CC}'),
('NOAES', '奥勒松', 'Alesund', 0, 1, 'NO', 0, 0, '{CC}'),
('NRINU', '瑙鲁岛', 'Nauru Island', 0, 1, 'NR', 0, 0, '{CC}'),
('NUIUE', '纽埃岛', 'Niue Island', 0, 1, 'NU', 0, 0, '{CC}'),
('NUALO', '阿洛菲', 'Alofi', 0, 1, 'NU', 0, 0, '{CC}'),
('NZWSZ', '韦斯特波特', 'Westport', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZWRE', '旺阿雷', 'Whangarei', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZWLG', '惠灵顿', 'Wellington', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZWAV', '韦弗利港', 'Waverley Harbour', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZTRG', '陶朗阿', 'Tauranga', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZTIU', '蒂马鲁', 'Timaru', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZTHH', '塔哈罗阿', 'Taharoa', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZPOE', '查默斯港', 'Port Chalmers', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZPCN', '皮克顿', 'Picton', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZORR', '奥塔戈', 'Otago Harbour', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZOPX', '奥普阿', 'Opua', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZNSN', '纳尔逊', 'Nelson', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZNPL', '新普利茅斯', 'New Plymouth', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZNPE', '内皮尔', 'Napier', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZLYT', '利特尔顿', 'Lyttelton', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZGIS', '吉斯珀恩', 'Gisborne', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZDUD', '达尼丁', 'Dunedin', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZCHC', '克赖斯特彻奇', 'Christchurch', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZBLU', '布拉夫', 'Bluff', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZAKL', '奥克兰', 'Auckland', 0, 1, 'NZ', 0, 0, '{CC}'),
('OMSLL', '塞拉莱', 'Salalah', 0, 1, 'OM', 0, 0, '{CC}'),
('OMRAY', '赖苏特', 'Raysut', 0, 1, 'OM', 0, 0, '{CC}'),
('OMOPQ', '卡布斯港', 'Port Qaboos（Mina Qaboos）', 0, 1, 'OM', 0, 0, '{CC}'),
('OMMUT', '马特拉', 'Muthra', 0, 1, 'OM', 0, 0, '{CC}'),
('OMMFH', '费赫勒港', 'Mina al Fahal', 0, 1, 'OM', 0, 0, '{CC}'),
('OMMCT', '马斯喀特', 'Muscat', 0, 1, 'OM', 0, 0, '{CC}'),
('PAPTY', '巴拿马城', 'Panama, Ciudad de', 0, 1, 'PA', 0, 0, '{CC}'),
('PAPAM', '阿尔米兰特', 'Almirante', 0, 1, 'PA', 0, 0, '{CC}'),
('PAONX', '科隆', 'Colon', 0, 1, 'PA', 0, 0, '{CC}'),
('PAMIT', '曼萨尼约', 'Manzanillo', 0, 1, 'PA', 0, 0, '{CC}'),
('PACTB', '克里斯托瓦尔', 'Cristobal', 0, 1, 'PA', 0, 0, '{CC}'),
('PABLB', '巴尔博亚', 'Balboa', 0, 1, 'PA', 0, 0, '{CC}'),
('PETYL', '塔拉拉', 'Talara', 0, 1, 'PE', 0, 0, '{CC}'),
('PETRU', '特鲁希略', 'Trujillo', 0, 1, 'PE', 0, 0, '{CC}'),
('PESUP', '苏佩', 'Supe', 0, 1, 'PE', 0, 0, '{CC}'),
('PEPUB', '巴约瓦尔港', 'Bayovar', 0, 1, 'PE', 0, 0, '{CC}'),
('PEPIO', '皮斯科', 'Pisco', 0, 1, 'PE', 0, 0, '{CC}'),
('PEPAI', '派塔', 'Paita', 0, 1, 'PE', 0, 0, '{CC}'),
('PEMRI', '马塔拉尼', 'Matarani', 0, 1, 'PE', 0, 0, '{CC}'),
('PEMLQ', '莫延多', 'Mollendo', 0, 1, 'PE', 0, 0, '{CC}'),
('PEILQ', '伊洛', 'Ilo', 0, 1, 'PE', 0, 0, '{CC}'),
('PEHCO', '瓦乔', 'Huacho', 0, 1, 'PE', 0, 0, '{CC}'),
('PEEEN', '埃腾', 'Eten', 0, 1, 'PE', 0, 0, '{CC}'),
('PECLL', '卡亚俄', 'Callao', 0, 1, 'PE', 0, 0, '{CC}'),
('PECHM', '钦博塔', 'Chimbote', 0, 1, 'PE', 0, 0, '{CC}'),
('PFPPT', '帕皮提', 'Papeete', 0, 1, 'PF', 0, 0, '{CC}'),
('PFBOB', '波拉波拉', 'Bora-Bora', 0, 1, 'PF', 0, 0, '{CC}'),
('PGWWK', '威瓦克', 'Wewak', 0, 1, 'PG', 0, 0, '{CC}'),
('PGRAB', '拉包尔', 'Rabaul', 0, 1, 'PG', 0, 0, '{CC}'),
('PGPOM', '莫尔兹比港', 'Port Moresby', 0, 1, 'PG', 0, 0, '{CC}'),
('PGMAG', '马当', 'Madang', 0, 1, 'PG', 0, 0, '{CC}'),
('PGLAE', '莱城', 'Lae', 0, 1, 'PG', 0, 0, '{CC}'),
('PGKIM', '金贝', 'Kimbe', 0, 1, 'PG', 0, 0, '{CC}'),
('PGKIE', '基埃塔', 'Kieta', 0, 1, 'PG', 0, 0, '{CC}'),
('PGANB', '阿内瓦湾', 'Anewa Bay', 0, 1, 'PG', 0, 0, '{CC}'),
('PHZAM', '三宝颜', 'Zamboanga', 0, 1, 'PH', 0, 0, '{CC}'),
('PHSFE', '圣弗尔南多', 'San Fernando', 0, 1, 'PH', 0, 0, '{CC}'),
('PHMVS', '马里韦莱斯', 'Mariveles', 0, 1, 'PH', 0, 0, '{CC}'),
('PHMNL', '马尼拉', 'Manila', 0, 1, 'PH', 0, 0, '{CC}'),
('PHLIN', '林加延', 'Lingayen', 0, 1, 'PH', 0, 0, '{CC}'),
('PHLGP', '黎牙实比', 'Legaspi', 0, 1, 'PH', 0, 0, '{CC}'),
('PHILO', '伊洛伊洛', 'Iloilo', 0, 1, 'PH', 0, 0, '{CC}'),
('PHDVO', '达沃', 'Davao', 0, 1, 'PH', 0, 0, '{CC}'),
('PHCGY', '卡加延德奥罗', 'Cagayan de Oro', 0, 1, 'PH', 0, 0, '{CC}'),
('PHCEB', '宿务', 'Cebu', 0, 1, 'PH', 0, 0, '{CC}'),
('PHBTG', '八打雁', 'Batangas', 0, 1, 'PH', 0, 0, '{CC}'),
('PHAPR', '阿帕里', 'Aparri', 0, 1, 'PH', 0, 0, '{CC}'),
('PKPSI', '伯斯尼', 'Pasni', 0, 1, 'PK', 0, 0, '{CC}'),
('PKORW', '奥尔马拉', 'Ormara', 0, 1, 'PK', 0, 0, '{CC}'),
('PKKHI', '卡拉奇', 'Karachi', 0, 1, 'PK', 0, 0, '{CC}'),
('PKGWD', '瓜德尔', 'Gwadar', 0, 1, 'PK', 0, 0, '{CC}'),
('PKBQM', '穆罕默德宾加西姆', 'Muhammad Bin Qasim', 0, 1, 'PK', 0, 0, '{CC}'),
('PLSZZ', '什切青', 'Szczecin', 0, 1, 'PL', 0, 0, '{CC}'),
('PLSWI', '希维诺乌伊希切', 'Swinoujscie', 0, 1, 'PL', 0, 0, '{CC}'),
('PLGDY', '格丁尼亚', 'Gdynia', 0, 1, 'PL', 0, 0, '{CC}'),
('PLGDN', '格但斯克', 'Gdansk', 0, 1, 'PL', 0, 0, '{CC}'),
('PMFSP', '圣皮埃尔', 'St Pierre', 0, 1, 'PM', 0, 0, '{CC}'),
('PNPCN', '皮特凯恩岛', 'Pitcairn Island', 0, 1, 'PN', 0, 0, '{CC}'),
('PRSJU', '圣胡安', 'San Juan', 0, 1, 'PR', 0, 0, '{CC}'),
('PRPSE', '蓬塞', 'Ponce', 0, 1, 'PR', 0, 0, '{CC}'),
('PRMAZ', '马亚圭斯', 'Mayaguez', 0, 1, 'PR', 0, 0, '{CC}'),
('PRLAM', '拉斯马雷亚斯', 'Las Mareas (Guayama)', 0, 1, 'PR', 0, 0, '{CC}'),
('PTSET', '塞图巴尔', 'Setubal', 0, 1, 'PT', 0, 0, '{CC}'),
('PTPRM', '波尔蒂芒', 'Portimao', 0, 1, 'PT', 0, 0, '{CC}'),
('PTPDL', '蓬塔德尔加达港', 'Ponta Delgada', 0, 1, 'PT', 0, 0, '{CC}'),
('PTOPO', '波尔图', 'Porto', 0, 1, 'PT', 0, 0, '{CC}'),
('PTLIS', '里斯本', 'Lisboa', 0, 1, 'PT', 0, 0, '{CC}'),
('PTLEI', '雷克索斯', 'Leixoes', 0, 1, 'PT', 0, 0, '{CC}'),
('PTHOR', '奥尔塔', 'Horta', 0, 1, 'PT', 0, 0, '{CC}'),
('PTFNC', '丰沙尔', 'Funchal', 0, 1, 'PT', 0, 0, '{CC}'),
('PTADH', '英雄港', 'Angra do Heroismo', 0, 1, 'PT', 0, 0, '{CC}'),
('PWROR', '科罗尔', 'Koror', 0, 1, 'PW', 0, 0, '{CC}'),
('QAUMS', '乌姆赛义德', 'Umm Said', 0, 1, 'QA', 0, 0, '{CC}'),
('QADOH', '多哈', 'Doha', 0, 1, 'QA', 0, 0, '{CC}'),
('REPDG', '加勒茨角港', 'Port de Pointe des Galets', 0, 1, 'RE', 0, 0, '{CC}'),
('RELPT', '勒波尔', 'Le Port', 0, 1, 'RE', 0, 0, '{CC}'),
('ROSUL', '苏利纳', 'Sulina', 0, 1, 'RO', 0, 0, '{CC}'),
('ROMAG', '曼加利亚', 'Mangalia', 0, 1, 'RO', 0, 0, '{CC}'),
('ROCND', '康斯坦察', 'Constanta', 0, 1, 'RO', 0, 0, '{CC}'),
('ROBRA', '布勒伊拉', 'Braila', 0, 1, 'RO', 0, 0, '{CC}'),
('RUZAR', '扎鲁比诺', 'Zarubino', 0, 1, 'RU', 0, 0, '{CC}'),
('RUVYP', '东方港', 'Vostochnyy（Vostochniy, Port）', 0, 1, 'RU', 0, 0, '{CC}'),
('RUVVO', '符拉迪沃斯托克/海参崴', 'Vladivostok', 0, 1, 'RU', 0, 0, '{CC}'),
('RUVNN', '瓦尼诺', 'Vanino', 0, 1, 'RU', 0, 0, '{CC}'),
('RUUKK', '乌斯季堪察茨克', 'Ust-Kamchatsk', 0, 1, 'RU', 0, 0, '{CC}'),
('RUUGL', '乌格里哥斯克', 'Uglegorsk', 0, 1, 'RU', 0, 0, '{CC}'),
('RUTUA', '图阿普谢', 'Tuapse', 0, 1, 'RU', 0, 0, '{CC}'),
('RUTAG', '塔甘罗格', 'Taganrog', 0, 1, 'RU', 0, 0, '{CC}'),
('RUSOC', '索契', 'Sochi', 0, 1, 'RU', 0, 0, '{CC}'),
('RUSAK', '亚历山徳罗夫斯克', 'Aleksandrovsk-Sakhalinskiy', 0, 1, 'RU', 0, 0, '{CC}'),
('RUROV', '罗斯托夫', 'Rostov', 0, 1, 'RU', 0, 0, '{CC}'),
('RUPRN', '波罗奈斯克', 'Poronaisk', 0, 1, 'RU', 0, 0, '{CC}'),
('RUPKC', '彼得罗巴浦洛夫斯克', '	Petropavlovsk', 0, 1, 'RU', 0, 0, '{CC}'),
('RUOHO', '鄂霍次克', 'Okhotsk', 0, 1, 'RU', 0, 0, '{CC}'),
('RUNVS', '新罗西斯克', 'Novorossiysk', 0, 1, 'RU', 0, 0, '{CC}'),
('RUNJK', '纳霍德卡', 'Nakhodka', 0, 1, 'RU', 0, 0, '{CC}'),
('RUNEV', '涅韦尔斯克', 'Nevelsk', 0, 1, 'RU', 0, 0, '{CC}'),
('RUMMK', '摩尔曼斯克', 'Murmansk', 0, 1, 'RU', 0, 0, '{CC}'),
('RUMAG', '马加丹', 'Magadan（Magadansky, Port）', 0, 1, 'RU', 0, 0, '{CC}'),
('RULED', '圣彼得堡', 'ST. Petersburg', 0, 1, 'RU', 0, 0, '{CC}'),
('RUKOR', '科尔萨科夫', 'Korsakov', 0, 1, 'RU', 0, 0, '{CC}'),
('RUKHO', '霍尔姆斯克', 'Kholmsk', 0, 1, 'RU', 0, 0, '{CC}'),
('RUKGD', '加里宁格勒', 'Kaliningrad', 0, 1, 'RU', 0, 0, '{CC}'),
('RUDYR', '阿纳德尔', 'Anadyr', 0, 1, 'RU', 0, 0, '{CC}'),
('RUARH', '阿尔汉格尔斯克', 'Arkhangelsk', 0, 1, 'RU', 0, 0, '{CC}'),
('SAYNB', '延布', 'Yanbu al-Bahr', 0, 1, 'SA', 0, 0, '{CC}'),
('SARTA', '拉斯坦努拉', 'Ras Tanura', 0, 1, 'SA', 0, 0, '{CC}'),
('SAJUT', '朱阿马港', 'Juaymah Terminal', 0, 1, 'SA', 0, 0, '{CC}'),
('SAJUB', '朱拜勒', 'Jubail', 0, 1, 'SA', 0, 0, '{CC}'),
('SAJED', '吉达', 'Jeddah', 0, 1, 'SA', 0, 0, '{CC}'),
('SAGIZ', '吉赞', 'Jizan', 0, 1, 'SA', 0, 0, '{CC}'),
('SADMM', '达曼', 'Ad Dammam', 0, 1, 'SA', 0, 0, '{CC}'),
('SBSHH', '肖特兰岛', 'Shortland Harbour', 0, 1, 'SB', 0, 0, '{CC}'),
('SBRIN', '林吉科弗', 'Ringgi Cove', 0, 1, 'SB', 0, 0, '{CC}'),
('SBHIR', '霍尼亚拉', 'Honiara', 0, 1, 'SB', 0, 0, '{CC}'),
('SCPOV', '维多利亚港', 'Port Victoria', 0, 1, 'SC', 0, 0, '{CC}'),
('SDPZU', '苏丹港', 'Port Sudan', 0, 1, 'SD', 0, 0, '{CC}'),
('SEUME', '于默奥', 'Umea', 0, 1, 'SE', 0, 0, '{CC}'),
('SEUDD', '乌德瓦拉', 'Uddevalla', 0, 1, 'SE', 0, 0, '{CC}'),
('SESTO', '斯德哥尔摩', 'Stockholm', 0, 1, 'SE', 0, 0, '{CC}'),
('SESDL', '松兹瓦尔', 'Sundsvall', 0, 1, 'SE', 0, 0, '{CC}'),
('SEPIT', '皮特奥', 'Pitea', 0, 1, 'SE', 0, 0, '{CC}'),
('SEOXE', '乌克瑟勒松德', 'Oxelosund', 0, 1, 'SE', 0, 0, '{CC}'),
('SEOER', '恩舍尔兹维克', 'Ornskoldsvik', 0, 1, 'SE', 0, 0, '{CC}'),
('SENRK', '诺尔雪平', 'Norrkoping', 0, 1, 'SE', 0, 0, '{CC}'),
('SEMMA', '马尔默', 'Malmo', 0, 1, 'SE', 0, 0, '{CC}'),
('SELLA', '吕勒奥', 'Lulea', 0, 1, 'SE', 0, 0, '{CC}'),
('SELAA', '兰斯克鲁纳', 'Landskrona', 0, 1, 'SE', 0, 0, '{CC}'),
('SEKLR', '卡尔马', 'Kalmar', 0, 1, 'SE', 0, 0, '{CC}'),
('SEKAN', '卡尔斯港', 'Karlshamn', 0, 1, 'SE', 0, 0, '{CC}'),
('SEKAA', '卡尔斯克鲁纳', 'Karlskrona', 0, 1, 'SE', 0, 0, '{CC}'),
('SEHND', '海讷桑德', 'Harnosand', 0, 1, 'SE', 0, 0, '{CC}'),
('SEHEL', '赫尔辛堡', 'Helsingborg', 0, 1, 'SE', 0, 0, '{CC}'),
('SEHAD', '哈尔姆斯塔德', 'Halmstad', 0, 1, 'SE', 0, 0, '{CC}'),
('SEGVX', '耶夫勒', 'Gavle', 0, 1, 'SE', 0, 0, '{CC}'),
('SEGOT', '哥德堡', 'Goteborg', 0, 1, 'SE', 0, 0, '{CC}'),
('SEFAG', '法尔肯贝里', 'Falkenberg', 0, 1, 'SE', 0, 0, '{CC}'),
('SGSIN', '新加坡', 'Singapore', 0, 1, 'SG', 0, 0, '{CC}'),
('SHSHN', '詹姆斯敦', 'Jamestown', 0, 1, 'SH', 0, 0, '{CC}'),
('SHASI', '乔治敦', 'Georgetown', 0, 1, 'SH', 0, 0, '{CC}'),
('SIKOP', '科佩尔', 'Koper', 0, 1, 'SI', 0, 0, '{CC}'),
('SLPEP', '佩佩尔', 'Pepel', 0, 1, 'SL', 0, 0, '{CC}'),
('SLFNA', '弗里敦', 'Freetown', 0, 1, 'SL', 0, 0, '{CC}'),
('SLBTE', '邦特', 'Bonthe', 0, 1, 'SL', 0, 0, '{CC}'),
('SNZIG', '济金绍尔', 'Ziguinchor', 0, 1, 'SN', 0, 0, '{CC}'),
('SNXLS', '圣路易', 'St Louis', 0, 1, 'SN', 0, 0, '{CC}'),
('SNKLC', '考拉克', 'Kaolack', 0, 1, 'SN', 0, 0, '{CC}'),
('SNDKR', '达喀尔', 'Dakar', 0, 1, 'SN', 0, 0, '{CC}'),
('SOMGQ', '摩加迪沙', 'Mogadishu', 0, 1, 'SO', 0, 0, '{CC}'),
('SOKMU', '基斯马尤', 'Kismayu', 0, 1, 'SO', 0, 0, '{CC}'),
('SOBBO', '柏培拉', 'Berbera', 0, 1, 'SO', 0, 0, '{CC}'),
('SRPRM', '帕拉南', 'Paranam', 0, 1, 'SR', 0, 0, '{CC}'),
('SRPBM', '帕拉马里博', 'Paramaribo', 0, 1, 'SR', 0, 0, '{CC}'),
('SRMOJ', '蒙戈', 'Moengo', 0, 1, 'SR', 0, 0, '{CC}'),
('STTMS', '圣多美', 'Sao Tome Island', 0, 1, 'ST', 0, 0, '{CC}'),
('SVLLD', '拉利贝塔德', 'La Libertad', 0, 1, 'SV', 0, 0, '{CC}'),
('SVAQJ', '阿卡胡特拉', 'Acajutla', 0, 1, 'SV', 0, 0, '{CC}'),
('SYTTS', '塔尔图斯', 'Tartus', 0, 1, 'SY', 0, 0, '{CC}'),
('SYLTK', '拉塔基亚', 'Latakia', 0, 1, 'SY', 0, 0, '{CC}'),
('SYBAN', '巴尼亚斯', 'Baniyas', 0, 1, 'SY', 0, 0, '{CC}'),
('TCGDT', '大特克', 'Grand Turk Island', 0, 1, 'TC', 0, 0, '{CC}'),
('TGLFW', '洛美', 'Lome', 0, 1, 'TG', 0, 0, '{CC}'),
('TGKPE', '佩梅', 'Kpeme', 0, 1, 'TG', 0, 0, '{CC}'),
('THSIR', '是拉差', 'Si Racha', 0, 1, 'TH', 0, 0, '{CC}'),
('THSGZ', '宋卡', 'Songkh1a', 0, 1, 'TH', 0, 0, '{CC}'),
('THSAT', '梭桃邑', 'Sattahip', 0, 1, 'TH', 0, 0, '{CC}'),
('THPAN', '北大年', 'Pattani', 0, 1, 'TH', 0, 0, '{CC}'),
('THNAW', '那拉提瓦', 'Narathiwat', 0, 1, 'TH', 0, 0, '{CC}'),
('THLCH', '林查班', 'Laem Chabang', 0, 1, 'TH', 0, 0, '{CC}'),
('THHKT', '普吉', 'Phuket', 0, 1, 'TH', 0, 0, '{CC}'),
('THBKK', '曼谷', 'Bangkok', 0, 1, 'TH', 0, 0, '{CC}'),
('TKAFU', '阿塔富', 'Atafu', 0, 1, 'TK', 0, 0, '{CC}'),
('TLDIL', '帝力', 'Dili', 0, 1, 'TL', 0, 0, '{CC}'),
('TNTUN', '突尼斯', 'Tunis', 0, 1, 'TN', 0, 0, '{CC}'),
('TNSUS', '苏塞', 'Sousse', 0, 1, 'TN', 0, 0, '{CC}'),
('TNSFA', '斯法克斯', 'Sfax', 0, 1, 'TN', 0, 0, '{CC}'),
('TNLSK', '拉斯基拉', 'La Skhirra', 0, 1, 'TN', 0, 0, '{CC}'),
('TNGAE', '加贝斯', 'Gabes', 0, 1, 'TN', 0, 0, '{CC}'),
('TNBIZ', '比塞大', 'Bizerte', 0, 1, 'TN', 0, 0, '{CC}'),
('TOTBU', '努库阿洛法', 'Nuku alofa', 0, 1, 'TO', 0, 0, '{CC}'),
('TONEI', '内亚富', 'Neiafu', 0, 1, 'TO', 0, 0, '{CC}'),
('TRZON', '宗古尔达克', 'Zonguldak', 0, 1, 'TR', 0, 0, '{CC}'),
('TRTZX', '特拉布宗', 'Trabzon', 0, 1, 'TR', 0, 0, '{CC}'),
('TRTEK', '泰基尔达', 'Tekirdag', 0, 1, 'TR', 0, 0, '{CC}'),
('TRSSX', '萨姆松', 'Samsun', 0, 1, 'TR', 0, 0, '{CC}'),
('TRSIC', '锡诺普', 'Sinop', 0, 1, 'TR', 0, 0, '{CC}'),
('TRMER', '梅尔辛', 'Mersin', 0, 1, 'TR', 0, 0, '{CC}'),
('TRKUS', '库沙达瑟', 'Kusadasi', 0, 1, 'TR', 0, 0, '{CC}'),
('TRIZT', '伊兹米特', 'Izmit', 0, 1, 'TR', 0, 0, '{CC}'),
('TRIZM', '伊兹密尔', 'Izmir', 0, 1, 'TR', 0, 0, '{CC}'),
('TRIST', '伊斯坦布尔', 'Istanbul', 0, 1, 'TR', 0, 0, '{CC}'),
('TRISK', '伊斯肯德伦', 'Iskenderun', 0, 1, 'TR', 0, 0, '{CC}'),
('TRGIR', '吉雷松', 'Giresun', 0, 1, 'TR', 0, 0, '{CC}'),
('TRGEM', '盖姆利克', 'Gemlik', 0, 1, 'TR', 0, 0, '{CC}'),
('TRGEL', '盖利博卢', 'Gelibolu', 0, 1, 'TR', 0, 0, '{CC}'),
('TRERE', '埃雷利', 'Eregli', 0, 1, 'TR', 0, 0, '{CC}'),
('TRDRC', '代林杰', 'Derince', 0, 1, 'TR', 0, 0, '{CC}'),
('TRCKZ', '恰纳卡莱', 'Canakkale', 0, 1, 'TR', 0, 0, '{CC}'),
('TRBDM', '班德尔马', 'Bandirma', 0, 1, 'TR', 0, 0, '{CC}'),
('TRAYT', '安塔利亚', 'Antalya', 0, 1, 'TR', 0, 0, '{CC}'),
('TTPTS', '利萨斯角', 'Point Lisas', 0, 1, 'TT', 0, 0, '{CC}'),
('TTPOS', '西班牙港', 'Port-of-Spain', 0, 1, 'TT', 0, 0, '{CC}'),
('TTCHA', '查瓜拉马斯', 'Chaguaramas', 0, 1, 'TT', 0, 0, '{CC}'),
('TVFUN', '富纳富提', 'Funafuti', 0, 1, 'TV', 0, 0, '{CC}'),
('TWTXG', '台中', 'Taichung', 0, 1, 'TW', 0, 0, '{CC}'),
('TWTPE', '台北', 'Taipei', 0, 1, 'TW', 0, 0, '{CC}'),
('TWTNN', '台南', 'Tainan', 0, 1, 'TW', 0, 0, '{CC}'),
('TWSUO', '苏澳', 'Suao', 0, 1, 'TW', 0, 0, '{CC}'),
('TWKHH', '高雄', 'Kaohsiung', 0, 1, 'TW', 0, 0, '{CC}'),
('TWKEL', '基隆', 'Keelung(Chilung)', 0, 1, 'TW', 0, 0, '{CC}'),
('TWHUN', '花莲', 'Hualien', 0, 1, 'TW', 0, 0, '{CC}'),
('TZZNZ', '桑给巴尔岛', 'Zanzibar', 0, 1, 'TZ', 0, 0, '{CC}'),
('TZTGT', '坦噶', 'Tanga', 0, 1, 'TZ', 0, 0, '{CC}'),
('TZMYW', '姆特瓦拉', 'Mtwara', 0, 1, 'TZ', 0, 0, '{CC}'),
('TZLDI', '林迪', 'Lindi', 0, 1, 'TZ', 0, 0, '{CC}'),
('TZDAR', '达累斯萨拉姆', 'Dar es Salaam', 0, 1, 'TZ', 0, 0, '{CC}'),
('UAYAL', '雅尔塔', 'Yalta', 0, 1, 'UA', 0, 0, '{CC}'),
('UASVP', '塞瓦斯托波尔', 'Sevastopol', 0, 1, 'UA', 0, 0, '{CC}'),
('UAODS', '敖德萨', 'Odessa', 0, 1, 'UA', 0, 0, '{CC}'),
('UANIK', '尼古拉耶夫', 'Nikolayev', 0, 1, 'UA', 0, 0, '{CC}'),
('UAMPW', '马里乌波尔', 'Mariupol（Zhdanov）', 0, 1, 'UA', 0, 0, '{CC}'),
('UAKHE', '赫尔松', 'Kherson', 0, 1, 'UA', 0, 0, '{CC}'),
('UAKEH', '刻赤', 'Kertch', 0, 1, 'UA', 0, 0, '{CC}'),
('UAIZM', '伊兹梅尔', 'Izmail', 0, 1, 'UA', 0, 0, '{CC}'),
('UAILK', '伊利乔夫斯克', 'Illichivs k（Ilichevsk）', 0, 1, 'UA', 0, 0, '{CC}'),
('UAERD', '别尔江斯克', 'Berdyansk', 0, 1, 'UA', 0, 0, '{CC}'),
('USWTN', '威尔明顿', 'Wilmington', 0, 1, 'US', 0, 0, '{CC}'),
('USTXT', '得克萨斯城', 'Texas City', 0, 1, 'US', 0, 0, '{CC}'),
('USTPA', '坦帕', 'Tampa', 0, 1, 'US', 0, 0, '{CC}'),
('USTOL', '托莱多', 'Toledo', 0, 1, 'US', 0, 0, '{CC}'),
('USTIW', '塔科马', 'Tacoma', 0, 1, 'US', 0, 0, '{CC}'),
('USSSI', '不伦瑞克', 'Brunswick', 0, 1, 'US', 0, 0, '{CC}'),
('USSFO', '圣弗朗西斯科', 'San Francisco', 0, 1, 'US', 0, 0, '{CC}'),
('USSEW', '苏厄德', 'Seward', 0, 1, 'US', 0, 0, '{CC}'),
('USSEA', '西雅图', 'Seattle', 0, 1, 'US', 0, 0, '{CC}'),
('USSAV', '萨凡纳', 'Savannah', 0, 1, 'US', 0, 0, '{CC}'),
('USSAN', '圣迭戈', 'San Diego', 0, 1, 'US', 0, 0, '{CC}'),
('USPWM', '波特兰', 'Portland', 0, 1, 'US', 0, 0, '{CC}'),
('USPSM', '朴次茅斯', 'Portsmouth', 0, 1, 'US', 0, 0, '{CC}'),
('USPHL', '费城', 'Philadelphia', 0, 1, 'US', 0, 0, '{CC}'),
('USPDX', '波特兰', 'Portland', 0, 1, 'US', 0, 0, '{CC}'),
('USORF', '诺福克', 'Norfolk', 0, 1, 'US', 0, 0, '{CC}'),
('USOAK', '奥克兰', 'Oakland', 0, 1, 'US', 0, 0, '{CC}'),
('USNYC', '纽约', 'New York', 0, 1, 'US', 0, 0, '{CC}'),
('USNBD', '新贝德福德', 'New Bedford', 0, 1, 'US', 0, 0, '{CC}'),
('USMSY', '新奥尔良', 'New Orleans', 0, 1, 'US', 0, 0, '{CC}'),
('USMOB', '莫比尔', 'Mobile', 0, 1, 'US', 0, 0, '{CC}'),
('USMIA', '迈阿密', 'Miami', 0, 1, 'US', 0, 0, '{CC}'),
('USMEM', '孟菲斯', 'Memphis', 0, 1, 'US', 0, 0, '{CC}'),
('USLGB', '长滩', 'Long Beach', 0, 1, 'US', 0, 0, '{CC}'),
('USLCH', '莱克查尔斯', 'Lake Charles', 0, 1, 'US', 0, 0, '{CC}'),
('USLAX', '洛杉矶', 'Los Angeles', 0, 1, 'US', 0, 0, '{CC}'),
('USJVL', '杰克逊维尔', 'Janesville', 0, 1, 'US', 0, 0, '{CC}'),
('USJAX', '杰克逊维尔', 'Jacksonville', 0, 1, 'US', 0, 0, '{CC}'),
('USHVN', '纽黑文', 'New Haven', 0, 1, 'US', 0, 0, '{CC}'),
('USHOU', '休斯敦', 'Houston', 0, 1, 'US', 0, 0, '{CC}'),
('USHNL', '火奴鲁鲁', 'Honolulu', 0, 1, 'US', 0, 0, '{CC}'),
('USDUT', '荷兰港', 'Dutch Harbor', 0, 1, 'US', 0, 0, '{CC}'),
('USDST', '亚当斯顿', 'Adamston', 0, 1, 'US', 0, 0, '{CC}'),
('USDET', '底特律', 'Detroit', 0, 1, 'US', 0, 0, '{CC}'),
('USCLE', '克利夫兰', 'Cleveland', 0, 1, 'US', 0, 0, '{CC}'),
('USCHS', '查尔斯顿', 'Charleston', 0, 1, 'US', 0, 0, '{CC}'),
('USCHI', '芝加哥', 'Chicago', 0, 1, 'US', 0, 0, '{CC}'),
('USCDE', '卡姆登', 'Camden', 0, 1, 'US', 0, 0, '{CC}'),
('USBOS', '波士顿', 'Boston', 0, 1, 'US', 0, 0, '{CC}'),
('USBAL', '巴尔的摩', 'Baltimore', 0, 1, 'US', 0, 0, '{CC}'),
('USANC', '安科雷奇', 'Anchorage', 0, 1, 'US', 0, 0, '{CC}'),
('USALB', '奥尔巴尼', 'Albany', 0, 1, 'US', 0, 0, '{CC}'),
('UYPDP', '埃斯特角', 'Punta del Este', 0, 1, 'UY', 0, 0, '{CC}'),
('UYNVP', '新帕尔米拉', 'Nueva Palmira', 0, 1, 'UY', 0, 0, '{CC}'),
('UYMVD', '蒙得维的亚', 'Montevideo', 0, 1, 'UY', 0, 0, '{CC}'),
('VCKTN', '金斯敦', 'Kingstown', 0, 1, 'VC', 0, 0, '{CC}'),
('VEPZO', '奥尔达斯港', 'Puerto Ordaz', 0, 1, 'VE', 0, 0, '{CC}'),
('VEPPD', '蓬塔-德彼徳拉斯', 'Punta de Piedra', 0, 1, 'VE', 0, 0, '{CC}'),
('VEPCZ', '拉克鲁斯港', 'Puerto La Cruz', 0, 1, 'VE', 0, 0, '{CC}'),
('VEPCN', '篷塔卡尔东', 'Punta Cardon', 0, 1, 'VE', 0, 0, '{CC}'),
('VEPBL', '卡贝略港', 'Puerto Cabello', 0, 1, 'VE', 0, 0, '{CC}'),
('VEMAR', '马拉开波', 'Maracaibo', 0, 1, 'VE', 0, 0, '{CC}'),
('VELAG', '拉瓜伊拉', 'La Guaira', 0, 1, 'VE', 0, 0, '{CC}'),
('VEGUI', '圭里亚', 'Guiria', 0, 1, 'VE', 0, 0, '{CC}'),
('VECUM', '库马纳', 'Cumana', 0, 1, 'VE', 0, 0, '{CC}'),
('VEAMY', '阿穆艾', 'Amuay', 0, 1, 'VE', 0, 0, '{CC}'),
('VGRAD', '罗德城', 'Road Town', 0, 1, 'VG', 0, 0, '{CC}'),
('VICHA', '夏洛特阿马利亚', 'Charlotte Amalie', 0, 1, 'VI', 0, 0, '{CC}'),
('VNVUT', '头顿', 'Vung Tau', 0, 1, 'VN', 0, 0, '{CC}'),
('VNUIH', '归仁', 'Qui Nhon', 0, 1, 'VN', 0, 0, '{CC}'),
('VNSGN', '胡志明市', 'Ho Chi Minh City', 0, 1, 'VN', 0, 0, '{CC}'),
('VNNHA', '芽庄', 'Nha Trang', 0, 1, 'VN', 0, 0, '{CC}'),
('VNHUI', '顺化', 'Hue', 0, 1, 'VN', 0, 0, '{CC}'),
('VNHPH', '海防', 'Haiphong', 0, 1, 'VN', 0, 0, '{CC}'),
('VNHON', '鸿基', 'Hongai', 0, 1, 'VN', 0, 0, '{CC}'),
('VNDAD', '岘港', 'Da Nang', 0, 1, 'VN', 0, 0, '{CC}'),
('VNCRB', '金兰', 'Camranh', 0, 1, 'VN', 0, 0, '{CC}'),
('VUVLI', '维拉港', 'Port Vila/Vila', 0, 1, 'VU', 0, 0, '{CC}'),
('VUSAN', '桑托', 'Santo', 0, 1, 'VU', 0, 0, '{CC}'),
('WFMAU', '马塔乌图', 'Mata utu', 0, 1, 'WF', 0, 0, '{CC}'),
('WSAPW', '阿皮亚', 'Apia', 0, 1, 'WF', 0, 0, '{CC}'),
('YESAL', '萨利夫', 'Saleef Port', 0, 1, 'YE', 0, 0, '{CC}'),
('YEMOK', '穆哈', 'Mokha', 0, 1, 'YE', 0, 0, '{CC}'),
('YEMKX', '穆卡拉', 'Mukalla', 0, 1, 'YE', 0, 0, '{CC}'),
('YEHOD', '荷台达', 'Hodeidah', 0, 1, 'YE', 0, 0, '{CC}'),
('YEADE', '亚丁', 'Aden', 0, 1, 'YE', 0, 0, '{CC}'),
('YTDZA', '藻德济', 'Dzaoudzi', 0, 1, 'YT', 0, 0, '{CC}'),
('ZASDB', '萨尔达尼亚湾', 'Saldanha Bay', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZARCB', '理查兹贝', 'Richards Bay', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZAPLZ', '伊丽莎白港', 'Port Elizabeth', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZAMZY', '莫塞尔贝', 'Mossel Bay', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZAELS', '东伦敦', 'East London', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZADUR', '德班', 'Durban', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZACPT', '开普敦', 'Cape Town', 0, 1, 'ZA', 0, 0, '{CC}')
;

