--
-- 初始化 `G_PORT`
--
INSERT INTO `G_PORT` (`PORT_CODE`,`PORT_NAME_CN`,  `PORT_NAME_EN`, `PORT_TYPE`, `ACTIVE`, `COUN_CODE`, `VERSION`, `REMOVED`, `COMP_CODE`) VALUES
('AESHJ', '沙迦', 'SHARJAH',  0, 1, 'AE', 0, 0, '{CC}'),
('AEPRA', '拉希德港', 'PORT RASHID',  0, 1, 'AE', 0, 0, '{CC}'),
('AEKLF', '豪尔费坎','KHOR AL FAKKAN（KHAWR FAKKAN）',  0, 1, 'AE', 0, 0, '{CC}'),
('AEJEA', '阿里山','JEBEL ALI',  0, 1, 'AE', 0, 0, '{CC}'),
('AEFJR', '富查伊拉','AL FUJAYRAH',  0, 1, 'AE', 0, 0, '{CC}'),
('AEDXB', '迪拜','DUBAI',  0, 1, 'AE', 0, 0, '{CC}'),
('AEAUH', '阿布扎比','ABU DHABI',  0, 1, 'AE', 0, 0, '{CC}'),
('AGSJO', '圣约翰斯','ST JOHNS',  0, 1, 'AG', 0, 0, '{CC}'),
('AIROA', '路德湾','THE ROAD',  0, 1, 'AI', 0, 0, '{CC}'),
('ALVOA', '发罗拉','VLORA（VLONE）',  0, 1, 'AL', 0, 0, '{CC}'),
('ALSHG', '圣吉尼','SHENGJIN',  0, 1, 'AL', 0, 0, '{CC}'),
('ALSAR', '萨兰达','SARANDE',  0, 1, 'AL', 0, 0, '{CC}'),
('ALDRZ', '都拉斯','DURRES',  0, 1, 'AL', 0, 0, '{CC}'),
('ANWIL', '威廉斯塔德', 'WILLEMSTAD', 0, 1, 'AN', 0, 0, '{CC}'),
('ANPHI', '菲利普斯堡', 'PHILIPSBURG', 0, 1, 'AN', 0, 0, '{CC}'),
('ANKRA', '克拉伦代克', 'KRALENDIJK', 0, 1, 'AN', 0, 0, '{CC}'),
('AOPLE', '亚历山大港', 'PORTO ALEXANDRE (TOMBUA)', 0, 1, 'AO', 0, 0, '{CC}'),
('AOPBN', '安博因港', 'PORTO AMBOIM', 0, 1, 'AO', 0, 0, '{CC}'),
('AONDD', '松贝', 'SUMBE（NOVO REDONDO）', 0, 1, 'AO', 0, 0, '{CC}'),
('AOMSZ', '纳米贝', 'NAMIBE', 0, 1, 'AO', 0, 0, '{CC}'),
('AOLOB', '洛比托', 'LOBITO', 0, 1, 'AO', 0, 0, '{CC}'),
('AOLAD', '罗安达', 'LUANDA', 0, 1, 'AO', 0, 0, '{CC}'),
('AOCAB', '卡宾达', 'CABINDA', 0, 1, 'AO', 0, 0, '{CC}'),
('AOBUG', '本格拉', 'BENGUELA', 0, 1, 'AO', 0, 0, '{CC}'),
('ARUSH', '乌斯怀亚', 'USHUAIA', 0, 1, 'AR', 0, 0, '{CC}'),
('ARULA', '圣胡利安', 'SAN JULIAN', 0, 1, 'AR', 0, 0, '{CC}'),
('ARSSN', '圣塞瓦斯蒂安', 'SAN SEBASTIAN', 0, 1, 'AR', 0, 0, '{CC}'),
('ARSNS', '圣尼古拉斯', 'SAN NICOLAS DE LOS ARROYOS', 0, 1, 'AR', 0, 0, '{CC}'),
('ARRZA', '圣克鲁斯', 'SANTA CRUZ', 0, 1, 'AR', 0, 0, '{CC}'),
('ARROS', '罗萨里奥', 'ROSARIO', 0, 1, 'AR', 0, 0, '{CC}'),
('ARRGL', '里奥加耶戈斯', 'RIO GALLEGOS', 0, 1, 'AR', 0, 0, '{CC}'),
('ARQQN', '克肯', 'QUEQUEN', 0, 1, 'AR', 0, 0, '{CC}'),
('ARPUD', '德塞阿多港', 'PUERTO DESEADO', 0, 1, 'AR', 0, 0, '{CC}'),
('ARPMY', '马德林港', 'PUERTO MADRYN', 0, 1, 'AR', 0, 0, '{CC}'),
('ARNEC', '内科切阿', 'NECOCHEA', 0, 1, 'AR', 0, 0, '{CC}'),
('ARMDQ', '马德普拉塔', 'MAR DEL PLATA', 0, 1, 'AR', 0, 0, '{CC}'),
('ARLPG', '拉普拉塔', 'LA PLATA', 0, 1, 'AR', 0, 0, '{CC}'),
('ARDME', '迪亚曼泰', 'DIAMANTE', 0, 1, 'AR', 0, 0, '{CC}'),
('ARCVI', '奥利维亚', 'CALETA OLIVIA', 0, 1, 'AR', 0, 0, '{CC}'),
('ARCRD', '里瓦达维亚海军准将城', 'COMODORO RIVADAVIA', 0, 1, 'AR', 0, 0, '{CC}'),
('ARCMP', '坎帕纳', 'CAMPANA', 0, 1, 'AR', 0, 0, '{CC}'),
('ARBUE', '布宜诺斯艾利斯', 'BUENOS AIRES', 0, 1, 'AR', 0, 0, '{CC}'),
('ARBHI', '布兰卡港', 'BAHIA BLANCA', 0, 1, 'AR', 0, 0, '{CC}'),
('ASPPG', '帕果帕果', 'PAGO PAGO', 0, 1, 'AS', 0, 0, '{CC}'),
('AUYAM', '扬皮桑德', 'YAMPI SOUND', 0, 1, 'AU', 0, 0, '{CC}'),
('AUWYA', '怀阿拉', 'WHYALLA', 0, 1, 'AU', 0, 0, '{CC}'),
('AUWEI', '韦帕', 'WEIPA', 0, 1, 'AU', 0, 0, '{CC}'),
('AUTSV', '汤斯维尔', 'TOWNSVILLE', 0, 1, 'AU', 0, 0, '{CC}'),
('AUSYD', '悉尼', 'SYDNEY', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPUG', '奥古斯塔港', 'PORT AUGUSTA', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPTJ', '波特兰', 'PORTLAND', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPPI', '皮里港', 'PORT PIRIE', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPLO', '林肯港', 'PORT LINCOLN', 0, 1, 'AU', 0, 0, '{CC}'),
('AUPHE', '黑德兰港', 'PORT HEDLAND', 0, 1, 'AU', 0, 0, '{CC}'),
('AUNTL', '纽卡斯尔', 'NEWCASTLE', 0, 1, 'AU', 0, 0, '{CC}'),
('AUMKY', '麦凯', 'MACKAY', 0, 1, 'AU', 0, 0, '{CC}'),
('AUMEL', '墨尔本', 'MELBOURNE', 0, 1, 'AU', 0, 0, '{CC}'),
('AUHBA', '霍巴特', 'HOBART', 0, 1, 'AU', 0, 0, '{CC}'),
('AUGLT', '格拉德斯通', 'GLADSTONE', 0, 1, 'AU', 0, 0, '{CC}'),
('AUGEX', '吉朗', 'GEELONG', 0, 1, 'AU', 0, 0, '{CC}'),
('AUGET', '杰拉尔顿', 'GERALDTON', 0, 1, 'AU', 0, 0, '{CC}'),
('AUFRE', '弗里曼特尔', 'FREMANTLE', 0, 1, 'AU', 0, 0, '{CC}'),
('AUDRW', '达尔文', 'DARWIN', 0, 1, 'AU', 0, 0, '{CC}'),
('AUDAM', '丹皮尔', 'DAMPIER', 0, 1, 'AU', 0, 0, '{CC}'),
('AUCNS', '凯恩斯', 'CAIRNS', 0, 1, 'AU', 0, 0, '{CC}'),
('AUBUY', '班伯里', 'BUNBURY', 0, 1, 'AU', 0, 0, '{CC}'),
('AUBNE', '布里斯班', 'BRISBANE', 0, 1, 'AU', 0, 0, '{CC}'),
('AUALH', '奥尔巴尼', 'ALBANY', 0, 1, 'AU', 0, 0, '{CC}'),
('AUADL', '阿德莱德', 'ADELAIDE', 0, 1, 'AU', 0, 0, '{CC}'),
('AWSNL', '圣尼古拉斯湾', 'SINT NICOLAAS', 0, 1, 'AW', 0, 0, '{CC}'),
('AWORJ', '奥拉涅斯塔德', 'ORANJESTAD', 0, 1, 'AW', 0, 0, '{CC}'),
('BBBGI', '布里奇敦', 'BRIDGETOWN',  0, 1, 'BB', 0, 0, '{CC}'),
('BDMGL', '蒙拉', 'MONGLA（MUNGLA）', 0, 1, 'BD', 0, 0, '{CC}'),
('BDKHL', '库尔纳', 'KHULNA', 0, 1, 'BD', 0, 0, '{CC}'),
('BDCHL', '贾尔纳', 'CHALNA',  0, 1, 'BD', 0, 0, '{CC}'),
('BDCGP', '吉大港', 'CHITTAGONG', 0, 1, 'BD', 0, 0, '{CC}'),
('BEZEE', '泽布吕赫/泽布腊赫', 'ZEEBRUGGE', 0, 1, 'BE', 0, 0, '{CC}'),
('BEOST', '奥斯坦德', 'OSTEND (OOSTENDE)', 0, 1, 'BE', 0, 0, '{CC}'),
('BEGNE', '根特', 'GENT (GHENT)', 0, 1, 'BE', 0, 0, '{CC}'),
('BEANR', '安特卫普', 'ANTWERPEN', 0, 1, 'BE', 0, 0, '{CC}'),
('BGVAR', '瓦尔纳', 'VARNA', 0, 1, 'BG', 0, 0, '{CC}'),
('BGSOZ', '索佐波尔', 'SOZOPOL', 0, 1, 'BG', 0, 0, '{CC}'),
('BGNES', '纳塞巴尔', 'NESSEBAR', 0, 1, 'BG', 0, 0, '{CC}'),
('BGBOJ', '布尔加斯', 'BURGAS', 0, 1, 'BG', 0, 0, '{CC}'),
('BHSIT', '锡特拉', 'SITRA', 0, 1, 'BH', 0, 0, '{CC}'),
('BHMIN', '米纳苏尔曼', 'MINA SULMAN', 0, 1, 'BH', 0, 0, '{CC}'),
('BHMAN', '麦纳麦', 'MANAMA（AL MANAMAH）', 0, 1, 'BH', 0, 0, '{CC}'),
('BHBAH', '巴林', 'BAHRAIN', 0, 1, 'BH', 0, 0, '{CC}'),
('BJPTN', '波多诺伏', 'PORTO-NOVO', 0, 1, 'BJ', 0, 0, '{CC}'),
('BJCOO', '科托努', 'COTONOU',  0, 1, 'BJ', 0, 0, '{CC}'),
('BMSGE', '圣乔治', 'SAINT GEORGE',  0, 1, 'BM', 0, 0, '{CC}'),
('BMBDA', '哈密尔顿', 'HAMILTON', 0, 1, 'BM', 0, 0, '{CC}'),
('BNSER', '诗里亚', 'SERIA', 0, 1, 'BM', 0, 0, '{CC}'),
('BNMUA', '麻拉', 'MUARA',  0, 1, 'BM', 0, 0, '{CC}'),
('BNBWN', '斯里巴加湾港', 'BANDAR SERI BEGAWAN', 0, 1, 'BM', 0, 0, '{CC}'),
('BRVIX', '维多利亚', 'VITORIA', 0, 1, 'BR', 0, 0, '{CC}'),
('BRTUB', '图巴朗', 'TUBARAO', 0, 1, 'BR', 0, 0, '{CC}'),
('BRTRM', '特拉曼达伊', 'TRAMANDAI', 0, 1, 'BR', 0, 0, '{CC}'),
('BRSSZ', '桑托斯', 'SANTOS', 0, 1, 'BR', 0, 0, '{CC}'),
('BRSSO', '圣塞巴斯蒂昂', 'SAO SEBASTIAO',  0, 1, 'BR', 0, 0, '{CC}'),
('BRSSA', '萨尔瓦多', 'SALVADOR',  0, 1, 'BR', 0, 0, '{CC}'),
('BRSLZ', '圣路易斯', 'SAO LUIS',  0, 1, 'BR', 0, 0, '{CC}'),
('BRSFS', '南圣弗朗西斯科', 'SAO FRANCISCO DO SUL',  0, 1, 'BR', 0, 0, '{CC}'),
('BRRIO', '里约热内卢', 'RIO DE JANEIRO',  0, 1, 'BR', 0, 0, '{CC}'),
('BRRIG', '里奥格兰德', 'RIO GRANDE',  0, 1, 'BR', 0, 0, '{CC}'),
('BRREC', '累西腓', 'RECIFE',  0, 1, 'BR', 0, 0, '{CC}'),
('BRPOA', '阿雷格里港', 'PORTO ALEGRE',  0, 1, 'BR', 0, 0, '{CC}'),
('BRPNG', '巴拉那瓜', 'PARANAGUA',  0, 1, 'BR', 0, 0, '{CC}'),
('BRPET', '佩洛塔斯', 'PELOTAS',  0, 1, 'BR', 0, 0, '{CC}'),
('BRNTR', '尼泰罗伊', 'NITEROI',  0, 1, 'BR', 0, 0, '{CC}'),
('BRNAT', '纳塔尔', 'NATAL',  0, 1, 'BR', 0, 0, '{CC}'),
('BRMCZ', '马塞约', 'MACEIO',  0, 1, 'BR', 0, 0, '{CC}'),
('BRMCP', '马卡帕', 'MACAPA',  0, 1, 'BR', 0, 0, '{CC}'),
('BRMAO', '马瑙斯', 'MANAUS',  0, 1, 'BR', 0, 0, '{CC}'),
('BRITJ', '伊塔雅伊', 'ITAJAI',  0, 1, 'BR', 0, 0, '{CC}'),
('BRIQI', '伊塔基', 'ITAQUI',  0, 1, 'BR', 0, 0, '{CC}'),
('BRIOS', '伊列乌斯', 'ILHEUS',  0, 1, 'BR', 0, 0, '{CC}'),
('BRIBB', '因比图巴', 'IMBITUBA',  0, 1, 'BR', 0, 0, '{CC}'),
('BRFOR', '福塔莱萨', 'FORTALEZA',  0, 1, 'BR', 0, 0, '{CC}'),
('BRBEL', '贝伦', 'BELEM',  0, 1, 'BR', 0, 0, '{CC}'),
('BRAJU', '阿拉卡茹', '	ARACAJU',  0, 1, 'BR', 0, 0, '{CC}'),
('BRADR', '安格拉-杜斯雷斯', 'ANGRA DOS REIS',  0, 1, 'BR', 0, 0, '{CC}'),
('BSNAS', '拿骚', 'NASSAU',  0, 1, 'BR', 0, 0, '{CC}'),
('BSFPO', '弗里波特', 'FREEPORT',  0, 1, 'BR', 0, 0, '{CC}'),
('BZBZE', '伯利兹城', 'BELIZE CITY',  0, 1, 'BR', 0, 0, '{CC}'),
('CAYRH', '雅茅思', 'YARMOUTH',  0, 1, 'CA', 0, 0, '{CC}'),
('CAVIC', '维多利亚', 'VICTORIA',  0, 1, 'CA', 0, 0, '{CC}'),
('CAVAN', '温哥华', 'VANCOUVER',  0, 1, 'CA', 0, 0, '{CC}'),
('CATRR', '三河城', 'THREE RIVERS（TROIS-RIVIERES）',  0, 1, 'CA', 0, 0, '{CC}'),
('CATOR', '多伦多', 'TORONTO',  0, 1, 'CA', 0, 0, '{CC}'),
('CATHU', '散德湾', 'THUNDER BAY',  0, 1, 'CA', 0, 0, '{CC}'),
('CASYD', '悉尼', 'SYDNEY',  0, 1, 'CA', 0, 0, '{CC}'),
('CASSM', '苏圣马丽', 'SAULT STE MARIE',  0, 1, 'CA', 0, 0, '{CC}'),
('CASNI', '萨尔尼亚', 'SARNIA',  0, 1, 'CA', 0, 0, '{CC}'),
('CASJF', '圣约翰斯', 'ST JOHN S',  0, 1, 'CA', 0, 0, '{CC}'),
('CASJB', '圣约翰', 'ST JOHN',  0, 1, 'CA', 0, 0, '{CC}'),
('CASEI', '七岛', 'SEPT-ILES',  0, 1, 'CA', 0, 0, '{CC}'),
('CAQUE', '魁北克', 'QUEBEC',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPTA', '塔西斯', 'TAHSIS',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPRR', '鲁珀特港', 'PRINCE RUPERT',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPOW', '鲍威尔', 'POWELL RIVER',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPCO', '科尔本港', 'PORT COLBORNE',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPCA', '卡捷港', 'PORT-CARTIER',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPAF', '艾尔夫雷德港', 'PORT-ALFRED',  0, 1, 'CA', 0, 0, '{CC}'),
('CAPAB', '艾伯尼港', 'PORT ALBERNI',  0, 1, 'CA', 0, 0, '{CC}'),
('CANNO', '纳奈莫', 'NANAIMO',  0, 1, 'CA', 0, 0, '{CC}'),
('CAMTR', '蒙特利尔', 'MONTREAL',  0, 1, 'CA', 0, 0, '{CC}'),
('CAHAM', '哈密尔顿', 'HAMILTON',  0, 1, 'CA', 0, 0, '{CC}'),
('CAHAL', '哈利法克斯', 'HALIFAX',  0, 1, 'CA', 0, 0, '{CC}'),
('CAGOR', '戈尔德里弗', 'GOLD RIVER',  0, 1, 'CA', 0, 0, '{CC}'),
('CACHV', '丘吉尔', 'CHURCHILL',  0, 1, 'CA', 0, 0, '{CC}'),
('CACHA', '夏洛特敦', 'CHARLOTTETOWN',  0, 1, 'CA', 0, 0, '{CC}'),
('CDMAT', '马塔迪', 'MATADI',  0, 1, 'CD', 0, 0, '{CC}'),
('CDBOA', '博马', 'BOMA',  0, 1, 'CD', 0, 0, '{CC}'),
('CDBNW', '巴纳纳', 'BANANA',  0, 1, 'CD', 0, 0, '{CC}'),
('CGPNR', '黑角', 'POINTE NOIRE',  0, 1, 'CG', 0, 0, '{CC}'),
('CGDJE', '杰诺港', 'DJENO TERMINAL',  0, 1, 'CG', 0, 0, '{CC}'),
('CIZSS', '萨桑德拉', 'SASSANDRA',  0, 1, 'CI', 0, 0, '{CC}'),
('CISPY', '圣佩德罗', 'SAN-PEDRO',  0, 1, 'CI', 0, 0, '{CC}'),
('CIDAB', '达布', 'DABOU',  0, 1, 'CI', 0, 0, '{CC}'),
('CIABJ', '阿比让', 'ABIDJAN',  0, 1, 'CI', 0, 0, '{CC}'),
('CKRAR', '拉罗通加岛', 'RAROTONGA',  0, 1, 'CK', 0, 0, '{CC}'),
('CKAVA', '阿瓦鲁阿', 'AVARUA',  0, 1, 'CK', 0, 0, '{CC}'),
('CKARU', '阿鲁通加', 'ARUTUNGA',  0, 1, 'CK', 0, 0, '{CC}'),
('CLZAL', '瓦尔迪维亚', 'VALDIVIA',  0, 1, 'CL', 0, 0, '{CC}'),
('CLWCA', '卡斯特罗', 'CASTRO',  0, 1, 'CL', 0, 0, '{CC}'),
('CLVAP', '瓦尔帕莱索', 'VALPARAISO',  0, 1, 'CL', 0, 0, '{CC}'),
('CLTOQ', '托科皮亚', 'TOCOPILLA',  0, 1, 'CL', 0, 0, '{CC}'),
('CLTAL', '塔尔卡瓦诺', 'TALCAHUANO',  0, 1, 'CL', 0, 0, '{CC}'),
('CLSVE', '圣维森特', 'SAN VICENTE',  0, 1, 'CL', 0, 0, '{CC}'),
('CLSAI', '圣安东尼奥', 'SAN ANTONIO',  0, 1, 'CL', 0, 0, '{CC}'),
('CLQTV', '金特罗', 'QUINTERO',  0, 1, 'CL', 0, 0, '{CC}'),
('CLQMC', '奎姆什', 'QUEMCHI',  0, 1, 'CL', 0, 0, '{CC}'),
('CLPUQ', '蓬塔阿雷纳斯', 'PUNTA ARENAS',  0, 1, 'CL', 0, 0, '{CC}'),
('CLPMC', '蒙特港', 'PUERTO MONTT',  0, 1, 'CL', 0, 0, '{CC}'),
('CLMJS', '梅希约内斯', 'MEJILLONES',  0, 1, 'CL', 0, 0, '{CC}'),
('CLLQN', '利尔奎', 'LIRQUEN',  0, 1, 'CL', 0, 0, '{CC}'),
('CLIQQ', '伊基克', 'IQUIQUE',  0, 1, 'CL', 0, 0, '{CC}'),
('CLHSO', '瓦斯科', 'HUASCO',  0, 1, 'CL', 0, 0, '{CC}'),
('CLCQQ', '科金博', 'COQUIMBO',  0, 1, 'CL', 0, 0, '{CC}'),
('CLCNR', '查尼亚拉尔', 'CHANARAL',  0, 1, 'CL', 0, 0, '{CC}'),
('CLCLD', '卡尔德拉', 'CALDERA',  0, 1, 'CL', 0, 0, '{CC}'),
('CLARI', '阿里卡', 'ARICA',  0, 1, 'CL', 0, 0, '{CC}'),
('CLANF', '安托法加斯塔', 'ANTOFAGASTA',  0, 1, 'CL', 0, 0, '{CC}'),
('CMVCC', '维多利亚', 'VICTORIA', 0, 1, 'CL', 0, 0, '{CC}'),
('CMTKC', '蒂科', 'TIKO', 0, 1, 'CL', 0, 0, '{CC}'),
('CMKBI', '克里比', 'KRIBI', 0, 1, 'CL', 0, 0, '{CC}'),
('CMDLA', '杜阿拉', 'DOUALA', 0, 1, 'CL', 0, 0, '{CC}'),
('CNZZU', '漳州', 'ZHANGZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZUH', '珠海', 'ZHUHAI', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZSN', '中山', 'ZHONGSHAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZPU', '乍浦', 'ZHAPU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZOS', '舟山', 'ZHOUSHAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZNG', '湛江', 'ZHANJIANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZJG', '张家港', 'ZHANGJIAGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZHI', '镇海港', 'ZHENHAIGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNZHE', '镇江', 'ZHENJIANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYZH', '扬州', 'YANGZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYUL', '榆林', 'YULIN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYTN', '盐田', 'YANTIAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYTG', '烟台', 'YANTAI', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYSA', '洋山港', 'YANGSHANGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYPG', '洋浦', 'YANGPU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYJI', '阳江', 'YANGJIANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNYIK', '营口', 'YINGKOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNXYG', '秀屿', 'XIUYU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNXIS', '象山港', 'XIANGSHANGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNXAM', '厦门', 'XIAMEN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWZO', '温州', 'WENZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWUG', '吴淞', 'WUSONG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWLG', '温岭港', 'WENLINGGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWGQ', '外高桥', 'WAIGAOQIAO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNWEI', '威海', 'WEIHAI', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTZU', '泰州', 'TAIZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTXG', '天津新港', 'TIANJINXINGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTNJ', '天津', 'TIANJIN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTGS', '唐山', 'TANGSHAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTAZ', '台州', 'TAIZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNTAC', '太仓', 'TAICANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSZH', '苏州', 'SUZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSZG', '深圳', 'SHENZHEN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSYA', '三亚', 'SANYA', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSWE', '汕尾', 'SHANWEI', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSTG', '汕头', 'SHANTOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSTB', '石头埠', 'SHITOUBU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSON', '松下', 'SONGXIA', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSHP', '秦皇岛', 'QINHUANGDAO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSHK', '蛇口', 'SHEKOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSHG', '上海', 'SHANGHAI', 0, 1, 'CN', 0, 0, '{CC}'),
('CNSHD', '石岛', 'SHIDAO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNRZH', '日照', 'RIZHAO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQZJ', '泉州', 'QUANZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQZH', '钦州', 'QINZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQSA', '企沙', 'QISHA', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQLN', '清澜', 'QINGLAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNQDG', '青岛', 'QINGDAO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNPUT', '莆田', 'PUTIAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNPTG', '普陀港', 'PUTUOGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNPLI', '蓬莱', 'PENGLAI', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNTG', '南通', 'NANTONG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNSA', '南沙', 'NANSHA', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNJG', '南京', 'NANJING', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNIH', '宁海港', 'NINGHAIGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNDS', '宁德', 'NINGDE', 0, 1, 'CN', 0, 0, '{CC}'),
('CNNBG', '宁波', 'NINGBO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNMWN', '妈湾', 'MAWAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNMSG', '梅山港', 'MEISHANGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNMMI', '茂名', 'MAOMING', 0, 1, 'CN', 0, 0, '{CC}'),
('CNMAW', '马尾', 'MAWEI', 0, 1, 'CN', 0, 0, '{CC}'),
('CNLZO', '莱州', 'LAIZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNLYG', '连云港', 'LIANYUNGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNLSN', '岚山', 'LANSHAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNLKU', '龙口', 'LONGKOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJZU', '九洲', 'JIUZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJTG', '京唐港', 'JINGTANGGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJNZ', '锦州', 'JINZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJMN', '江门', 'JIANGMEN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJIS', '江山', 'JIANGSHAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJIA', '江阴', 'JIANGYIN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNJAX', '嘉兴', 'JIAXING', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHXG', '海口新港', 'HAIKOUXINGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHUI', '惠州', 'HUIZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHUH', '黄骅', 'HUANGHUA', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHUD', '葫芦岛', 'HULUDAO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHUA', '黄埔', 'HUANGPU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHMN', '虎门', 'HUMEN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHME', '海门港', 'HAIMENGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHIG', '海口', 'HAIKOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNHDO', '黄岛', 'HUANGDAO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNGZG', '广州', 'GUANGZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNGNA', '广澳', 'GUANG AO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNGHI', '广海', 'GUANGHAI', 0, 1, 'CN', 0, 0, '{CC}'),
('CNGAO', '高港', 'GAOGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNFZG', '福州', 'FUZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNFAN', '防城港', 'FANGCHENGGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDYG', '东营', 'DONGYING', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDXG', '大连新港', 'DALIANXINGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDSN', '东山', 'DONGSHAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDOU', '斗门', 'DOUMEN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDJT', '东角头', 'DONGJIAOTOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDGG', '东莞', 'DONGGUAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDDG', '丹东', 'DANDONG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDAX', '大榭港', 'DAXIEGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNDAG', '大连', 'DALIAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCZX', '常州', 'CHANGZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCWN', '赤湾', 'CHIWAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCSG', '穿山港', 'CHUANSHANGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCOZ', '潮州', 'CHAOZHOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCHY', '潮阳', 'CHAOYANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCHE', '城澳', 'CHENG AO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCGS', '常熟', 'CHANGSHU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNCFD', '曹妃甸', 'CAOFEIDIAN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBSP', '八所', 'BASUO', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBSD', '宝山码头', 'BAOSHANMATOU', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBLG', '北仑港', 'BEILUNGANG', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBJN', '北津', 'BEIJIN', 0, 1, 'CN', 0, 0, '{CC}'),
('CNBIH', '北海', 'BEIHAI', 0, 1, 'CN', 0, 0, '{CC}'),
('COTRB', '图尔博', 'TURBO', 0, 1, 'CO', 0, 0, '{CC}'),
('COTCO', '图马科', 'TUMACO', 0, 1, 'CO', 0, 0, '{CC}'),
('COSMR', '圣玛尔塔', 'SANTA MARTA', 0, 1, 'CO', 0, 0, '{CC}'),
('COPCR', '卡雷尼奥港', 'PUERTO CARRENO', 0, 1, 'CO', 0, 0, '{CC}'),
('COCTG', '卡塔赫纳', 'CARTAGENA', 0, 1, 'CO', 0, 0, '{CC}'),
('COBUN', '布韦那文图拉', 'BUENAVENTURA', 0, 1, 'CO', 0, 0, '{CC}'),
('COBAQ', '巴兰基利亚', 'BARRANQUILLA', 0, 1, 'CO', 0, 0, '{CC}'),
('CRPAS', '彭塔雷纳斯', 'PUNTARENAS', 0, 1, 'CR', 0, 0, '{CC}'),
('CRLIO', '利蒙港', 'PUERTO LIMON', 0, 1, 'CR', 0, 0, '{CC}'),
('CRGLF', '戈尔菲托', 'GOLFITO', 0, 1, 'CR', 0, 0, '{CC}'),
('CRCAL', '卡尔德拉', 'CALDERA', 0, 1, 'CR', 0, 0, '{CC}'),
('CUSCU', '圣地亚哥', 'SANTIAGO DE CUBA', 0, 1, 'CU', 0, 0, '{CC}'),
('CUSCS', '南圣克鲁斯', 'SANTA CRUZ DEL SUR', 0, 1, 'CU', 0, 0, '{CC}'),
('CUQMA', '马坦萨斯', 'MATANZAS', 0, 1, 'CU', 0, 0, '{CC}'),
('CUMZO', '曼萨尼略', 'MANZANILLO', 0, 1, 'CU', 0, 0, '{CC}'),
('CUICR', '尼卡罗', 'NICARO', 0, 1, 'CU', 0, 0, '{CC}'),
('CUHAV', '哈瓦那', 'LA HABANA', 0, 1, 'CU', 0, 0, '{CC}'),
('CUCFG', '西恩富戈斯', 'CIENFUEGOS', 0, 1, 'CU', 0, 0, '{CC}'),
('CUCAR', '卡德纳斯', 'CARDENAS', 0, 1, 'CU', 0, 0, '{CC}'),
('CUCAI', '凯巴连', 'CAIBARIEN', 0, 1, 'CU', 0, 0, '{CC}'),
('CUANT', '安蒂亚', 'ANTILLA', 0, 1, 'CU', 0, 0, '{CC}'),
('CVRAI', '普拉亚', 'PRAIA', 0, 1, 'CV', 0, 0, '{CC}'),
('CVMIN', '明德卢', 'MINDELO', 0, 1, 'CV', 0, 0, '{CC}'),
('CYPFO', '帕福斯', 'PAPHOS', 0, 1, 'CY', 0, 0, '{CC}'),
('CYLMS', '利马索尔', 'LIMASSOL', 0, 1, 'CY', 0, 0, '{CC}'),
('CYLCA', '拉纳卡', 'LARNACA', 0, 1, 'CY', 0, 0, '{CC}'),
('CYFMG', '法马古斯塔', 'FAMAGUSTA', 0, 1, 'CY', 0, 0, '{CC}'),
('DEWVN', '威廉港', 'WILHELMSHAVEN', 0, 1, 'DE', 0, 0, '{CC}'),
('DEWIS', '维斯马', 'WISMAR', 0, 1, 'DE', 0, 0, '{CC}'),
('DERSK', '罗斯托克', 'ROSTOCK', 0, 1, 'DE', 0, 0, '{CC}'),
('DELBC', '吕贝克', 'LUBECK', 0, 1, 'DE', 0, 0, '{CC}'),
('DEKEL', '基尔', 'KIEL', 0, 1, 'DE', 0, 0, '{CC}'),
('DEHAM', '汉堡', 'HAMBURG', 0, 1, 'DE', 0, 0, '{CC}'),
('DEEME', '埃姆登', 'EMDEN', 0, 1, 'DE', 0, 0, '{CC}'),
('DECUX', '库克斯港', 'CUXHAVEN', 0, 1, 'DE', 0, 0, '{CC}'),
('DECGN', '科隆', 'KOLN（COLOGNE）', 0, 1, 'DE', 0, 0, '{CC}'),
('DEBRV', '不来梅港', 'BREMERHAVEN', 0, 1, 'DE', 0, 0, '{CC}'),
('DEBRE', '不来梅', 'BREMEN', 0, 1, 'DE', 0, 0, '{CC}'),
('DEBRB', '布伦斯比特尔', 'BRUNSBUTTEL', 0, 1, 'DE', 0, 0, '{CC}'),
('DJJIB', '吉布提', 'DJIBOUTI', 0, 1, 'DJ', 0, 0, '{CC}'),
('DKODE', '欧登塞', 'ODENSE', 0, 1, 'DK', 0, 0, '{CC}'),
('DKKAL', '凯隆堡', 'KALUNDBORG', 0, 1, 'DK', 0, 0, '{CC}'),
('DKHLS', '赫尔辛格', 'HELSINGOR', 0, 1, 'DK', 0, 0, '{CC}'),
('DKFRC', '腓特烈西亚', 'FREDERICIA', 0, 1, 'DK', 0, 0, '{CC}'),
('DKFDH', '腓特烈港', 'FREDERIKSHAVN', 0, 1, 'DK', 0, 0, '{CC}'),
('DKEBJ', '埃斯比约', 'ESBJERG', 0, 1, 'DK', 0, 0, '{CC}'),
('DKCPH', '哥本哈根', 'KOBENHAVN（COPENHAGEN）', 0, 1, 'DK', 0, 0, '{CC}'),
('DKAAR', '奥胡斯', 'ARHUS', 0, 1, 'DK', 0, 0, '{CC}'),
('DKAAL', '奥尔堡', 'AALBORG', 0, 1, 'DK', 0, 0, '{CC}'),
('DMRSU', '罗索', 'ROSEAU', 0, 1, 'DM', 0, 0, '{CC}'),
('DOSPM', '圣佩得罗德马科里斯', '	SAN PEDRO DE MACORIS', 0, 1, 'DO', 0, 0, '{CC}'),
('DOSDQ', '圣多明各', 'SANTO DOMINGO', 0, 1, 'DO', 0, 0, '{CC}'),
('DOPOP', '普拉塔港', 'PUERTO PLATA', 0, 1, 'DO', 0, 0, '{CC}'),
('DOLRM', '拉罗马纳', 'LA ROMANA', 0, 1, 'DO', 0, 0, '{CC}'),
('DOHAI', '海纳', 'RIO HAINA', 0, 1, 'DO', 0, 0, '{CC}'),
('DOBRX', '巴拉奥纳', 'BARAHONA', 0, 1, 'DO', 0, 0, '{CC}'),
('DZTEN', '提奈斯', 'TENES', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZSKI', '斯基克达', '	SKIKDA', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZORN', '奥兰', 'ORAN', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZDJI', '吉杰勒', 'DJIDJELLI（JIJEL）', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZBJA', '贝贾亚', 'BEJAIA', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZAZW', '阿尔泽', 'ARZEW', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZALG', '阿尔及尔', 'ALGER (ALGIERS)', 0, 1, 'DZ', 0, 0, '{CC}'),
('DZAAE', '安纳巴', 'ANNABA', 0, 1, 'DZ', 0, 0, '{CC}'),
('ECSNC', '萨利纳斯', 'SALINAS', 0, 1, 'EC', 0, 0, '{CC}'),
('ECMEC', '曼塔', 'MANTA', 0, 1, 'EC', 0, 0, '{CC}'),
('ECGYE', '瓜亚基尔', 'GUAYAQUIL', 0, 1, 'EC', 0, 0, '{CC}'),
('ECESM', '埃斯梅拉达斯', 'ESMERALDAS', 0, 1, 'EC', 0, 0, '{CC}'),
('ECBHA', '卡拉克斯港', 'BAHIA DE CARAQUEZ', 0, 1, 'EC', 0, 0, '{CC}'),
('EETLL', '塔林', 'TALLINN', 0, 1, 'EE', 0, 0, '{CC}'),
('EEPRN', '派尔努/皮亚尔努', 'PARNU', 0, 1, 'EE', 0, 0, '{CC}'),
('EGSUZ', '苏伊士', 'EL SUWEIS', 0, 1, 'EG', 0, 0, '{CC}'),
('EGSGA', '塞法杰', 'SAFAGA', 0, 1, 'EG', 0, 0, '{CC}'),
('EGRAG', '拉斯加里卜', 'RAS GHARIB', 0, 1, 'EG', 0, 0, '{CC}'),
('EGPSD', '塞得港', 'PORT SAID', 0, 1, 'EG', 0, 0, '{CC}'),
('EGDAM', '达米埃塔', 'DAMIETTA', 0, 1, 'EG', 0, 0, '{CC}'),
('EGAZA', '阿布宰尼迈', 'ABU ZENIMAH', 0, 1, 'EG', 0, 0, '{CC}'),
('EGALY', '亚历山大', 'EL ISKANDARIYA', 0, 1, 'EG', 0, 0, '{CC}'),
('EGADA', '阿代比耶', 'ADABIYA', 0, 1, 'EG', 0, 0, '{CC}'),
('EHVIC', '达赫拉', 'AD DAKHLA', 0, 1, 'EH', 0, 0, '{CC}'),
('ERMSW', '马萨瓦', 'MASSAWA (MITSIWA)', 0, 1, 'EH', 0, 0, '{CC}'),
('ERASA', '阿萨布', 'ASSAB', 0, 1, 'EH', 0, 0, '{CC}'),
('ESVLC', '巴伦西亚', 'VALENCIA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESVGO', '维哥', 'VIGO', 0, 1, 'ES', 0, 0, '{CC}'),
('ESTAR', '塔拉戈纳', 'TARRAGONA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESSVQ', '塞维利亚', 'SEVILLA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESSDR', '桑坦德', 'SANTANDER', 0, 1, 'ES', 0, 0, '{CC}'),
('ESSCT', '圣克鲁斯', 'SANTA CRUZ DE TENERIFE', 0, 1, 'ES', 0, 0, '{CC}'),
('ESSAG', '萨贡托', 'SAGUNTO', 0, 1, 'ES', 0, 0, '{CC}'),
('ESROT', '罗塔', 'ROTA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESPMI', '帕尔马', 'PALMA DE MALLORCA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESPAS', '帕萨赫斯', 'PASAJES', 0, 1, 'ES', 0, 0, '{CC}'),
('ESMLN', '梅利利亚', 'MELILLA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESLPA', '拉斯帕尔马斯', 'LAS PALMAS', 0, 1, 'ES', 0, 0, '{CC}'),
('ESLEI', '阿尔梅里亚', 'ALMERIA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESLCG', '拉科鲁尼亚', 'LA CORUNA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESGIJ', '希洪', 'GIJON', 0, 1, 'ES', 0, 0, '{CC}'),
('ESFUE', '罗萨里奥港', 'PUERTO DEL ROSARIO-FUERTEVENTURA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESFRO', '费罗尔', 'FERROL', 0, 1, 'ES', 0, 0, '{CC}'),
('ESCEU', '休达', 'CEUTA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESCAR', '卡塔赫纳', 'CARTAGENA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESCAD', '加的斯', 'CADIZ', 0, 1, 'ES', 0, 0, '{CC}'),
('ESBIO', '毕尔巴鄂', 'BILBAO', 0, 1, 'ES', 0, 0, '{CC}'),
('ESBCN', '巴塞罗那', 'BARCELONA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESAVS', '阿维莱斯', 'AVILES', 0, 1, 'ES', 0, 0, '{CC}'),
('ESALG', '阿尔赫西拉斯', 'ALGECIRAS', 0, 1, 'ES', 0, 0, '{CC}'),
('ESALC', '阿利坎特', 'ALICANTE', 0, 1, 'ES', 0, 0, '{CC}'),
('ESAGP', '马拉加', 'MALAGA', 0, 1, 'ES', 0, 0, '{CC}'),
('ESACE', '阿雷西费', 'ARRECIFE DE LANZAROTE', 0, 1, 'ES', 0, 0, '{CC}'),
('FIVAA', '瓦萨', 'VAASA (VASA)', 0, 1, 'FI', 0, 0, '{CC}'),
('FITOR', '托尔尼奥', 'TORNIO (TORNEA)', 0, 1, 'FI', 0, 0, '{CC}'),
('FITKU', '图尔库', 'TURKU (ABO)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIRAU', '劳马', 'RAUMA (RAUMO)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIPOR', '波里', 'PORI (BJORNEBORG)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIOLU', '奥卢', 'OULU', 0, 1, 'FI', 0, 0, '{CC}'),
('FIKTK', '科特卡', 'KOTKA', 0, 1, 'FI', 0, 0, '{CC}'),
('FIKRS', '克里斯蒂娜城', 'KRISTIINANKAUPUNKI (KRISTINESTAD)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIKOK', '科科拉', 'KOKKOLA (KARLEBY)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIKEM', '凯米', 'KEMI', 0, 1, 'FI', 0, 0, '{CC}'),
('FIHMN', '哈米纳', 'HAMINA (FREDRIKSHAMN)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIHKO', '汉科', 'HANGO (HANKO)', 0, 1, 'FI', 0, 0, '{CC}'),
('FIHEL', '赫尔辛基', 'HELSINKI (HELSINGFORS)', 0, 1, 'FI', 0, 0, '{CC}'),
('FJSUV', '苏瓦', 'SUVA', 0, 1, 'FJ', 0, 0, '{CC}'),
('FJLTK', '劳托卡', 'LAUTOKA', 0, 1, 'FJ', 0, 0, '{CC}'),
('FJLBS', '兰巴萨', 'LABASA(LAMBASA)', 0, 1, 'FJ', 0, 0, '{CC}'),
('FKPSY', '斯坦利港', 'PORT STANLEY', 0, 1, 'FK', 0, 0, '{CC}'),
('FMYAP', '雅浦', 'YAP', 0, 1, 'FM', 0, 0, '{CC}'),
('FMTKK', '丘克群岛', 'CHUUK (TRUK)', 0, 1, 'FM', 0, 0, '{CC}'),
('FMPNI', '波纳佩', 'POHNPEI', 0, 1, 'FM', 0, 0, '{CC}'),
('FOVES', '韦斯特门港', 'VESTMANHAVN', 0, 1, 'FO', 0, 0, '{CC}'),
('FOTHO', '托尔斯港', 'THORSHAVN', 0, 1, 'FO', 0, 0, '{CC}'),
('FRURO', '鲁昂', 'ROUEN', 0, 1, 'FR', 0, 0, '{CC}'),
('FRTLN', '土伦', 'TOULON', 0, 1, 'FR', 0, 0, '{CC}'),
('FRSNR', '圣纳泽尔', 'ST NAZAIRE', 0, 1, 'FR', 0, 0, '{CC}'),
('FRSML', '圣马洛', 'ST MALO', 0, 1, 'FR', 0, 0, '{CC}'),
('FRSET', '塞特', 'SETE', 0, 1, 'FR', 0, 0, '{CC}'),
('FRNTE', '南特', 'NANTES', 0, 1, 'FR', 0, 0, '{CC}'),
('FRNCE', '尼斯', 'NICE', 0, 1, 'FR', 0, 0, '{CC}'),
('FRMRS', '马赛', 'MARSEILLE', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLRT', '洛里昂', 'LORIENT', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLRH', '拉罗谢尔', 'LA ROCHELLE', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLEH', '勒阿弗尔', 'LE HAVRE', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLCT', '拉西约塔', 'LA CIOTAT', 0, 1, 'FR', 0, 0, '{CC}'),
('FRLAV', '拉瓦拉', 'LAVERA', 0, 1, 'FR', 0, 0, '{CC}'),
('FRFOS', '福斯', 'FOS-SUR-MER', 0, 1, 'FR', 0, 0, '{CC}'),
('FRDPE', '迪耶普', 'DIEPPE', 0, 1, 'FR', 0, 0, '{CC}'),
('FRDKK', '敦刻尔克', 'DUNKERQUE', 0, 1, 'FR', 0, 0, '{CC}'),
('FRCQF', '加来', 'CALAIS', 0, 1, 'FR', 0, 0, '{CC}'),
('FRCFR', '卡昂', 'CAEN', 0, 1, 'FR', 0, 0, '{CC}'),
('FRCER', '瑟堡', 'CHERBOURG', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBOL', '布洛涅', 'BOULOGNE-SUR-MER', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBOD', '波尔多', 'BORDEAUX', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBIA', '巴斯蒂亚', 'BASTIA', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBES', '布雷斯特', 'BREST', 0, 1, 'FR', 0, 0, '{CC}'),
('FRBAY', '巴约讷', 'BAYONNE', 0, 1, 'FR', 0, 0, '{CC}'),
('FRAJA', '阿雅克修', 'AJACCIO', 0, 1, 'FR', 0, 0, '{CC}'),
('GAPOG', '让蒂尔港', 'PORT GENTIL', 0, 1, 'FR', 0, 0, '{CC}'),
('GAOWE', '奥文多', 'OWENDO', 0, 1, 'FR', 0, 0, '{CC}'),
('GALBV', '利伯维尔', 'LIBREVILLE', 0, 1, 'FR', 0, 0, '{CC}'),
('GACLZ', '洛佩斯角', 'CAP LOPEZ', 0, 1, 'FR', 0, 0, '{CC}'),
('GBTIL', '蒂尔伯里', 'TILBURY', 0, 1, 'GB', 0, 0, '{CC}'),
('GBTEE', '提斯港', 'TEESPORT', 0, 1, 'GB', 0, 0, '{CC}'),
('GBSWA', '斯旺西', 'SWANSEA', 0, 1, 'GB', 0, 0, '{CC}'),
('GBSUN', '森德兰', 'SUNDERLAND', 0, 1, 'GB', 0, 0, '{CC}'),
('GBSOU', '南安普顿', 'SOUTHAMPTON', 0, 1, 'GB', 0, 0, '{CC}'),
('GBSHO', '肖勒姆', 'SHOREHAM', 0, 1, 'GB', 0, 0, '{CC}'),
('GBPTB', '塔尔伯特港', 'PORT TALBOT', 0, 1, 'GB', 0, 0, '{CC}'),
('GBPME', '朴次茅斯', 'PORTSMOUTH', 0, 1, 'GB', 0, 0, '{CC}'),
('GBPLY', '普利茅斯', 'PLYMOUTH', 0, 1, 'GB', 0, 0, '{CC}'),
('GBNPT', '纽波特', 'NEWPORT', 0, 1, 'GB', 0, 0, '{CC}'),
('GBNCL', '纽卡斯尔', 'NEWCASTLE UPON TYNE', 0, 1, 'GB', 0, 0, '{CC}'),
('GBMTH', '梅西尔', 'METHIL', 0, 1, 'GB', 0, 0, '{CC}'),
('GBMNC', '曼彻斯特', 'MANCHESTER', 0, 1, 'GB', 0, 0, '{CC}'),
('GBMLF', '米尔福德港', 'MILFORD HAVEN', 0, 1, 'GB', 0, 0, '{CC}'),
('GBMID', '米德尔斯伯勒', 'MIDDLESBROUGH', 0, 1, 'GB', 0, 0, '{CC}'),
('GBLON', '伦敦', 'LONDON', 0, 1, 'GB', 0, 0, '{CC}'),
('GBLIV', '利物浦', 'LIVERPOOL', 0, 1, 'GB', 0, 0, '{CC}'),
('GBLEI', '利斯', 'LEITH', 0, 1, 'GB', 0, 0, '{CC}'),
('GBLDY', '伦敦德里', 'LONDONDERRY', 0, 1, 'GB', 0, 0, '{CC}'),
('GBIPS', '伊普斯威奇', 'IPSWICH', 0, 1, 'GB', 0, 0, '{CC}'),
('GBIMM', '伊明赫姆', 'IMMINGHAM', 0, 1, 'GB', 0, 0, '{CC}'),
('GBHUL', '赫尔', 'HULL', 0, 1, 'GB', 0, 0, '{CC}'),
('GBHTP', '哈特尔浦', 'HARTLEPOOL', 0, 1, 'GB', 0, 0, '{CC}'),
('GBHRW', '哈里奇', 'HARWICH', 0, 1, 'GB', 0, 0, '{CC}'),
('GBGRG', '格兰奇茅斯', 'GRANGEMOUTH', 0, 1, 'GB', 0, 0, '{CC}'),
('GBGLW', '格拉斯哥', 'GLASGOW', 0, 1, 'GB', 0, 0, '{CC}'),
('GBFXT', '弗利克斯托', 'FELIXSTOWE', 0, 1, 'GB', 0, 0, '{CC}'),
('GBFAL', '法尔茅斯', 'FALMOUTH', 0, 1, 'GB', 0, 0, '{CC}'),
('GBDVR', '多佛尔', 'DOVER', 0, 1, 'GB', 0, 0, '{CC}'),
('GBDUN', '邓迪', 'DUNDEE', 0, 1, 'GB', 0, 0, '{CC}'),
('GBCYP', '克莱德港', 'CLYDEPORT', 0, 1, 'GB', 0, 0, '{CC}'),
('GBCDF', '加的夫', 'CARDIFF', 0, 1, 'GB', 0, 0, '{CC}'),
('GBBRS', '布里斯托尔', 'BRISTOL', 0, 1, 'GB', 0, 0, '{CC}'),
('GBBOS', '波士顿', 'BOSTON', 0, 1, 'GB', 0, 0, '{CC}'),
('GBBID', '比迪福德', 'BIDEFORD', 0, 1, 'GB', 0, 0, '{CC}'),
('GBBEL', '贝尔法斯特', 'BELFAST', 0, 1, 'GB', 0, 0, '{CC}'),
('GBABD', '阿伯丁', 'ABERDEEN', 0, 1, 'GB', 0, 0, '{CC}'),
('GDSTG', '圣乔治', 'SAINT GEORGE S', 0, 1, 'GD', 0, 0, '{CC}'),
('GEPTI', '波季', 'POTI', 0, 1, 'GE', 0, 0, '{CC}'),
('GEBUS', '巴统', 'BATUMI', 0, 1, 'GE', 0, 0, '{CC}'),
('GFQKR', '库鲁', 'KOUROU', 0, 1, 'GF', 0, 0, '{CC}'),
('GFCAY', '卡宴', 'CAYENNE', 0, 1, 'GF', 0, 0, '{CC}'),
('GGSPT', '圣彼得港', 'ST PETER PORT', 0, 1, 'GG', 0, 0, '{CC}'),
('GHWEA', '温尼巴', 'WINNEBA', 0, 1, 'GH', 0, 0, '{CC}'),
('GHTKD', '塔科拉迪', 'TAKORADI', 0, 1, 'GH', 0, 0, '{CC}'),
('GHTEM', '特马', 'TEMA', 0, 1, 'GH', 0, 0, '{CC}'),
('GHCCT', '海岸角', 'CAPE COAST', 0, 1, 'GH', 0, 0, '{CC}'),
('GIGIB', '直布罗陀', 'GIBRALTAR', 0, 1, 'GI', 0, 0, '{CC}'),
('GLUAK', '纳萨尔苏瓦克', 'NARSARSUAQ', 0, 1, 'GI', 0, 0, '{CC}'),
('GLJSU', '马尼措克', 'MANIITSOQ (SUKKERTOPPEN)', 0, 1, 'GI', 0, 0, '{CC}'),
('GLJEG', '奥希奥特', 'AASIAAT (EGEDESMINDE)', 0, 1, 'GI', 0, 0, '{CC}'),
('GLGOH', '努克', 'NUUK (GODTHAAB)', 0, 1, 'GI', 0, 0, '{CC}'),
('GMBJL', '班珠尔', 'BANJUL', 0, 1, 'GM', 0, 0, '{CC}'),
('GNKMR', '卡姆萨尔', 'PORT-KAMSAR', 0, 1, 'GN', 0, 0, '{CC}'),
('GNCKY', '科纳克里', 'CONAKRY', 0, 1, 'GN', 0, 0, '{CC}'),
('GPPTP', '皮特尔角城', 'POINTE-A-PITRE', 0, 1, 'GP', 0, 0, '{CC}'),
('GPBBR', '巴斯特尔', 'BASSE-TERRE', 0, 1, 'GP', 0, 0, '{CC}'),
('GQSSG','马拉博', 'MALABO', 0, 1, 'GQ', 0, 0, '{CC}'),
('GQBSG', '巴塔', 'BATA', 0, 1, 'GQ', 0, 0, '{CC}'),
('GRVOL', '沃洛斯', 'VOLOS', 0, 1, 'GR', 0, 0, '{CC}'),
('GRSKG', '塞萨洛尼基', 'THESSALONIKI', 0, 1, 'GR', 0, 0, '{CC}'),
('GRRHO', '罗得', 'RHODES', 0, 1, 'GR', 0, 0, '{CC}'),
('GRPIR', '比雷埃夫斯', 'PIRAEUS', 0, 1, 'GR', 0, 0, '{CC}'),
('GRMJT', '米提林尼', 'MITYLENE', 0, 1, 'GR', 0, 0, '{CC}'),
('GRMGR', '迈加拉', 'MEGARA', 0, 1, 'GR', 0, 0, '{CC}'),
('GRKVA', '卡瓦拉', 'KAVALA', 0, 1, 'GR', 0, 0, '{CC}'),
('GRKLX', '卡拉迈', 'KALAMATA', 0, 1, 'GR', 0, 0, '{CC}'),
('GRJSY', '锡罗斯', 'SYROS（SYRA）', 0, 1, 'GR', 0, 0, '{CC}'),
('GRJKH', '希俄斯', 'CHIOS', 0, 1, 'GR', 0, 0, '{CC}'),
('GRITA', '伊泰阿', 'ITEA', 0, 1, 'GR', 0, 0, '{CC}'),
('GRHER', '伊拉克利翁', 'IRAKLION（HERAKLION）', 0, 1, 'GR', 0, 0, '{CC}'),
('GRGPA', '帕特雷', 'PATRAS', 0, 1, 'GR', 0, 0, '{CC}'),
('GTSTC', '圣托马斯德卡斯蒂利亚', 'PUERTO SANTO TOMAS DE CASTILLA', 0, 1, 'GT', 0, 0, '{CC}'),
('GTSNJ', '圣何塞', 'SAN JOSE', 0, 1, 'GT', 0, 0, '{CC}'),
('GTPRQ', '夸特扎尔港', 'PUERTO QUETZAL', 0, 1, 'GT', 0, 0, '{CC}'),
('GTPBR', '巴里奥斯港', 'PUERTO BARRIOS', 0, 1, 'GT', 0, 0, '{CC}'),
('GUGUM', '关岛', 'GUAM', 0, 1, 'GU', 0, 0, '{CC}'),
('GUAPR', '阿普拉', 'APRA', 0, 1, 'GU', 0, 0, '{CC}'),
('GUAGA', '阿加尼亚', 'AGANA', 0, 1, 'GU', 0, 0, '{CC}'),
('GWOXB', '比绍', 'BISSAU', 0, 1, 'GW', 0, 0, '{CC}'),
('GWCAC', '卡谢马', 'CACHEU', 0, 1, 'GW', 0, 0, '{CC}'),
('GWBOL', '博拉多', 'BOLAMA', 0, 1, 'GW', 0, 0, '{CC}'),
('GYNAM', '新阿姆斯特丹', 'NEW AMSTERDAM', 0, 1, 'GY', 0, 0, '{CC}'),
('GYGEO', '乔治敦', 'GEORGETOWN', 0, 1, 'GY', 0, 0, '{CC}'),
('HKHKG', '香港', 'HONG KONG', 0, 1, 'HK', 0, 0, '{CC}'),
('HNTEA', '特拉', 'TELA', 0, 1, 'HN', 0, 0, '{CC}'),
('HNSLO', '圣洛伦索', 'SAN LORENZO', 0, 1, 'HN', 0, 0, '{CC}'),
('HNPCR', '科尔特斯港', 'PUERTO CORTES', 0, 1, 'HN', 0, 0, '{CC}'),
('HNPCA', '卡斯蒂利亚港', 'PUERTO CASTILLA', 0, 1, 'HN', 0, 0, '{CC}'),
('HRZAD', '扎达尔', 'ZADAR', 0, 1, 'HR', 0, 0, '{CC}'),
('HRSPU', '斯普利特', 'SPLIT', 0, 1, 'HR', 0, 0, '{CC}'),
('HRRJK', '里耶卡', 'RIJEKA', 0, 1, 'HR', 0, 0, '{CC}'),
('HRPUY', '普拉', 'PULA', 0, 1, 'HR', 0, 0, '{CC}'),
('HRPLE', '普洛切', 'PLOCE', 0, 1, 'HR', 0, 0, '{CC}'),
('HRDBV', '杜布罗夫尼克', 'DUBROVNIK', 0, 1, 'HR', 0, 0, '{CC}'),
('HTPAP', '太子港', 'PORT-AU-PRINCE', 0, 1, 'HR', 0, 0, '{CC}'),
('HTGVS', '戈纳伊夫', 'GONAIVES', 0, 1, 'HR', 0, 0, '{CC}'),
('HTCAP', '海地角', 'CAP-HAITIEN', 0, 1, 'HR', 0, 0, '{CC}'),
('HTACA', '莱凯', 'LES CAYES', 0, 1, 'HR', 0, 0, '{CC}'),
('IDUPG', '乌戎潘当', 'UJUNG PANDANG', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTTE', '德那第', 'TERNATE', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTRH', '打拉根', 'TARAHAN', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTJQ', '丹戎潘丹', 'TANJUNG PANDAN', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTBR', '直落巴由', 'TELUKBAYUR', 0, 1, 'ID', 0, 0, '{CC}'),
('IDTAN', '丹戎乌班', 'TANJUNGUBAN', 0, 1, 'ID', 0, 0, '{CC}'),
('IDSUB', '泗水', 'SURABAYA', 0, 1, 'ID', 0, 0, '{CC}'),
('IDSRG', '三宝垄', 'SEMARANG', 0, 1, 'ID', 0, 0, '{CC}'),
('IDSBG', '沙璜', 'SABANG', 0, 1, 'ID', 0, 0, '{CC}'),
('IDSAT', '桑坦港', 'SANTAN TERMINAL', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPRO', '普罗博林戈', 'PROBOLINGGO', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPNK', '坤甸', 'PONTIANAK', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPNJ', '潘姜', 'PANJANG', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPLM', '巨港', 'PALEMBANG', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPKS', '庞卡兰苏苏', 'PANGKALAN SUSU', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPEX', '北加浪岸', 'PEKALONGAN', 0, 1, 'ID', 0, 0, '{CC}'),
('IDPDG', '巴东', 'PADANG', 0, 1, 'ID', 0, 0, '{CC}'),
('IDMDC', '万鸦老', 'MENADO', 0, 1, 'ID', 0, 0, '{CC}'),
('IDKOE', '古邦', 'KUPANG', 0, 1, 'ID', 0, 0, '{CC}'),
('IDJKT', '雅加达', 'JAKARTA', 0, 1, 'ID', 0, 0, '{CC}'),
('IDDUM', '杜迈', 'DUMAI', 0, 1, 'ID', 0, 0, '{CC}'),
('IDDJJ', '查亚普拉', 'JAYAPURA', 0, 1, 'ID', 0, 0, '{CC}'),
('IDCXP', '芝拉扎', 'CILACAP', 0, 1, 'ID', 0, 0, '{CC}'),
('IDBPN', '巴厘巴板', 'BALIKPAPAN', 0, 1, 'ID', 0, 0, '{CC}'),
('IDBLW', '勿拉湾', 'BELAWAN', 0, 1, 'ID', 0, 0, '{CC}'),
('IDBJU', '巴纽旺宣', 'BANJUWANGI', 0, 1, 'ID', 0, 0, '{CC}'),
('IDBIT', '比通', 'BITUNG', 0, 1, 'ID', 0, 0, '{CC}'),
('IDAMQ', '安汶', 'AMBON', 0, 1, 'ID', 0, 0, '{CC}'),
('IEWAT', '沃特福德', 'WATERFORD', 0, 1, 'IE', 0, 0, '{CC}'),
('IEORK', '科克', 'CORK', 0, 1, 'IE', 0, 0, '{CC}'),
('IELMK', '利默里克', 'LIMERICK', 0, 1, 'IE', 0, 0, '{CC}'),
('IEGWY', '戈尔韦', 'GALWAY', 0, 1, 'IE', 0, 0, '{CC}'),
('IEFOV', '福因斯', 'FOYNES', 0, 1, 'IE', 0, 0, '{CC}'),
('IEDUB', '都柏林', 'DUBLIN', 0, 1, 'IE', 0, 0, '{CC}'),
('IEDLG', '邓莱里', 'DUN LAOGHAIRE', 0, 1, 'IE', 0, 0, '{CC}'),
('IEBYT', '班特里', 'BANTRY', 0, 1, 'IE', 0, 0, '{CC}'),
('ILTLV', '特拉维夫-雅法', 'TEL AVIV-YAFO', 0, 1, 'IE', 0, 0, '{CC}'),
('ILHFA', '海法', 'HAIFA', 0, 1, 'IE', 0, 0, '{CC}'),
('ILETH', '埃拉特', 'EILAT（EILATH）', 0, 1, 'IE', 0, 0, '{CC}'),
('ILASH', '阿什杜德', 'ASHDOD', 0, 1, 'IE', 0, 0, '{CC}'),
('ILAKL', '阿什克伦', 'ASHKELON', 0, 1, 'IE', 0, 0, '{CC}'),
('IMDGS', '道格拉斯', 'DOUGLAS', 0, 1, 'IM', 0, 0, '{CC}'),
('INVTZ', '维沙卡帕特南', 'VISAKHAPATNAM', 0, 1, 'IN', 0, 0, '{CC}'),
('INTUT', '杜蒂戈林', 'TUTICORIN', 0, 1, 'IN', 0, 0, '{CC}'),
('INRED', '雷迪', 'REDI', 0, 1, 'IN', 0, 0, '{CC}'),
('INPRT', '巴拉迪布', 'PARADIP GARH', 0, 1, 'IN', 0, 0, '{CC}'),
('INPBD', '博尔本德尔', 'PORBANDAR', 0, 1, 'IN', 0, 0, '{CC}'),
('INNSA', '哈瓦舍瓦（尼赫鲁）', '	NHAVA SHEVA (JAWAHARLAL NEHRU)', 0, 1, 'IN', 0, 0, '{CC}'),
('INNPT', '纳格伯蒂讷姆', 'NAGAPPATTINAM', 0, 1, 'IN', 0, 0, '{CC}'),
('INNML', '新芒格洛尔', 'NEW MANGALORE', 0, 1, 'IN', 0, 0, '{CC}'),
('INMUN', '蒙德拉', 'MUNDRA', 0, 1, 'IN', 0, 0, '{CC}'),
('INMRM', '莫尔穆冈', 'MARMAGAO (MARMUGAO)', 0, 1, 'IN', 0, 0, '{CC}'),
('INMAA', '金奈', 'CHENNAI（MADRAS）', 0, 1, 'IN', 0, 0, '{CC}'),
('INKRK', '加里加尔', 'KARAIKAL（KARIKAL）', 0, 1, 'IN', 0, 0, '{CC}'),
('INIXZ', '布莱尔港', 'PORT BLAIR', 0, 1, 'IN', 0, 0, '{CC}'),
('INIXY', '根德拉', 'KANDLA', 0, 1, 'IN', 0, 0, '{CC}'),
('INCOK', '科钦', 'COCHIN', 0, 1, 'IN', 0, 0, '{CC}'),
('INCCU', '加尔各答', 'KOLKATA（CALCUTTA）', 0, 1, 'IN', 0, 0, '{CC}'),
('INBOM', '孟买', 'MUMBAI（BOMBAY）', 0, 1, 'IN', 0, 0, '{CC}'),
('INBHU', '包纳加尔', 'BHAVNAGAR', 0, 1, 'IN', 0, 0, '{CC}'),
('IQUQR', '乌姆盖斯尔', 'UMM QASR', 0, 1, 'IQ', 0, 0, '{CC}'),
('IQFAO', '法奥', 'FAO', 0, 1, 'IQ', 0, 0, '{CC}'),
('IQBSR', '巴士拉', 'BASRA', 0, 1, 'IQ', 0, 0, '{CC}'),
('IRZBR', '恰赫巴哈尔', 'CHAH BAHAR', 0, 1, 'IR', 0, 0, '{CC}'),
('IRMRX', '马赫沙赫尔港', 'BANDAR-E MAH SHAHR', 0, 1, 'IR', 0, 0, '{CC}'),
('IRKHO', '胡宁沙赫尔', 'KHORRAMSHAHR', 0, 1, 'IR', 0, 0, '{CC}'),
('IRKHK', '哈尔克岛', 'KHARK ISLAND（KHARG ISLAND）', 0, 1, 'IR', 0, 0, '{CC}'),
('IRBUZ', '布什尔', 'BUSHEHR（BUSHIRE）', 0, 1, 'IR', 0, 0, '{CC}'),
('IRBND', '阿巴斯港', 'BANDAR ABBAS', 0, 1, 'IR', 0, 0, '{CC}'),
('IRBKM', '霍梅尼港', 'BANDAR KHOMEINI', 0, 1, 'IR', 0, 0, '{CC}'),
('IRABD', '阿巴丹', 'ABADAN', 0, 1, 'IR', 0, 0, '{CC}'),
('ISVES', '韦斯特曼纳岛', 'VESTMANNAEYJAR - HOFN', 0, 1, 'IS', 0, 0, '{CC}'),
('ISREY', '雷克雅未克', 'REYKJAVIK', 0, 1, 'IS', 0, 0, '{CC}'),
('ISKEV', '凯夫拉维克', 'KEFLAVIKURKAUPSTADUR', 0, 1, 'IS', 0, 0, '{CC}'),
('ISISA', '伊萨菲厄泽', 'ISAFJORDUR - HOFN', 0, 1, 'IS', 0, 0, '{CC}'),
('ISAKU', '阿克雷里', 'AKUREYRI', 0, 1, 'IS', 0, 0, '{CC}'),
('ITVCE', '威尼斯', 'VENEZIA（VENICE）', 0, 1, 'IT', 0, 0, '{CC}'),
('ITTRS', '的里雅斯特', 'TRIESTE', 0, 1, 'IT', 0, 0, '{CC}'),
('ITTAR', '塔兰托', 'TARANTO', 0, 1, 'IT', 0, 0, '{CC}'),
('ITSVN', '萨沃纳', 'SAVONA/ FUNIVIE', 0, 1, 'IT', 0, 0, '{CC}'),
('ITSPE', '斯佩齐亚', 'LA SPEZIA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITSAL', '萨莱诺', 'SALERNO', 0, 1, 'IT', 0, 0, '{CC}'),
('ITRAN', '腊万纳', 'RAVENNA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITPTO', '托雷斯港', 'PORTO TORRES', 0, 1, 'IT', 0, 0, '{CC}'),
('ITPMO', '巴勒莫', 'PALERMO', 0, 1, 'IT', 0, 0, '{CC}'),
('ITPFX', '萨罗克（福克西港）', '	SARROCH (PORTO FOXI)', 0, 1, 'IT', 0, 0, '{CC}'),
('ITNAP', '那波利', 'NAPOLI', 0, 1, 'IT', 0, 0, '{CC}'),
('ITMSN', '墨西拿', 'MESSINA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITMLZ', '米拉佐', 'MILAZZO', 0, 1, 'IT', 0, 0, '{CC}'),
('ITLIV', '里窝那', 'LIVORNO', 0, 1, 'IT', 0, 0, '{CC}'),
('ITGOA', '热那亚', 'GENOA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITGEA', '杰拉', 'GELA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITGAE', '加埃塔', 'GAETA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITFCO', '菲乌米奇诺', 'FIUMICINO', 0, 1, 'IT', 0, 0, '{CC}'),
('ITFAL', '法尔科纳拉', 'FALCONARA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITCVV', '奇维塔韦基亚', 'CIVITAVECCHIA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITCTA', '卡塔尼亚', 'CATANIA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITCAG', '卡利亚里', 'CAGLIARI', 0, 1, 'IT', 0, 0, '{CC}'),
('ITBRI', '巴里', 'BARI', 0, 1, 'IT', 0, 0, '{CC}'),
('ITBLT', '巴列塔', 'BARLETTA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITBDS', '布林迪西', 'BRINDISI', 0, 1, 'IT', 0, 0, '{CC}'),
('ITAUG', '奥古斯塔', 'AUGUSTA', 0, 1, 'IT', 0, 0, '{CC}'),
('ITAOI', '安科纳', 'ANCONA', 0, 1, 'IT', 0, 0, '{CC}'),
('JESTH', '圣赫利尔', 'ST HELIER', 0, 1, 'JE', 0, 0, '{CC}'),
('JMPOT', '安东尼奥港', 'PORT ANTONIO', 0, 1, 'JM', 0, 0, '{CC}'),
('JMOCJ', '奥乔里奥斯', 'OCHO RIOS', 0, 1, 'JM', 0, 0, '{CC}'),
('JMMBJ', '蒙特哥贝', 'MONTEGO BAY', 0, 1, 'JM', 0, 0, '{CC}'),
('JMKIN', '金斯敦', 'KINGSTON', 0, 1, 'JM', 0, 0, '{CC}'),
('JOAQJ', '亚喀巴', 'AQABA（AL ‘AQABAH）', 0, 1, 'JO', 0, 0, '{CC}'),
('JPYOS', '横须贺', 'YOKOSUKA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPYOK', '横滨', 'YOKOHAMA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPYKK', '四日市', 'YOKKAICHI', 0, 1, 'JP', 0, 0, '{CC}'),
('JPWAK', '和歌山', 'WAKAYAMA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPUKB', '神户', 'KOBE', 0, 1, 'JP', 0, 0, '{CC}'),
('JPUBJ', '宇部', 'UBE', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTYO', '东京', 'TOKYO', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTRG', '敦贺', 'TSURUGA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTMK', '苫小牧', 'TOMAKOMAI', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTKY', '德山', 'TOKUYAMA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPTAK', '高松', 'TAKAMATSU', 0, 1, 'JP', 0, 0, '{CC}'),
('JPSSB', '佐世保', 'SASEBO', 0, 1, 'JP', 0, 0, '{CC}'),
('JPSMZ', '清水', 'SHIMIZU', 0, 1, 'JP', 0, 0, '{CC}'),
('JPSHS', '下关', 'SHIMONOSEKI', 0, 1, 'JP', 0, 0, '{CC}'),
('JPOTR', '小樽', 'OTARU', 0, 1, 'JP', 0, 0, '{CC}'),
('JPOSA', '大阪', 'OSAKA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPONA', '小名滨', 'ONAHAMA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPOIT', '大分', 'OITA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPNGS', '长崎', 'NAGASAKI', 0, 1, 'JP', 0, 0, '{CC}'),
('JPNGO', '名古屋', 'NAGOYA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPNAH', '那霸', 'NAHA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPMUR', '室兰', 'MURORAN', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKZU', '木更津', 'KISARAZU', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKUH', '钏路', 'KUSHIRO', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKOJ', '鹿儿岛', 'KAGOSHIMA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKNZ', '金泽', 'KANAZAWA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKKJ', '北九州', 'KITAKYUSHU', 0, 1, 'JP', 0, 0, '{CC}'),
('JPKIJ', '新泻', 'NIIGATA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPIWK', '岩国', 'IWAKUNI', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHTC', '日立', 'HITACHI', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHSM', '细岛', 'HOSOSHIMA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHMD', '滨田', 'HAMADA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHKD', '函馆', 'HAKODATE', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHIM', '姬路', 'HIMEJI', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHIJ', '广岛', 'HIROSHIMA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPHHE', '八户', 'HACHINOHE', 0, 1, 'JP', 0, 0, '{CC}'),
('JPFUK', '福冈', 'FUKUOKA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPFKY', '福山', 'FUKUYAMA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPCHB', '千叶', 'CHIBA', 0, 1, 'JP', 0, 0, '{CC}'),
('JPAXT', '秋田', '	AKITA', 0, 1, 'JP', 0, 0, '{CC}'),
('KEMYD', '马林迪', 'MALINDI', 0, 1, 'KE', 0, 0, '{CC}'),
('KEMBA', '蒙巴萨', 'MOMBASA', 0, 1, 'KE', 0, 0, '{CC}'),
('KELAU', '拉穆', 'LAMU', 0, 1, 'KE', 0, 0, '{CC}'),
('KHPNH', '金边', 'PHNOM PENH', 0, 1, 'KH', 0, 0, '{CC}'),
('KHKOS', '磅逊', 'KOMPONG SOM（KAMPONG SAOM）', 0, 1, 'KH', 0, 0, '{CC}'),
('KITRW', '塔拉瓦', 'TARAWA', 0, 1, 'KI', 0, 0, '{CC}'),
('KMYVA', '莫罗尼', 'MORONI', 0, 1, 'KM', 0, 0, '{CC}'),
('KNBAS', '巴斯特尔', 'BASSETERRE', 0, 1, 'KN', 0, 0, '{CC}'),
('KPWON', '元山', 'WONSAN', 0, 1, 'KP', 0, 0, '{CC}'),
('KPSIN', '新浦', 'SINPO', 0, 1, 'KP', 0, 0, '{CC}'),
('KPNAM', '南浦', 'NAMPO', 0, 1, 'KP', 0, 0, '{CC}'),
('KPHGM', '兴南', 'HUNGNAM', 0, 1, 'KP', 0, 0, '{CC}'),
('KPHAE', '海州', 'HAEJU', 0, 1, 'KP', 0, 0, '{CC}'),
('KPCHO', '清津', 'CHONGJIN', 0, 1, 'KP', 0, 0, '{CC}'),
('KRYOS', '丽水', 'YEOSU(YOSU)', 0, 1, 'KR', 0, 0, '{CC}'),
('KRUSN', '蔚山', 'ULSAN', 0, 1, 'KR', 0, 0, '{CC}'),
('KRPUS', '釜山', 'BUSAN', 0, 1, 'KR', 0, 0, '{CC}'),
('KRPTK', '平泽', 'PYEONGTAEK', 0, 1, 'KR', 0, 0, '{CC}'),
('KRMUK', '墨湖', 'MUKHO', 0, 1, 'KR', 0, 0, '{CC}'),
('KRMOK', '木浦', 'MOKPO', 0, 1, 'KR', 0, 0, '{CC}'),
('KRMAS', '马山', 'MASAN', 0, 1, 'KR', 0, 0, '{CC}'),
('KRKUV', '群山', 'GUNSAN(KUNSAN)', 0, 1, 'KR', 0, 0, '{CC}'),
('KRKPO', '浦项', 'POHANG', 0, 1, 'KR', 0, 0, '{CC}'),
('KRKAN', '光阳', 'GWANGYANG(KWANGYANG)', 0, 1, 'KR', 0, 0, '{CC}'),
('KRICH', '仁川', 'INCHEON(INCHON)', 0, 1, 'KR', 0, 0, '{CC}'),
('KWSAA', '舒艾拜', 'SHUAIBA', 0, 1, 'KW', 0, 0, '{CC}'),
('KWMEA', '艾哈迈迪港', 'MINA’ AL AHMADI', 0, 1, 'KW', 0, 0, '{CC}'),
('KWKWI', '科威特', 'KUWAIT', 0, 1, 'KW', 0, 0, '{CC}'),
('KYGEC', '乔治敦', 'GEORGETOWN', 0, 1, 'KY', 0, 0, '{CC}'),
('LBSUR', '苏尔', 'SUR（TYRE） ', 0, 1, 'LB', 0, 0, '{CC}'),
('LBSAY', '赛达', 'SAYDA', 0, 1, 'LB', 0, 0, '{CC}'),
('LBKYE', '的黎波里', 'TRIPOLI', 0, 1, 'LB', 0, 0, '{CC}'),
('LBBEY', '贝鲁特', 'BEIRUT', 0, 1, 'LB', 0, 0, '{CC}'),
('LCCAS', '卡斯特里', 'CASTRIES', 0, 1, 'LC', 0, 0, '{CC}'),
('LKTRR', '亭可马里', 'TRINCOMALEE', 0, 1, 'LK', 0, 0, '{CC}'),
('LKTAL', '塔莱曼纳尔', 'TALAIMANNAR', 0, 1, 'LK', 0, 0, '{CC}'),
('LKMAN', '马纳尔', 'MANNAR', 0, 1, 'LK', 0, 0, '{CC}'),
('LKKNK', '坎凯桑图赖', 'KANKESANTURAI', 0, 1, 'LK', 0, 0, '{CC}'),
('LKGAL', '加勒', 'GALLE', 0, 1, 'LK', 0, 0, '{CC}'),
('LKCMB', '科伦坡', 'COLOMBO', 0, 1, 'LK', 0, 0, '{CC}'),
('LRUCN', '布坎南', 'BUCHANAN', 0, 1, 'LR', 0, 0, '{CC}'),
('LRMLW', '蒙罗维亚', 'MONROVIA', 0, 1, 'LR', 0, 0, '{CC}'),
('LRCPA', '帕尔马斯角', 'CAPE PALMAS', 0, 1, 'LR', 0, 0, '{CC}'),
('LTKLJ', '克莱佩达', 'KLAIPEDA', 0, 1, 'LR', 0, 0, '{CC}'),
('LVVNT', '文茨皮尔斯', 'VENTSPILS', 0, 1, 'LV', 0, 0, '{CC}'),
('LVRIX', '里加', 'RIGA', 0, 1, 'LV', 0, 0, '{CC}'),
('LVLPX', '利耶帕亚', 'LIEPAJA', 0, 1, 'LV', 0, 0, '{CC}'),
('LYZUE', '祖埃提纳', 'ZUEITINA', 0, 1, 'LY', 0, 0, '{CC}'),
('LYTOB', '图卜鲁格', 'TOBRUK', 0, 1, 'LY', 0, 0, '{CC}'),
('LYTIP', '的黎波里', 'TRIPOLI', 0, 1, 'LY', 0, 0, '{CC}'),
('LYRLA', '拉斯拉努夫', 'RAS LANUF', 0, 1, 'LY', 0, 0, '{CC}'),
('LYMRA', '米苏拉塔', 'MISURATA', 0, 1, 'LY', 0, 0, '{CC}'),
('LYMHR', '哈里盖港', 'MARSA EL HARIGA', 0, 1, 'LY', 0, 0, '{CC}'),
('LYLMQ', '卜雷加港', 'MARSA BREGA', 0, 1, 'LY', 0, 0, '{CC}'),
('LYESI', '锡德尔', 'AS SIDR', 0, 1, 'LY', 0, 0, '{CC}'),
('LYDRX', '德尔纳', 'DARNAH', 0, 1, 'LY', 0, 0, '{CC}'),
('LYBEN', '班加西', 'BINGAZI (BENGHAZI)', 0, 1, 'LY', 0, 0, '{CC}'),
('MATTU', '得土安', 'TETOUAN', 0, 1, 'MA', 0, 0, '{CC}'),
('MATNG', '丹吉尔', 'TANGIER', 0, 1, 'MA', 0, 0, '{CC}'),
('MASFI', '萨菲', 'SAFI', 0, 1, 'MA', 0, 0, '{CC}'),
('MARBA', '拉巴特', 'RABAT', 0, 1, 'MA', 0, 0, '{CC}'),
('MANNA', '盖尼特拉', 'KENITRA', 0, 1, 'MA', 0, 0, '{CC}'),
('MAMOH', '穆罕默迪耶', 'MOHAMMEDIA', 0, 1, 'MA', 0, 0, '{CC}'),
('MAEUN', '欧云（阿尤恩）', 'LAAYOUNE（EL AAIUN）', 0, 1, 'MA', 0, 0, '{CC}'),
('MACAS', '卡萨布兰卡', 'CASABLANCA', 0, 1, 'MA', 0, 0, '{CC}'),
('MAAGA', '阿加迪尔', 'AGADIR', 0, 1, 'MA', 0, 0, '{CC}'),
('MCMON', '摩纳哥', 'MONACO', 0, 1, 'MC', 0, 0, '{CC}'),
('MCMCM', '蒙特卡洛', 'MONTE CARLO', 0, 1, 'MC', 0, 0, '{CC}'),
('MEKOT', '科托尔', 'KOTOR', 0, 1, 'ME', 0, 0, '{CC}'),
('MEBAR', '巴尔', 'BAR', 0, 1, 'ME', 0, 0, '{CC}'),
('MGWVK', '马纳卡拉', 'MANAKARA', 0, 1, 'MG', 0, 0, '{CC}'),
('MGTMM', '塔马塔夫', 'TAMATAVE (TOAMASINA)', 0, 1, 'MG', 0, 0, '{CC}'),
('MGTLE', '图莱亚尔', 'TULEAR (TOLIARA)', 0, 1, 'MG', 0, 0, '{CC}'),
('MGRVA', '法拉凡加纳', 'FARAFANGANA', 0, 1, 'MG', 0, 0, '{CC}'),
('MGMXM', '穆龙贝', 'MOROMBE', 0, 1, 'MG', 0, 0, '{CC}'),
('MGMOQ', '穆龙达瓦', 'MORONDAVA', 0, 1, 'MG', 0, 0, '{CC}'),
('MGMNJ', '马南扎里', 'MANANJARY', 0, 1, 'MG', 0, 0, '{CC}'),
('MGMJN', '马任加', 'MAJUNGA (MAHAJANGA)', 0, 1, 'MG', 0, 0, '{CC}'),
('MGFTU', '多凡堡', 'FORT DAUPHIN (TOALAGNARO)', 0, 1, 'MG', 0, 0, '{CC}'),
('MGDIE', '安齐拉纳纳', 'ANTSIRANANA（DIEGO-SUAREZ）', 0, 1, 'MG', 0, 0, '{CC}'),
('MHTAR', '塔罗阿', 'TAROA', 0, 1, 'MH', 0, 0, '{CC}'),
('MHMAJ', '马朱罗', 'MAJURO', 0, 1, 'MH', 0, 0, '{CC}'),
('MMXYE', '耶城', 'YE', 0, 1, 'MM', 0, 0, '{CC}'),
('MMTAV', '土瓦', 'TAVOY', 0, 1, 'MM', 0, 0, '{CC}'),
('MMSAN', '丹兑（山多威）', 'THANDWE（SANDOWAY）', 0, 1, 'MM', 0, 0, '{CC}'),
('MMRGN', '仰光', 'YANGON（RANGOON）', 0, 1, 'MM', 0, 0, '{CC}'),
('MMMNU', '毛淡棉', 'MAWLAMYINE（MOULMEIN）', 0, 1, 'MM', 0, 0, '{CC}'),
('MMMER', '墨吉', 'MERGUI', 0, 1, 'MM', 0, 0, '{CC}'),
('MMKYP', '皎漂', 'KYAUKPYU', 0, 1, 'MM', 0, 0, '{CC}'),
('MMBSX', '勃生', 'BASSEIN', 0, 1, 'MM', 0, 0, '{CC}'),
('MMAKY', '实兑', 'AKYAB（SITTWE）', 0, 1, 'MM', 0, 0, '{CC}'),
('MOMFM', '澳门', 'MACAU', 0, 1, 'MO', 0, 0, '{CC}'),
('MPTIQ', '提尼安岛', 'TINIAN', 0, 1, 'MP', 0, 0, '{CC}'),
('MPSPN', '塞班岛', 'SAIPAN', 0, 1, 'MP', 0, 0, '{CC}'),
('MQFDF', '法兰西堡', 'FORT-DE-FRANCE', 0, 1, 'MQ', 0, 0, '{CC}'),
('MRNKC', '努瓦克肖特', 'NOUAKCHOTT', 0, 1, 'MR', 0, 0, '{CC}'),
('MRNDB', '努瓦迪布', 'NOUADHIBOU', 0, 1, 'MR', 0, 0, '{CC}'),
('MSPLY', '普利茅斯', 'PLYMOUTH', 0, 1, 'MS', 0, 0, '{CC}'),
('MTMLA', '瓦莱塔', 'VALETTA', 0, 1, 'MT', 0, 0, '{CC}'),
('MTMAR', '马尔萨什洛克', 'MARSAXLOKK', 0, 1, 'MT', 0, 0, '{CC}'),
('MUPLU', '路易港', 'PORT LOUIS', 0, 1, 'MU', 0, 0, '{CC}'),
('MVMLE', '马累岛', 'MALE ISLAND', 0, 1, 'MV', 0, 0, '{CC}'),
('MXZLO', '曼萨尼略', 'MANZANILLO', 0, 1, 'MX', 0, 0, '{CC}'),
('MXVER', '韦拉克鲁斯', 'VERACRUZ', 0, 1, 'MX', 0, 0, '{CC}'),
('MXTAM', '坦皮科', 'TAMPICO', 0, 1, 'MX', 0, 0, '{CC}'),
('MXSRL', '圣罗萨利亚', 'SANTA ROSALIA', 0, 1, 'MX', 0, 0, '{CC}'),
('MXSCX', '萨利纳克鲁斯', 'SALINA CRUZ', 0, 1, 'MX', 0, 0, '{CC}'),
('MXPMD', '马德罗港', 'PUERTO MADERO', 0, 1, 'MX', 0, 0, '{CC}'),
('MXMZT', '马萨特兰', 'MAZATLAN', 0, 1, 'MX', 0, 0, '{CC}'),
('MXMTT', '米纳蒂特兰', 'MINATITLAN', 0, 1, 'MX', 0, 0, '{CC}'),
('MXLZC', '拉萨罗卡德纳斯', 'LAZARO CARDENAS', 0, 1, 'MX', 0, 0, '{CC}'),
('MXGYM', '瓜伊马斯', 'GUAYMAS', 0, 1, 'MX', 0, 0, '{CC}'),
('MXESE', '恩塞纳达', 'ENSENADA', 0, 1, 'MX', 0, 0, '{CC}'),
('MXCPE', '坎佩切', 'CAMPECHE', 0, 1, 'MX', 0, 0, '{CC}'),
('MXCOA', '夸察夸尔科斯', 'COATZACOALCOS', 0, 1, 'MX', 0, 0, '{CC}'),
('MXAVD', '阿尔瓦拉多', 'ALVARADO', 0, 1, 'MX', 0, 0, '{CC}'),
('MXACA', '阿卡普尔科', 'ACAPULCO', 0, 1, 'MX', 0, 0, '{CC}'),
('MYTWU', '斗湖', 'TAWAU', 0, 1, 'MY', 0, 0, '{CC}'),
('MYSDK', '山打根', 'SANDAKAN', 0, 1, 'MY', 0, 0, '{CC}'),
('MYSBW', '诗巫', 'SIBU', 0, 1, 'MY', 0, 0, '{CC}'),
('MYPKG', '巴生港', 'PORT KELANG', 0, 1, 'MY', 0, 0, '{CC}'),
('MYPGU', '帕西古当', 'PASIR GUDANG', 0, 1, 'MY', 0, 0, '{CC}'),
('MYPEN', '槟城', 'PENANG(GEORGETOWN)', 0, 1, 'MY', 0, 0, '{CC}'),
('MYMYY', '米里', 'MIRI', 0, 1, 'MY', 0, 0, '{CC}'),
('MYMKZ', '马六甲', 'MALACCA', 0, 1, 'MY', 0, 0, '{CC}'),
('MYLBU', '纳闽', 'LABUAN', 0, 1, 'MY', 0, 0, '{CC}'),
('MYKUD', '古达', 'KUDAT', 0, 1, 'MY', 0, 0, '{CC}'),
('MYKCH', '古晋', 'KUCHING', 0, 1, 'MY', 0, 0, '{CC}'),
('MYJHB', '新山', 'JOHORE BAHRU', 0, 1, 'MY', 0, 0, '{CC}'),
('MYBTU', '民都鲁', 'BINTULU', 0, 1, 'MY', 0, 0, '{CC}'),
('MYBKI', '哥打基纳巴卢', 'KOTA KINABALU', 0, 1, 'MY', 0, 0, '{CC}'),
('MZPOL', '彭巴', 'PEMBA', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZMZQ', '莫桑比克', 'MOCAMBIQUE', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZMPM', '马普托', 'MAPUTO', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZMNC', '纳卡拉', 'NACALA', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZINH', '伊尼扬巴内', 'INHAMBANE', 0, 1, 'MZ', 0, 0, '{CC}'),
('MZBEW', '贝拉', 'BEIRA', 0, 1, 'MZ', 0, 0, '{CC}'),
('NAWVB', '鲸湾港', 'WALVIS BAY', 0, 1, 'NA', 0, 0, '{CC}'),
('NALUD', '吕德里茨', 'LUDERITZ', 0, 1, 'NA', 0, 0, '{CC}'),
('NCNOU', '努美阿', 'NOUMEA', 0, 1, 'NC', 0, 0, '{CC}'),
('NFNLK', '诺福克岛', 'NORFOLK ISLAND', 0, 1, 'NF', 0, 0, '{CC}'),
('NGWAR', '瓦里', 'WARRI', 0, 1, 'NG', 0, 0, '{CC}'),
('NGTIN', '廷坎岛', 'TINCAN', 0, 1, 'NG', 0, 0, '{CC}'),
('NGPHC', '哈科特港', 'PORT HARCOURT', 0, 1, 'NG', 0, 0, '{CC}'),
('NGORO', '奥尼', 'ORON', 0, 1, 'NG', 0, 0, '{CC}'),
('NGLOS', '拉各斯', 'LAGOS', 0, 1, 'NG', 0, 0, '{CC}'),
('NGFOR', '福卡多斯', 'FORCADOS', 0, 1, 'NG', 0, 0, '{CC}'),
('NGCBQ', '卡拉巴尔', 'CALABAR', 0, 1, 'NG', 0, 0, '{CC}'),
('NGBON', '邦尼', 'BONNY', 0, 1, 'NG', 0, 0, '{CC}'),
('NGAPP', '阿帕帕', 'APAPA', 0, 1, 'NG', 0, 0, '{CC}'),
('NISJS', '南圣胡安', 'SAN JUAN DEL SUR', 0, 1, 'NI', 0, 0, '{CC}'),
('NIPUZ', '卡贝萨斯港', 'PUERTO CABEZAS', 0, 1, 'NI', 0, 0, '{CC}'),
('NICIO', '科林托', 'CORINTO', 0, 1, 'NI', 0, 0, '{CC}'),
('NIBEF', '布卢菲尔兹', 'BLUEFIELDS', 0, 1, 'NI', 0, 0, '{CC}'),
('NLZAA', '赞丹', 'ZAANDAM', 0, 1, 'NL', 0, 0, '{CC}'),
('NLVLI', '弗利辛恩', 'VLISSINGEN', 0, 1, 'NL', 0, 0, '{CC}'),
('NLVLA', '弗拉尔丁恩', 'VLAARDINGEN', 0, 1, 'NL', 0, 0, '{CC}'),
('NLTNZ', '泰尔讷曾', 'TERNEUZEN', 0, 1, 'NL', 0, 0, '{CC}'),
('NLRTM', '鹿特丹', 'ROTTERDAM', 0, 1, 'NL', 0, 0, '{CC}'),
('NLIJM', '艾默伊登', 'IJMUIDEN', 0, 1, 'NL', 0, 0, '{CC}'),
('NLDZL', '代尔夫宰尔', 'DELFZIJL', 0, 1, 'NL', 0, 0, '{CC}'),
('NLAMS', '阿姆斯特丹', 'AMSTERDAM', 0, 1, 'NL', 0, 0, '{CC}'),
('NOTRD', '特隆赫姆', 'TRONDHEIM', 0, 1, 'NO', 0, 0, '{CC}'),
('NOTOS', '特罗姆瑟', 'TROMSO', 0, 1, 'NO', 0, 0, '{CC}'),
('NOTON', '滕斯贝格', 'TONSBERG', 0, 1, 'NO', 0, 0, '{CC}'),
('NOSVG', '斯塔万格', 'STAVANGER', 0, 1, 'NO', 0, 0, '{CC}'),
('NOOSL', '奥斯陆', 'OSLO', 0, 1, 'NO', 0, 0, '{CC}'),
('NONVK', '纳尔维克', 'NARVIK', 0, 1, 'NO', 0, 0, '{CC}'),
('NOMSS', '莫斯', 'MOSS', 0, 1, 'NO', 0, 0, '{CC}'),
('NOMOL', '莫尔德', 'MOLDE', 0, 1, 'NO', 0, 0, '{CC}'),
('NOMJF', '莫舍恩', 'MOSJOEN', 0, 1, 'NO', 0, 0, '{CC}'),
('NOLAR', '拉尔维克', 'LARVIK', 0, 1, 'NO', 0, 0, '{CC}'),
('NOKSU', '克里斯蒂安松', 'KRISTIANSUND', 0, 1, 'NO', 0, 0, '{CC}'),
('NOKRS', '克里斯蒂安桑', 'KRISTIANSAND', 0, 1, 'NO', 0, 0, '{CC}'),
('NOKKN', '希尔克内斯', 'KIRKENES', 0, 1, 'NO', 0, 0, '{CC}'),
('NOHRD', '哈尔斯塔', 'HARSTAD', 0, 1, 'NO', 0, 0, '{CC}'),
('NOHFT', '哈默弗斯特', 'HAMMERFEST', 0, 1, 'NO', 0, 0, '{CC}'),
('NOHAU', '海于格松', 'HAUGESUND', 0, 1, 'NO', 0, 0, '{CC}'),
('NOGTD', '格里姆斯塔', 'GRIMSTAD', 0, 1, 'NO', 0, 0, '{CC}'),
('NOFRK', '腓特烈斯塔', 'FREDRIKSTAD', 0, 1, 'NO', 0, 0, '{CC}'),
('NODRM', '德拉门', 'DRAMMEN', 0, 1, 'NO', 0, 0, '{CC}'),
('NOBOO', '博多', 'BODO', 0, 1, 'NO', 0, 0, '{CC}'),
('NOBGO', '卑尔根', 'BERGEN', 0, 1, 'NO', 0, 0, '{CC}'),
('NOARE', '阿伦达尔', 'ARENDAL', 0, 1, 'NO', 0, 0, '{CC}'),
('NOAES', '奥勒松', 'ALESUND', 0, 1, 'NO', 0, 0, '{CC}'),
('NRINU', '瑙鲁岛', 'NAURU ISLAND', 0, 1, 'NR', 0, 0, '{CC}'),
('NUIUE', '纽埃岛', 'NIUE ISLAND', 0, 1, 'NU', 0, 0, '{CC}'),
('NUALO', '阿洛菲', 'ALOFI', 0, 1, 'NU', 0, 0, '{CC}'),
('NZWSZ', '韦斯特波特', 'WESTPORT', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZWRE', '旺阿雷', 'WHANGAREI', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZWLG', '惠灵顿', 'WELLINGTON', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZWAV', '韦弗利港', 'WAVERLEY HARBOUR', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZTRG', '陶朗阿', 'TAURANGA', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZTIU', '蒂马鲁', 'TIMARU', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZTHH', '塔哈罗阿', 'TAHAROA', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZPOE', '查默斯港', 'PORT CHALMERS', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZPCN', '皮克顿', 'PICTON', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZORR', '奥塔戈', 'OTAGO HARBOUR', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZOPX', '奥普阿', 'OPUA', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZNSN', '纳尔逊', 'NELSON', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZNPL', '新普利茅斯', 'NEW PLYMOUTH', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZNPE', '内皮尔', 'NAPIER', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZLYT', '利特尔顿', 'LYTTELTON', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZGIS', '吉斯珀恩', 'GISBORNE', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZDUD', '达尼丁', 'DUNEDIN', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZCHC', '克赖斯特彻奇', 'CHRISTCHURCH', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZBLU', '布拉夫', 'BLUFF', 0, 1, 'NZ', 0, 0, '{CC}'),
('NZAKL', '奥克兰', 'AUCKLAND', 0, 1, 'NZ', 0, 0, '{CC}'),
('OMSLL', '塞拉莱', 'SALALAH', 0, 1, 'OM', 0, 0, '{CC}'),
('OMRAY', '赖苏特', 'RAYSUT', 0, 1, 'OM', 0, 0, '{CC}'),
('OMOPQ', '卡布斯港', 'PORT QABOOS（MINA QABOOS）', 0, 1, 'OM', 0, 0, '{CC}'),
('OMMUT', '马特拉', 'MUTHRA', 0, 1, 'OM', 0, 0, '{CC}'),
('OMMFH', '费赫勒港', 'MINA AL FAHAL', 0, 1, 'OM', 0, 0, '{CC}'),
('OMMCT', '马斯喀特', 'MUSCAT', 0, 1, 'OM', 0, 0, '{CC}'),
('PAPTY', '巴拿马城', 'PANAMA, CIUDAD DE', 0, 1, 'PA', 0, 0, '{CC}'),
('PAPAM', '阿尔米兰特', 'ALMIRANTE', 0, 1, 'PA', 0, 0, '{CC}'),
('PAONX', '科隆', 'COLON', 0, 1, 'PA', 0, 0, '{CC}'),
('PAMIT', '曼萨尼约', 'MANZANILLO', 0, 1, 'PA', 0, 0, '{CC}'),
('PACTB', '克里斯托瓦尔', 'CRISTOBAL', 0, 1, 'PA', 0, 0, '{CC}'),
('PABLB', '巴尔博亚', 'BALBOA', 0, 1, 'PA', 0, 0, '{CC}'),
('PETYL', '塔拉拉', 'TALARA', 0, 1, 'PE', 0, 0, '{CC}'),
('PETRU', '特鲁希略', 'TRUJILLO', 0, 1, 'PE', 0, 0, '{CC}'),
('PESUP', '苏佩', 'SUPE', 0, 1, 'PE', 0, 0, '{CC}'),
('PEPUB', '巴约瓦尔港', 'BAYOVAR', 0, 1, 'PE', 0, 0, '{CC}'),
('PEPIO', '皮斯科', 'PISCO', 0, 1, 'PE', 0, 0, '{CC}'),
('PEPAI', '派塔', 'PAITA', 0, 1, 'PE', 0, 0, '{CC}'),
('PEMRI', '马塔拉尼', 'MATARANI', 0, 1, 'PE', 0, 0, '{CC}'),
('PEMLQ', '莫延多', 'MOLLENDO', 0, 1, 'PE', 0, 0, '{CC}'),
('PEILQ', '伊洛', 'ILO', 0, 1, 'PE', 0, 0, '{CC}'),
('PEHCO', '瓦乔', 'HUACHO', 0, 1, 'PE', 0, 0, '{CC}'),
('PEEEN', '埃腾', 'ETEN', 0, 1, 'PE', 0, 0, '{CC}'),
('PECLL', '卡亚俄', 'CALLAO', 0, 1, 'PE', 0, 0, '{CC}'),
('PECHM', '钦博塔', 'CHIMBOTE', 0, 1, 'PE', 0, 0, '{CC}'),
('PFPPT', '帕皮提', 'PAPEETE', 0, 1, 'PF', 0, 0, '{CC}'),
('PFBOB', '波拉波拉', 'BORA-BORA', 0, 1, 'PF', 0, 0, '{CC}'),
('PGWWK', '威瓦克', 'WEWAK', 0, 1, 'PG', 0, 0, '{CC}'),
('PGRAB', '拉包尔', 'RABAUL', 0, 1, 'PG', 0, 0, '{CC}'),
('PGPOM', '莫尔兹比港', 'PORT MORESBY', 0, 1, 'PG', 0, 0, '{CC}'),
('PGMAG', '马当', 'MADANG', 0, 1, 'PG', 0, 0, '{CC}'),
('PGLAE', '莱城', 'LAE', 0, 1, 'PG', 0, 0, '{CC}'),
('PGKIM', '金贝', 'KIMBE', 0, 1, 'PG', 0, 0, '{CC}'),
('PGKIE', '基埃塔', 'KIETA', 0, 1, 'PG', 0, 0, '{CC}'),
('PGANB', '阿内瓦湾', 'ANEWA BAY', 0, 1, 'PG', 0, 0, '{CC}'),
('PHZAM', '三宝颜', 'ZAMBOANGA', 0, 1, 'PH', 0, 0, '{CC}'),
('PHSFE', '圣弗尔南多', 'SAN FERNANDO', 0, 1, 'PH', 0, 0, '{CC}'),
('PHMVS', '马里韦莱斯', 'MARIVELES', 0, 1, 'PH', 0, 0, '{CC}'),
('PHMNL', '马尼拉', 'MANILA', 0, 1, 'PH', 0, 0, '{CC}'),
('PHLIN', '林加延', 'LINGAYEN', 0, 1, 'PH', 0, 0, '{CC}'),
('PHLGP', '黎牙实比', 'LEGASPI', 0, 1, 'PH', 0, 0, '{CC}'),
('PHILO', '伊洛伊洛', 'ILOILO', 0, 1, 'PH', 0, 0, '{CC}'),
('PHDVO', '达沃', 'DAVAO', 0, 1, 'PH', 0, 0, '{CC}'),
('PHCGY', '卡加延德奥罗', 'CAGAYAN DE ORO', 0, 1, 'PH', 0, 0, '{CC}'),
('PHCEB', '宿务', 'CEBU', 0, 1, 'PH', 0, 0, '{CC}'),
('PHBTG', '八打雁', 'BATANGAS', 0, 1, 'PH', 0, 0, '{CC}'),
('PHAPR', '阿帕里', 'APARRI', 0, 1, 'PH', 0, 0, '{CC}'),
('PKPSI', '伯斯尼', 'PASNI', 0, 1, 'PK', 0, 0, '{CC}'),
('PKORW', '奥尔马拉', 'ORMARA', 0, 1, 'PK', 0, 0, '{CC}'),
('PKKHI', '卡拉奇', 'KARACHI', 0, 1, 'PK', 0, 0, '{CC}'),
('PKGWD', '瓜德尔', 'GWADAR', 0, 1, 'PK', 0, 0, '{CC}'),
('PKBQM', '穆罕默德宾加西姆', 'MUHAMMAD BIN QASIM', 0, 1, 'PK', 0, 0, '{CC}'),
('PLSZZ', '什切青', 'SZCZECIN', 0, 1, 'PL', 0, 0, '{CC}'),
('PLSWI', '希维诺乌伊希切', 'SWINOUJSCIE', 0, 1, 'PL', 0, 0, '{CC}'),
('PLGDY', '格丁尼亚', 'GDYNIA', 0, 1, 'PL', 0, 0, '{CC}'),
('PLGDN', '格但斯克', 'GDANSK', 0, 1, 'PL', 0, 0, '{CC}'),
('PMFSP', '圣皮埃尔', 'ST PIERRE', 0, 1, 'PM', 0, 0, '{CC}'),
('PNPCN', '皮特凯恩岛', 'PITCAIRN ISLAND', 0, 1, 'PN', 0, 0, '{CC}'),
('PRSJU', '圣胡安', 'SAN JUAN', 0, 1, 'PR', 0, 0, '{CC}'),
('PRPSE', '蓬塞', 'PONCE', 0, 1, 'PR', 0, 0, '{CC}'),
('PRMAZ', '马亚圭斯', 'MAYAGUEZ', 0, 1, 'PR', 0, 0, '{CC}'),
('PRLAM', '拉斯马雷亚斯', 'LAS MAREAS (GUAYAMA)', 0, 1, 'PR', 0, 0, '{CC}'),
('PTSET', '塞图巴尔', 'SETUBAL', 0, 1, 'PT', 0, 0, '{CC}'),
('PTPRM', '波尔蒂芒', 'PORTIMAO', 0, 1, 'PT', 0, 0, '{CC}'),
('PTPDL', '蓬塔德尔加达港', 'PONTA DELGADA', 0, 1, 'PT', 0, 0, '{CC}'),
('PTOPO', '波尔图', 'PORTO', 0, 1, 'PT', 0, 0, '{CC}'),
('PTLIS', '里斯本', 'LISBOA', 0, 1, 'PT', 0, 0, '{CC}'),
('PTLEI', '雷克索斯', 'LEIXOES', 0, 1, 'PT', 0, 0, '{CC}'),
('PTHOR', '奥尔塔', 'HORTA', 0, 1, 'PT', 0, 0, '{CC}'),
('PTFNC', '丰沙尔', 'FUNCHAL', 0, 1, 'PT', 0, 0, '{CC}'),
('PTADH', '英雄港', 'ANGRA DO HEROISMO', 0, 1, 'PT', 0, 0, '{CC}'),
('PWROR', '科罗尔', 'KOROR', 0, 1, 'PW', 0, 0, '{CC}'),
('QAUMS', '乌姆赛义德', 'UMM SAID', 0, 1, 'QA', 0, 0, '{CC}'),
('QADOH', '多哈', 'DOHA', 0, 1, 'QA', 0, 0, '{CC}'),
('REPDG', '加勒茨角港', 'PORT DE POINTE DES GALETS', 0, 1, 'RE', 0, 0, '{CC}'),
('RELPT', '勒波尔', 'LE PORT', 0, 1, 'RE', 0, 0, '{CC}'),
('ROSUL', '苏利纳', 'SULINA', 0, 1, 'RO', 0, 0, '{CC}'),
('ROMAG', '曼加利亚', 'MANGALIA', 0, 1, 'RO', 0, 0, '{CC}'),
('ROCND', '康斯坦察', 'CONSTANTA', 0, 1, 'RO', 0, 0, '{CC}'),
('ROBRA', '布勒伊拉', 'BRAILA', 0, 1, 'RO', 0, 0, '{CC}'),
('RUZAR', '扎鲁比诺', 'ZARUBINO', 0, 1, 'RU', 0, 0, '{CC}'),
('RUVYP', '东方港', 'VOSTOCHNYY（VOSTOCHNIY, PORT）', 0, 1, 'RU', 0, 0, '{CC}'),
('RUVVO', '符拉迪沃斯托克/海参崴', 'VLADIVOSTOK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUVNN', '瓦尼诺', 'VANINO', 0, 1, 'RU', 0, 0, '{CC}'),
('RUUKK', '乌斯季堪察茨克', 'UST-KAMCHATSK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUUGL', '乌格里哥斯克', 'UGLEGORSK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUTUA', '图阿普谢', 'TUAPSE', 0, 1, 'RU', 0, 0, '{CC}'),
('RUTAG', '塔甘罗格', 'TAGANROG', 0, 1, 'RU', 0, 0, '{CC}'),
('RUSOC', '索契', 'SOCHI', 0, 1, 'RU', 0, 0, '{CC}'),
('RUSAK', '亚历山徳罗夫斯克', 'ALEKSANDROVSK-SAKHALINSKIY', 0, 1, 'RU', 0, 0, '{CC}'),
('RUROV', '罗斯托夫', 'ROSTOV', 0, 1, 'RU', 0, 0, '{CC}'),
('RUPRN', '波罗奈斯克', 'PORONAISK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUPKC', '彼得罗巴浦洛夫斯克', '	PETROPAVLOVSK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUOHO', '鄂霍次克', 'OKHOTSK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUNVS', '新罗西斯克', 'NOVOROSSIYSK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUNJK', '纳霍德卡', 'NAKHODKA', 0, 1, 'RU', 0, 0, '{CC}'),
('RUNEV', '涅韦尔斯克', 'NEVELSK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUMMK', '摩尔曼斯克', 'MURMANSK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUMAG', '马加丹', 'MAGADAN（MAGADANSKY, PORT）', 0, 1, 'RU', 0, 0, '{CC}'),
('RULED', '圣彼得堡', 'ST. PETERSBURG', 0, 1, 'RU', 0, 0, '{CC}'),
('RUKOR', '科尔萨科夫', 'KORSAKOV', 0, 1, 'RU', 0, 0, '{CC}'),
('RUKHO', '霍尔姆斯克', 'KHOLMSK', 0, 1, 'RU', 0, 0, '{CC}'),
('RUKGD', '加里宁格勒', 'KALININGRAD', 0, 1, 'RU', 0, 0, '{CC}'),
('RUDYR', '阿纳德尔', 'ANADYR', 0, 1, 'RU', 0, 0, '{CC}'),
('RUARH', '阿尔汉格尔斯克', 'ARKHANGELSK', 0, 1, 'RU', 0, 0, '{CC}'),
('SAYNB', '延布', 'YANBU AL-BAHR', 0, 1, 'SA', 0, 0, '{CC}'),
('SARTA', '拉斯坦努拉', 'RAS TANURA', 0, 1, 'SA', 0, 0, '{CC}'),
('SAJUT', '朱阿马港', 'JUAYMAH TERMINAL', 0, 1, 'SA', 0, 0, '{CC}'),
('SAJUB', '朱拜勒', 'JUBAIL', 0, 1, 'SA', 0, 0, '{CC}'),
('SAJED', '吉达', 'JEDDAH', 0, 1, 'SA', 0, 0, '{CC}'),
('SAGIZ', '吉赞', 'JIZAN', 0, 1, 'SA', 0, 0, '{CC}'),
('SADMM', '达曼', 'AD DAMMAM', 0, 1, 'SA', 0, 0, '{CC}'),
('SBSHH', '肖特兰岛', 'SHORTLAND HARBOUR', 0, 1, 'SB', 0, 0, '{CC}'),
('SBRIN', '林吉科弗', 'RINGGI COVE', 0, 1, 'SB', 0, 0, '{CC}'),
('SBHIR', '霍尼亚拉', 'HONIARA', 0, 1, 'SB', 0, 0, '{CC}'),
('SCPOV', '维多利亚港', 'PORT VICTORIA', 0, 1, 'SC', 0, 0, '{CC}'),
('SDPZU', '苏丹港', 'PORT SUDAN', 0, 1, 'SD', 0, 0, '{CC}'),
('SEUME', '于默奥', 'UMEA', 0, 1, 'SE', 0, 0, '{CC}'),
('SEUDD', '乌德瓦拉', 'UDDEVALLA', 0, 1, 'SE', 0, 0, '{CC}'),
('SESTO', '斯德哥尔摩', 'STOCKHOLM', 0, 1, 'SE', 0, 0, '{CC}'),
('SESDL', '松兹瓦尔', 'SUNDSVALL', 0, 1, 'SE', 0, 0, '{CC}'),
('SEPIT', '皮特奥', 'PITEA', 0, 1, 'SE', 0, 0, '{CC}'),
('SEOXE', '乌克瑟勒松德', 'OXELOSUND', 0, 1, 'SE', 0, 0, '{CC}'),
('SEOER', '恩舍尔兹维克', 'ORNSKOLDSVIK', 0, 1, 'SE', 0, 0, '{CC}'),
('SENRK', '诺尔雪平', 'NORRKOPING', 0, 1, 'SE', 0, 0, '{CC}'),
('SEMMA', '马尔默', 'MALMO', 0, 1, 'SE', 0, 0, '{CC}'),
('SELLA', '吕勒奥', 'LULEA', 0, 1, 'SE', 0, 0, '{CC}'),
('SELAA', '兰斯克鲁纳', 'LANDSKRONA', 0, 1, 'SE', 0, 0, '{CC}'),
('SEKLR', '卡尔马', 'KALMAR', 0, 1, 'SE', 0, 0, '{CC}'),
('SEKAN', '卡尔斯港', 'KARLSHAMN', 0, 1, 'SE', 0, 0, '{CC}'),
('SEKAA', '卡尔斯克鲁纳', 'KARLSKRONA', 0, 1, 'SE', 0, 0, '{CC}'),
('SEHND', '海讷桑德', 'HARNOSAND', 0, 1, 'SE', 0, 0, '{CC}'),
('SEHEL', '赫尔辛堡', 'HELSINGBORG', 0, 1, 'SE', 0, 0, '{CC}'),
('SEHAD', '哈尔姆斯塔德', 'HALMSTAD', 0, 1, 'SE', 0, 0, '{CC}'),
('SEGVX', '耶夫勒', 'GAVLE', 0, 1, 'SE', 0, 0, '{CC}'),
('SEGOT', '哥德堡', 'GOTEBORG', 0, 1, 'SE', 0, 0, '{CC}'),
('SEFAG', '法尔肯贝里', 'FALKENBERG', 0, 1, 'SE', 0, 0, '{CC}'),
('SGSIN', '新加坡', 'SINGAPORE', 0, 1, 'SG', 0, 0, '{CC}'),
('SHSHN', '詹姆斯敦', 'JAMESTOWN', 0, 1, 'SH', 0, 0, '{CC}'),
('SHASI', '乔治敦', 'GEORGETOWN', 0, 1, 'SH', 0, 0, '{CC}'),
('SIKOP', '科佩尔', 'KOPER', 0, 1, 'SI', 0, 0, '{CC}'),
('SLPEP', '佩佩尔', 'PEPEL', 0, 1, 'SL', 0, 0, '{CC}'),
('SLFNA', '弗里敦', 'FREETOWN', 0, 1, 'SL', 0, 0, '{CC}'),
('SLBTE', '邦特', 'BONTHE', 0, 1, 'SL', 0, 0, '{CC}'),
('SNZIG', '济金绍尔', 'ZIGUINCHOR', 0, 1, 'SN', 0, 0, '{CC}'),
('SNXLS', '圣路易', 'ST LOUIS', 0, 1, 'SN', 0, 0, '{CC}'),
('SNKLC', '考拉克', 'KAOLACK', 0, 1, 'SN', 0, 0, '{CC}'),
('SNDKR', '达喀尔', 'DAKAR', 0, 1, 'SN', 0, 0, '{CC}'),
('SOMGQ', '摩加迪沙', 'MOGADISHU', 0, 1, 'SO', 0, 0, '{CC}'),
('SOKMU', '基斯马尤', 'KISMAYU', 0, 1, 'SO', 0, 0, '{CC}'),
('SOBBO', '柏培拉', 'BERBERA', 0, 1, 'SO', 0, 0, '{CC}'),
('SRPRM', '帕拉南', 'PARANAM', 0, 1, 'SR', 0, 0, '{CC}'),
('SRPBM', '帕拉马里博', 'PARAMARIBO', 0, 1, 'SR', 0, 0, '{CC}'),
('SRMOJ', '蒙戈', 'MOENGO', 0, 1, 'SR', 0, 0, '{CC}'),
('STTMS', '圣多美', 'SAO TOME ISLAND', 0, 1, 'ST', 0, 0, '{CC}'),
('SVLLD', '拉利贝塔德', 'LA LIBERTAD', 0, 1, 'SV', 0, 0, '{CC}'),
('SVAQJ', '阿卡胡特拉', 'ACAJUTLA', 0, 1, 'SV', 0, 0, '{CC}'),
('SYTTS', '塔尔图斯', 'TARTUS', 0, 1, 'SY', 0, 0, '{CC}'),
('SYLTK', '拉塔基亚', 'LATAKIA', 0, 1, 'SY', 0, 0, '{CC}'),
('SYBAN', '巴尼亚斯', 'BANIYAS', 0, 1, 'SY', 0, 0, '{CC}'),
('TCGDT', '大特克', 'GRAND TURK ISLAND', 0, 1, 'TC', 0, 0, '{CC}'),
('TGLFW', '洛美', 'LOME', 0, 1, 'TG', 0, 0, '{CC}'),
('TGKPE', '佩梅', 'KPEME', 0, 1, 'TG', 0, 0, '{CC}'),
('THSIR', '是拉差', 'SI RACHA', 0, 1, 'TH', 0, 0, '{CC}'),
('THSGZ', '宋卡', 'SONGKH1A', 0, 1, 'TH', 0, 0, '{CC}'),
('THSAT', '梭桃邑', 'SATTAHIP', 0, 1, 'TH', 0, 0, '{CC}'),
('THPAN', '北大年', 'PATTANI', 0, 1, 'TH', 0, 0, '{CC}'),
('THNAW', '那拉提瓦', 'NARATHIWAT', 0, 1, 'TH', 0, 0, '{CC}'),
('THLCH', '林查班', 'LAEM CHABANG', 0, 1, 'TH', 0, 0, '{CC}'),
('THHKT', '普吉', 'PHUKET', 0, 1, 'TH', 0, 0, '{CC}'),
('THBKK', '曼谷', 'BANGKOK', 0, 1, 'TH', 0, 0, '{CC}'),
('TKAFU', '阿塔富', 'ATAFU', 0, 1, 'TK', 0, 0, '{CC}'),
('TLDIL', '帝力', 'DILI', 0, 1, 'TL', 0, 0, '{CC}'),
('TNTUN', '突尼斯', 'TUNIS', 0, 1, 'TN', 0, 0, '{CC}'),
('TNSUS', '苏塞', 'SOUSSE', 0, 1, 'TN', 0, 0, '{CC}'),
('TNSFA', '斯法克斯', 'SFAX', 0, 1, 'TN', 0, 0, '{CC}'),
('TNLSK', '拉斯基拉', 'LA SKHIRRA', 0, 1, 'TN', 0, 0, '{CC}'),
('TNGAE', '加贝斯', 'GABES', 0, 1, 'TN', 0, 0, '{CC}'),
('TNBIZ', '比塞大', 'BIZERTE', 0, 1, 'TN', 0, 0, '{CC}'),
('TOTBU', '努库阿洛法', 'NUKU ALOFA', 0, 1, 'TO', 0, 0, '{CC}'),
('TONEI', '内亚富', 'NEIAFU', 0, 1, 'TO', 0, 0, '{CC}'),
('TRZON', '宗古尔达克', 'ZONGULDAK', 0, 1, 'TR', 0, 0, '{CC}'),
('TRTZX', '特拉布宗', 'TRABZON', 0, 1, 'TR', 0, 0, '{CC}'),
('TRTEK', '泰基尔达', 'TEKIRDAG', 0, 1, 'TR', 0, 0, '{CC}'),
('TRSSX', '萨姆松', 'SAMSUN', 0, 1, 'TR', 0, 0, '{CC}'),
('TRSIC', '锡诺普', 'SINOP', 0, 1, 'TR', 0, 0, '{CC}'),
('TRMER', '梅尔辛', 'MERSIN', 0, 1, 'TR', 0, 0, '{CC}'),
('TRKUS', '库沙达瑟', 'KUSADASI', 0, 1, 'TR', 0, 0, '{CC}'),
('TRIZT', '伊兹米特', 'IZMIT', 0, 1, 'TR', 0, 0, '{CC}'),
('TRIZM', '伊兹密尔', 'IZMIR', 0, 1, 'TR', 0, 0, '{CC}'),
('TRIST', '伊斯坦布尔', 'ISTANBUL', 0, 1, 'TR', 0, 0, '{CC}'),
('TRISK', '伊斯肯德伦', 'ISKENDERUN', 0, 1, 'TR', 0, 0, '{CC}'),
('TRGIR', '吉雷松', 'GIRESUN', 0, 1, 'TR', 0, 0, '{CC}'),
('TRGEM', '盖姆利克', 'GEMLIK', 0, 1, 'TR', 0, 0, '{CC}'),
('TRGEL', '盖利博卢', 'GELIBOLU', 0, 1, 'TR', 0, 0, '{CC}'),
('TRERE', '埃雷利', 'EREGLI', 0, 1, 'TR', 0, 0, '{CC}'),
('TRDRC', '代林杰', 'DERINCE', 0, 1, 'TR', 0, 0, '{CC}'),
('TRCKZ', '恰纳卡莱', 'CANAKKALE', 0, 1, 'TR', 0, 0, '{CC}'),
('TRBDM', '班德尔马', 'BANDIRMA', 0, 1, 'TR', 0, 0, '{CC}'),
('TRAYT', '安塔利亚', 'ANTALYA', 0, 1, 'TR', 0, 0, '{CC}'),
('TTPTS', '利萨斯角', 'POINT LISAS', 0, 1, 'TT', 0, 0, '{CC}'),
('TTPOS', '西班牙港', 'PORT-OF-SPAIN', 0, 1, 'TT', 0, 0, '{CC}'),
('TTCHA', '查瓜拉马斯', 'CHAGUARAMAS', 0, 1, 'TT', 0, 0, '{CC}'),
('TVFUN', '富纳富提', 'FUNAFUTI', 0, 1, 'TV', 0, 0, '{CC}'),
('TWTXG', '台中', 'TAICHUNG', 0, 1, 'TW', 0, 0, '{CC}'),
('TWTPE', '台北', 'TAIPEI', 0, 1, 'TW', 0, 0, '{CC}'),
('TWTNN', '台南', 'TAINAN', 0, 1, 'TW', 0, 0, '{CC}'),
('TWSUO', '苏澳', 'SUAO', 0, 1, 'TW', 0, 0, '{CC}'),
('TWKHH', '高雄', 'KAOHSIUNG', 0, 1, 'TW', 0, 0, '{CC}'),
('TWKEL', '基隆', 'KEELUNG(CHILUNG)', 0, 1, 'TW', 0, 0, '{CC}'),
('TWHUN', '花莲', 'HUALIEN', 0, 1, 'TW', 0, 0, '{CC}'),
('TZZNZ', '桑给巴尔岛', 'ZANZIBAR', 0, 1, 'TZ', 0, 0, '{CC}'),
('TZTGT', '坦噶', 'TANGA', 0, 1, 'TZ', 0, 0, '{CC}'),
('TZMYW', '姆特瓦拉', 'MTWARA', 0, 1, 'TZ', 0, 0, '{CC}'),
('TZLDI', '林迪', 'LINDI', 0, 1, 'TZ', 0, 0, '{CC}'),
('TZDAR', '达累斯萨拉姆', 'DAR ES SALAAM', 0, 1, 'TZ', 0, 0, '{CC}'),
('UAYAL', '雅尔塔', 'YALTA', 0, 1, 'UA', 0, 0, '{CC}'),
('UASVP', '塞瓦斯托波尔', 'SEVASTOPOL', 0, 1, 'UA', 0, 0, '{CC}'),
('UAODS', '敖德萨', 'ODESSA', 0, 1, 'UA', 0, 0, '{CC}'),
('UANIK', '尼古拉耶夫', 'NIKOLAYEV', 0, 1, 'UA', 0, 0, '{CC}'),
('UAMPW', '马里乌波尔', 'MARIUPOL（ZHDANOV）', 0, 1, 'UA', 0, 0, '{CC}'),
('UAKHE', '赫尔松', 'KHERSON', 0, 1, 'UA', 0, 0, '{CC}'),
('UAKEH', '刻赤', 'KERTCH', 0, 1, 'UA', 0, 0, '{CC}'),
('UAIZM', '伊兹梅尔', 'IZMAIL', 0, 1, 'UA', 0, 0, '{CC}'),
('UAILK', '伊利乔夫斯克', 'ILLICHIVS K（ILICHEVSK）', 0, 1, 'UA', 0, 0, '{CC}'),
('UAERD', '别尔江斯克', 'BERDYANSK', 0, 1, 'UA', 0, 0, '{CC}'),
('USWTN', '威尔明顿', 'WILMINGTON', 0, 1, 'US', 0, 0, '{CC}'),
('USTXT', '得克萨斯城', 'TEXAS CITY', 0, 1, 'US', 0, 0, '{CC}'),
('USTPA', '坦帕', 'TAMPA', 0, 1, 'US', 0, 0, '{CC}'),
('USTOL', '托莱多', 'TOLEDO', 0, 1, 'US', 0, 0, '{CC}'),
('USTIW', '塔科马', 'TACOMA', 0, 1, 'US', 0, 0, '{CC}'),
('USSSI', '不伦瑞克', 'BRUNSWICK', 0, 1, 'US', 0, 0, '{CC}'),
('USSFO', '圣弗朗西斯科', 'SAN FRANCISCO', 0, 1, 'US', 0, 0, '{CC}'),
('USSEW', '苏厄德', 'SEWARD', 0, 1, 'US', 0, 0, '{CC}'),
('USSEA', '西雅图', 'SEATTLE', 0, 1, 'US', 0, 0, '{CC}'),
('USSAV', '萨凡纳', 'SAVANNAH', 0, 1, 'US', 0, 0, '{CC}'),
('USSAN', '圣迭戈', 'SAN DIEGO', 0, 1, 'US', 0, 0, '{CC}'),
('USPWM', '波特兰', 'PORTLAND', 0, 1, 'US', 0, 0, '{CC}'),
('USPSM', '朴次茅斯', 'PORTSMOUTH', 0, 1, 'US', 0, 0, '{CC}'),
('USPHL', '费城', 'PHILADELPHIA', 0, 1, 'US', 0, 0, '{CC}'),
('USPDX', '波特兰', 'PORTLAND', 0, 1, 'US', 0, 0, '{CC}'),
('USORF', '诺福克', 'NORFOLK', 0, 1, 'US', 0, 0, '{CC}'),
('USOAK', '奥克兰', 'OAKLAND', 0, 1, 'US', 0, 0, '{CC}'),
('USNYC', '纽约', 'NEW YORK', 0, 1, 'US', 0, 0, '{CC}'),
('USNBD', '新贝德福德', 'NEW BEDFORD', 0, 1, 'US', 0, 0, '{CC}'),
('USMSY', '新奥尔良', 'NEW ORLEANS', 0, 1, 'US', 0, 0, '{CC}'),
('USMOB', '莫比尔', 'MOBILE', 0, 1, 'US', 0, 0, '{CC}'),
('USMIA', '迈阿密', 'MIAMI', 0, 1, 'US', 0, 0, '{CC}'),
('USMEM', '孟菲斯', 'MEMPHIS', 0, 1, 'US', 0, 0, '{CC}'),
('USLGB', '长滩', 'LONG BEACH', 0, 1, 'US', 0, 0, '{CC}'),
('USLCH', '莱克查尔斯', 'LAKE CHARLES', 0, 1, 'US', 0, 0, '{CC}'),
('USLAX', '洛杉矶', 'LOS ANGELES', 0, 1, 'US', 0, 0, '{CC}'),
('USJVL', '杰克逊维尔', 'JANESVILLE', 0, 1, 'US', 0, 0, '{CC}'),
('USJAX', '杰克逊维尔', 'JACKSONVILLE', 0, 1, 'US', 0, 0, '{CC}'),
('USHVN', '纽黑文', 'NEW HAVEN', 0, 1, 'US', 0, 0, '{CC}'),
('USHOU', '休斯敦', 'HOUSTON', 0, 1, 'US', 0, 0, '{CC}'),
('USHNL', '火奴鲁鲁', 'HONOLULU', 0, 1, 'US', 0, 0, '{CC}'),
('USDUT', '荷兰港', 'DUTCH HARBOR', 0, 1, 'US', 0, 0, '{CC}'),
('USDST', '亚当斯顿', 'ADAMSTON', 0, 1, 'US', 0, 0, '{CC}'),
('USDET', '底特律', 'DETROIT', 0, 1, 'US', 0, 0, '{CC}'),
('USCLE', '克利夫兰', 'CLEVELAND', 0, 1, 'US', 0, 0, '{CC}'),
('USCHS', '查尔斯顿', 'CHARLESTON', 0, 1, 'US', 0, 0, '{CC}'),
('USCHI', '芝加哥', 'CHICAGO', 0, 1, 'US', 0, 0, '{CC}'),
('USCDE', '卡姆登', 'CAMDEN', 0, 1, 'US', 0, 0, '{CC}'),
('USBOS', '波士顿', 'BOSTON', 0, 1, 'US', 0, 0, '{CC}'),
('USBAL', '巴尔的摩', 'BALTIMORE', 0, 1, 'US', 0, 0, '{CC}'),
('USANC', '安科雷奇', 'ANCHORAGE', 0, 1, 'US', 0, 0, '{CC}'),
('USALB', '奥尔巴尼', 'ALBANY', 0, 1, 'US', 0, 0, '{CC}'),
('UYPDP', '埃斯特角', 'PUNTA DEL ESTE', 0, 1, 'UY', 0, 0, '{CC}'),
('UYNVP', '新帕尔米拉', 'NUEVA PALMIRA', 0, 1, 'UY', 0, 0, '{CC}'),
('UYMVD', '蒙得维的亚', 'MONTEVIDEO', 0, 1, 'UY', 0, 0, '{CC}'),
('VCKTN', '金斯敦', 'KINGSTOWN', 0, 1, 'VC', 0, 0, '{CC}'),
('VEPZO', '奥尔达斯港', 'PUERTO ORDAZ', 0, 1, 'VE', 0, 0, '{CC}'),
('VEPPD', '蓬塔-德彼徳拉斯', 'PUNTA DE PIEDRA', 0, 1, 'VE', 0, 0, '{CC}'),
('VEPCZ', '拉克鲁斯港', 'PUERTO LA CRUZ', 0, 1, 'VE', 0, 0, '{CC}'),
('VEPCN', '篷塔卡尔东', 'PUNTA CARDON', 0, 1, 'VE', 0, 0, '{CC}'),
('VEPBL', '卡贝略港', 'PUERTO CABELLO', 0, 1, 'VE', 0, 0, '{CC}'),
('VEMAR', '马拉开波', 'MARACAIBO', 0, 1, 'VE', 0, 0, '{CC}'),
('VELAG', '拉瓜伊拉', 'LA GUAIRA', 0, 1, 'VE', 0, 0, '{CC}'),
('VEGUI', '圭里亚', 'GUIRIA', 0, 1, 'VE', 0, 0, '{CC}'),
('VECUM', '库马纳', 'CUMANA', 0, 1, 'VE', 0, 0, '{CC}'),
('VEAMY', '阿穆艾', 'AMUAY', 0, 1, 'VE', 0, 0, '{CC}'),
('VGRAD', '罗德城', 'ROAD TOWN', 0, 1, 'VG', 0, 0, '{CC}'),
('VICHA', '夏洛特阿马利亚', 'CHARLOTTE AMALIE', 0, 1, 'VI', 0, 0, '{CC}'),
('VNVUT', '头顿', 'VUNG TAU', 0, 1, 'VN', 0, 0, '{CC}'),
('VNUIH', '归仁', 'QUI NHON', 0, 1, 'VN', 0, 0, '{CC}'),
('VNSGN', '胡志明市', 'HO CHI MINH CITY', 0, 1, 'VN', 0, 0, '{CC}'),
('VNNHA', '芽庄', 'NHA TRANG', 0, 1, 'VN', 0, 0, '{CC}'),
('VNHUI', '顺化', 'HUE', 0, 1, 'VN', 0, 0, '{CC}'),
('VNHPH', '海防', 'HAIPHONG', 0, 1, 'VN', 0, 0, '{CC}'),
('VNHON', '鸿基', 'HONGAI', 0, 1, 'VN', 0, 0, '{CC}'),
('VNDAD', '岘港', 'DA NANG', 0, 1, 'VN', 0, 0, '{CC}'),
('VNCRB', '金兰', 'CAMRANH', 0, 1, 'VN', 0, 0, '{CC}'),
('VUVLI', '维拉港', 'PORT VILA/VILA', 0, 1, 'VU', 0, 0, '{CC}'),
('VUSAN', '桑托', 'SANTO', 0, 1, 'VU', 0, 0, '{CC}'),
('WFMAU', '马塔乌图', 'MATA UTU', 0, 1, 'WF', 0, 0, '{CC}'),
('WSAPW', '阿皮亚', 'APIA', 0, 1, 'WF', 0, 0, '{CC}'),
('YESAL', '萨利夫', 'SALEEF PORT', 0, 1, 'YE', 0, 0, '{CC}'),
('YEMOK', '穆哈', 'MOKHA', 0, 1, 'YE', 0, 0, '{CC}'),
('YEMKX', '穆卡拉', 'MUKALLA', 0, 1, 'YE', 0, 0, '{CC}'),
('YEHOD', '荷台达', 'HODEIDAH', 0, 1, 'YE', 0, 0, '{CC}'),
('YEADE', '亚丁', 'ADEN', 0, 1, 'YE', 0, 0, '{CC}'),
('YTDZA', '藻德济', 'DZAOUDZI', 0, 1, 'YT', 0, 0, '{CC}'),
('ZASDB', '萨尔达尼亚湾', 'SALDANHA BAY', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZARCB', '理查兹贝', 'RICHARDS BAY', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZAPLZ', '伊丽莎白港', 'PORT ELIZABETH', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZAMZY', '莫塞尔贝', 'MOSSEL BAY', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZAELS', '东伦敦', 'EAST LONDON', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZADUR', '德班', 'DURBAN', 0, 1, 'ZA', 0, 0, '{CC}'),
('ZACPT', '开普敦', 'CAPE TOWN', 0, 1, 'ZA', 0, 0, '{CC}')
;

