INSERT INTO `G_PACKAGE` (`PACK_CODE`, `PACK_NAME`, `ACTIVE`, `COMP_CODE`, `VERSION`, `REMOVED`) VALUES
('BAGS', 'BAGS', 1, '{CC}', 0, 0),
('BIG BAGS', 'BIG BAGS', 1, '{CC}', 0, 0),
('BALES', 'BALES', 1, '{CC}', 0, 0),
('BOXES', 'BOXES', 1, '{CC}', 0, 0),
('BDLS', 'BUNDLES', 1, '{CC}', 0, 0),
('BUNDLES', 'BUNDLES', 1, '{CC}', 0, 1),
('BTL', 'BOTTOLS', 1, '{CC}', 0, 0),
('BOTTOLS', 'BTLS', 1, '{CC}', 0, 0),
('BLDS', 'BLDS', 1, '{CC}', 0, 0),
('CANS', 'CANS', 1, '{CC}', 0, 0),
('CASES', 'CASES', 1, '{CC}', 0, 0),
('CLOTH BA', 'CLOTH BALE', 1, '{CC}', 0, 0),
('CNTRS', 'CONTAINERS', 1, '{CC}', 0, 0),
('COILS', 'COILS', 1, '{CC}', 0, 0),
('COM', 'COMPOUND BAGS', 1, '{CC}', 0, 0),
('CRATE', 'CRATES', 1, '{CC}', 0, 0),
('CTNS', 'CARTONS', 1, '{CC}', 0, 0),
('C/DRUM', 'CARDBOARD DRUMS', 1, '{CC}', 0, 0),
('CYL', 'CYLINDERS', 1, '{CC}', 0, 0),
('DZS', 'DOZENS', 1, '{CC}', 0, 0),
('DRUMS', 'DRUMS', 1, '{CC}', 0, 0),
('DOUBLE', 'DOUBLE PP BAGS', 1, '{CC}', 0, 0),
('DUNDLES', 'DUNDLES', 1, '{CC}', 0, 0),
('ENDCAPS', 'CLEAR FLOAT GLASS', 1, '{CC}', 0, 0),
('FDRUMS', 'FIBRE DRUMS', 1, '{CC}', 0, 0),
('GUN', 'GUNNY SACKS', 1, '{CC}', 0, 0),
('GUNNY', 'GUNNY BAG', 1, '{CC}', 0, 0),
('HANGERS', 'HANGERS', 1, '{CC}', 0, 0),
('IRONPALE', 'IRON PALLETS', 1, '{CC}', 0, 0),
('IRON C', 'IRON CRATES', 1, '{CC}', 0, 0),
('IRON DRU', 'IRON DRUMS', 1, '{CC}', 0, 0),
('JUMBOBAG', 'JUMBO BAGS', 1, '{CC}', 0, 0),
('KINT BAG', 'KINTTING BAG', 1, '{CC}', 0, 0),
('LOT', 'LOT', 1, '{CC}', 0, 0),
('MTS', 'MTS', 1, '{CC}', 0, 0),
('PAPER', 'PAPER BAGS', 1, '{CC}', 0, 0),
('PCS', 'PIECES', 1, '{CC}', 0, 0),
('P/CS', 'PLYWOOD CASES', 1, '{CC}', 0, 0),
('PLT', 'PALLET', 1, '{CC}', 0, 0),
('PLTS', 'PALLETS', 1, '{CC}', 0, 0),
('PAIRS', 'PAIRS', 1, '{CC}', 0, 0),
('PLASTICD', 'PLASTIC DRUMS', 1, '{CC}', 0, 0),
('PLASTICB', 'PLASTIC BAGS', 1, '{CC}', 0, 0),
('PPWOVENB', 'PP WOVEN BAGS', 1, '{CC}', 0, 0),
('PRS', 'PRS', 1, '{CC}', 0, 0),
('PRESS PA', 'PRESS PACKED BALES', 1, '{CC}', 0, 0),
('PACKAGES', 'PACKAGES', 1, '{CC}', 0, 0),
('RACKS', 'RACKS', 1, '{CC}', 0, 0),
('ROLLS', 'ROLLS', 1, '{CC}', 0, 0),
('REELS', 'REELS', 1, '{CC}', 0, 0),
('S/P', 'SETS/PCS', 1, '{CC}', 0, 0),
('SKIDS', 'SKIDS', 1, '{CC}', 0, 0),
('SETS', 'SETS', 1, '{CC}', 0, 0),
('SACKS', 'SACKS', 1, '{CC}', 0, 0),
('SUPER', 'SUPER SACKS', 1, '{CC}', 0, 0),
('SB.CASES', 'SYNTHETIC BOARD CASES', 1, '{CC}', 0, 0),
('TUBES', 'TUBES', 1, '{CC}', 0, 0),
('TRAYS', 'TRAYS', 1, '{CC}', 0, 0),
('TINS', 'TINS', 1, '{CC}', 0, 0),
('TANK', 'TANK', 1, '{CC}', 0, 0),
('T/BAGS', 'TOTE BAGS', 1, '{CC}', 0, 0),
('UNPACKED', 'UNPACKED', 1, '{CC}', 0, 0),
('UNITS', 'UNITS', 1, '{CC}', 0, 0),
('W/P', 'WOODEN PALLETS', 1, '{CC}', 0, 0),
('WDCS', 'WDCS', 1, '{CC}', 0, 0),
('WOVEN BS', 'WOVEN BAGS', 1, '{CC}', 0, 0),
('W/BAGS', 'WEAVING BAGS', 1, '{CC}', 0, 0),
('W/CS', 'WOODEN CASES', 1, '{CC}', 0, 0),
('W/BS', 'WOODEN BOXES', 1, '{CC}', 0, 0),
('W/CRS', 'WOODEN CRATES', 1, '{CC}', 0, 0),
('W/DRUMS', 'WOODEN DRUMS', 1, '{CC}', 0, 0)
;