ALTER TABLE `S_BALANCE`
	ADD COLUMN `REMARKS` VARCHAR(500) NULL AFTER `BALA_AMOUNT`;	
INSERT INTO `P_ACTION` (`ACT_NAME`, `ACT_SERVICE`, `ACT_METHOD`, `ACT_REMARK`) VALUES
	('BALA_S', 'SBalanceService', 'save', '客户余额保存');
	
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_INVOICE_NO` varchar(32) NULL AFTER `CUDE_OPEN_FLAG`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_INVOICE_DATE` date NULL AFTER `CUDE_INVOICE_NO`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_CONSIGNEE` VARCHAR(500) NULL DEFAULT NULL AFTER `CUDE_SHIPPER`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_CARGO_COMPANY` VARCHAR(200) NULL DEFAULT NULL AFTER `CUDE_CUSTOMER`
	
ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_CUSTOMS_CONTACT` varchar(32) NULL AFTER `CONS_CUSTOMS_VENDOR_NAME`;
ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_TEL` varchar(32) NULL AFTER `CONS_CUSTOMS_CONTACT`;

ALTER TABLE `F_CUSTOMS_ENTRY`
	ADD COLUMN `CUEN_CARGO_GROSS_WEIGHT` DECIMAL(9,2) NULL DEFAULT NULL AFTER `CUEN_CARGO_UNIT`,
	ADD COLUMN `CUEN_CARGO_NET_WEIGHT` DECIMAL(9,2) NULL DEFAULT NULL AFTER `CUEN_CARGO_GROSS_WEIGHT`,
	ADD COLUMN `CUEN_CARGO_MEASUREMENT` DECIMAL(9,2) NULL DEFAULT NULL AFTER `CUEN_CARGO_NET_WEIGHT`;
	
ALTER TABLE `f_customs_declaration`
	CHANGE COLUMN `CUDE_VENDOR_CONTACT` `CUDE_VENDOR_CONTACT` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUDE_VENDOR_NAME`,
	CHANGE COLUMN `CUDE_VENDOR_TEL` `CUDE_VENDOR_TEL` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUDE_VENDOR_CONTACT`;