--
-- 转存表中的数据 `P_TEMPLATE_TYPE`
--

INSERT INTO `P_TEMPLATE_TYPE` (`TETY_ID`, `TETY_NAME`, `TETY_CODE`, `TETY_DESC`, `TETY_ACTION`, `TETY_PARENT`, `TETY_CHILD`, `TETY_CLASS`, `TETY_TYPE`, `TETY_FORM_FLAG`, `ACTIVE`, `VERSION`, `REMOVED`) VALUES
(1, '提单模板', 'BL', NULL, 'BL_Q', 'FBl', NULL, 'B', 'P', 1, 1, 1, 0),
(4, '报关单模板', 'CUDE', NULL, 'CUDE_Q', 'FCustomsDeclaration', 'FCustomsEntry', 'B', 'P', 1, 1, 1, 0),
(5, '报检单模板', 'INSP', NULL, 'INSP_Q', 'FInspection', NULL, 'B', 'P', 1, 1, 1, 0),
(6, '装箱清单模板', 'CONTL', NULL, 'CONT_Q', NULL, NULL, 'B', 'P', 1, 1, 1, 0),
(7, '十联单模板', 'CONS', NULL, 'CONS_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 1, 0),
(8, '装箱单模板', 'CONT', NULL, 'CONT_Q', 'FContainer', 'FContainerCargo', 'B', 'P', 1, 1, 1, 0),
(9, '发票模板', 'INVO', NULL, 'INVO_Q', 'SInvoice', 'SinvoiceEntry', 'B', 'P', 1, 1, 1, 0),
(15, '委托列表', 'CONS_LIST', '委托列表导出模板', 'CONS_CHECK_X', NULL, 'FConsign', 'A', 'P', 1, 1, 1, 0),
(16, '单票审核', 'CONS_AUDIT', '单票审核导出模板', 'CONS_CHECK_X', NULL, 'FConsign', 'A', 'P', 1, 1, 1, 0),
(17, '对账单', 'BILL', NULL, 'BILL_EQ', 'SBill', 'SBillItem', 'B', 'P', 1, 1, 1, 0),
(18, '进仓/装箱通知单', 'WARE_INFO', NULL, 'CONS_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 0, 0),
(19, '订舱确认书', 'BOOK_C', NULL, 'CONS_Q', 'FConsign', 'SExpense', 'B', 'P', 1, 1, 0, 0),
(20, '代运联系单', 'TRAN', NULL, 'TRAN_QWC', 'FTrans', 'FTransCargo', 'B', 'P', 1, 1, 0, 0),
(21, '仓储联系单', 'WARE', NULL, 'WARE_Q', 'FWarehouse', 'FWarehouseCargo', 'B', 'P', 1, 1, 0, 0),
(22, '电放保函', 'BLER', '电放保函模板', 'CONS_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 0, 0),
(23, 'SEAWAYBILL保函', 'SEAW', NULL, 'CONS_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 0, 0),
(24, '进口分拨申请', 'SPLI', NULL, 'CONS_Q', 'FConsign', 'FDo', 'B', 'P', 1, 1, 0, 0),
(25, '进口提货单', 'DO', NULL, 'DO_Q', 'FDo', NULL, 'B', 'P', 1, 1, 0, 0),
(26, '订舱委托书', 'CONS_B', '订舱委托书', 'CONS_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 0, 0),
(27, '进口到货通知', 'ARAD', '进口到货通知', 'CONS_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 0, 0),
(28, '船期表', 'VOYA_LIST', NULL, 'VOYA_X', NULL, 'GVoyage', 'B', 'P', 1, 1, 0, 0),
(29, '整船舱单', 'MANIFEST', NULL, 'CONT_X', 'GVoyage', 'FContainer', 'B', 'P', 1, 1, 0, 0),
(30, '单证清单输出模板', 'FDOC_LIST', '单证清单输出模板', 'FDOC_X', NULL, 'FDoc', 'A', 'P', 1, 1, 0, 0),
(31, '核销明细', 'VOUC_LIST', '核销明细', 'VOUC_Q', 'SVoucher', 'SVoucherItem', 'B', 'P', 1, 1, 0, 0),
(32, '运价表', 'PRSH_LIST', '运价表', 'PRSH_X', NULL, 'CPriceRecord', 'B', 'P', 1, 1, 0, 0),
(33, '配载清单', 'LOLI', '配载清单', 'VOYA_LOLI_Q', 'GVoyage', 'FLoadingList', 'B', 'P', 1, 1, 0, 0),
(34, '费用确认单', 'EXPE_CONFIRM', '费用确认单', 'EXPE_CONFIRM', 'FConsign', 'SExpense', 'B', 'P', 1, 1, 0, 0),
(35, '发货清单导入模板', 'PALI_IMPORT', '发货清单表', 'PALI_S', NULL, 'FPackingList', 'B', 'P', 1, 1, 0, 0),
(36, '账单清单', 'INVO_LIST', '账单清单', 'INVO_X', '', 'SInvoice', 'B', 'P', 1, 1, 0, 0),
(37, '委托信息', 'CONS_INFO', '委托信息', '', 'FConsign', '', 'B', 'M', 1, 1, 0, 0),
(38, '发货清单', 'PACK_LIST', '发货清单输出模板', 'PALI_X', NULL, 'FPackingList', 'A', 'P', 1, 1, 0, 0),
(39, 'SGS检验通知', 'SGS_INFO', 'SGS检验通知', 'CONS_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 0, 0),
(40, '装船通知', 'SHIP_INFO', '装船通知', 'CONS_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 0, 0),
(41, '订舱委托书（货物）', 'CONS_B_CARG', '订舱委托书（货物）', 'CONS_CARGO_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 0, 0),
(42, '订舱委托书（提单）', 'CONS_B_BL', '订舱委托书（提单）', 'CONS_BL_Q', 'FConsign', NULL, 'B', 'P', 1, 1, 0, 0),
(43, '核销单信息', 'FDOC_INFO', '核销单信息（定时提醒）', NULL, 'FDoc', NULL, 'B', 'M', 1, 1, 0, 0),
(44, '导出到站地点', 'PLAC_E', '导出到站地点', 'PLAC_E', 'GPlace', 'FContract', 'A', 'P', 0, 1, 0, 0),
(45, '业务员超期提示', 'FCONSIGN_INFO', '业务员超期提示', NULL, 'FConsign', NULL, 'B', 'M', 1, 1, 0, 0),
(46, '减免税统计表', 'RELIEF_TAX_STAT', '减免税统计表', 'CONS_X',  NULL, 'FConsign','B', 'M', 1, 1, 0, 0),
(47, '加工贸易催核表', 'TRADE_STAT', '加工贸易催核表', 'CONS_X',  NULL, 'FConsign','B', 'M', 1, 1, 0, 0),
(48, '退单申请表', 'CUSTOMS_DOC_STAT', '退单申请表', 'CONS_X',  NULL, 'FConsign','B', 'M', 1, 1, 0, 0),
(49, '商业发票', 'CUDE_INVOICE', NULL, 'CUDE_Q', 'FCustomsDeclaration', 'FCustomsEntry', 'B', 'P', 1, 1, 1, 0),
(50, '报关装箱单', 'CUDE_PACKING', NULL, 'CUDE_Q', 'FCustomsDeclaration', 'FCustomsEntry', 'B', 'P', 1, 1, 1, 0),
(51, '贸易合同', 'CUDE_CONTRACT', NULL, 'CUDE_Q', 'FCustomsDeclaration', 'FCustomsEntry', 'B', 'P', 1, 1, 1, 0),
(52, '费用结算单', 'EXPE_SETTLEMENT', '费用结算单', 'CONS_CHECK_X', 'FConsign', 'SExpense', 'B', 'P', 1, 1, 0, 0);
(53, '业务流程表', 'BUSINESS_PROCESS', '业务流程表', 'CONS_T_X', 'FConsign', 'FTask', 'B', 'P', 1, 1, 0, 0);

-- 提单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(1, '发货人', 'FBl', 'blShipper', NULL),
(1, '收货人', 'FBl', 'blConsignee', NULL),
(1, '通知人', 'FBl', 'blNotifyParty', NULL),
(1, '第二通知人', 'FBl', 'blNotifyParty2', NULL),
(1, '提单号', 'FBl', 'blNo', NULL),
(1, 'HBLNo', 'FBl', 'blNo', NULL),
(1, 'MBLNo', 'FBl', 'mblNo', NULL),
(1, 'HAWBNO', 'FBl', 'blNo', NULL),
(1, 'MAWBNO', 'FBl', 'mblNo', NULL),
(1, '装运方式', 'FBl', 'consShipType', NULL),
(1, '贸易合同号', 'FBl', 'consTradeContractNo', NULL),
(1, '业务号', 'FBl', 'consNo', NULL),
(1, '目的港代理', 'FBl', 'blOverseaAgency', NULL),
(1, '收货地', 'FBl', 'blReceiptPlace', NULL),
(1, '前程运输', 'FBl', 'blPrecarriage', NULL),
(1, '船名', 'FBl', 'blVessel', NULL),
(1, '航次', 'FBl', 'blVoyage', NULL),
(1, '航班号', 'FBl', 'blVoyage', NULL),
(1, '装货港', 'FBl', 'blPol', NULL),
(1, '卸货港', 'FBl', 'blPod', NULL),
(1, '交货地', 'FBl', 'blDeliveryPlace', NULL),
(1, '标记唛码', 'FBl', 'blMarks', NULL),
(1, '件数', 'FBl', 'blPackages', NULL),
(1, '包装', 'FBl', 'packName', NULL),
(1, '货物描述', 'FBl', 'blCargoDesc', NULL),
(1, '毛重', 'FBl', 'blGrossWeight', NULL),
(1, '体积', 'FBl', 'blMeasurement', NULL),
(1, '合计大写', 'FBl', 'blTotalSay', NULL),
(1, '运费条款', 'FBl', 'blPaymentTerm', NULL),
(1, '付费地点', 'FBl', 'blPaidAt', NULL),
(1, '附加条款', 'FBl', 'consChargeRemarks', NULL),
(1, '运输条款', 'FBl', 'blTransTerm', NULL),
(1, '正本份数', 'FBl', 'blOriginalNum', NULL),
(1, '签发人', 'FBl', 'blIssueBy', NULL),
(1, '签发地点', 'FBl', 'blIssuePlace', NULL),
(1, '签发日期', 'FBl', 'blIssueDate', NULL),
(1, '装运方式', 'FBl', 'consShipType', NULL),
(1, '箱型箱量', 'FBl', 'blContainerInfo', NULL),
(1, '箱号', 'FBl', 'blContainerNo', NULL),
(1, '清洁提单', 'FBl', 'blCleanFlag', 'getCleanBL'),
(1, '承运人', 'FBl', 'blCarrierName', NULL),
(1, '备注', 'FBl', 'blRemarks', NULL),
(1, '装船日期', 'FBl', 'blLoadDate', NULL),
(1, '到港日期', 'FBl', 'blEta', NULL),
(1, '开航日期', 'FBl', 'blEtd', NULL),
(1, '第一中转港代码', 'FBl', 'blToFirst', NULL),
(1, '第二中转港代码', 'FBl', 'blToSecond', NULL),
(1, '第三中转港代码', 'FBl', 'blToThird', NULL),
(1, '头程承运人代码', 'FBl', 'blByFirst', NULL),
(1, '二程承运人代码', 'FBl', 'blBySecond', NULL),
(1, '三程承运人代码', 'FBl', 'blByThird', NULL),
(1, '币种', 'FBl', 'currCode', NULL),
(1, '从价从量运费条款', 'FBl', 'blWeightPayment', NULL),
(1, '其它费用条款', 'FBl', 'blOtherPayment', NULL),
(1, '承运申报价值', 'FBl', 'blDvCarriage', NULL),
(1, '海关申报价值', 'FBl', 'blDvCustoms', NULL),
(1, '保险金额', 'FBl', 'blAmountInvoice', NULL),
(1, '其它操作信息', 'FBl', 'blHandlingInfo', NULL),
(1, '费率等级', 'FBl', 'blRateClass', NULL),
(1, '商品代码', 'FBl', 'blRateClass', NULL),
(1, '付费重量', 'FBl', 'blChargeWeight', NULL),
(1, '费率', 'FBl', 'blChargeRate', NULL),
(1, '运费总额', 'FBl', 'blTotalCharge', NULL),
(1, '从量运费预付额', 'FBl', 'blWeightChargePp', NULL),
(1, '从量运费到付额', 'FBl', 'blWeightChargeCc', NULL),
(1, '从价运费预付额', 'FBl', 'blValuationChargePp', NULL),
(1, '从价运费到付额', 'FBl', 'blValuationChargeCc', NULL),
(1, '其它费用', 'FBl', 'consChargeRemarks', NULL),
(1, '预付总额', 'FBl', 'blTotalPp', NULL),
(1, '到付总额', 'FBl', 'blTotalCc', NULL)
;

-- 报关单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(4, '预录入编号', 'FCustomsDeclaration', 'cudePreNo', NULL),
(4, '海关编号', 'FCustomsDeclaration', 'cudeCustomsNo', NULL),
(4, '出口口岸', 'FCustomsDeclaration', 'cudePol', NULL),
(4, '进口口岸', 'FCustomsDeclaration', 'cudePod', NULL),
(4, '备案号', 'FCustomsDeclaration', 'cudeRecordNo', NULL),
(4, '出口日期', 'FCustomsDeclaration', 'cudeEntryDate', NULL),
(4, '进口日期', 'FCustomsDeclaration', 'cudeEntryDate', NULL),
(4, '申报日期', 'FCustomsDeclaration', 'cudeDeclarDate', NULL),
(4, '经营单位', 'FCustomsDeclaration', 'cudeCustomer', NULL),
(4, '运输方式', 'FCustomsDeclaration', 'tratCode', NULL),
(4, '运输工具名称', 'FCustomsDeclaration', 'cudeConveyance', NULL),
(4, '提运单号', 'FCustomsDeclaration', 'cudeBlNo', NULL),
(4, '发货单位', 'FCustomsDeclaration', 'cudeShipper', NULL),
(4, '收货单位', 'FCustomsDeclaration', 'cudeShipper', NULL),
(4, '贸易方式', 'FCustomsDeclaration', 'trtyCode', NULL),
(4, '征免性质', 'FCustomsDeclaration', 'letyCode', NULL),
(4, '征税比例', 'FCustomsDeclaration', 'cudeLevyPercent', NULL),
(4, '结汇方式', 'FCustomsDeclaration', 'exseCode', NULL),
(4, '许可证号', 'FCustomsDeclaration', 'cudeApprovalNo', NULL),
(4, '运抵国', 'FCustomsDeclaration', 'cudeDischargeCountry', NULL),
(4, '指运港', 'FCustomsDeclaration', 'cudePod', NULL),
(4, '装货港', 'FCustomsDeclaration', 'cudePol', NULL),
(4, '境内货源地', 'FCustomsDeclaration', 'cudePlace', NULL),
(4, '境内目的地', 'FCustomsDeclaration', 'cudePlace', NULL),
(4, '批准文号', 'FCustomsDeclaration', 'cudeApprovalNo', NULL),
(4, '成交方式', 'FCustomsDeclaration', 'trteCode', NULL),
(4, '运费', 'FCustomsDeclaration', 'cudeFreight', NULL),
(4, '保费', 'FCustomsDeclaration', 'cudeInsurance', NULL),
(4, '杂费', 'FCustomsDeclaration', 'cudeCharge', NULL),
(4, '合同协议号', 'FCustomsDeclaration', '', NULL),
(4, '件数', 'FCustomsDeclaration', 'cudePackageNum', NULL),
(4, '包装种类', 'FCustomsDeclaration', 'packCode', NULL),
(4, '毛重', 'FCustomsDeclaration', 'cudeGrossWeight', NULL),
(4, '净重', 'FCustomsDeclaration', 'cudeNetWeight', NULL),
(4, '集装箱号', 'FCustomsDeclaration', 'cudeContainerNo', NULL),
(4, '随附单据', 'FCustomsDeclaration', 'cudeAttachment', NULL),
(4, '用途', 'FCustomsDeclaration', 'usagName', NULL),
(4, '生产厂家', 'FCustomsDeclaration', 'cudeManu', NULL),
(4, '标记麦码及备注', 'FCustomsDeclaration', 'cudeMarks', NULL),
(4, '税费征收情况', 'FCustomsDeclaration', 'cudeTaxLevy', NULL),
(4, '录入员', 'FCustomsDeclaration', 'cudeCreator', NULL),
(4, '录入单位', 'FCustomsDeclaration', 'cudeCompany', NULL),
(4, '报关员', 'FCustomsDeclaration', 'cudeDeclarent', NULL),
(4, '单位地址', 'FCustomsDeclaration', 'cudeCompanyAddress', NULL),
(4, '邮编', 'FCustomsDeclaration', 'cudeCompanyZip', NULL),
(4, '电话', 'FCustomsDeclaration', 'cudeCompanyTel', NULL),
(4, '填制日期', 'FCustomsDeclaration', 'cudeCreateDate', NULL),
(4, '项号', 'FCustomsEntry', 'cuenNo', NULL),
(4, '商品编号', 'FCustomsEntry', 'cuenCargoNo', NULL),
(4, '英文品名', 'FCustomsEntry', 'cuenCargoNameEn', NULL),
(4, '商品名称', 'FCustomsEntry', 'cuenCargoNameCn', NULL),
(4, '规格型号', 'FCustomsEntry', 'cuenCargoSpec', NULL),
(4, '数量', 'FCustomsEntry', 'cuenCargoNum', NULL),
(4, '单位', 'FCustomsEntry', 'cuenCargoUnit', NULL),
(4, '原产国', 'FCustomsEntry', 'cuenCountry', NULL),
(4, '目的国', 'FCustomsEntry', 'cuenCountry', NULL),
(4, '单价', 'FCustomsEntry', 'cuenUnitPrice', NULL),
(4, '总价', 'FCustomsEntry', 'cuenTotalPrice', NULL),
(4, '币制', 'FCustomsEntry', 'currCode', NULL),
(4, '征免', 'FCustomsEntry', 'cuenLevyType', NULL),
(4, '备注', 'FCustomsEntry', 'cuenRemarks', NULL)
;

-- 报检单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(5, '报检单位', 'FInspection', 'inspVendorName', NULL),
(5, '报检单位登记号', 'FInspection', 'inspVendorContact', NULL),
(5, '联系人', 'FInspection', 'inspVendorContact', NULL),
(5, '电话', 'FInspection', 'inspVendorTel', NULL),
(5, '报检日期', 'FInspection', 'inspDate', NULL),
(5, '发货人中文', 'FInspection', 'inspShipperCn', NULL),
(5, '发货人英文', 'FInspection', 'inspShipperEn', NULL),
(5, '收货人中文', 'FInspection', 'inspConsigneeCn', NULL),
(5, '收货人英文', 'FInspection', 'inspConsigneeEn', NULL),
(5, '货物名称', 'FInspection', 'inspCargoName', NULL),
(5, 'H.S.编号', 'FInspection', 'inspHsNo', NULL),
(5, '产地', 'FInspection', 'inspMadeIn', NULL),
(5, '数/重量', 'FInspection', 'inspNum', NULL),
(5, '货物总值', 'FInspection', 'inspValue', NULL),
(5, '包装种类及数量', 'FInspection', 'inspPackages', NULL),
(5, '运输工具名称号码', 'FInspection', 'inspConveyance', NULL),
(5, '贸易方式', 'FInspection', 'inspTradeType', NULL),
(5, '货物存放地点', 'FInspection', 'inspCargoAddress', NULL),
(5, '合同号', 'FInspection', 'inspContractNo', NULL),
(5, '信用证号', 'FInspection', 'inspCreditNo', NULL),
(5, '用途', 'FInspection', 'inspUsage', NULL),
(5, '发货日期', 'FInspection', 'inspShippingDate', NULL),
(5, '输往国家', 'FInspection', 'inspTradeCountry', NULL),
(5, '审批号', 'FInspection', 'inspCertificateNo', NULL),
(5, '启运地', 'FInspection', 'inspPol', NULL),
(5, '到达口岸', 'FInspection', 'inspPod', NULL),
(5, '生产单位注册号', 'FInspection', 'inspRegisterNo', NULL),
(5, '集装箱', 'FInspection', 'inspContainerInfo', NULL),
(5, '条款', 'FInspection', 'inspSpecialTerm', NULL),
(5, '标记号码', 'FInspection', 'inspMarks', NULL);

-- 十联单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(7, '发货人', 'FConsign', 'consShipper', NULL),
(7, '收货人', 'FConsign', 'consConsignee', NULL),
(7, '通知人', 'FConsign', 'consNotifyParty', NULL),
(7, '前程运输', 'FConsign', 'consPrecarriage', NULL),
(7, '收货地', 'FConsign', 'consReceiptPlace', NULL),
(7, '船名', 'FConsign', 'vessName', NULL),
(7, '航次', 'FConsign', 'voyaName', NULL),
(7, '装货港', 'FConsign', 'consPolEn', NULL),
(7, '卸货港', 'FConsign', 'consPodEn', NULL),
(7, '交货地', 'FConsign', 'consDeliveryPlace', NULL),
(7, '目的地', 'FConsign', 'consDestination', NULL),
(7, '标记唛码', 'FConsign', 'consCargoMarks', NULL),
(7, '箱型箱量', 'FConsign', 'consContainersInfo', NULL),
(7, '件数包装', 'FConsign', 'consCargoPackages', NULL),
(7, '货物描述', 'FConsign', 'consCargoDesc', NULL),
(7, '毛重', 'FConsign', 'consCargoGrossWeight', NULL),
(7, '尺码', 'FConsign', 'consCargoMeasurement', NULL),
(7, '运费条款', 'FConsign', 'pateId', 'getPateName'),
(7, '运输条款', 'FConsign', 'tranId', 'getTranCode'),
(7, '签发地点', 'FConsign', 'consBlIssuePlace', NULL),
(7, '正本提单份数', 'FConsign', 'consOriginalBlNum', NULL),
(7, '可否转船', 'FConsign', 'consTransFlag', 'Bool'),
(7, '可否分批', 'FConsign', 'consPartialFlag', 'Bool'),
(7, '装期', 'FConsign', 'consLoadDate', NULL),
(7, '开船日期', 'FConsign', 'consEtd', NULL),
(7, '业务号', 'FConsign', 'consNo', NULL),
(7, '船公司', 'FConsign', 'consCarrierName', NULL),
(7, '装运方式', 'FConsign', 'consShipType', NULL),
(7, '备注', 'FConsign', 'consBlRemarks', NULL),
(7, '大写件数', 'FConsign', 'consTotalPackagesInWord', NULL),
(7, '特殊货物信息', 'FConsign', 'consCargoSpecial', NULL),
(7, '第二通知人', 'FConsign', 'consNotifyParty2', NULL),
(7, '操作员', 'FConsign', 'consOperatorId', 'getUserName'),
(7, '提单号', 'FConsign', 'consMblNo', NULL);

-- 装箱单模板
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(8, '冷藏温度', 'FContainer', 'cargTemperature', NULL),
(8, '等级', 'FContainer', 'cargDanagerClass', NULL),
(8, '页号', 'FContainer', 'cargImdgPage', NULL),
(8, '编号', 'FContainer', 'cargUnNo', NULL),
(8, '闪点', 'FContainer', 'cargFlashPoint', NULL),
(8, '船名', 'FContainer', 'contVessel', NULL),
(8, '航次', 'FContainer', 'contVoyage', NULL),
(8, '箱号', 'FContainer', 'contNo', NULL),
(8, '封号', 'FContainer', 'contSealNo', NULL),
(8, '箱型', 'FContainer', 'cotyId', 'getCotyCode'),
(8, '箱类', 'FContainer', 'cotyId', 'getCoclCode'),
(8, 'ISO', 'FContainer', 'cotyId', 'getCotyIsoCode'),
(8, '装港', 'FContainer', 'contPol', NULL),
(8, '卸港', 'FContainer', 'contPod', NULL),
(8, '交货地', 'FContainer', 'contDeliveryPlace', NULL),
(8, '装箱地址', 'FContainer', 'contAddress', NULL),
(8, '备注', 'FContainer', 'contRemarks', NULL),
(8, '提单号', 'FContainerCargo', 'consMblNo', NULL),
(8, '件数', 'FContainerCargo', 'cocaPackageNum', NULL),
(8, '包装', 'FContainerCargo', 'packName', NULL),
(8, '毛重', 'FContainerCargo', 'cocaGrossWeight', NULL),
(8, '尺码', 'FContainerCargo', 'cocaMeasurement', NULL),
(8, '货名', 'FContainerCargo', 'cocaCargoName', NULL),
(8, '唛头', 'FContainerCargo', 'cocaMarks', NULL),
(8, '总件数', 'FContainer', 'contPackageNum', NULL),
(8, '总毛重', 'FContainer', 'contGrossWeight', NULL),
(8, '总体积', 'FContainer', 'contMeasurement', NULL),
(8, '装箱日期', 'FContainer', 'contLoadDate', NULL);

-- 发票模板
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(9, '账单号', 'SInvoice', 'invoNo', NULL),
(9, '税务发票号', 'SInvoice', 'invoTaxNo', NULL),
(9, '银行', 'SInvoice', 'invoBank', NULL),
(9, '账号', 'SInvoice', 'invoAccount', NULL),
(9, '结算单位', 'SInvoice', 'invoTitle', NULL),
(9, '账单日期', 'SInvoice', 'invoDate', NULL),
(9, '船名', 'SInvoice', 'invoVessel', NULL),
(9, '航次', 'SInvoice', 'invoVoyage', NULL),
(9, '业务号', 'SInvoice', 'invoConsNo', NULL),
(9, '开航日期', 'SInvoice', 'invoSailDate', NULL),
(9, '起运港', 'SInvoice', 'invoPol', NULL),
(9, '卸货港', 'SInvoice', 'invoPod', NULL),
(9, '目的港', 'SInvoice', 'invoDeliveryPlace', NULL),
(9, '提单号', 'SInvoice', 'invoBlNo', NULL),
(9, '货物名称', 'SInvoice', 'invoCargoName', NULL),
(9, '件数包装', 'SInvoice', 'invoCargoPackages', NULL),
(9, '重量', 'SInvoice', 'invoCargoGrossWeight', NULL),
(9, '体积', 'SInvoice', 'invoCargoMeasurement', NULL),
(9, '合同号', 'SInvoice', 'invoContractNo', NULL),
(9, '箱型箱量', 'SInvoice', 'invoContainersInfo', NULL),
(9, '币种', 'SInvoice', 'currCode', NULL),
(9, '费用名称', 'SInvoiceEntry', 'charName', NULL),
(9, '费用英文名称', 'SInvoiceEntry', 'charNameEn', NULL),
(9, '数量', 'SInvoiceEntry', 'inenNum', NULL),
(9, '行币种', 'SInvoiceEntry', 'currCode', NULL),
(9, '单价', 'SInvoiceEntry', 'inenUnitPrice', NULL),
(9, '金额', 'SInvoiceEntry', 'inenInvoiceAmount', NULL),
(9, '合计金额大写', 'SInvoice', 'invoAmountCapital', NULL),
(9, '合计金额英文', 'SInvoice', 'invoAmountCapitalEn', NULL),
(9, '合计金额', 'SInvoice', 'invoAmount', NULL),
(9, '付款期限', 'SInvoice', 'invoDueDate', NULL),
(9, '制单人', 'SInvoice', 'invoIssuer', NULL),
(9, '复核人', 'SInvoice', 'invoChecker', NULL),
(9, '操作员', 'SInvoice', 'invoOperator', NULL),
(9, '备注', 'SInvoice', 'invoRemarks', NULL);

-- 单票列表
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(15, '委托号', 'FConsign', 'consNo', NULL),
(15, '委托单位', 'FConsign', 'custName', NULL),
(15, '委托日期', 'FConsign', 'consDate', NULL),
(15, '操作员', 'FConsign', 'consOperatorName',NULL),
(15, '业务员', 'FConsign', 'consSalesRepName',NULL),
(15, '整拼', 'FConsign', 'consShipType', NULL),
(15, '船名', 'FConsign', 'vessName', NULL),
(15, '航次', 'FConsign', 'voyaName', NULL),
(15, 'MBL', 'FConsign', 'consMblNo', NULL),
(15, 'HBL', 'FConsign', 'consHblNo', NULL),
(15, '件数', 'FConsign', 'consTotalPackages', NULL),
(15, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(15, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(15, '箱量', 'FConsign', 'consTotalContainers', NULL),
(15, '20箱量', 'FConsign', 'consContainers20', NULL),
(15, '40箱量', 'FConsign', 'consContainers40', NULL),
(15, '40H箱量', 'FConsign', 'consContainers40h', NULL),
(15, '45H箱量', 'FConsign', 'consContainers45', NULL),
(15, 'ETA', 'FConsign', 'consEta', NULL),
(15, 'ETD', 'FConsign', 'consEtd', NULL),
(15, '启运港', 'FConsign', 'consPolEn', NULL),
(15, '目的港', 'FConsign', 'consPodEn', NULL),
(15, '中转港', 'FConsign', 'consPotEn', NULL),
(15, '承运人', 'FConsign', 'consCarrier', NULL),
(15, '订舱代理', 'FConsign', 'consBookingAgency', NULL),
(15, '运费条款', 'FConsign', 'pateId', NULL),
(15, '主委托号', 'FConsign', 'consMasterNo', NULL),
(15, '报检号', 'FConsign', 'consCustomsDeclearationNo', NULL),
(15, '进出口', 'FConsign', 'consBizClass', 'getBizClass'),
(15, '报检企业', 'FConsign', 'consCompany', NULL),
(15, '报检日期', 'FConsign', 'consCustomsDeclearDate', NULL),
(15, '品名', 'FConsign', 'consCargoNameCn', NULL),
(15, '合同号', 'FConsign', '', NULL),
(15, '申请号', 'FConsign', 'consBookingDeclareNoUs', NULL),
(15, '商检发票号', 'FConsign', 'consTradeContractNo', NULL),
(15, '我司发票号', 'FConsign', 'consMasterNo', NULL),
(15, '应收合计', 'FConsign', 'sumR', NULL),
(15, '贸易方式', 'FConsign', 'attr1', NULL),
(15, '我司发票号','FConsign', 'attr2',NULL),
(15, '手册号', 'FConsign', 'consManualNo', NULL),
(15, '产地证号', 'FConsign', 'consCertNo', NULL),
(15, '报关类型', 'FConsign', 'consCertNo', NULL),
(15, '报关日期', 'FConsign', 'consCustomsDeclearDate', NULL),
(15, '报关单号', 'FConsign', 'consCustomsDeclearationNo', NULL),
(15, '备注', 'FConsign', 'consRemarks', NULL);

-- 单票审核
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(16, '委托号', 'FConsign', 'consNo', NULL),
(16, '委托单位', 'FConsign', 'custName', NULL),
(16, '委托日期', 'FConsign', 'consDate', NULL),
(16, '业务员', 'FConsign', 'consSalesRepName', NULL),
(16, '操作员', 'FConsign', 'consOperatorName', NULL),
(16, '整拼', 'FConsign', 'consShipType', NULL),
(16, '船名', 'FConsign', 'vessName', NULL),
(16, '航次', 'FConsign', 'voyaName', NULL),
(16, 'MBL', 'FConsign', 'consMblNo', NULL),
(16, 'HBL', 'FConsign', 'consHblNo', NULL),
(16, '件数', 'FConsign', 'consTotalPackages', NULL),
(16, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(16, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(16, '箱量', 'FConsign', 'consTotalContainers', NULL),
(16, '20箱量', 'FConsign', 'consContainers20', NULL),
(16, '40箱量', 'FConsign', 'consContainers40', NULL),
(16, '40H箱量', 'FConsign', 'consContainers40h', NULL),
(16, '45H箱量', 'FConsign', 'consContainers45', NULL),
(16, '开船日期', 'FConsign', 'consSailDate', NULL),
(16, 'ETA', 'FConsign', 'consEta', NULL),
(16, 'ETD', 'FConsign', 'consEtd', NULL),
(16, '启运港', 'FConsign', 'consPolEn', NULL),
(16, '目的港', 'FConsign', 'consPodEn', NULL),
(16, '中转港', 'FConsign', 'consPotEn', NULL),
(16, '承运人', 'FConsign', 'consCarrierName', NULL),
(16, '订舱代理', 'FConsign', 'consBookingAgencyName', NULL),
(16, '运费条款', 'FConsign', 'pateId', NULL),
(16, '主委托号', 'FConsign', 'consMasterNo', NULL),
(16, '备注', 'FConsign', 'consRemarks', NULL),
(16, '应收合计', 'FConsign', 'sumR', NULL),
(16, '应付合计', 'FConsign', 'sumP', NULL),
(16, '毛利', 'FConsign', 'grossProfit', NULL),
(16, '毛利率', 'FConsign', 'grossProfitRate', NULL),
(16, '应收USD', 'FConsign', 'sumRUsd', NULL),
(16, '应收USD已开票', 'FConsign', 'sumRUsdInvoice', NULL),
(16, '应收USD已核销', 'FConsign', 'sumRUsdWriteOff', NULL),
(16, '应收CNY', 'FConsign', 'sumRCny', NULL),
(16, '应收CNY已开票', 'FConsign', 'sumRCnyInvoice', NULL),
(16, '应收CNY已核销', 'FConsign', 'sumRCnyWriteOff', NULL),
(16, '应付USD', 'FConsign', 'sumPUsd', NULL),
(16, '应付USD已开票', 'FConsign', 'sumPUsdInvoice', NULL),
(16, '应付USD已核销', 'FConsign', 'sumPUsdWriteOff', NULL),
(16, '应付CNY', 'FConsign', 'sumPCny', NULL),
(16, '应付CNY已开票', 'FConsign', 'sumPCnyInvoice', NULL),
(16, '应付CNY已核销', 'FConsign', 'sumPCnyWriteOff', NULL);

-- 对账单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(17, '对账单位', 'SBill', 'custName', NULL),
(17, '对账单号', 'SBill', 'billNo', NULL),
(17, '制单日期', 'SBill', 'billDate', NULL),
(17, '美元合计', 'SBill', 'billAmountUsd', NULL),
(17, '人民币合计', 'SBill', 'billAmountCny', NULL),
(17, '本币合计', 'SBill', 'billAmount', NULL),
(17, '制单人', 'SBill', 'billIssuer', NULL),
(17, '备注', 'SBill', 'billRemarks', NULL),
(17, 'MBL', 'SBillItem', 'consMblNo', NULL),
(17, 'HBL', 'SBillItem', 'consHblNo', NULL),
(17, '船名', 'SBillItem', 'consVessel', NULL),
(17, '航次', 'SBillItem', 'consVoyage', NULL),
(17, '业务号', 'SBillItem', 'consNo', NULL),
(17, '结算单位', 'SBillItem', 'custName', NULL),
(17, '费用名称', 'SBillItem', 'charName', NULL),
(17, '数量', 'SBillItem', 'expeNum', NULL),
(17, '单位', 'SBillItem', 'unitName', NULL),
(17, '币种', 'SBillItem', 'currCode', NULL),
(17, '收付类型', 'SBillItem', 'expeType', NULL),
(17, '支付条款', 'SBillItem', 'expePaymentType', NULL),
(17, '费用日期', 'SBillItem', 'expeDate', NULL),
(17, '单价', 'SBillItem', 'expeUnitPrice', NULL),
(17, '金额', 'SBillItem', 'expeTotalAmount', NULL),
(17, '汇率', 'SBillItem', 'expeExRate', NULL),
(17, '装货港', 'SBillItem', 'consPodEn', NULL),
(17, '卸货港', 'SBillItem', 'consPolEn', NULL),
(17, '品名', 'SBillItem', 'consCargoNameCn', NULL),
(17, '包装', 'SBillItem', 'consPackName', NULL),
(17, '件数', 'SBillItem', 'consTotalPackages', NULL),
(17, '毛重', 'SBillItem', 'consTotalGrossWeight', NULL),
(17, '净重', 'SBillItem', 'consTotalNetWeight', NULL),
(17, '体积', 'SBillItem', 'consTotalMeasurement', NULL),
(17, '箱型箱量', 'SBillItem', 'consContainersInfo', NULL),
(17, '开航日期', 'SBillItem', 'consSailDate', NULL),
(17, '费用备注', 'SBillItem', 'expeRemarks', NULL);

-- 装箱通知单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(18, '客户', 'FConsign', 'custName', NULL),
(18, '客户联系人', 'FConsign', 'custContact', NULL),
(18, '客户编号', 'FConsign', 'consRefNo', NULL),
(18, '船名', 'FConsign', 'vessName', NULL),
(18, '航次', 'FConsign', 'voyaName', NULL),
(18, '船公司', 'FConsign', 'consCarrierName', NULL),
(18, '开航日期', 'FConsign', 'consEtd', NULL),
(18, '截关日期', 'FConsign', 'consExpiryDate', NULL),
(18, '起运港', 'FConsign', 'consPolEn', NULL),
(18, '中转港', 'FConsign', 'consPotEn', NULL),
(18, '卸货港', 'FConsign', 'consPodEn', NULL),
(18, '目的港', 'FConsign', 'consDestination', NULL),
(18, '业务号', 'FConsign', 'consNo', NULL),
(18, '提单号', 'FConsign', 'consMblNo', NULL),
(18, '主单号', 'FConsign', 'consMblNo', NULL),
(18, '分单号', 'FConsign', 'consHblNo', NULL),
(18, '操作员', 'FConsign', 'consOperatorId', 'getUserName'),
(18, '操作员电话', 'FConsign', 'consOperatorId', 'getUserTel'),
(18, '业务员', 'FConsign', 'consSalesRepId', 'getUserName'),
(18, '业务员电话', 'FConsign', 'consSalesRepId', 'getUserTel'),
(18, '进仓编号', 'FConsign', 'consWarehouseNo', NULL),
(18, '装箱编号', 'FConsign', 'consNo', NULL),
(18, '货名', 'FConsign', 'consCargoNameCn', NULL),
(18, '中文品名', 'FConsign', 'consCargoNameCn', NULL),
(18, '英文品名', 'FConsign', 'consCargoNameEn', NULL),
(18, '件数', 'FConsign', 'consTotalPackages', NULL),
(18, '包装', 'FConsign', 'packName', NULL),
(18, '箱型箱量', 'FConsign', 'consContainersInfo', NULL),
(18, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(18, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(18, '唛头', 'FConsign', 'consCargoMarks', NULL),
(18, '装货日期', 'FConsign', 'consTrackLoadDate', NULL),
(18, '装货时间', 'FConsign', 'consTrackLoadTime', NULL),
(18, '装货地址', 'FConsign', 'consTrackLoadAddress', NULL),
(18, '装货工厂', 'FConsign', 'consLoadFactory', NULL),
(18, '装货要求', 'FConsign', 'consTrackRemarks', NULL),
(18, '仓库', 'FConsign', 'consWarehouseName', NULL),
(18, '装箱日期', 'FConsign', 'consContainerLoadDate', NULL),
(18, '进仓日期', 'FConsign', 'consContainerLoadDate', NULL),
(18, '进仓时间', 'FConsign', 'consContainerLoadTime', NULL),
(18, '装箱要求', 'FConsign', 'consWarehouseRemarks', NULL),
(18, '车队', 'FConsign', 'consTrackVendorName', NULL),
(18, '车队联系人', 'FConsign', 'consTrackContact', NULL),
(18, '车队联系电话', 'FConsign', 'consTrackTel', NULL),
(18, '装货联系人', 'FConsign', 'consLoadContact', NULL),
(18, '装货联系电话', 'FConsign', 'consLoadTel', NULL),
(18, '装箱联系人', 'FConsign', 'consWarehouseContact', NULL),
(18, '装箱联系电话', 'FConsign', 'consWarehouseTel', NULL),
(18, '仓库联系人', 'FConsign', 'consWarehouseContact', NULL),
(18, '仓库联系电话', 'FConsign', 'consWarehouseTel', NULL),
(18, '仓库地址', 'FConsign', 'consWarehouseAddress', NULL),
(18, '装箱地址', 'FConsign', 'consWarehouseAddress', NULL),
(18, '内装要求', 'FConsign', 'consWarehouseRemarks', NULL);

-- 订舱确认书
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(19, '委托日期', 'FConsign', 'consDate', NULL),
(19, '委托单位', 'FConsign', 'custName', NULL),
(19, '客户业务号', 'FConsign', 'consRefNo', NULL),
(19, '承运人', 'FConsign', 'consCarrierName', NULL),
(19, '船名', 'FConsign', 'vessName', NULL),
(19, '航次', 'FConsign', 'voyaName', NULL),
(19, '提单号', 'FConsign', 'consMblNo', NULL),
(19, '目的港', 'FConsign', 'consPodEn', NULL),
(19, '箱型箱量', 'FConsign', 'consContainersInfo', NULL),
(19, '件数', 'FConsign', 'consTotalPackages', NULL),
(19, '包装', 'FConsign', 'packId', NULL),
(19, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(19, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(19, '费目', 'SExpense', 'charName', NULL),
(19, '单价', 'SExpense', 'expeUnitPrice', NULL),
(19, '计费单位', 'SExpense', 'unitName', NULL),
(19, '数量', 'SExpense', 'expeNum', NULL),
(19, '总价', 'SExpense', 'expeTotalAmount', NULL),
(19, '币种', 'SExpense', 'currCode', NULL),
(19, '业务号', 'FConsign', 'consNo', NULL),
(19, '操作员', 'FConsign', 'consOperatorName', NULL),
(19, '操作员电话', 'FConsign', 'consOperatorId', 'getUserTel'),
(19, '订舱代理', 'FConsign', 'consBookingAgencyName', NULL),
(19, '船期', 'FConsign', 'consLoadDate', NULL);

-- 代运联系单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(20, '委托日期', 'FTrans', 'tranDate', NULL),
(20, '业务号', 'FTrans', 'consNo', NULL),
(20, '车队', 'FTrans', 'tranVendorName', NULL),
(20, '代运单号', 'FTrans', 'tranNo', NULL),
(20, '船名', 'FTrans', 'tranVessel', NULL),
(20, '航次', 'FTrans', 'tranVoyage', NULL),
(20, 'MBLNO', 'FTrans', 'consMblNo', NULL),
(20, 'HBLNO', 'FTrans', 'consHblNo', NULL),
(20, '订舱号', 'FTrans', 'consSoNo', NULL),
(20, '装货港', 'FTrans', 'tranPol', NULL),
(20, '卸货港', 'FTrans', 'tranPod', NULL),
(20, '截关日期', 'FTrans', 'tranExpiryDate', NULL),
(20, '装货日期', 'FTrans', 'tranStartDate', NULL),
(20, '装货联系人', 'FTrans', 'tranLoadContact', NULL),
(20, '装货联系电话', 'FTrans', 'tranLoadTel', NULL),
(20, '装货地点', 'FTrans', 'tranLoadFactory', NULL),
(20, '装货地址', 'FTrans', 'tranLoadAddress', NULL),
(20, '送货联系人', 'FTrans', 'tranLoadContact', NULL),
(20, '送货联系电话', 'FTrans', 'tranLoadTel', NULL),
(20, '送货地点', 'FTrans', 'tranLoadFactory', NULL),
(20, '送货日期', 'FTrans', 'tranDeliveryDate', NULL),
(20, '送货地址', 'FTrans', 'tranLoadAddress', NULL),
(20, '收货地址', 'FTrans', 'tranDeliveryAddress', NULL),
(20, '箱公司', 'FTrans', 'tranContainerCompanyName', NULL),

(20, '提箱堆场', 'FTrans', 'tranCyDraw', NULL),
(20, '还箱堆场', 'FTrans', 'tranCyBack', NULL),
(20, '提箱日期', 'FTrans', 'tranDrawDate', NULL),
(20, '还箱日期', 'FTrans', 'tranBackDate', NULL),
(20, '箱型箱量', 'FTrans', 'tranContainerInfo', NULL),
(20, '件数', 'FTrans', 'tranTotalPackages', NULL),
(20, '毛重', 'FTrans', 'tranTotalGrossWeight', NULL),
(20, '体积', 'FTrans', 'tranTotalMeasurement', NULL),
(20, '报关公司', 'FTrans', 'tranCustomsBrokerName', NULL),
(20, '报关公司联系人', 'FTrans', 'tranCustomsContact', NULL),
(20, '报关公司电话', 'FTrans', 'tranCustomsTel', NULL),
(20, '报关公司地址', 'FTrans', 'tranCustomsAddress', NULL),
(20, '备注', 'FTrans', 'tranRemarks', NULL),
(20, '包装', 'FTrans', 'packName', NULL),
(20, 'MBL/NO', 'FTransCargo', 'consMblNo', NULL),
(20, '货物品名', 'FTransCargo', 'trcaCargoName', NULL),
(20, '货物件数', 'FTransCargo', 'trcaPackageNum', NULL),
(20, '货物毛重', 'FTransCargo', 'trcaGrossWeight', NULL),
(20, '货物体积', 'FTransCargo', 'trcaMeasurement', NULL),
(20, '货物备注', 'FTransCargo', 'trcaRemarks', NULL);

-- 仓储联系单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(21, '联系日期', 'FWarehouse', 'wareDate', NULL),
(21, '业务号', 'FWarehouse', 'consNo', NULL),
(21, '仓库', 'FWarehouse', 'wareVendorName', NULL),
(21, '联系单号', 'FWarehouse', 'wareNo', NULL),
(21, '联系目的', 'FWarehouse', 'wareType', NULL),
(21, '预约日期', 'FWarehouse', 'wareBookDate', NULL),
(21, '客户联系人', 'FWarehouse', 'wareCustomerContact', NULL),
(21, '客户电话', 'FWarehouse', 'wareCustomerTel', NULL),
(21, '客户传真', 'FWarehouse', 'wareCustomerFax', NULL),
(21, '船名', 'FWarehouse', 'wareVessel', NULL),
(21, '航次', 'FWarehouse', 'wareVoyage', NULL),
(21, '提单号', 'FWarehouse', 'wareMblNo', NULL),
(21, '运输公司', 'FWarehouse', 'wareTransVendorName', NULL),
(21, '车牌号', 'FWarehouse', 'wareTrackNo', NULL),
(21, '集装箱号', 'FWarehouse', 'wareContainerNo', NULL),
(21, '件数', 'FWarehouse', 'wareTotalPackages', NULL),
(21, '包装', 'FWarehouse', 'packName', NULL),
(21, '毛重', 'FWarehouse', 'wareTotalGrossWeight', NULL),
(21, '体积', 'FWarehouse', 'wareTotalMeasurement', NULL),
(21, '备注', 'FWarehouse', 'wareRemarks', NULL),
(21, '我司联系人', 'FWarehouse', 'wareOperator', NULL),
(21, '我司电话', 'FWarehouse', 'wareOperatorTel', NULL),
(21, '我司传真', 'FWarehouse', 'wareOperatorFax', NULL);

-- 电放保函
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(22, '船公司中文名', 'FConsign', 'consCarrierName', NULL),
(22, '船公司英文名', 'FConsign', 'consCarrier', NULL),
(22, '起运港', 'FConsign', 'consPolEn', NULL),
(22, '目的港', 'FConsign', 'consPodEn', NULL),
(22, '船名', 'FConsign', 'vessName', NULL),
(22, '航次', 'FConsign', 'voyaName', NULL),
(22, '中转港', 'FConsign', 'consPotEn', NULL),
(22, '提单号', 'FConsign', 'consMblNo', NULL),
(22, '发货人', 'FConsign', 'consShipper', NULL),
(22, '收货人', 'FConsign', 'consConsignee', 'getFirstLine'),
(22, '承运人', 'FConsign', 'consCarrierName', NULL),
(22, '件数', 'FConsign', 'consTotalPackages', NULL),
(22, '包装', 'FConsign', 'packName', NULL),
(22, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(22, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(22, '业务号', 'FConsign', 'consNo', NULL),
(22, '起运日期', 'FConsign', 'consSailDate', NULL),
(22, '操作员', 'FConsign', 'consOperatorId', 'getUserName');

-- SEAWAYBILL保函
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(23, '船公司', 'FConsign', 'consCarrierName', NULL),
(23, '船名', 'FConsign', 'vessName', NULL),
(23, '航次', 'FConsign', 'voyaName', NULL),
(23, '提单号', 'FConsign', 'consMblNo', NULL);

-- 分拨申请
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(24, '船名', 'FConsign', 'vessName', NULL),
(24, '航次', 'FConsign', 'voyaName', NULL),
(24, 'MBL', 'FConsign', 'consMblNo', NULL),
(24, '箱号', 'FConsign', 'consContainerNo', NULL),
(24, '港区', 'FConsign', 'consHarbour', NULL),
(24, '委托公司', 'FConsign', 'consSplitContact', NULL),
(24, '委托公司电话', 'FConsign', 'consSplitTel', NULL),
(24, '申请公司', 'FConsign', 'consSplitConsignee', NULL),
(24, '申请公司电话', 'FConsign', 'consSplitConsigneeTel', NULL),
(24, '船号', 'FConsign', 'consShipCode', NULL),
(24, '合计箱量', 'FConsign', 'consTotalContainers', NULL),
(24, '合计件数', 'FConsign', 'consTotalPackages', NULL),
(24, '合计重量', 'FConsign', 'consTotalGrossWeight', NULL),
(24, '合计体积', 'FConsign', 'consTotalMeasurement', NULL),
(24, '到港日期', 'FConsign', 'consSailDate', NULL),
(24, 'HBL', 'FDo', 'hblNo', NULL),
(24, '唛头', 'FDo', 'doMarks', NULL),
(24, ' ', 'FDo', 'doCargoName', NULL),
(24, '件数', 'FDo', 'doPackages', NULL),
(24, '重量', 'FDo', 'doGrossWeight', NULL),
(24, '体积', 'FDo', 'doMeasurement', NULL),
(24, '收货单位', 'FDo', 'doConsignee', NULL),
(24, '备注', 'FDo', 'doRemarks', NULL);

-- 进口提货单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(25, '提货单号', 'FDo', 'doNo', NULL),
(25, '收货人', 'FDo', 'doConsignee', NULL),
(25, '货物流向', 'FDo', 'doCargoDirection', NULL),
(25, '船名', 'FDo', 'doVessel', NULL),
(25, '航次', 'FDo', 'doVoyage', NULL),
(25, '提单号', 'FDo', 'hblNo', NULL),
(25, '启运港', 'FDo', 'doPort', NULL),
(25, '靠港时间', 'FDo', 'doArriveDate', NULL),
(25, '箱号', 'FDo', 'doContainerNo', NULL),
(25, '唛头', 'FDo', 'doMarks', NULL),
(25, '库位', 'FDo', 'doWarehouseAddress', NULL),
(25, '进库日期', 'FDo', 'doInDate', NULL),
(25, '出库日期', 'FDo', 'doOutDate', NULL),
(25, '货名', 'FDo', 'doCargoName', NULL),
(25, '件数', 'FDo', 'doPackages', NULL),
(25, '包装', 'FDo', 'packName', NULL),
(25, '重量', 'FDo', 'doGrossWeight', NULL),
(25, '体积', 'FDo', 'doMeasurement', NULL),
(25, '备注', 'FDo', 'doRemarks', NULL);

-- 订舱委托书
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(26, '发货人', 'FConsign', 'consShipper', NULL),
(26, '收货人', 'FConsign', 'consConsignee', NULL),
(26, '通知人', 'FConsign', 'consNotifyParty', NULL),
(26, '前程运输', 'FConsign', 'consPrecarriage', NULL),
(26, '收货地点', 'FConsign', 'consReceiptPlace', NULL),
(26, '船名', 'FConsign', 'vessName', NULL),
(26, '航次', 'FConsign', 'voyaName', NULL),
(26, '装货港', 'FConsign', 'consPolEn', NULL),
(26, '卸货港', 'FConsign', 'consPodEn', NULL),
(26, '交货地点', 'FConsign', 'consDeliveryPlace', NULL),
(26, '目的地', 'FConsign', 'consDestination', NULL),
(26, '标记唛码', 'FConsign', 'consCargoMarks', NULL),
(26, '件数包装', 'FConsign', 'consCargoPackages', NULL),
(26, '货物描述', 'FConsign', 'consCargoDesc', NULL),
(26, '货物中文名称', 'FConsign', 'consCargoDesc', NULL),
(26, '货物英文名称', 'FConsign', 'consCargoDesc', NULL),
(26, '毛重', 'FConsign', 'consCargoGrossWeight', NULL),
(26, '件数', 'FConsign', 'consTotalPackages', NULL),
(26, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(26, '包装', 'FConsign', 'packName', NULL),
(26, '运输条款', 'FConsign', 'tranId', 'getTranCode'),
(26, '尺码', 'FConsign', 'consCargoMeasurement', NULL),
(26, '运费条款', 'FConsign', 'pateName', NULL),
(26, '运输方式', 'FConsign', 'tranCode', NULL),
(26, '英文件数', 'FConsign', 'consTotalPackagesInWord', NULL),
(26, '签发地点', 'FConsign', 'consBlIssuePlace', NULL),
(26, '正本份数', 'FConsign', 'consOriginalBlNum', NULL),
(26, '可否转船', 'FConsign', 'consTransFlag', 'Bool'),
(26, '可否分批', 'FConsign', 'consPartialFlag', 'Bool'),
(26, '装期', 'FConsign', 'consLoadDate', NULL),
(26, '备注', 'FConsign', 'consRemarks', NULL),
(26, '特约事项', 'FConsign', 'consServiceSpec', NULL),
(26, '合计大写', 'FConsign', 'consTotalPackagesInWord', NULL),
(26, '特殊货物信息', 'FConsign', 'consCargoSpecial', NULL),
(26, '第二通知人', 'FConsign', 'consNotifyParty2', NULL),
(26, '操作员', 'FConsign', 'consOperatorName', NULL),
(26, '操作员电话', 'FConsign', 'consOperatorId', 'getUserTel'),
(26, '业务号', 'FConsign', 'consNo', NULL),
(26, '承运人', 'FConsign', 'consCarrierName', NULL),
(26, '订舱代理', 'FConsign', 'consBookingAgencyName', NULL),
(26, '订舱代理联系人', 'FConsign', 'consBookingAgencyContact', NULL),
(26, '订舱代理电话', 'FConsign', 'consBookingAgencyTel', NULL),
(26, '开航日期', 'FConsign', 'consEtd', NULL),
(26, '单票号', 'FConsign', 'consNo', NULL),
(26, '合同号', 'FConsign', '', NULL),
(26, '提单号', 'FConsign', 'consMblNo', NULL),
(26, '提单备注', 'FConsign', 'consBlRemarks', NULL),
(26, '箱型箱量', 'FConsign', 'consContainersInfo', NULL);

-- 进口到货通知
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(27, '客户名称', 'FConsign', 'custName', NULL),
(27, '客户联系人', 'FConsign', 'custContact', NULL),
(27, '船名', 'FConsign', 'vessName', NULL),
(27, '航次', 'FConsign', 'voyaName', NULL),
(27, '装货港', 'FConsign', 'consPolEn', NULL),
(27, '卸货港', 'FConsign', 'consPodEn', NULL),
(27, '件数包装', 'FConsign', 'consCargoPackages', NULL),
(27, '毛重', 'FConsign', 'consCargoGrossWeight', NULL),
(27, '体积', 'FConsign', 'consCargoMeasurement', NULL),
(27, '抵港日期', 'FConsign', 'consSailDate', 'toLocalDate'),
(27, '提单号', 'FConsign', 'consMblNo', NULL),
(27, '业务号', 'FConsign', 'consNo', NULL),
(27, '品名', 'FConsign', 'consCargoNameEn', NULL);

-- 船期表
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(28, '调度', 'GVoyage', 'voyaDispatcherName', NULL),
(28, '操作', 'GVoyage', 'voyaOperatorName', NULL),
(28, '船名', 'GVoyage', 'vessName', NULL),
(28, '中文船名', 'GVoyage', 'vessNameCn', NULL),
(28, '航次', 'GVoyage', 'voyaName', NULL),
(28, '承运人', 'GVoyage', 'voyaCarrierName', NULL),
(28, '港区', 'GVoyage', 'voyaHarbourName', NULL),
(28, '挂港', 'GVoyage', 'voyaPorts', NULL),
(28, '航线', 'GVoyage', 'shliName', NULL),
(28, 'LAY', 'GVoyage', 'voyaShipDateF', NULL),
(28, 'CAN', 'GVoyage', 'voyaShipDateT', NULL),
(28, '预计到港日期', 'GVoyage', 'voyaEta', NULL),
(28, '预计到港时间', 'GVoyage', 'voyaEtaT', NULL),
(28, '实际到港日期', 'GVoyage', 'voyaBerthingDate', NULL),
(28, '实际到港时间', 'GVoyage', 'voyaBerthingDateT', NULL),
(28, '预计开船日期', 'GVoyage', 'voyaEtd', NULL),
(28, '预计开船时间', 'GVoyage', 'voyaEtdT', NULL),
(28, '实际开船日期', 'GVoyage', 'voyaSailDate', NULL),
(28, '实际开船时间', 'GVoyage', 'voyaSailDateT', NULL),
(28, '船公司航线', 'GVoyage', 'voyaCarrierLine', NULL),
(28, '装船日期（到）', 'GVoyage', 'voyaLoadDateF', NULL),
(28, '装船日期（到）', 'GVoyage', 'voyaLoadDateT', NULL),
(28, '已配重量', 'GVoyage', 'voyaShippedQuantity', NULL),
(28, '实配重量', 'GVoyage', 'voyaFactQuantity', NULL);

-- 整船舱单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(29, '船名', 'GVoyage', 'vessName', NULL),
(29, '航次', 'GVoyage', 'voyaName', NULL),
(29, '承运人', 'GVoyage', 'voyaCarrierName', NULL),
(29, '提单号', 'FContainer', 'consMblNo', NULL),
(29, '箱号', 'FContainer', 'contNo', NULL),
(29, '封号', 'FContainer', 'contSealNo', NULL),
(29, '目的港', 'FContainer', 'contPodEn', NULL),
(29, '毛重', 'FContainer', 'contGrossWeight', NULL),
(29, '体积', 'FContainer', 'contMeasurement', NULL);

-- 单证清单输出模板
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(30, '订舱客户', 'FDoc', 'custName', NULL),
(30, '货主', 'FDoc', 'consCargoOwnerName', NULL),
(30, '船名', 'FDoc', 'vessName', NULL),
(30, '航次', 'FDoc', 'voyaName', NULL),
(30, '提单号', 'FDoc', 'consMblNo', NULL),
(30, '开航日期', 'FDoc', 'consSailDate', NULL),
(30, '业务员', 'FDoc', 'consSalesRepName', NULL),
(30, '操作员', 'FDoc', 'consOperatorName', NULL),
(30, '业务号', 'FDoc', 'consNo', NULL),
(30, '单证号', 'FDoc', 'fdocNo', NULL),
(30, '单证名称', 'FDoc', 'dotyName', NULL),
(30, '报关行', 'FDoc', 'fdocSendSigner', NULL),
(30, '报送日期', 'FDoc', 'fdocSendDate', NULL),
(30, '退回日期', 'FDoc', 'fdocReturnDate', NULL),
(30, '退还日期', 'FDoc', 'fdocBackDate', NULL);

-- 核销单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(31, '结算单位', 'SVoucher', 'custName', NULL),
(31, '收款单号', 'SVoucher', 'voucNo', NULL),
(31, '核销号', 'SVoucher', 'voucWriteOffNo', NULL),
(31, '付款币别', 'SVoucher', 'currCode', NULL),
(31, '金额', 'SVoucher', 'voucAmount', NULL),
(31, '核销金额', 'SVoucher', 'voucWriteOffAmount', NULL),
(31, '订舱客户', 'SVoucherItem', 'custName', NULL),
(31, '船名', 'SVoucherItem', 'consVessel', NULL),
(31, '航次', 'SVoucherItem', 'consVoyage', NULL),
(31, '提单号', 'SVoucherItem', 'consMblNo', NULL),
(31, '开航日期', 'SVoucherItem', 'consSailDate', NULL),
(31, '业务号', 'SVoucherItem', 'consNo', NULL),
(31, '账单号', 'SVoucherItem', 'invoNo', NULL),
(31, '税务发票号', 'SVoucherItem', 'invoTaxNo', NULL),
(31, '费用类别', 'SVoucherItem', 'charName', NULL),
(31, '币别', 'SVoucherItem', 'currCode', NULL),
(31, '开票金额', 'SVoucherItem', 'initInvoiceAmountOri', NULL),
(31, '付款金额', 'SVoucherItem', 'voitAmountOriW', NULL),
(31, '汇率', 'SVoucherItem', 'initExRate', NULL),
(31, '折算金额', 'SVoucherItem', 'voitAmountVoucW', NULL);

-- 运价表
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(32, '价格号', 'CPriceRecord', 'prshId', NULL),
(32, '生效日期', 'CPriceRecord', 'prshStartDate', NULL),
(32, '失效日期', 'CPriceRecord', 'prshEndDate', NULL),
(32, '船公司', 'CPriceRecord', 'prshCarrierName', NULL),
(32, '订舱代理', 'CPriceRecord', 'prshVendorName', NULL),
(32, '起运港', 'CPriceRecord', 'prshPolEn', NULL),
(32, '目的港', 'CPriceRecord', 'prliPodEn', NULL),
(32, '船名', 'CPriceRecord', 'vessName', NULL),
(32, '航次', 'CPriceRecord', 'voyaName', NULL),
(32, '中转港', 'CPriceRecord', 'prliPodEn', NULL),
(32, '船期', 'CPriceRecord', 'prliShipDate', NULL),
(32, '运输条款', 'CPriceRecord', 'tranName', NULL),
(32, '运费条款', 'CPriceRecord', 'pateName', NULL),
(32, '货物种类', 'CPriceRecord', 'caclName', NULL),
(32, '费用名称', 'CPriceRecord', 'charName', NULL),
(32, '币种', 'CPriceRecord', 'currCode', NULL),
(32, '佣金', 'CPriceRecord', 'prreCommissionRate', NULL),
(32, '20', 'CPriceRecord', 'prrePriceP20', NULL),
(32, '40', 'CPriceRecord', 'prrePriceP40', NULL),
(32, '40H', 'CPriceRecord', 'prrePriceP40h', NULL),
(32, 'CBM', 'CPriceRecord', 'prrePricePCbm', NULL),
(32, 'KGS', 'CPriceRecord', 'prrePricePKgs', NULL),
(32, 'TON', 'CPriceRecord', 'prrePricePTon', NULL);

-- 配载清单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(33, '船名', 'GVoyage', 'vessName', NULL),
(33, '航次', 'GVoyage', 'voyaName', NULL),
(33, '船公司', 'GVoyage', 'voyaCarrierName', NULL),
(33, '船期从', 'GVoyage', 'voyaShipDateF', NULL),
(33, '船期到', 'GVoyage', 'voyaShipDateT', NULL),
(33, '港区', 'GVoyage', 'voyaLoadArea', NULL),
(33, '航线', 'GVoyage', 'shliName', NULL),
(33, '可配货量', 'GVoyage', 'voyaQuantity', NULL),
(33, '已配货量', 'GVoyage', 'voyaShippedQuantity', NULL),
(33, '委托单位', 'FLoadingList', 'custName', NULL),
(33, '合同号', 'FLoadingList', 'fconContractNo', NULL),
(33, '配载货量', 'FLoadingList', 'loliShippedQuantity', NULL),
(33, '预计发货日期', 'FLoadingList', 'fconLoadDate', NULL),
(33, '预配船期从', 'FLoadingList', 'fconShipDateF', NULL),
(33, '预配船期到', 'FLoadingList', 'fconShipDateT', NULL),
(33, '装货港', 'FLoadingList', 'fconPolEn', NULL),
(33, '卸货港', 'FLoadingList', 'fconPodEn', NULL),
(33, '货物描述', 'FLoadingList', 'fconCargoDesc', NULL),
(33, '备注', 'FLoadingList', 'loliRemarks', NULL);

-- 费用确认单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(34, '船名', 'FConsign', 'vessName', NULL),
(34, '航次', 'FConsign', 'voyaName', NULL),
(34, '起运港', 'FConsign', 'consPolEn', NULL),
(34, '卸货港', 'FConsign', 'consPodEn', NULL),
(34, '中转港', 'FConsign', 'consPotEn', NULL),
(34, '件数包装', 'FConsign', 'consCargoPackages', NULL),
(34, '英文品名', 'FConsign', 'consCargoNameEn', NULL),
(34, '中文品名', 'FConsign', 'consCargoNameCn', NULL),
(34, '运费条款', 'FConsign', 'pateName', NULL),
(34, '报关方式', 'FConsign', 'consCudeType', 'getCudeType'),
(34, '装箱地点', 'FConsign', 'consWarehouseAddress', NULL),
(34, '件数', 'FConsign', 'consTotalPackages', NULL),
(34, '包装', 'FConsign', 'packName', NULL),
(34, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(34, '尺码', 'FConsign', 'consTotalMeasurement', NULL),
(34, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(34, 'MBL', 'FConsign', 'consMblNo', NULL),
(34, 'HBL', 'FConsign', 'consHblNo', NULL),
(34, '业务号', 'FConsign', 'consNo', NULL),
(34, '委托日期', 'FConsign', 'consDate', 'toLocalDate'),
(34, '订舱客户', 'FConsign', 'custName', NULL),
(34, '联系人', 'FConsign', 'custContact', NULL),
(34, '客户联系人', 'FConsign', 'custTel', NULL),
(34, '客户传真', 'FConsign', 'custFax', NULL),
(34, '箱型箱量', 'FConsign', 'consContainersInfo', NULL),
(34, '开航日期', 'FConsign', 'consSailDate', NULL),
(34, '人民币合计', 'FConsign', 'sumRCny', NULL),
(34, '人民币合计大写', 'FConsign', 'sumRCny', 'getAmountCap'),
(34, '美元合计', 'FConsign', 'sumRUsd', NULL),
(34, '美元合计大写', 'FConsign', 'sumRUsd', 'getAmountCap'),
(34, '应付人民币合计', 'FConsign', 'sumPCny', NULL),
(34, '应付美元合计', 'FConsign', 'sumPUsd', NULL),
(34, '应付人民币合计大写', 'FConsign', 'sumPCny', 'getAmountCap'),
(34, '应付美元合计大写', 'FConsign', 'sumPUsd',  'getAmountCap'),
(34, '发票抬头', 'FConsign', 'custName', NULL),
(34, '结算单位', 'FConsign', 'settlementObject', NULL),
(34, '币种', 'SExpense', 'currCode', NULL),
(34, '费用名称', 'SExpense', 'charName', NULL),
(34, '数量', 'SExpense', 'expeNum', NULL),
(34, '单价', 'SExpense', 'expeUnitPrice', NULL),
(34, '金额', 'SExpense', 'expeTotalAmount', NULL),
(34, '备注', 'SExpense', 'expeRemarks', NULL);

-- 发货清单模板
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(35, '车牌号', 'FPackingList', 'paliTrackNo', NULL),
(35, '行号', 'FPackingList', 'paliLineNo', NULL),
(35, '捆数', 'FPackingList', 'paliPackages', NULL),
(35, '重量', 'FPackingList', 'paliGrossWeight', NULL),
(35, '提单号', 'FPackingList', 'consMblNo', NULL),
(35, '标牌号', 'FPackingList', 'paliLabel', NULL),
(35, '规格型号', 'FPackingList', 'paliSpec', NULL),
(35, '体积', 'FPackingList', 'paliCbm', NULL),
(35, '核算体积', 'FPackingList', 'paliCbmC', NULL),
(35, '支数', 'FPackingList', 'paliPieces', NULL),
(35, '长度', 'FPackingList', 'paliLength', NULL),
(35, '总长度', 'FPackingList', 'paliTotalLength', NULL),
(35, '装车日期', 'FPackingList', 'paliLoadDate', NULL);

-- 账单清单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(36, '账单号', 'SInvoice', 'invoNo', NULL),
(36, '税务发票号', 'SInvoice', 'invoTaxNo', NULL),
(36, '银行', 'SInvoice', 'invoBank', NULL),
(36, '账号', 'SInvoice', 'invoAccount', NULL),
(36, '结算单位', 'SInvoice', 'invoTitle', NULL),
(36, '客户代码', 'SInvoice', 'custSname', NULL),
(36, '账单日期', 'SInvoice', 'invoDate', NULL),
(36, '船名', 'SInvoice', 'invoVessel', NULL),
(36, '航次', 'SInvoice', 'invoVoyage', NULL),
(36, '业务号', 'SInvoice', 'invoConsNo', NULL),
(36, '开航日期', 'SInvoice', 'invoSailDate', NULL),
(36, '起运港', 'SInvoice', 'invoPol', NULL),
(36, '卸货港', 'SInvoice', 'invoPod', NULL),
(36, '目的港', 'SInvoice', 'invoDeliveryPlace', NULL),
(36, '提单号', 'SInvoice', 'invoBlNo', NULL),
(36, '货物名称', 'SInvoice', 'invoCargoName', NULL),
(36, '件数包装', 'SInvoice', 'invoCargoPackages', NULL),
(36, '重量', 'SInvoice', 'invoCargoGrossWeight', NULL),
(36, '体积', 'SInvoice', 'invoCargoMeasurement', NULL),
(36, '箱型箱量', 'SInvoice', 'invoContainersInfo', NULL),
(36, '币种', 'SInvoice', 'currCode', NULL),
(36, '账单金额', 'SInvoice', 'invoAmount', NULL),
(36, '付款期限', 'SInvoice', 'invoDueDate', NULL),
(36, '发票状态', 'SInvoice', 'invoStatus', 'invoStatus'),
(36, '核销状态', 'SInvoice', 'invoWriteOffStatus', 'writeoffStatus'),
(36, '制单人', 'SInvoice', 'invoIssuer', NULL),
(36, '复核人', 'SInvoice', 'invoChecker', NULL),
(36, '操作员', 'SInvoice', 'invoOperator', NULL);

-- 委托信息
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(37, '委托号', 'FConsign', 'consNo', NULL),
(37, '委托日期', 'FConsign', 'consDate', NULL),
(37, '操作', 'FConsign', 'consOperatorName', NULL),
(37, '船名', 'FConsign', 'vessName', NULL),
(37, '发货人', 'FConsign', 'consCargoOwnerName', NULL),
(37, '租船人', 'FConsign', 'custName', NULL),
(37, '船期从', 'FConsign', 'voyaShipDateF', NULL),
(37, '船期到', 'FConsign', 'voyaShipDateT', NULL),
(37, '预计船期从', 'FConsign', 'fconShipDateF', NULL),
(37, '预计船期到', 'FConsign', 'fconShipDateT', NULL),
(37, '船期', 'FConsign', 'consSailDate', NULL),
(37, '船公司', 'FConsign', 'consCarrierName', NULL),
(37, '船代', 'FConsign', 'consBookingAgencyName', NULL),
(37, '客户计费单位', 'FConsign', 'unitCode', NULL),
(37, '船公司计费单位', 'FConsign', 'unitCodeM', NULL),
(37, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(37, '中文品名', 'FConsign', 'consCargoNameCn', NULL),
(37, '装货港', 'FConsign', 'consPolEn', NULL),
(37, '卸货港', 'FConsign', 'consPodEn', NULL),
(37, '客户条款', 'FConsign', 'tranCode', NULL),
(37, '注意事项', 'FConsign', 'consServiceSpec', NULL),
(37, '备注', 'FConsign', 'consRemarks', NULL),
(37, '货物描述', 'FConsign', 'consCargoDesc', NULL),
(37, '港区', 'FConsign', 'consHarbour', NULL),
(37, '合同号', 'FConsign', '', NULL),
(37, '船公司条款', 'FConsign', 'tranCodeCarrier', NULL);

-- 发货清单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(38, '合同号', 'FPackingList', 'fconContractNo', NULL),
(38, '标牌号', 'FPackingList', 'paliLabel', NULL),
(38, '车皮号', 'FPackingList', 'paliTrackNo', NULL),
(38, '行号', 'FPackingList', 'paliLineNo', NULL),
(38, '规格型号', 'FPackingList', 'paliSpec', NULL),
(38, '件数', 'FPackingList', 'paliPackages', NULL),
(38, '包装种类', 'FPackingList', 'packName', NULL),
(38, '毛重', 'FPackingList', 'paliGrossWeight', NULL),
(38, '发货日期', 'FPackingList', 'paliLoadDate', NULL),
(38, '出货港', 'FPackingList', 'paliHarbourName', NULL),
(38, '到站', 'FPackingList', 'paliStationName', NULL),
(38, '到站方式', 'FPackingList', 'paliTrackType', NULL),
(38, '到达日期', 'FPackingList', 'paliArriveDate', NULL),
(38, '场地位置', 'FPackingList', 'paliLocation', NULL),
(38, '当前站', 'FPackingList', 'paliStationNameNow', NULL),
(38, '当前位置', 'FPackingList', 'paliLocationNow', NULL),
(38, '船名', 'FPackingList', 'vessName', NULL),
(38, '卸货港', 'FPackingList', 'fconPodEn', NULL),
(38, '租船人', 'FPackingList', 'charterName', NULL),
(38, '发货人', 'FPackingList', 'custName', NULL),
(38, '中文品名', 'FPackingList', 'cargNameCn', NULL),
(38, '英文品名', 'FPackingList', 'cargNameEn', NULL),
(38, '中文船名', 'FPackingList', 'vessNameCn', NULL),
(38, '航次', 'FPackingList', 'voyaName', NULL),
(38, '报关类型', 'FPackingList', 'fconCudeType', NULL),
(38, '进港方式', 'FPackingList', 'paliTrackTypeP', NULL),
(38, '提单号', 'FPackingList', 'consMblNo', NULL),
(38, '体积', 'FPackingList', 'paliCbm', NULL),
(38, '核算体积', 'FPackingList', 'paliCbmC', NULL),
(38, '支数', 'FPackingList', 'paliPieces', NULL),
(38, '长度', 'FPackingList', 'paliLength', NULL),
(38, '总长度', 'FPackingList', 'paliTotalLength', NULL),
(38, '长度单位', 'FPackingList', 'unitNameLen', NULL),
(38, '转运次数', 'FPackingList', 'paliTransTimes', NULL),
(38, '是否转运', 'FPackingList', 'paliTransFlag', 'Bool'),
(38, '商检', 'FPackingList', 'fconInspectionFlag', 'Bool'),
(38, '箱单', 'FPackingList', 'fconInvoiceFlag', 'Bool');

-- SGS检验通知
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(39, '客户', 'FConsign', 'custName', NULL),
(39, '客户联系人', 'FConsign', 'custContact', NULL),
(39, '客户编号', 'FConsign', 'consRefNo', NULL),
(39, '船名', 'FConsign', 'vessName', NULL),
(39, '航次', 'FConsign', 'voyaName', NULL),
(39, '船期', 'FConsign', 'consEtd', NULL),
(39, '装箱日期', 'FConsign', 'consTrackLoadDate', NULL),
(39, '提单号', 'FConsign', 'consMblNo', NULL),
(39, '进仓编号', 'FConsign', 'consWarehouseNo', NULL),
(39, '品名', 'FConsign', 'consCargoNameCn', NULL),
(39, '件数', 'FConsign', 'consTotalPackages', NULL),
(39, '包装', 'FConsign', 'packName', NULL),
(39, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(39, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(39, '仓库联系人', 'FConsign', 'consTrackContact', NULL),
(39, '仓库地址', 'FConsign', 'consTrackLoadAddress', NULL),
(39, '备注', 'FConsign', 'consTrackRemarks', NULL);

-- 装船通知
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(40, '客户', 'FConsign', 'custName', NULL),
(40, '客户联系人', 'FConsign', 'custContact', NULL),
(40, '客户编号', 'FConsign', 'consRefNo', NULL),
(40, '船名', 'FConsign', 'vessName', NULL),
(40, '航次', 'FConsign', 'voyaName', NULL),
(40, '船公司', 'FConsign', 'consCarrierName', NULL),
(40, '合同号', 'FConsign', '', NULL),
(40, '开航日期', 'FConsign', 'consEtd', NULL),
(40, '到港日期', 'FConsign', 'consEta', NULL),
(40, '启运港', 'FConsign', 'consPolEn', NULL),
(40, '目的港', 'FConsign', 'consPodEn', NULL),
(40, '提单号', 'FConsign', 'consMblNo', NULL),
(40, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(40, '装船日期', 'FConsign', 'consLoadDate', NULL),
(40, '签单日期', 'FConsign', 'consBlIssueDate', NULL),
(40, '海外代理', 'FConsign', 'consNotifyParty2', NULL);

-- 订舱委托书（货物）
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(41, '发货人', 'FConsign', 'consShipper', NULL),
(41, '收货人', 'FConsign', 'consConsignee', NULL),
(41, '通知人', 'FConsign', 'consNotifyParty', NULL),
(41, '前程运输', 'FConsign', 'consPrecarriage', NULL),
(41, '收货地点', 'FConsign', 'consReceiptPlace', NULL),
(41, '船名', 'FConsign', 'vessName', NULL),
(41, '航次', 'FConsign', 'voyaName', NULL),
(41, '装货港', 'FConsign', 'consPolEn', NULL),
(41, '卸货港', 'FConsign', 'consPodEn', NULL),
(41, '交货地点', 'FConsign', 'consDeliveryPlace', NULL),
(41, '目的地', 'FConsign', 'consDestination', NULL),
(41, '标记唛码', 'FConsign', 'consCargoMarks', NULL),
(41, '件数', 'FConsign', 'consCargoPackages', NULL),
(41, '包装', 'FConsign', 'packName', NULL),
(41, '货物描述', 'FConsign', 'consCargoDesc', NULL),
(41, '毛重', 'FConsign', 'consCargoGrossWeight', NULL),
(41, '尺码', 'FConsign', 'consCargoMeasurement', NULL),
(41, '运费条款', 'FConsign', 'pateName', NULL),
(41, '运输方式', 'FConsign', 'tranId', NULL),
(41, '英文件数', 'FConsign', 'consTotalPackagesInWord', NULL),
(41, '签发地点', 'FConsign', 'consBlIssuePlace', NULL),
(41, '正本份数', 'FConsign', 'consOriginalBlNum', NULL),
(41, '可否转船', 'FConsign', 'consTransFlag', 'Bool'),
(41, '可否分批', 'FConsign', 'consPartialFlag', 'Bool'),
(41, '装期', 'FConsign', 'consLoadDate', NULL),
(41, '备注', 'FConsign', 'consBlRemarks', NULL),
(41, '合计大写', 'FConsign', 'consTotalPackagesInWord', NULL),
(41, '特殊货物信息', 'FConsign', 'consCargoSpecial', NULL),
(41, '第二通知人', 'FConsign', 'consNotifyParty2', NULL),
(41, '操作员', 'FConsign', 'consOperatorName', NULL),
(41, '提单号', 'FConsign', 'consMblNo', NULL);

-- 订舱委托书（提单）
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(42, '发货人', 'FConsign', 'consShipper', NULL),
(42, '收货人', 'FConsign', 'consConsignee', NULL),
(42, '通知人', 'FConsign', 'consNotifyParty', NULL),
(42, '前程运输', 'FConsign', 'consPrecarriage', NULL),
(42, '收货地点', 'FConsign', 'consReceiptPlace', NULL),
(42, '船名', 'FConsign', 'vessName', NULL),
(42, '航次', 'FConsign', 'voyaName', NULL),
(42, '装货港', 'FConsign', 'consPolEn', NULL),
(42, '卸货港', 'FConsign', 'consPodEn', NULL),
(42, '交货地点', 'FConsign', 'consDeliveryPlace', NULL),
(42, '目的地', 'FConsign', 'consDestination', NULL),
(42, '标记唛码', 'FConsign', 'consCargoMarks', NULL),
(42, '件数包装', 'FConsign', 'consCargoPackages', NULL),
(42, '货物描述', 'FConsign', 'consCargoDesc', NULL),
(42, '毛重', 'FConsign', 'consCargoGrossWeight', NULL),
(42, '尺码', 'FConsign', 'consCargoMeasurement', NULL),
(42, '运费条款', 'FConsign', 'pateName', NULL),
(42, '运输方式', 'FConsign', 'tranId', NULL),
(42, '英文件数', 'FConsign', 'consTotalPackagesInWord', NULL),
(42, '签发地点', 'FConsign', 'consBlIssuePlace', NULL),
(42, '正本份数', 'FConsign', 'consOriginalBlNum', NULL),
(42, '可否转船', 'FConsign', 'consTransFlag', 'Bool'),
(42, '可否分批', 'FConsign', 'consPartialFlag', 'Bool'),
(42, '装期', 'FConsign', 'consLoadDate', NULL),
(42, '备注', 'FConsign', 'consBlRemarks', NULL),
(42, '合计大写', 'FConsign', 'consTotalPackagesInWord', NULL),
(42, '特殊货物信息', 'FConsign', 'consCargoSpecial', NULL),
(42, '第二通知人', 'FConsign', 'consNotifyParty2', NULL),
(42, '操作员', 'FConsign', 'consOperatorName', NULL),
(42, '提单号', 'FConsign', 'consMblNo', NULL);

-- 核销单信息
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(43, '核销单号', 'FDoc', 'fdocNo', NULL),
(43, '委托号', 'FDoc', 'consNo', NULL);

-- 导出到站地点
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(44, '合同号', 'FContract', 'fconContractNo', NULL),
(44, '合同重量', 'FContract', 'fconContractQuantity', NULL),
(44, '目的港', 'FContract', 'fconPodEn', NULL),
(44, '到栈', 'GPlace', 'placName', NULL),
(44, '地址', 'GPlace', 'placAddress', NULL),
(44, '到站', 'GPlace', 'placStation', NULL);

-- 业务员超期提示
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(45, '业务员', 'FConsign', 'consSalesRepName', NULL),
(45, '提单号', 'FConsign', 'consMblNo', NULL);

-- 减免税统计表
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(46, '业务号', 'FConsign', 'consNo', NULL),
(46, '委托单位', 'FConsign', 'custName', NULL),
(46, '委托日期', 'FConsign', 'consDate', NULL),
(46, '合同号', 'FConsign', 'consDate', NULL),
(46, '免表号', 'FConsign', 'consFreeTableNo', NULL),
(46, '项目号', 'FConsign', 'consCustomRegNo', NULL),
(46, '经营单位', 'FConsign', 'consCompany', NULL),
(46, '品名', 'FConsign', 'consCargoNameCn', NULL),
(46, '数量', 'FConsign', 'consTotalPackages', NULL),
(46, '金额', 'FConsign', 'consTax', NULL),
(46, '市审结日期', 'FConsign', 'consAuditDate', NULL),
(46, '省审结日期', 'FConsign', 'consAuditDate2', NULL);

-- 加工贸易催核表
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(47, '业务号', 'FConsign', 'consNo', NULL),
(47, '委托单位', 'FConsign', 'custName', NULL),
(47, '委托日期', 'FConsign', 'consDate', NULL),
(47, '结单日期', 'FConsign', 'consCloseDate', NULL),
(47, '合同号', 'FConsign', 'consDate', NULL),
(47, '手册号', 'FConsign', 'consManualNo', NULL),
(47, '手册有效期', 'FConsign', 'consManualExpirationDate', NULL),
(47, '扩展字段1', 'FConsign', 'attr1', NULL),
(47, '扩展字段2', 'FConsign', 'attr2', NULL),
(47, '扩展字段3', 'FConsign', 'attr3', NULL),
(47, '扩展字段4', 'FConsign', 'attr4', NULL),
(47, '经营单位', 'FConsign', 'consCompany', NULL),
(47, '保证金', 'FConsign', 'consCargoNameCn', NULL);

-- 商业发票
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(49, '指运国', 'FCustomsDeclaration', 'cudeDischargeCountry', NULL),
(49, '装货港', 'FCustomsDeclaration', 'cudePolEn', NULL),
(49, '卸货港', 'FCustomsDeclaration', 'cudePodEn', NULL),
(49, '发票号', 'FCustomsDeclaration', 'cudeInvoiceNo', NULL),
(49, '发票日期', 'FCustomsDeclaration', 'cudeInvoiceDate', NULL),
(49, '发货人', 'FCustomsDeclaration', 'cudeShipper', NULL),
(49, '收货人', 'FCustomsDeclaration', 'cudeConsignee', NULL),
(49, '装船期限从', 'FCustomsDeclaration', 'cudeShipDateF', NULL),
(49, '装船期限到', 'FCustomsDeclaration', 'cudeShipDateT', NULL),
(49, '出口口岸', 'FCustomsDeclaration', 'cudePol', NULL),
(49, '英文出口口岸', 'FCustomsDeclaration', 'cudePolEn', NULL),
(49, '指运港', 'FCustomsDeclaration', 'cudePod', NULL),
(49, '英文指运港', 'FCustomsDeclaration', 'cudePodEn', NULL),
(49, '结汇方式', 'FCustomsDeclaration', 'exseCode', NULL),
(49, '成交方式', 'FCustomsDeclaration', 'trteCode', NULL),
(49, '英文结汇方式', 'FCustomsDeclaration', 'exseCodeEn', NULL),
(49, '英文成交方式', 'FCustomsDeclaration', 'trteCodeEn', NULL),
(49, '总价合计', 'FCustomsDeclaration', 'cudeTotalAmount', NULL),
(49, '大写总价合计', 'FCustomsDeclaration', 'cudeTotalAmountCap', NULL),
(49, '大写件数', 'FCustomsDeclaration', 'cudeTotalSay', NULL),
(49, '唛头', 'FCustomsDeclaration', 'cudeMarks', NULL),
(49, '唛头与项号', 'FCustomsEntry', 'cuenNo', NULL),
(49, '英文品名', 'FCustomsEntry', 'cuenCargoNameEn', NULL),
(49, '件数', 'FCustomsEntry', 'cuenPackageNum', NULL),
(49, '包装', 'FCustomsEntry', 'packCode', NULL),
(49, '英文包装', 'FCustomsEntry', 'packCodeEn', NULL),
(49, '货物件数', 'FCustomsEntry', 'cuenCargoNum', NULL),
(49, '货物单位', 'FCustomsEntry', 'cuenCargoUnit', NULL),
(49, '单价', 'FCustomsEntry', 'cuenUnitPrice', NULL),
(49, '总价', 'FCustomsEntry', 'cuenTotalPrice', NULL),
(49, '币种', 'FCustomsEntry', 'currCode', NULL),
(49, '备注', 'FCustomsEntry', 'cuenRemarks', NULL);

-- PACKING LIST
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(50, '装货港', 'FCustomsDeclaration', 'cudePolEn', NULL),
(50, '卸货港', 'FCustomsDeclaration', 'cudePodEn', NULL),
(50, '发票号', 'FCustomsDeclaration', 'cudeInvoiceNo', NULL),
(50, '发票日期', 'FCustomsDeclaration', 'cudeInvoiceDate', NULL),
(50, '发货人', 'FCustomsDeclaration', 'cudeShipper', NULL),
(50, '收货人', 'FCustomsDeclaration', 'cudeConsignee', NULL),
(50, '结汇方式', 'FCustomsDeclaration', 'exseCode', NULL),
(50, '成交方式', 'FCustomsDeclaration', 'trteCode', NULL),
(50, '英文结汇方式', 'FCustomsDeclaration', 'exseCodeEn', NULL),
(50, '英文成交方式', 'FCustomsDeclaration', 'trteCodeEn', NULL),
(50, '件数合计', 'FCustomsDeclaration', 'cudePackageNum', NULL),
(50, '包装合计', 'FCustomsDeclaration', 'packCode', NULL),
(50, '大写件数', 'FCustomsDeclaration', 'cudeTotalSay', NULL),
(50, '唛头与项号', 'FCustomsEntry', 'cuenNo', NULL),
(50, '英文品名', 'FCustomsEntry', 'cuenCargoNameEn', NULL),
(50, '件数', 'FCustomsEntry', 'cuenPackageNum', NULL),
(50, '包装', 'FCustomsEntry', 'packCode', NULL),
(50, '毛重', 'FCustomsEntry', 'cuenCargoGrossWeight', NULL),
(50, '净重', 'FCustomsEntry', 'cuenCargoNetWeight', NULL),
(50, '体积', 'FCustomsEntry', 'cuenCargoMeasurement', NULL),
(51, '备注', 'FCustomsEntry', 'cuenRemarks', NULL);

-- 贸易合同
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(51, '指运国', 'FCustomsDeclaration', 'cudeDischargeCountry', NULL),
(51, '原产国', 'FCustomsDeclaration', 'cudeLoadCountry', NULL),
(51, '装货港', 'FCustomsDeclaration', 'cudePolEn', NULL),
(51, '卸货港', 'FCustomsDeclaration', 'cudePodEn', NULL),
(51, '合同号', 'FCustomsDeclaration', 'cudeContractNo', NULL),
(51, '合同日期', 'FCustomsDeclaration', 'cudeContractDate', NULL),
(51, '发货人', 'FCustomsDeclaration', 'cudeShipper', NULL),
(51, '收货人', 'FCustomsDeclaration', 'cudeConsignee', NULL),
(51, '可分批', 'FCustomsDeclaration', 'cudePartialFlag', 'Allowed'),
(51, '可转运', 'FCustomsDeclaration', 'cudeTransFlag', 'Allowed'),
(51, '装船期限从', 'FCustomsDeclaration', 'cudeShipDateF', NULL),
(51, '装船期限到', 'FCustomsDeclaration', 'cudeShipDateT', NULL),
(51, '出口口岸', 'FCustomsDeclaration', 'cudePol', NULL),
(51, '英文出口口岸', 'FCustomsDeclaration', 'cudePolEn', NULL),
(51, '指运港', 'FCustomsDeclaration', 'cudePod', NULL),
(51, '英文指运港', 'FCustomsDeclaration', 'cudePodEn', NULL),
(51, '结汇方式', 'FCustomsDeclaration', 'exseCode', NULL),
(51, '成交方式', 'FCustomsDeclaration', 'trteCode', NULL),
(51, '英文结汇方式', 'FCustomsDeclaration', 'exseCodeEn', NULL),
(51, '英文成交方式', 'FCustomsDeclaration', 'trteCodeEn', NULL),
(51, '总价合计', 'FCustomsDeclaration', 'cudeTotalAmount', NULL),
(51, '大写总价合计', 'FCustomsDeclaration', 'cudeTotalAmountCap', NULL),
(51, '大写件数', 'FCustomsDeclaration', 'cudeTotalSay', NULL),
(51, '唛头', 'FCustomsDeclaration', 'cudeMarks', NULL),
(51, '唛头与项号', 'FCustomsEntry', 'cuenNo', NULL),
(51, '英文品名', 'FCustomsEntry', 'cuenCargoNameEn', NULL),
(51, '件数', 'FCustomsEntry', 'cuenPackageNum', NULL),
(51, '包装', 'FCustomsEntry', 'packCode', NULL),
(51, '英文包装', 'FCustomsEntry', 'packCodeEn', NULL),
(51, '货物件数', 'FCustomsEntry', 'cuenCargoNum', NULL),
(51, '货物单位', 'FCustomsEntry', 'cuenCargoUnit', NULL),
(51, '单价', 'FCustomsEntry', 'cuenUnitPrice', NULL),
(51, '总价', 'FCustomsEntry', 'cuenTotalPrice', NULL),
(51, '币种', 'FCustomsEntry', 'currCode', NULL),
(51, '备注', 'FCustomsEntry', 'cuenRemarks', NULL);

-- 费用结算单
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(52, '业务号', 'FConsign', 'consNo', NULL),
(52, '业务类型', 'FConsign', 'consBizType', 'getBizType'),
(52, '订舱客户', 'FConsign', 'custName', NULL),
(52, '联系人', 'FConsign', 'custContact', NULL),
(52, '客户联系人', 'FConsign', 'custContact', NULL),
(52, '客户联系电话', 'FConsign', 'custTel', NULL),
(52, '客户传真', 'FConsign', 'custFax', NULL),
(52, '船名', 'FConsign', 'vessName', NULL),
(52, '航次', 'FConsign', 'voyaName', NULL),
(52, '起运港', 'FConsign', 'consPolEn', NULL),
(52, '目的港', 'FConsign', 'consPodEn', NULL),
(52, '件数包装', 'FConsign', 'consCargoPackages', NULL),
(52, '件数', 'FConsign', 'consTotalPackages', NULL),
(52, '包装', 'FConsign', 'packName', NULL),
(52, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(52, '尺码', 'FConsign', 'consTotalMeasurement', NULL),
(52, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(52, 'MBL', 'FConsign', 'consMblNo', NULL),
(52, 'HBL', 'FConsign', 'consHblNo', NULL),
(52, '合同号', 'FConsign', 'consContractNo', NULL),
(52, '箱型箱量', 'FConsign', 'consContainersInfo', NULL),
(52, '开航日期', 'FConsign', 'consSailDate', NULL),
(52, '进仓编号', 'FConsign', 'consNo', NULL),
(52, '核销单号', 'FConsign', 'consVerificationNo', NULL),
(52, '经营单位', 'FConsign', 'consCompany', NULL),
(52, '应收人民币合计', 'FConsign', 'sumRCny', NULL),
(52, '应付人民币合计', 'FConsign', 'sumPCny', NULL),
(52, '人民币利润', 'FConsign', 'cnyGrossProfit', NULL),
(52, '应收美元合计', 'FConsign', 'sumRUsd', NULL),
(52, '应付美元合计', 'FConsign', 'sumPUsd', NULL),
(52, '美元利润', 'FConsign', 'usdGrossProfit', NULL),
(52, '其它币种应收合计', 'FConsign', 'sumROther', NULL),
(52, '其它币种应付合计', 'FConsign', 'sumPOther', NULL),
(52, '其它币种利润', 'FConsign', 'otherGrossProfit', NULL),
(52, '折算人民币应收合计', 'FConsign', 'sumR', NULL),
(52, '折算人民币应付合计', 'FConsign', 'sumP', NULL),
(52, '折算人民币利润', 'FConsign', 'grossProfit', NULL),
(52, '操作员', 'FConsign', 'consOperatorName', NULL),
(52, '业务员', 'FConsign', 'consSalesRepName', NULL),
(52, '费用类型', 'SExpense', 'expeType', 'getExpeType'),
(52, '结算对象', 'SExpense', 'custName', NULL),
(52, '发票抬头', 'SExpense', 'custName', NULL),
(52, '币种', 'SExpense', 'currCode', NULL),
(52, '费用名称', 'SExpense', 'charName', NULL),
(52, '数量', 'SExpense', 'expeNum', NULL),
(52, '单价', 'SExpense', 'expeUnitPrice', NULL),
(52, '金额', 'SExpense', 'expeTotalAmount', NULL),
(52, '汇率', 'SExpense', 'expeExRate', NULL),
(52, '发票号', 'SExpense', 'expeInvoiceNo', NULL),
(52, '备注', 'SExpense', 'expeRemarks', NULL)
;

-- 进口业务流程
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(53, '业务号', 'FConsign', 'consNo', NULL),
(53, '业务类型', 'FConsign', 'consBizType', 'getBizType'),
(53, '委托单位', 'FConsign', 'custName', NULL),
(53, '委托联系人', 'FConsign', 'custContact', NULL),
(53, '委托电话', 'FConsign', 'custTel', NULL),
(53, '委托传真', 'FConsign', 'custFax', NULL),
(53, '船名', 'FConsign', 'vessName', NULL),
(53, '航次', 'FConsign', 'voyaName', NULL),
(53, '起运港', 'FConsign', 'consPolEn', NULL),
(53, '起运国', 'FConsign', 'consTradeCountry', NULL),
(53, '目的港', 'FConsign', 'consPodEn', NULL),
(53, '卸货港', 'FConsign', 'consPodEn', NULL),
(53, '件数', 'FConsign', 'consTotalPackages', NULL),
(53, '包装', 'FConsign', 'packName', NULL),
(53, '毛重', 'FConsign', 'consTotalGrossWeight', NULL),
(53, '体积', 'FConsign', 'consTotalMeasurement', NULL),
(53, 'MBL', 'FConsign', 'consMblNo', NULL),
(53, 'HBL', 'FConsign', 'consHblNo', NULL),
(53, '合同号', 'FConsign', 'consContractNo', NULL),
(53, '箱型箱量', 'FConsign', 'consContainersInfo', NULL),
(53, '承运人', 'FConsign', 'consCarrierName', NULL),
(53, '承运联系人', 'FConsign', 'consCarrierContact', NULL),
(53, '承运电话', 'FConsign', 'consCarrierTel', NULL),
(53, '到港日期', 'FConsign', 'consEta', NULL),
(53, '操作员', 'FConsign', 'consOperatorName', NULL),
(53, '业务员', 'FConsign', 'consSalesRepName', NULL),
(53, '换单地址', 'FConsign', 'consDoAgencyAddress', NULL),
(53, '是否有THC', 'FConsign', 'consThcFlag', 'Bool'),
(53, '是否压箱', 'FConsign', 'consPressBoxFlag', 'Bool'),
(53, '备注', 'FConsign', 'consRemarks', NULL),
(53, '起运国', 'FConsign', 'consTradeCountry', NULL),
(53, '拖车公司', 'FConsign', 'consTrackVendorName', NULL),
(53, '拖车公司联系人', 'FConsign', 'consTrackContact', NULL),
(53, '拖车公司电话', 'FConsign', 'consTrackTel', NULL),
(53, '提货日期', 'FConsign', 'consTrackLoadDate', NULL),
(53, '提货时间', 'FConsign', 'consTrackLoadTime', NULL),
(53, '报关行', 'FConsign', 'consCustomsVendorName', NULL),
(53, '报关公司联系人', 'FConsign', 'consCustomsContact', NULL),
(53, '报关公司电话', 'FConsign', 'consCustomsTel', NULL),
(53, '中文品名', 'FConsign', 'consCargoNameCn', NULL),
(53, '任务时间', 'FTask', 'consPressBoxFlag', NULL),
(53, '任务名称', 'FTask', 'consPressBoxFlag', NULL),
(53, '任务事项', 'FTask', 'consPressBoxFlag', NULL)
;
