ALTER TABLE `f_consign`	DROP COLUMN `CONS_CARGO_HS_CODE`;
ALTER TABLE `f_consign`
	ADD COLUMN `CONS_LOAD_CONTACT` VARCHAR(32) NULL DEFAULT NULL AFTER `CONS_LOAD_FACTORY`;
ALTER TABLE `f_consign`
	ADD COLUMN `CONS_LOAD_TEL` VARCHAR(32) NULL DEFAULT NULL AFTER `CONS_LOAD_CONTACT`;