ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_TOTAL_AMOUNT` DECIMAL(9,2) NULL DEFAULT NULL AFTER `CUDE_CHARGE`,
	ADD COLUMN `CUDE_TOTAL_SAY` VARCHAR(200) NULL DEFAULT NULL AFTER `CUDE_TOTAL_AMOUNT`;
	
ALTER TABLE `F_CUSTOMS_ENTRY`
	CHANGE COLUMN `CUEN_NO` `CUEN_NO` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CARG_ID`;

ALTER TABLE `F_CUSTOMS_ENTRY`
	ADD COLUMN `CUEN_PACKAGE_NUM` DECIMAL(9,2) NULL DEFAULT NULL AFTER `CUEN_CARGO_SPEC`,
	ADD COLUMN `PACK_CODE` VARCHAR(64) NULL DEFAULT NULL AFTER `CUEN_PACKAGE_NUM`;