ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_POL_CODE` VARCHAR(16) NULL DEFAULT NULL AFTER `CONS_POL`,
	ADD COLUMN `CONS_POD_CODE` VARCHAR(16) NULL DEFAULT NULL AFTER `CONS_POD`,
	ADD COLUMN `CONS_POT_CODE` VARCHAR(16) NULL DEFAULT NULL AFTER `CONS_POT`,
	ADD COLUMN `VESS_CODE` VARCHAR(32) NULL DEFAULT NULL AFTER `VESS_NAME_CN`;