ALTER TABLE `f_consign`
	ADD COLUMN `CONS_WAREHOUSE_NO` VARCHAR(32) NULL DEFAULT NULL AFTER `CONS_WAREHOUSE_ADDRESS`;
	
UPDATE `P_ACTION` SET `ACT_METHOD`='complexQueryConsign' WHERE `ACT_ID`=295 LIMIT 1;