ALTER TABLE `C_CUSTOMER_CONTACT`
	ADD COLUMN `CUCO_SKYPE` VARCHAR(32) NULL DEFAULT NULL AFTER `CUCO_QQ`;
ALTER TABLE `c_customer_contact`
	CHANGE COLUMN `CUCO_TEL` `CUCO_TEL` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUCO_ADDRESS2`,
	CHANGE COLUMN `CUCO_HOME_TEL` `CUCO_HOME_TEL` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUCO_TEL`,
	CHANGE COLUMN `CUCO_MOBILE` `CUCO_MOBILE` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUCO_HOME_TEL`,
	CHANGE COLUMN `CUCO_FAX` `CUCO_FAX` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUCO_SKYPE`;