ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_PORT_DOMESTIC_EN` VARCHAR(64) NULL DEFAULT NULL AFTER `CUDE_PORT_DOMESTIC`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_PORT_FOREIGN` VARCHAR(64) NULL DEFAULT NULL AFTER `CUDE_COUNTRY`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_PORT_FOREIGN_EN` VARCHAR(64) NULL DEFAULT NULL AFTER `CUDE_PORT_FOREIGN`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_PLACE_EN` VARCHAR(64) NULL DEFAULT NULL AFTER `CUDE_PLACE`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `EXSE_CODE_EN` VARCHAR(32) NULL DEFAULT NULL AFTER `EXSE_CODE`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `PACK_CODE_EN` VARCHAR(32) NULL DEFAULT NULL AFTER `PACK_CODE`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `TRTE_CODE_EN` VARCHAR(32) NULL DEFAULT NULL AFTER `TRTE_CODE`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_TOTAL_AMOUNT_CAP` VARCHAR(200) NULL DEFAULT NULL AFTER `CUDE_TOTAL_AMOUNT`;