ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_TOTAL_AMOUNT` DECIMAL(9,2) NULL DEFAULT NULL AFTER `CUDE_CHARGE`,
	ADD COLUMN `CUDE_TOTAL_SAY` VARCHAR(200) NULL DEFAULT NULL AFTER `CUDE_TOTAL_AMOUNT`;
	
ALTER TABLE `F_CUSTOMS_ENTRY`
	CHANGE COLUMN `CUEN_NO` `CUEN_NO` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CARG_ID`;

ALTER TABLE `F_CUSTOMS_ENTRY`
	ADD COLUMN `CUEN_PACKAGE_NUM` DECIMAL(9,2) NULL DEFAULT NULL AFTER `CUEN_CARGO_SPEC`,
	ADD COLUMN `PACK_CODE` VARCHAR(64) NULL DEFAULT NULL AFTER `CUEN_PACKAGE_NUM`;
	
ALTER TABLE `F_CONSIGN`
	CHANGE COLUMN `CONS_CARGO_MARKS` `CONS_CARGO_MARKS` TEXT NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONS_CARGO_DESC`,
	CHANGE COLUMN `CONS_CARGO_NAME_EN` `CONS_CARGO_NAME_EN` TEXT NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONS_CARGO_MEASUREMENT`,
	CHANGE COLUMN `CONS_CARGO_SPECIAL` `CONS_CARGO_SPECIAL` TEXT NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONS_CARGO_NAME_CN`,
	CHANGE COLUMN `ATTR9` `ATTR9` TEXT NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `ATTR8`,
	CHANGE COLUMN `ATTR10` `ATTR10` TEXT NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `ATTR9`;
	
ALTER TABLE `F_CONSIGN`
	ADD COLUMN CONS_VERIFICATION_FLAG TINYINT DEFAULT 0 AFTER `CONS_CUSTOMS_DECLEAR_DATE`,
    ADD COLUMN CONS_BULKY_CARRIER  DECIMAL(10, 4) AFTER `CONS_VERIFICATION_FLAG`,
    ADD COLUMN CONS_BULKY_CUSTOMER 	  		DECIMAL(10, 4) AFTER `CONS_BULKY_CARRIER`,
    ADD COLUMN CONS_CHARGE_WEIGHT_CARRIER      DECIMAL(10, 4) AFTER `CONS_BULKY_CUSTOMER`,
    ADD COLUMN CONS_CHARGE_WEIGHT_CUSTOMER 	DECIMAL(10, 4) AFTER `CONS_CHARGE_WEIGHT_CARRIER`,
    ADD COLUMN CONS_TOTAL_GROSS_WEIGHT_CUSTOMER      DECIMAL(10, 4) AFTER `CONS_CHARGE_WEIGHT_CUSTOMER`,
    ADD COLUMN CONS_TOTAL_MEASUREMENT_CUSTOMER 	  DECIMAL(10, 4) AFTER `CONS_TOTAL_GROSS_WEIGHT_CUSTOMER`;
	
INSERT INTO `P_TEMPLATE_TYPE` (`TETY_ID`, `TETY_NAME`, `TETY_CODE`, `TETY_DESC`, `TETY_ACTION`, `TETY_PARENT`, `TETY_CHILD`, `TETY_CLASS`, `TETY_TYPE`, `TETY_FORM_FLAG`, `ACTIVE`, `VERSION`, `REMOVED`) VALUES
(49, '商业发票', 'CUDE_INVOICE', NULL, 'CUDE_Q', 'FCustomsDeclaration', 'FCustomsEntry', 'B', 'P', 1, 1, 1, 0),
(50, '报关装箱单', 'CUDE_PACKING', NULL, 'CUDE_Q', 'FCustomsDeclaration', 'FCustomsEntry', 'B', 'P', 1, 1, 1, 0)
;

-- 第二中转港代码    To
-- 第三中转港代码    To
-- 头程承运人代码    BY First Carrier
-- 二程承运人代码    By
-- 三程承运人代码    By
-- 航班号        Flight
-- 币种Currency 
-- 从价/从量运费预付WT/VAL PPD
-- 从价/从量运费到付WT/VAL COLL
-- 其它费用预付Other PPD 
-- 其它费用到付Other COLL
-- 承运申报价值Delcalred Value for carriage
-- 海关申报价值Declared Value for Customs
-- 保险金额Amount of Insurrance
-- 其它操作信息Handling information
-- 费率等级Rate Class
-- 商品代码Commodity item NO.
-- 付费重量Chargeable Weight 
-- 费率Rate charge
-- 运费总额Total
-- 从量运费预付额weight charge prepaid
-- 从量运费到付额weight charge collect
-- 从价运费预付额valuation charge prepaid
-- 从价运费到付额valuation charge collect
-- 其它费用other charges
-- 预付总额Total prepaid
-- 到付总额total collect
-- 主运单号MAWB NO.
-- 分运单号HAWB NO.
