ALTER TABLE `F_CONTAINER`
	CHANGE COLUMN `CONT_CARGO_NAME_EN` `CONT_CARGO_NAME_EN` TEXT NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONT_PACKAGE_NUM`,
	CHANGE COLUMN `CONT_CARGO_NAME_CN` `CONT_CARGO_NAME_CN` TEXT NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONT_CARGO_NAME_EN`;