UPDATE `P_TEMPLATE_TYPE` SET `TETY_ACTION`='EXPE_CONFIRM' WHERE `TETY_ID`=34;
UPDATE `P_TEMPLATE_TYPE` SET `TETY_ACTION`='CONS_CHECK_X' WHERE `TETY_ID`=16;
DELETE FROM `P_ACTION` WHERE `ACT_NAME`='CONS_CHECK_Q';
INSERT INTO `P_ACTION` (`ACT_NAME`, `ACT_SERVICE`, `ACT_METHOD`, `ACT_REMARK`) VALUES
('EXPE_CONFIRM', 'FConsignService', 'queryForBill', '导出费用确认');