ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_POL_CN` VARCHAR(64) NULL DEFAULT NULL AFTER `CONS_POL_EN`;
ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_POD_CN` VARCHAR(64) NULL DEFAULT NULL AFTER `CONS_POD_EN`;
ALTER TABLE `f_consign`
	ADD COLUMN `CONS_POT_CN` VARCHAR(64) NULL DEFAULT NULL AFTER `CONS_POT_EN`;
	
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(1, '装运方式', 'FBl', 'consShipType', NULL);