ALTER TABLE `W_INQUIRY`
	ADD COLUMN `WINQ_COMPANY` VARCHAR(64) NULL DEFAULT NULL AFTER `WINQ_ID`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_LOAD_COUNTRY` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUDE_CONTAINER_NO`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_DISCHARGE_COUNTRY` VARCHAR(64) NULL DEFAULT NULL AFTER `CUDE_LOAD_COUNTRY`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	CHANGE COLUMN `CUDE_PORT_FOREIGN` `CUDE_POL` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUDE_DISCHARGE_COUNTRY`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	CHANGE COLUMN `CUDE_PORT_FOREIGN_EN` `CUDE_POL_EN` VARCHAR(64) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CUDE_POL`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_POD` VARCHAR(64) NULL DEFAULT NULL AFTER `CUDE_POL_EN`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_POD_EN` VARCHAR(64) NULL DEFAULT NULL AFTER `CUDE_POD`;
	