INSERT INTO `P_COMPANY_CONFIG` (`COCO_CODE`, `COCO_NAME`, `COCO_VALUE`, `COCO_VALUE_TYPE`, `COCO_VALUE_OPTIONS`,
 `COCO_GROUP`, `COCO_TYPE`, `COCO_DESC`, `COMP_CODE`, `VERSION`, `REMOVED`) VALUES
('CONS_NO_SERIAL_DATE_TYPE', '业务号生成日期类型', 2, 14, NULL, '业务设置', 'A', '开航日期', '{CC}', 0, 0);