CREATE TABLE IF NOT EXISTS G_PAYMENT_WAY (
  PAYW_ID INT NOT NULL auto_increment,
  PAYW_CODE VARCHAR(16) NOT NULL,
  PAYW_NAME VARCHAR(16) NOT NULL,
  ACTIVE TINYINT(4) default '1',
  COMP_CODE VARCHAR(32) NOT NULL,
  VERSION INT NOT NULL default '0',
  REMOVED TINYINT(4) NOT NULL default '0',
  PRIMARY KEY  (PAYW_ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `P_ACTION` (`ACT_NAME`, `ACT_SERVICE`, `ACT_METHOD`, `ACT_REMARK`) VALUES
('PAYW_S', 'GPaymentWayService', 'save', '付款方式保存'),
('PAYW_Q', 'GPaymentWayService', 'query', '付款方式查询');

INSERT INTO `P_FUNCTION` (`FUNC_CODE`, `FUNC_NAME`, `FUNC_TYPE`, `ACTIVE`) VALUES
('001033', '付款方式', 'M', 1),
('00103301', '查看', 'F', 1),
('00103302', '编辑', 'F', 1),
('00103303', '删除', 'F', 1);

ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CARG_DANGER_REPORT_FLAG` TINYINT NULL DEFAULT '0' AFTER `CONS_TOTAL_MEASUREMENT_CUSTOMER`,
	ADD COLUMN `CARG_DANGER_REPORT_DATE` DATE NULL DEFAULT NULL AFTER `CARG_DANGER_REPORT_FLAG`,
	ADD COLUMN `CARG_REPORT_FLAG` TINYINT NULL DEFAULT '0' AFTER `CARG_DANGER_REPORT_DATE`,
	ADD COLUMN `CARG_REPORT_DATE` DATE NULL DEFAULT NULL AFTER `CARG_REPORT_FLAG`,
	ADD COLUMN `SEWA_NAME` VARCHAR(32) NULL DEFAULT NULL AFTER `CARG_REPORT_DATE`,
	ADD COLUMN `SETTLEMENT_OBJECT_ID` INT(11) NULL DEFAULT NULL AFTER `SEWA_NAME`,
	ADD COLUMN `SETTLEMENT_OBJECT_NAME` VARCHAR(32) NULL DEFAULT NULL AFTER `SETTLEMENT_OBJECT_ID`;

