-- add by yinyulong
ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_CONTAINER_SEAL_NO` VARCHAR(500) NULL DEFAULT NULL AFTER `CONS_SEAL_NO`;
ALTER TABLE `F_BL`
	ADD COLUMN `BL_CONTAINER_SEAL_NO` VARCHAR(500) NULL DEFAULT NULL AFTER `BL_SEAL_NO`;

-- 模板增加箱号/封号字段
INSERT INTO `P_TEMPLATE_MAP` (`TETY_ID`, `TEMA_NAME`, `TEMA_TABLE`, `TEMA_FIELD`, `TEMA_CONVERTER`) VALUES
(1, '箱号/封号', 'FBl', 'blContainerSealNo', NULL);