ALTER TABLE `F_CONSIGN`
	ADD COLUMN `TRTY_NAME` VARCHAR(32) NULL DEFAULT NULL AFTER `TRTY_ID`;
	
ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CUDE_BIZ_TYPE` VARCHAR(32) NULL DEFAULT NULL AFTER `SETTLEMENT_OBJECT_NAME`;
	
ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CUDE_TITLE` VARCHAR(32) NULL DEFAULT NULL AFTER `CUDE_BIZ_TYPE`;