-- add by yinyulong  sql字段漏掉补充。
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_CONTAINER_FREE_DAYS` INT NULL DEFAULT NULL AFTER `CUDE_SHIP_DATE_T`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_EXPIRE_CONTAINER_DATE` DATE NULL DEFAULT NULL AFTER `CUDE_CONTAINER_FREE_DAYS`;
ALTER TABLE `F_CUSTOMS_DECLARATION`
	ADD COLUMN `CUDE_EXPIRE_DECLAR_DATE` DATE NULL DEFAULT NULL AFTER `CUDE_EXPIRE_CONTAINER_DATE`;
ALTER TABLE `f_customs_declaration`
	ADD COLUMN `CUDE_INSPECTION_DATE` DATE NULL DEFAULT NULL AFTER `CUDE_EXPIRE_DECLAR_DATE`;

