ALTER TABLE `P_USER`
	ADD COLUMN `UUID` VARCHAR(64) NULL DEFAULT NULL AFTER `USER_PASSWORD_MODIFY_DATE`;
	
-- add by yinyulong
ALTER TABLE `S_EXPENSE`
	CHANGE COLUMN `CONS_NO` `CONS_NO` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONS_ID`;

ALTER TABLE `S_EXPENSE_B`
	CHANGE COLUMN `CONS_NO` `CONS_NO` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONS_ID`;

ALTER TABLE `F_CARGO`
	CHANGE COLUMN `CONS_NO` `CONS_NO` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONS_ID`;

ALTER TABLE `F_CUSTOMS_DOC`
	CHANGE COLUMN `CONS_NO` `CONS_NO` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8_unicode_ci' AFTER `CONS_ID`;
