FContract = Ext.data.Record.create(['id',
	'fconId','fconNo','custId','custName','custSname','charterId','charterName','charterSname','custContact','custTel','custFax',
	'fconContractNo','unitId','unitName','unitIdCarrier','unitNameCarrier','packId','packName','fconShipper','fconConsignee','fconNotifyParty',
	'fconPol','fconPolEn','fconPod','fconPodEn','fconCargoDesc',
	{name:'fconContractQuantity',type:'float'},
	{name:'fconForcastQuantity',type:'float'},
	{name:'fconShippedQuantity',type:'float'},
	{name:'fconRemainQuantity',type:'float'},
	{name:'fconFactQuantity',type:'float'},
	{name:'fconForcastCbm',type:'float'},
	{name:'fconShippedCbm',type:'float'},
	{name:'fconRemainCbm',type:'float'},
	{name:'fconFactCbm',type:'float'},
	{name:'fconArrivedGrossWeight',type:'float'},
	{name:'fconArrivedPackages',type:'float'},
	{name:'fconUnitPriceR',type:'float'},
	{name:'fconTotalPriceR',type:'float'},
	{name:'fconUnitPriceP',type:'float'},
	{name:'fconTotalPriceP',type:'float'},
	{name:'fconTotalPackages',type:'float'},
	{name:'fconTotalGrossWeight',type:'float'},
	{name:'fconInwareGrossWeight',type:'float'},	
	{name:'fconLoadDate',type:'date',dateFormat:DATEF},
	{name:'fconShipDateF',type:'date',dateFormat:DATEF},
	{name:'fconShipDateT',type:'date',dateFormat:DATEF},
	{name:'voyaShipDateF',type:'date',dateFormat:DATEF},
	{name:'voyaShipDateT',type:'date',dateFormat:DATEF},
	{name:'voyaSailDate',type:'date',dateFormat:DATEF},
	'voyaSailedFlag','blCargoPackages',
	{name:'blCargoGrossWeight',type:'float'},
	{name:'blCargoNetWeight',type:'float'},
	{name:'blCargoMeasurement',type:'float'},
	'cargNameCn','cargNameEn',
	'fconRemarks','fconServiceSpec','fconStatus','fconVesselVoyage','fconVessNameCn','fconCarrier','packId','packName',
	'tranId','tranName','tranIdCarrier','tranNameCarrier','shliId','shliName','pateIdR',
	'pateNameR','pateIdP','pateNameP','fconOperatorId','fconOperatorName','fconSalesRepId','fconSalesRepName',
	'consId','consNo','consMblNo',
	{name:'fconInvoiceFlag',type:'boolean',convert:function(v){return v==1;}},
	{name:'fconInspectionFlag',type:'boolean',convert:function(v){return v==1;}},
	{name:'fconSumListFlag',type:'boolean',convert:function(v){return v==1;}},
	{name:'fconCopyFlag',type:'boolean',convert:function(v){return v==1;}},
	{name:'fconExpeConfirmFlag',type:'boolean',convert:function(v){return v==1;}},
	{name:'fconCudeDocFlag',type:'boolean',convert:function(v){return v==1;}},
	{name:'fconPhotoFlag',type:'boolean',convert:function(v){return v==1;}},
	{name:'fconMatesReceiptFlag',type:'boolean',convert:function(v){return v==1;}},
	'fconCudeType',
	'userId','grouId','createBy','modifyBy',{name:'createTime',type:'date',dateFormat:'Y-m-d H:i:s'},{name:'modifyTime',type:'date',dateFormat:'Y-m-d H:i:s'},
	'compCode','version','rowAction']);

FPackingList = Ext.data.Record.create(['id',
	'paliId','fconId','fconNo','fconContractNo','paliLabel','packId','packName',
	'paliTrackType','paliTrackTypeP','paliTransTimes','paliTrackNo','paliLineNo','paliSpec','paliPackages','cargNameCn','cargNameEn',
	{name:'paliGrossWeight',type:'float'},{name:'paliCbm',type:'float'},{name:'paliCbmC',type:'float'},'paliPieces',
	'vessId','vessName','vessNameCn','voyaId','voyaName','loliId','consId','consNo','consMblNo',
	{name:'paliLoadDate',type:'date',dateFormat:DATEF},'paliLength','paliTotalLength','unitIdLen','unitNameLen',
	{name:'paliArriveDate',type:'date',dateFormat:DATEF},
	'paliHarbourId','paliHarbourName','paliStationId','paliStationName','paliLocation','paliStationIdNow','paliStationNameNow','paliLocationNow',
	{name:'paliTransFlag',type:'boolean',convert:function(v){return v==1;}},
	{name:'voyaSailedFlag',type:'boolean',convert:function(v){return v==1;}},
	'paliRemarks','paliStatus','charterName','custName','fconContractNo','fconPodEn',{name:'fconInvoiceFlag',type:'boolean',convert:function(v){return v==1;}},
	'fconCudeType',{name:'fconInspectionFlag',type:'boolean',convert:function(v){return v==1;}},
	'userId','grouId','createBy','modifyBy',{name:'createTime',type:'date',dateFormat:'Y-m-d H:i:s'},{name:'modifyTime',type:'date',dateFormat:'Y-m-d H:i:s'},
	'compCode','version','rowAction']);

FTransList = Ext.data.Record.create(['id',
	'trliId','fconId','paliId','trliStationId','trliStationName','trliLocation',
	'trliStationIdO','trliStationNameO','trliLocationO','trliRemarks','trliTrackType',
	{name:'trliTranDate',type:'date',dateFormat:DATEF},
	{name:'trliArriveDate',type:'date',dateFormat:DATEF},
	'userId','grouId','createBy','modifyBy',
	{name:'createTime',type:'date',dateFormat:'Y-m-d H:i:s'},
	{name:'modifyTime',type:'date',dateFormat:'Y-m-d H:i:s'},
	'compCode','version','rowAction']);

FLoadingList = Ext.data.Record.create(['id',
	'loliId','fconId','fconNo','fconContractNo','carrierId',
	'carrierName','vessId','vessName','vessNameCn','voyaId','voyaName','fconUnit',
	{name:'fconForcastQuantity',type:'float'},
	{name:'fconShippedQuantity',type:'float'},
	{name:'loliShippedQuantity',type:'float'},
    {name:'loliFactQuantity',type:'float'}, 
	{name:'fconForcastCbm',type:'float'},
    {name:'fconShippedCbm',type:'float'},
    {name:'loliShippedCbm',type:'float'},
    {name:'loliFactCbm',type:'float'},	
	'loliStatus','consId','consNo','consMblNo',
	{name:'voyaShipDateF',type:'date',dateFormat:DATEF},
	{name:'voyaShipDateT',type:'date',dateFormat:DATEF},	
	{name:'fconLoadDate',type:'date',dateFormat:DATEF},
	{name:'fconShipDateF',type:'date',dateFormat:DATEF},
	{name:'fconShipDateT',type:'date',dateFormat:DATEF},
	{name:'voyaSailDate',type:'date',dateFormat:DATEF},
	'custName','charterName','fconPolEn','fconPodEn','fconCargoDesc','tranName',
	'userId','grouId','createBy','modifyBy',{name:'createTime',type:'date',dateFormat:'Y-m-d H:i:s'},{name:'modifyTime',type:'date',dateFormat:'Y-m-d H:i:s'},
	'compCode','version','rowAction']);