ALTER TABLE `P_USER`
	ADD COLUMN `USER_SYSTEM_USER_FLAG` TINYINT(4) NULL DEFAULT NULL DEFAULT '1' AFTER `USER_OPERATOR_FLAG`,
	ADD COLUMN `USER_GROU_VIEW_FLAG` TINYINT(4) NULL DEFAULT '0' AFTER `USER_SYSTEM_USER_FLAG`,
	ADD COLUMN `USER_GROU_EDIT_FLAG` TINYINT(4) NULL DEFAULT '0' AFTER `USER_GROU_VIEW_FLAG`;