ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_LOAD_CONTACT` VARCHAR(32) NULL DEFAULT NULL AFTER `CONS_LOAD_FACTORY`;
ALTER TABLE `F_CONSIGN`
	ADD COLUMN `CONS_LOAD_TEL` VARCHAR(32) NULL DEFAULT NULL AFTER `CONS_LOAD_CONTACT`;