ALTER TABLE`F_TRANS`
    ADD COLUMN `TRAN_DELIVERY_DATE` DATE default NULL  AFTER `TRAN_LOAD_TIME`,
    ADD COLUMN `TRAN_DELIVERY_TIME` VARCHAR(16) NULL DEFAULT NULL  AFTER `TRAN_DELIVERY_DATE`;
  